### ISSUE TITLE
请教一下 visual studio 中如何编译运行

### ISSUE THREAD

**Issue by Textcat** [netchx/netch#10]
在visual studio 中编译运行时出现如下的报错：

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'Task.Run<TResult>(Func<TResult>)' and 'Task.Run(Func<Task>)'	Netch	C:\Users\duan\Desktop\developer\Netch\Netch\Forms\MainForm.cs	188	Active

**Comment by BingLingGroup** [comment]
visual studio 2019打开后经提示安装.NET Framework 4.8后可编译运行

**Comment by ghost** [comment]
安装 .NET Framework 4.8 Dev Pack + Runtime 谢谢

1. clone 此项目
2. 打开 INIT.BAT 用于初始化子模块
3. 打开 UPDATE.BAT 用于更新子模块
4. Visual Studio 2019 打开 Netch.sln 即可
