### ISSUE TITLE
托盘图标

### ISSUE THREAD

**Issue by TonyShitDark** [netchx/netch#100]
**功能描述**
win10风格图标纯白色⚡闪电
通过类似win10网络托盘图标的状态角标来显示状态

**额外信息**

**Comment by ghost** [comment]
这需要人帮忙啊 ...

**Comment by TonyShitDark** [comment]
![-60eef55571194fbc](https://user-images.githubusercontent.com/32632071/64156042-97c88e00-ce66-11e9-85b8-e72dba6b95e5.png)
就类似这种就挺好

**Comment by miozx** [comment]
已做好图标，黑白两色用于对应系统 Light Mode 和 Dark Mode，后面也许会有人跟进这个功能
![White](https://raw.githubusercontent.com/NetchX/Netch/master/Netch/Resources/Netchiconwhite.png) ![Black](https://raw.githubusercontent.com/NetchX/Netch/master/Netch/Resources/Netchiconblack.png)

**Comment by TonyShitDark** [comment]
![2cdeee2e242feac1](https://user-images.githubusercontent.com/32632071/64157810-f93e2c00-ce69-11e9-8eca-e823abfa6b43.png)
我觉得光闪电图案就够了 多余的其他反而有点繁琐不美

**Comment by BingLingGroup** [comment]
@wsdd977 说只搞闪电图案的，让我想到只搞纸飞机的telegram和shadowsocks傻傻分不清，还有只搞闪电图案的充电USB和雷电……

**Comment by miozx** [comment]
@wsdd977 我的想法是尽量保持原设，以减少版本更新的不适应感（主要是不想背锅，万一有人提 issue 说更新版本后托盘图标消失怎么办）

**Comment by TonyShitDark** [comment]
😂闪电右下角加上类似QQ状态那种角标显示状态嘛  比如延迟状态断开状态
辨识性我觉得还好

**Comment by gongyoyo** [comment]
建议⚡图标可以更改颜色，快捷代理全局或者其他模式时会变色

**Comment by ghost** [comment]
先把这个 issue 关了，暂时不会再考虑给 Netch 上新的托盘图标
