### ISSUE TITLE
netch 1.9.6/1.9.7 在WIN11 22H2中存在闪退情况

### ISSUE THREAD

**Issue by JERRYisMe330** [netchx/netch#1000]
### Describe the bug

netch 1.9.6/1.9.7 在WIN11 22H2中存在闪退情况

### To Reproduce

netch 1.9.6/1.9.7 在WIN11 22H2中存在闪退情况

### Log

netch 1.9.6/1.9.7 在WIN11 22H2中存在闪退情况

### Environment

```txt
netch 1.9.6/1.9.7 在WIN11 22H2中存在闪退情况
```

**Comment by egg1234** [comment]
建议尝试nekoray这个项目，完全多平台桌面支持windows 10/11，windows server 2022，MacOS，Ubuntu桌面版，选择sing-box核心情况下，原生支持hysteria等多种可以直接FullCone NAT的协议（当然也原生支持trojan等FullCone热门协议），在vpn模式下，使用NatTypeTester.exe轻而易举就能使用前面的协议测试出FullCone的NAT模式，
并且完全没有DNS泄漏的情况
https://github.com/MatsuriDayo/nekoray
https://github.com/HMBSbige/NatTypeTester
下面是测试DNS泄漏的网站
https://browserleaks.com/dns

**Comment by Ookvkin1oO** [comment]
貌似目前有个救急方案，使用兼容模式选择win8，代理可以正常使用但是流量统计行不通了，并且会提示不兼容，但是他确确实实让游戏走代理了

**Comment by shanggl** [comment]
1.9.2  的说明中提到了 “目前aiodns 可能导致闪退，解决方案讨论中。如果你遇到闪退问题，请启用 设置-WinTUN-使用自定义 DNS 以禁用” 
我这里测试发现在1.9.7 上同样适用。 

我的是win11 22H2 ，设置为自定义dns后不再闪退

**Comment by SenjiMuramasa** [comment]
> 

请问这个修改是怎么操作的？在Netch中我没有找到设置栏。

**Comment by papeqaq** [comment]
> 1.9.2 的说明中提到了 “目前aiodns 可能导致闪退，解决方案讨论中。如果你遇到闪退问题，请启用 设置-WinTUN-使用自定义 DNS 以禁用” 我这里测试发现在1.9.7 上同样适用。
> 
> 我的是win11 22H2 ，设置为自定义dns后不再闪退

win10 21H2 同样有闪退情况，设置为自定义dns后恢复，谢谢! 不过小白想问下自定义dns用哪个比较好，不闪退了但网速变得很慢很慢。

**Comment by Ookvkin1oO** [comment]
> > 1.9.2 的说明中提到了 “目前aiodns 可能导致闪退，解决方案讨论中。如果你遇到闪退问题，请启用 设置-WinTUN-使用自定义 DNS 以禁用” 我这里测试发现在1.9.7 上同样适用。
> > 我的是win11 22H2 ，设置为自定义dns后不再闪退
> 
> win10 21H2 同样有闪退情况，设置为自定义dns后恢复，谢谢! 不过小白想问下自定义dns用哪个比较好，不闪退了但网速变得很慢很慢。

可以使用1.1.1.1或者8.8.8.8，顺便试试勾选“代理dns”，不过这样直连的那些国内的服务器可能会出问题，如果解决不了再用223.5.5.5试试。

**Comment by papeqaq** [comment]
> > > 1.9.2 的说明中提到了 “目前aiodns 可能导致闪退，解决方案讨论中。如果你遇到闪退问题，请启用 设置-WinTUN-使用自定义 DNS 以禁用” 我这里测试发现在1.9.7 上同样适用。
> > > 我的是win11 22H2 ，设置为自定义dns后不再闪退
> > 
> > 
> > win10 21H2 同样有闪退情况，设置为自定义dns后恢复，谢谢! 不过小白想问下自定义dns用哪个比较好，不闪退了但网速变得很慢很慢。
> 
> 可以使用1.1.1.1或者8.8.8.8，顺便试试勾选“代理dns”，不过这样直连的那些国内的服务器可能会出问题，如果解决不了再用223.5.5.5试试。

每个都试了下 自己也搜到了一些 不过还是没有达到期望速度 可能也和机场速度有关吧。感谢这么快的回复!

**Comment by 1601305088** [comment]
> 
大哥，在哪里设置自定义dns，我找不到。，/(ㄒoㄒ)/~~

**Comment by Ookvkin1oO** [comment]
> > 
> 
> 大哥，在哪里设置自定义dns，我找不到。，/(ㄒoㄒ)/~~

图片1：https://imgloc.com/i/iEaJUU
图片2：https://imgloc.com/i/iEaK3v
图片3：https://imgloc.com/i/iEaLS3

**Comment by 1601305088** [comment]
> > > 
> > 
> > 
> > 大哥，在哪里设置自定义dns，我找不到。，/(ㄒoㄒ)/~~
> 
> 图片1：https://imgloc.com/i/iEaJUU 图片2：https://imgloc.com/i/iEaK3v 图片3：https://imgloc.com/i/iEaLS3

大哥，闪电小图标是什么软件，我这sing-box只能用cmd命令打开

**Comment by FantomY** [comment]
我在22H2上用了好几个月了，这两天才开始频繁闪退，先尝试自定义DNS试试看

**Comment by ArickV3** [comment]
> 1.9.2 的说明中提到了 “目前aiodns 可能导致闪退，解决方案讨论中。如果你遇到闪退问题，请启用 设置-WinTUN-使用自定义 DNS 以禁用” 我这里测试发现在1.9.7 上同样适用。
> 
> 我的是win11 22H2 ，设置为自定义dns后不再闪退

NICE!!!! IS WORK NOW !!!!!!!!!!!!
