### ISSUE TITLE
Automatically close when netch started

### ISSUE THREAD

**Issue by SyntaxKavindu** [netchx/netch#1002]
### Describe the bug

When I click on the Start button, it closes the application

### To Reproduce

1. Open Netch
2. and Click "Start"

### Log

[2023-01-27 21:55:07][Information] Netch Version: NetchX/Netch@1.9.7
[2023-01-27 21:55:07][Information] OS: Microsoft Windows NT 10.0.22621.0
[2023-01-27 21:55:08][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2023-01-27 21:55:08][Information] System Language: en-US
[2023-01-27 21:55:08][Debug] Running Processes: 
C:\Netch\Netch.exe
C:\Program Files (x86)\3 APPES\Sound Lock\SoundLock.exe
C:\Program Files (x86)\AMG_NUKE_11\AMG_NUKE_11 Audio 7.1\AMG_NUKE_11 Audio 7.1.exe
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\109.0.1518.61\msedgewebview2.exe
C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe
C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe
C:\Program Files (x86)\RivaTuner Statistics Server\EncoderServer.exe
C:\Program Files (x86)\RivaTuner Statistics Server\RTSS.exe
C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooksLoader64.exe
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files\Highresolution Enterprises\X-Mouse Button Control\XMouseButtonControl.exe
C:\Program Files\LGHUB\lghub_agent.exe
C:\Program Files\LGHUB\lghub_updater.exe
C:\Program Files\LGHUB\lghub.exe
C:\Program Files\LGHUB\system_tray\lghub_system_tray.exe
C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe
C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA Share.exe
C:\Program Files\NVIDIA Corporation\ShadowPlay\nvsphelper64.exe
C:\Program Files\obs-studio\bin\64bit\obs-ffmpeg-mux.exe
C:\Program Files\obs-studio\bin\64bit\obs64.exe
C:\Users\kavin\AppData\Local\Programs\Microsoft VS Code\Code.exe
C:\Users\kavin\AppData\Roaming\Zoom\bin\cpthost.exe
C:\Users\kavin\AppData\Roaming\Zoom\bin\Zoom.exe
C:\Users\kavin\AppData\Roaming\Zoom\bin\zWebview2Agent.exe
[2023-01-27 21:55:08][Debug] Third-party Drivers:
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdgpio2.sys
AMD GPIO Client Driver [AMD GPIO Client Driver]((C)2012-2022 Advanced Micro Devices, INC.)
	C:\Windows\system32\drivers\amdgpio3.sys
AMD PSP Service [AMD PSP Service](Copyright (c) 2013 - 2022 Advanced Micro Devices, Inc.)
	C:\Windows\system32\drivers\amdpsp.sys
aow_drv [aow_drv]()
	\??\C:\Program Files\TxGameAssistant\UI\3.91.4600.81\aow_drv_x64_ev.sys
DroidCam Virtual Audio [DroidCam Virtual Audio](Copyright (C) 2010)
	C:\Windows\system32\drivers\droidcam.sys
DroidCam Source 3 [DroidCam Source 3]((C) 2019)
	C:\Windows\system32\DriverStore\FileRepository\droidcamvideo.inf_amd64_47e18363cbf3dfe0\droidcamvideo.sys
IDMWFP [IDMWFP](Copyright © 1999 - 2018 Tonec Inc.)
	C:\Windows\system32\DRIVERS\idmwfp.sys
Logitech G HUB Virtual Bus Enumerator Driver [Logitech G HUB Virtual Bus Enumerator Driver](Copyright © Logitech, Inc. 2022)
	C:\Windows\system32\drivers\logi_joy_bus_enum.sys
Logitech G HUB Virtual HID Device Driver [Logitech G HUB Virtual HID Device Driver](Copyright © Logitech, Inc. 2022)
	C:\Windows\system32\drivers\logi_joy_vir_hid.sys
Logitech G HUB Translation Layer Driver [Logitech G HUB Translation Layer Driver](Copyright © Logitech, Inc. 2022)
	C:\Windows\system32\drivers\logi_joy_xlcore.sys
Nahimic mirroring device - Driver [Nahimic mirroring device - Driver](Copyright 2019 (C) A-Volute2019)
	C:\Windows\system32\drivers\Nahimic_Mirroring.sys
RTCore64 [RTCore64]()
	\??\C:\Program Files (x86)\MSI Afterburner\RTCore64.sys
UAExt [UAExt](Copyright (C) 2015 Solid State System.)
	C:\Windows\system32\DRIVERS\UAExt.sys
unirsdt [unirsdt](Copyright (c) 2009 TENCENT. All Rights Reserved)
	C:\Windows\system32\drivers\unirsdt.sys
Wintun [Wintun](Copyright © 2018-2021 WireGuard LLC. All Rights Reserved.)
	C:\Windows\system32\DRIVERS\wintun.sys
[2023-01-27 21:55:08][Information] Github latest release: 1.9.7
[2023-01-27 21:55:08][Information] Already the latest version
[2023-01-27 21:55:13][Information] Start MainController: VLESS [2]Bypass LAN
[2023-01-27 21:55:13][Debug] Server Information: VLESS none + ws + xudp + none + tls
[2023-01-27 21:55:13][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2023-01-27 21:55:13][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2023-01-27 21:55:20][Information] Net traffic processes: (30576)v2ray-sn

### Environment

```txt
windows 11 latest
```

**Comment by user9825** [comment]
This is my problem too

**Comment by user9825** [comment]
I installed  .NET and the problem was solved

**Comment by user9825** [comment]
But when I change the mode to "bypassLan ", there is a problem and it exits the program

**Comment by SyntaxKavindu** [comment]
> But when I change the mode to "bypassLan ", there is a problem and it exits the program

no automatic exit
use 1.9.2 https://github.com/netchx/netch/releases/tag/1.9.2

**Comment by psnwd** [comment]
The issue occurs when the "Bypass LAN" mode is enabled, and the network interface (`netch`) fails to create properly. The process attempts to create the interface up to 20 times before exiting silently without any error message.
