### ISSUE TITLE
Netch启动出错， Microsoft windows NT 6.1.7601 service pack 1将不会得到开发者的支持.

### ISSUE THREAD

**Issue by zzzyting** [netchx/netch#1007]
### 错误描述

启动 Netch.exe ，提示 Microsoft windows NT 6.1.7601 service pack 1将不会得到开发者的支持.

![image](https://user-images.githubusercontent.com/25153242/217186558-684aab5c-f5e4-4289-8cfb-dc9701d9790d.png)

在界面启动，又出现提示框 
![image](https://user-images.githubusercontent.com/25153242/217186909-48716250-be55-48b4-93ce-11889138f9da.png)

总之Netch用不了了

### 复现步骤

1.启动 Netch.exe 

### 日志

[2023-02-07 16:07:26][Information] Netch Version: NetchX/Netch@1.9.7
[2023-02-07 16:07:26][Information] OS: Microsoft Windows NT 6.1.7601 Service Pack 1
[2023-02-07 16:07:28][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2023-02-07 16:07:28][Information] System Language: zh-CN
[2023-02-07 16:07:28][Debug] Running Processes: 
\SystemRoot\System32\smss.exe
C:\Program Files (x86)\4DEasyConnect\EasyConnect.exe
C:\Program Files (x86)\ASUS\AXSP\1.01.01\atkexComSvc.exe
C:\Program Files (x86)\Common Files\Microsoft Shared\DevServer\9.0\WebDev.WebServer.exe
C:\Program Files (x86)\Common Files\Microsoft Shared\Phone Tools\CoreCon\11.0\bin\IpOverUsbSvc.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\Binn\sqlservr.exe
C:\Program Files (x86)\Microsoft\Skype for Desktop\Skype.exe
C:\Program Files (x86)\Tencent\QQ\Bin\QQ.exe
C:\Program Files (x86)\Tencent\QQ\Bin\TXPlatform.exe
C:\Program Files\Microsoft SQL Server\90\Shared\sqlwriter.exe
C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe
D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Ssms.exe
D:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\devenv.exe
D:\Program Files (x86)\SogouInput\9.5.0.3517\SGTool.exe
D:\Program Files (x86)\SogouInput\9.5.0.3517\SogouCloud.exe
D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\QQPCLeakScan.exe
D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\QQPCRealTimeSpeedup.exe
D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\QQPCRtp.exe
D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\QQPCTray.exe
D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\TSVulFixInc64.exe
D:\Program Files\Microsoft SQL Server\110\DTS\Binn\MsDtsSrvr.exe
D:\Program Files\Microsoft SQL Server\MSAS11.MSSQLSERVER\OLAP\bin\msmdsrv.exe
D:\Program Files\Microsoft SQL Server\MSRS11.MSSQLSERVER\Reporting Services\ReportServer\bin\ReportingServicesService.exe
D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\fdhost.exe
D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\fdlauncher.exe
D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\sqlservr.exe
D:\Program Files\Oray\SunLogin\SunloginClient\SunloginClient.exe
E:\Program Files\Microsoft Office\Office15\EXCEL.EXE
F:\Netch\Netch.exe
F:\Program Files (x86)\VMware\VMware Workstation\vmware-authd.exe
F:\Program Files (x86)\VMware\VMware Workstation\vmware-hostd.exe
F:\Program Files (x86)\VMware\VMware Workstation\vmware-tray.exe
f:\Program Files\TeamViewer\TeamViewer_Service.exe
F:\工具\HBuilderX\plugins\launcher\tools\adbs\adb.exe
[2023-02-07 16:07:28][Information] Github latest release: 1.9.7
[2023-02-07 16:07:28][Information] Already the latest version
[2023-02-07 16:07:29][Debug] Third-party Drivers:
VMware hcmon [VMware hcmon](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\hcmon.sys
Oraymir [Oraymir](© Oray Corporation. All rights reserved.)
	C:\Windows\system32\DRIVERS\Oraymir.sys
tencent QMUdisk [tencent QMUdisk]()
	\??\D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\QMUdisk64.sys
QQProtect Driver For x64 [QQProtect Driver For x64]()
	\??\C:\Windows\system32\drivers\QQProtectX64.sys
QQSysMonX64 [QQSysMonX64]()
	\??\D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\QQSysMonX64.sys
Serial port driver [Serial port driver](Copyright (C) Brother Industries Ltd.1997-2006)
	C:\Windows\system32\DRIVERS\serial.sys
softaal [softaal]()
	\??\D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\softaal64.sys
Tencent TAOAccelerator driver. [Tencent TAOAccelerator driver.]()
	\??\C:\Windows\system32\Drivers\TAOAccelerator64.sys
Tencent Auto Optimize Platform. [Tencent Auto Optimize Platform.]()
	\??\C:\Windows\system32\Drivers\TAOKernel64.sys
TFsFlt [TFsFlt](Copyright ? 2021 Tencent. All Rights Reserved.)
	C:\Windows\system32\Drivers\TFsFltX64.sys
TSDefenseBt [TSDefenseBt]()
	\??\D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\TsDefenseBT64.sys
TsNetHlpX64.sys [TsNetHlpX64.sys]()
	\??\D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\TsNetHlpX64.sys
TSSKX64 [TSSKX64](Copyright ? 2021 Tencent. All Rights Reserved.)
	C:\Windows\system32\drivers\tsskx64.sys
TSSysKit [TSSysKit]()
	\??\D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\TSSysKit64.sys
VMware VMCI Bus Driver [VMware VMCI Bus Driver](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmci.sys
VMware Virtual Ethernet Adapter Driver [VMware Virtual Ethernet Adapter Driver](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetadapter.sys
VMware Bridge Protocol [VMware Bridge Protocol](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetbridge.sys
VMware Virtual Ethernet Userif for VMnet [VMware Virtual Ethernet Userif for VMnet](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetuserif.sys
VMware vmparport [VMware vmparport](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmparport.sys
VMware vmx86 [VMware vmx86](Copyright © 1998-2017 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmx86.sys
vSockets Virtual Machine Communication Interface Sockets driver [vSockets Virtual Machine Communication Interface Sockets driver](Copyright © 1998-2016 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vsock.sys
TcHardWare [TcHardWare]()
	\??\D:\Program Files (x86)\Tencent\QQPCMgr\13.10.21914.214\QQPCHW-x64.sys
[2023-02-07 16:07:30][Information] Start MainController: VMess [2]Bypass LAN and China
[2023-02-07 16:07:30][Debug] Server Information: VMess auto + ws + xudp + none + none
[2023-02-07 16:07:31][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2023-02-07 16:07:31][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2023-02-07 16:07:46][Information] Stop Main Controller

### 操作环境

```txt
Windows 7

Netch 1.9.7
```

**Comment by OPNetworkLOL** [comment]
Microsoft windows NT 6.1.7601 service pack 1 将不会得到开发者的支持，请不要报告任何问题或寻求开发人员的帮助。
don't open issue, it's not a bug
you can upgrade to windows 10 to fix this problem, windows 7 not supported.

**Comment by RigoLigoRLC** [comment]
赶来嘲笑

**Comment by shenao1100** [comment]
赶紧把这个issue给close吧，看着丢人

**Comment by ZYGLQexplorer** [comment]
Microsoft windows NT 6.1.7601 service pack 1 将**_不会_**得到开发者的支持，请_**不要**_报告任何问题或寻求开发人员的帮助。

**Comment by Molyuu** [comment]
Microsoft windows NT 6.1.7601 service pack 1 将**不会**得到开发者的支持，请**不要**报告任何问题或寻求开发人员的帮助。

**Comment by BadLuckW** [comment]
![image](https://user-images.githubusercontent.com/12430183/218344062-ac9b9b6f-7464-4830-a9d0-91ce5b1e2f05.png)
不要说我们没有警告过你

**Comment by KawaiiSh1zuku** [comment]
赶来嘲笑
