### ISSUE TITLE
这个程序是不是不支持win7啊？

### ISSUE THREAD

**Issue by fendoubuxi** [NetchX/Netch#1008]
### 错误描述

这个程序是不是不支持win7啊？

### 复现步骤

这个程序是不是不支持win7啊？
win7直接显示启动失败  

### 日志

启动失败

### 操作环境

```txt
win7
```

**Comment by OPNetworkLOL** [comment]
不支持Windows 7，请升级到Windows 10（你升级到Windows 11都没问题）
