### ISSUE TITLE
加速以后游览器无法上外网，软件可以正常连接，困扰好久了

### ISSUE THREAD

**Issue by iToolstm** [NetchX/Netch#1009]
### Describe the bug

netch版本是1.9.7，系统是Windows10。模式是 [3] Bypass LAN and China 点加速没有任何的报错，右下角显示的是NAT：NoUDP
![image](https://user-images.githubusercontent.com/112534695/218258412-d6aecab8-54f2-4d6d-baa5-f1971622058a.png)
系统网络提示有一个 aioCloud 无法连接到Internet
![image](https://user-images.githubusercontent.com/112534695/218258478-0dbb0ef8-269f-4e82-93fd-f25c2692a96f.png)
![image](https://user-images.githubusercontent.com/112534695/218258496-be8d00c9-4ec0-4427-80db-0e1b3af76308.png)
加速后软件是可以使用的，比如telegram，功能都可以正常使用
![image](https://user-images.githubusercontent.com/112534695/218258575-13f0a5c1-efbd-4e83-8035-192d4ef64bf2.png)
但是游览器网页就是无法加载，比如YouTube
![image](https://user-images.githubusercontent.com/112534695/218258592-42914873-1a75-4cf7-b18f-06f149f47bbd.png)
我可以确保我的订阅节点没有问题，手机上可以正常使用和游览
这个问题困扰我好久了，我也不知道如何解决，半年前是可以正常使用的
麻烦大佬了！

### To Reproduce

1、双击打开netch1.9.7
2、选择模式 [3] Bypass LAN and China
3、启动
4、启动成功，右下角显示NAT：NoUDP
5、系统网络提示有一个 aioCloud 无法连接到Internet

### Log

[application.log](https://github.com/netchx/netch/files/10713674/application.log)
[V2Ray (SagerNet).log](https://github.com/netchx/netch/files/10713675/V2Ray.SagerNet.log)
我不确定是哪个，就都上传了

### Environment

```txt
操作系统：Windows10 专业工作站版 21H2
操作系统内部版本 19044.1889
netch版本 1.9.7
```

**Comment by li-wilbur** [comment]
和你一模一样的问题，不知道什么原因

**Comment by wnlonesome** [comment]
我也是，被墙的网页都打不开！

**Comment by egg1234** [comment]
建议使用下面这个issue 介绍的项目解决，既可以游戏udp FullCone nat加速也可以上所有外网
https://github.com/netchx/netch/issues/1000

**Comment by qxsyb** [comment]
你这种情况我也碰到了，点那个no udp刷新几次就好了。但是我的TR节点是真无解，根本用不了。这软件是不是不支持TR节点吖？

**Comment by hsmingyi** [comment]
楼主解决了吗

**Comment by qxsyb** [comment]
解决了，设置—v2ray—fullcore钩上就可以了，节点如果no udp就多点击几次刷新状态。

发自我的iPad

**Comment by Senmau** [comment]
> 解决了，设置—v2ray—fullcore钩上就可以了，节点如果没有udp就多点击几次刷新状态。 发自我的iPad
> […](#)
> 
> 在 2023 年 10 月 31 日，15:21，hsmingyi ***@***.***> 写道： ﻿ 楼主解决了吗 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。

我勾选了，然后并不能解决问题

**Comment by egg1234** [comment]
@Senmau netch项目都停止更新这么久了，不会解决这个问题的了

建议你用 https://github.com/MatsuriDayo/nekoray 项目，

进去TUN设置勾选“Strict Route”选项，以防止DNS泄漏，

如果你需要做排除代理的进程，那么在画面的右面“绕过的进程”框框里面填入绕过不代理的进程，例如大陆的各类应用程序的.exe运行文件名，

如果你想做类似netch的只加速某个进程，如某个游戏，勾选画面左下方的“白名单模式”，这时画面右上方的“绕过的进程”会改成“代理的进程”，把游戏的.exe运行文件名写到这个框框里面，这时nekoray只代理转发在框框里面列出的游戏程序的流量，这时包括浏览器chrome，firefox等的流量都不会被代理

以上“绕过的进程”与“白名单模式”是互斥的，同一时间只能一种转发逻辑起作用

另外进入路由菜单，点击“简易路由”标签，画面左下角点“预设”，选“绕过局域网和大陆”，然后点确定

之后在主画面点选TUN模式上网，因为以上所有设置只针对TUN模式起作用，系统代理模式无效

还要提一下，进去nekoray后，点首选项->基本设置->核心->点选“sing-box”，因为sing-box支持的代理协议更多，而且经过测试使用nekoray客户端情况下，直接支持socks5，ss，trojan，hysteria v1，TUIC等协议的udp Fullcone

这个可以使用 https://github.com/HMBSbige/NatTypeTester 项目的程序进行测试，它可以准确测试NAT的类型，因为有时NAT不一定是NAT1（Fullcone），但是有一些NAT类型还是支持游戏的要求的

另外从nekoray项目演变出来的 https://github.com/throneproj/Throne 项目就支持更多的代理协议了，除了上面提到原生支持Fullcone的代理协议，还新增加了hysteria v2，AnyTLS等原生支持Fullcone的代理协议，
但Throne支持“绕过的进程”与“白名单模式”的设置方法有很大改变，它的设置路径是
设置->路由设置->路由->点选框框里面的“default”->然后点画面下方的“编辑”->在“基本”的标签下
分别有“直连”“代理”“阻止”3个框框，点击框框里面会出现同时选择相应的定义前缀，并按照前缀要求的格式写域名或ip或程序名字等等，如果写程序名字就等于nekoray的上面的设置了
