### ISSUE TITLE
add support for plugin cloak

### ISSUE THREAD

**Issue by malikshi** [netchx/netch#101]
its will be helpful,
https://github.com/cbeuw/Cloak/releases

**Comment by BingLingGroup** [comment]
Ok. We will consider it. Currently you can use V2ray to implement TLS obfuscation. [English Guide](https://armazopu.github.io/v2ray+websocket+tls+caddy+cdn).

**Comment by ghost** [comment]
Status: Accepted

**Comment by malikshi** [comment]
thanks you very much,

**Comment by ConnectionRefused** [comment]
Added at [3a8fee0](https://github.com/NetchX/Netch/commit/3a8fee0cf71185b63e78e7e6c3a38d269d85201b)

Compiled based on the latest (bb78963)[https://github.com/NetchX/Netch/commit/bb7896361e201f411fe2c2f809da88115eb5e31f]

| Filename | SHA256 |
| :- | :- |
| [Netch x64.zip](https://github.com/NetchX/Netch/files/3589083/Netch.x64.zip) | ED6F46CF78145E93C4FE35BEC8CD51CCDA3E3BCEF435F73F84077EE6D332D5FA |
| [Netch x86.zip](https://github.com/NetchX/Netch/files/3589099/Netch.x86.zip) | 4FAC5DC6F6AD2A4AE494DAFC5E557C78C21E6ADF1906213594C03D5812F9D5AF |

**Comment by ghost** [comment]
Added at [3a8fee0](https://github.com/NetchX/Netch/commit/3a8fee0cf71185b63e78e7e6c3a38d269d85201b)
 
Compiled based on the latest [bb78963](https://github.com/NetchX/Netch/commit/bb7896361e201f411fe2c2f809da88115eb5e31f)
 
| Filename | SHA256 | 
| :- | :- | 
| [Netch x64.zip](https://github.com/NetchX/Netch/files/3589083/Netch.x64.zip) | ED6F46CF78145E93C4FE35BEC8CD51CCDA3E3BCEF435F73F84077EE6D332D5FA | 
| [Netch x86.zip](https://github.com/NetchX/Netch/files/3589099/Netch.x86.zip) | 4FAC5DC6F6AD2A4AE494DAFC5E557C78C21E6ADF1906213594C03D5812F9D5AF |

**Comment by malikshi** [comment]
its working perfectly :)
