### ISSUE TITLE
进程模式加速win11的xbox游戏没有效果

### ISSUE THREAD

**Issue by bakasine** [NetchX/Netch#1015]
### Describe the bug

进程模式加速win11的xbox游戏没有效果

### To Reproduce

1.打开netch
2.创建进程模式扫描win11的xbox下载的wolong的目录
3.启动netch
4.进入游戏匹配netch无流量统计, 联机报错

### Log

没有加速效果没有日志

### Environment

```txt
windows11
xbox wolong
netch v1.9.7
```

**Comment by hentai121** [comment]
今天又可以了 搞不懂
