### ISSUE TITLE
希望模式搜索能加入简单的搜索或者分组,将自带的模式分到system,并且可删除重载后恢复

### ISSUE THREAD

**Issue by wysnxzm** [netchx/netch#102]
首先十分感谢作者的付出,开源有你更精彩!
在$$tap停更时我就一直在期望着有新的代替品,等了两年终于来了!
有一点疑问和小建议:
设置(setting)中的子网掩码ip等等具体是什么作用?如何优化?
**模式搜索希望能加入简单的搜索或者分组,将自带的模式分到system,并且可删除重载后恢复**
谢谢!

**Comment by BingLingGroup** [comment]
1. 子网掩码，IP 这些是局域网的基本参数，建议自己谷歌 TAP-windows 的相关教程
2. 关于模式搜索，已有相关问题 #98 。重载后恢复是什么意思，我没懂，你没删模式文件（位置在`Netch/mode`下），又怎么会被删除。另外恢复的话，等于说是要自动下载或者说能自动生成[内置模式](https://github.com/NetchX/NetchMode)，你指的是这个功能吗

**Comment by wysnxzm** [comment]
> 1. 子网掩码，IP这些是局域网的基本参数，建议自己谷歌TAP-windows的相关教程
> 2. 关于模式搜索，已有相关问题[＃98](https://github.com/NetchX/Netch/issues/98)。重载后恢复是什么意思，我没懂，你没删模式文件（在位置`Netch/mode`下），又怎么会被删除。另外恢复的话，等于说是要自动下载说或者能自动生成[内置模式](https://github.com/NetchX/NetchMode)，你指的是这个功能吗

1. TAP-windows 已在学习中
2. 重载恢复是用于恢复初始状态,比如当前我把不想要默认的模式删除然后后悔了能够通过重载恢复到初始状态
3. 还有模式分组^_^
4. 还有就是建议把$$和vm的内置给删掉避免不必要的麻烦(你懂得)还有不必要的维护,让用户本地通过http或者$5的方式进行代理转发即可

**Comment by BingLingGroup** [comment]
2. 这个可以考虑，但实话讲不是很必要
3. 模式分组已经有 issue 提到了
4. ssr 的内置删除是因为考虑到 ssr-windows 端的 bug 不少，很多功能无法实现。但是 ss 和 vm 的内置没大问题的情况下不会删除

**Comment by wysnxzm** [comment]
> 1. 这个可以考虑，但实话讲不是很必要
> 2. 模式分组已经有 issue 提到了
> 3. ssr 的内置删除是因为考虑到 ssr-windows 端的 bug 不少，很多功能无法实现。但是 ss 和 vm 的内置没大问题的情况下不会删除

感谢解惑(๑•̀ㅂ•́)و✧

**Comment by BingLingGroup** [comment]
先留着呗，关啥呀
下载最新模式文件和下载最新版本可以加到一块嘛

**Comment by wysnxzm** [comment]
> 先留着呗，关啥呀
> 下载最新模式文件和下载最新版本可以加到一块嘛

只是觉得问题解决了就没必要留着哈哈

**Comment by bupt2017** [comment]
> 
> 
>     1. 这个可以考虑，但实话讲不是很必要
> 
>     2. 模式分组已经有 issue 提到了
> 
>     3. ssr 的内置删除是因为考虑到 ssr-windows 端的 bug 不少，很多功能无法实现。但是 ss 和 vm 的内置没大问题的情况下不会删除

首先很感谢楼主的软件，ssr-win换到netch像是打开了新世界的大门，因为有了订阅和自动检测节点的功能。（以前都是把节点复制到sscap上检测）。不知道有没有人和我一样是把netch当做ssr主力来使用的（很少玩游戏，也不需要ssr检测流量、二维码等花里胡哨的功能），如果真的去掉ssr的话挺可惜的。

**Comment by BingLingGroup** [comment]
@bupt2017 你可能是不知道这个版本的 [ssr-windows](https://github.com/HMBSbige/ShadowsocksR-Windows)，再说一次 netch 并不是为网页代理开发的

**Comment by bupt2017** [comment]
> 
> 
> @bupt2017 你可能是不知道这个版本的 [ssr-windows](https://github.com/HMBSbige/ShadowsocksR-Windows)，再说一次 netch 并不是为网页代理开发的

感谢管理指路，已在使用

**Comment by ssyangchn** [comment]
> > ```
> > 1. 这个可以考虑，但实话讲不是很必要
> > 
> > 2. 模式分组已经有 issue 提到了
> > 
> > 3. ssr 的内置删除是因为考虑到 ssr-windows 端的 bug 不少，很多功能无法实现。但是 ss 和 vm 的内置没大问题的情况下不会删除
> > ```
> 
> 首先很感谢楼主的软件，ssr-win换到netch像是打开了新世界的大门，因为有了订阅和自动检测节点的功能。（以前都是把节点复制到sscap上检测）。不知道有没有人和我一样是把netch当做ssr主力来使用的（很少玩游戏，也不需要ssr检测流量、二维码等花里胡哨的功能），如果真的去掉ssr的话挺可惜的。

其实clash for windows也不错

**Comment by xqXQzzz1** [comment]
> 
> 
> @bupt2017 你可能是不知道这个版本的 [ssr-windows](https://github.com/HMBSbige/ShadowsocksR-Windows)，再说一次 netch 并不是为网页代理开发的

感觉netch+switchyOmega挺好用的，砍掉SSR的话，就只有clashr能同时用ssr和v2ray了。
