### ISSUE TITLE
tun2socks start failed

### ISSUE THREAD

**Issue by Dr-Hebz** [NetchX/Netch#1022]
### Describe the bug

Whenever i press start the program send me this (tun2socks start failed).
What can i do?

### To Reproduce

![image](https://user-images.githubusercontent.com/123991283/229103198-978d759d-2246-4c42-b715-9e6c9137c7ba.png)
Open netch 
Choose Bypass lan 
press start
(tun2socks start failed) error appear

### Log

Welcome to trojan 1.16.0
[2023-03-31 12:57:23] [WARN] TCP_FASTOPEN is not supported
[2023-03-31 12:57:23] [WARN] TCP_FASTOPEN_CONNECT is not supported
[2023-03-31 12:57:23] [WARN] trojan service (client) started at 127.0.0.1:2801

### Environment

```txt
OS: Windows 10 Home
Netch : All versions
```

**Comment by facemikey** [comment]
怎么解决

**Comment by ylhy2299** [comment]
怎么解决

**Comment by du6rkx** [comment]
how to fix this TvT

**Comment by du6rkx** [comment]
> This issue was closed because it has been inactive for 14 days since being marked as stale.

how to fix ?

**Comment by HoTien2004** [comment]
How?
