### ISSUE TITLE
Crash on win 10

### ISSUE THREAD

**Issue by amin-en-sh** [NetchX/Netch#1024]
### Describe the bug

I have this problem that whenever the app starts connecting to server, it crashes all the time

### To Reproduce

1. open
2. start
3. crash

### Log

![Uploading Untitled1.jpg…]()

### Environment

```txt
windows 10 Pro 64-bit
netch 1.9.7
```

**Comment by AmirShahmohammadi** [comment]
I have the same problem, it crashes 5 seconds after the connection

**Comment by kumuweifengchun-sudo** [comment]
这个只要在设置里面把winTun里面的'使用自定义DNS'打开后就不会了，这个问题很早之前有人问过
