### ISSUE TITLE
选择模式Bypass LAN 以及 Bypass LAN and China启动时显示tun2socks started failed

### ISSUE THREAD

**Issue by Xiao1060** [NetchX/Netch#1037]
### 错误描述

选择模式Bypass LAN 以及 Bypass LAN and China启动时显示tun2socks started failed
使用Netch其他版本、重启、清理缓存、重装microsoft windows desktop runtime问题仍无法解决

### 复现步骤

1. 打开Netch软件
2. 选择模式Bypass LAN and China
3. 启动
4. 状态进度卡在正在启动tun2socks
5. 启动失败，显示tun2socks started failed

### 日志

[2023-05-16 12:21:52][Information] Start MainController: SSR [2]Bypass LAN and China
[2023-05-16 12:21:52][Debug] Server Information: SSR rc4-md5 + origin + http_simple
[2023-05-16 12:21:52][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2023-05-16 12:21:52][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[aiodns][aiodns_dial] TYPE_REST
[aiodns][aiodns_dial] TYPE_ADDR => 127.0.0.1:253
[aiodns][aiodns_dial] TYPE_LIST => D:\Netch (2)\Netch (2)\Netch\Netch\bin\aiodns.conf
[aiodns][aiodns_dial] TYPE_CDNS => tcp://223.5.5.5:53
[aiodns][aiodns_dial] TYPE_ODNS => tcp://1.1.1.1:53
2023/05/16 12:21:52 [Wintun] WintunCreateAdapter: Creating adapter
2023/05/16 12:21:52 [Wintun] SelectDriver: Using existing driver 0.13
2023/05/16 12:22:02 [Wintun] RegistryQueryStringWait: Timeout waiting for registry value \REGISTRY\MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\0019\NetCfgInstanceId (status: 0x102)
2023/05/16 12:22:02 [Wintun] WintunCreateAdapter: Failed to get \REGISTRY\MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\0019\NetCfgInstanceId
2023/05/16 12:22:02 [tun2socks][newTUN][tun.CreateTUN] Error creating interface: The system cannot find the file specified.
[2023-05-16 12:22:02][Information] Stop Main Controller

### 操作环境

```txt
win10 家庭版
```

**Comment by mifan09** [comment]
现在解决了吗

**Comment by wkp0** [comment]
可以参考这篇文章。
解决 Windows 10 端口被 Hyper-V 随机保留（占用）的问题 - 爱丽丝基的文章 - 知乎
https://zhuanlan.zhihu.com/p/474392069
