### ISSUE TITLE
暗黑四进程代理发现dns走的本地解析

### ISSUE THREAD

**Issue by godhangyu** [NetchX/Netch#1048]
### 错误描述

暗黑四用进程代理卡在初始化界面无法进入，等一段时间后提示网络错误

### 复现步骤

查看暗黑四的log发现是 prod.actual.battle.net 连接问题，本地ping解析到了cn.actual.battle.net 肯定无法ping通
但是在梯子上发现解析并没有问题怀疑dns并没有生效

已经在规则上勾上处理DNS/处理被处理进程DNS/经过代理处理DNS，目标8.8.8.8

还是不行，最后手动改本机host才能进游戏

### 日志

D4的log

[Interface.BgsLow] I 06:38:16.253864 [BGS] |event=Disconnected|method=OnDisconnectComplete|address=prod.actual.battle.net|port=1119|status=1016 (C:\projects\fenris\shared\Contrib\bgs-sdk\6.1.0-pre-release1\src\low\core\connection_handler.cpp:245)
I 2023.06.02 06:38:16.253887	[BgsClient] BgsConnection: connection failed. | connection_index: 0 | connection_id: 1 | bgs_error_code: 1016

### 操作环境

```txt
win11 
netch 1.9.7
```

**Comment by hbliu1985** [comment]
同样的问题，全局代理也不行

**Comment by sc1entist** [comment]
改了host之后能进去，但是不能加速，不知道咋设置

**Comment by minado008** [comment]
hosts 加个  59.153.40.90 prod.actual.battle.net 就好了

**Comment by godhangyu** [comment]
> 

我也是改host解决的，但是这个issue的目的不仅仅是玩d4，而是说这个代理解析dns没有生效

**Comment by Jetevos** [comment]
请教是否可以通过修改hosts的形式 加速一下 魔兽世界wow的初始化更新  经常卡初始化或者初始化很慢很慢

**Comment by hang1233** [comment]
> hosts 加个 59.153.40.90 prod.actual.battle.net 就好了

感谢
prod.actual.battle.net 默认解析的 cn.actual.battle.net(43.247.78.73)是位于杭州的网易服务器
可以强制解析成 kr.actual.battle.net (59.153.40.90) 或者 us.actual.battle.net (137.221.104.172)

**Comment by kalagxw** [comment]
有没有可能是代理不支持udp

**Comment by hyy34** [comment]
> > hosts 加个 59.153.40.90 prod.actual.battle.net 就好了
> 
> 感谢 prod.actual.battle.net 默认解析的 cn.actual.battle.net(43.247.78.73)是位于杭州的网易服务器 可以强制解析成 kr.actual.battle.net (59.153.40.90) 或者 us.actual.battle.net (137.221.104.172)

请问，代理暗黑4有无教程可供参考。如何加速暗黑4呢？模式里面没找到暗黑4呢。

**Comment by alisterk** [comment]
@hyy34 
1. hosts 加 59.153.40.90 prod.actual.battle.net 
2. netch 创建进程模式, 处理规则 处, 点击"扫描"按钮,选择暗黑4的安装根路径:
![image](https://github.com/netchx/netch/assets/14232993/278abd2c-03c4-4233-aa2d-e08a9eb2d6a8)
如果扫描后看到这个一样的列表,就直接保存, 之后就可以正常加速了

![image](https://github.com/netchx/netch/assets/14232993/6d474752-818a-4f78-b870-b2e5bea6ebd2)

**Comment by alisterk** [comment]
另外, 暗黑4应该是没有用udp协议,所以即使你用的服务器不支持udp,好像也没关系

**Comment by hang1233** [comment]
> 另外, 暗黑4应该是没有用udp协议,所以即使你用的服务器不支持udp,好像也没关系

是的，老老实实用加速器吧

**Comment by space22k** [comment]
59.153.40.90 好像是被封了，连不上

改了dns 8.8.8.8 也不行

在 https://www.nslookup.io/domains/prod.actual.battle.net/dns-records/ 上找个最新的ip改下hosts就可以了

34.125.17.43
