### ISSUE TITLE
建议“进程模式”弄一个“代理全部进程”的选项

### ISSUE THREAD

**Issue by lunhuil** [netchx/netch#106]
**功能描述**
个别游戏进程并非全部是.exe
这样就会漏掉进程，造成游戏加速失败
建议在现有进程模式进行加强
1.代理全部进程 （进程名称写入日志，方便找到漏掉的进程）
2.代理所有新进程（已存在的进程不受影响）
3.排除指定进程（其他的全部代理）

**额外信息**
建议思路来源一个 Super Socks5Cap 的游戏加速软件

**Comment by BingLingGroup** [comment]
1. 日志里现在就有进程名，在`redirector.log`里
2. 现在难道不是吗
3. 白名单进程代理这个 ……问 CR 吧

**Comment by ghost** [comment]
1. 建议从 binaries 文件夹里下载最新的 Redirector 以获得 UDP 日志
2. 不太考虑，我没需求（先挂着吧，其他人要了再说，看人数决定）
3. 这个可以有

**Comment by lunhuil** [comment]
> 1. 建议从 binaries 文件夹里下载最新的 Redirector 以获得 UDP 日志
> 2. 不太考虑，我没需求（先挂着吧，其他人要了再说，看人数决定）
> 3. 这个可以有

更正一下第一条建议的描述 之前的描述不太准确
1.代理所有进程（不指定进程  Netch 启动后即代理所有进程）

我不确定现在有没有这个功能，我没找到， 如果已经有了那就更好了

另外还想到一个功能

启动Netch 自动启动（连接）代理，并最小化窗口

免去每次点击的过程

**Comment by SmRiley** [comment]
3.白名单模式确实可以有,很期待

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/commit/a0fbcb588dad6b189f92b4733fdf062955f6c1a3
