### ISSUE TITLE
我看了下C++源码，发现好像DNS只判断了UDP，如果DNS使用了TCP协议怎么办

### ISSUE THREAD

**Issue by snltty** [NetchX/Netch#1063]
### 功能描述
我用作者的C++代码去自己写了个界面
看了下C++源码，发现好像DNS只判断了UDP，如果DNS使用了TCP协议怎么办
只在 EventHandler.cpp --> udpSend 方法中看到DNS判断

只因为，我使用进程劫持去代理steam，发现商店可以代理，但是社区不行
但是，我代理chrome.exe的话，商店、社区就都是可以的，所以有此怀疑

**Comment by Yuki-J1** [comment]
不用代理 抓包看看发出的是否是UDP DNS查询
