### ISSUE TITLE
Maybe it doesn't handle DNS requests at all.

### ISSUE THREAD

**Issue by EXStevens** [NetchX/Netch#1069]
### Describe the bug

Updated to 1.7.6 version recently, Roblox keep erroring "HttpError:DnsResolve", 
After some exhaust, I found that it was still using my system DNS, OpenDNS became unavailable in China mainland suddenly so I changed my system DNS and Roblox just ran normally.  It didn't handle DNS requests at all, even I enabled it in the configuration file.

### To Reproduce

1. Open Netch
2. Set your system DNS to some unreachable addresses in system settings
3. Write a process mode configuration file, Including Microsoft Edge & Webview and Roblox
> ![image](https://github.com/netchx/netch/assets/84963206/0225e486-25aa-47ce-8989-3e9d91bf6f64)
4. Start Netch
5. Try opening Roblox and Microsoft Edge

### Log

Already deleted
Some fragment according to my memory:
```
udpSend 8.8.8.8:53
```
etc.
That's weird, I didn't set 8.8.8.8 as Netch DNS, and the alternative DNS of the system is Google DNS DoH only.

### Environment

```txt
- OS: Windows 11 Pro 23H2
- Netch: 1.7.3
- Protocol: Vmess
- ESET InternetSecurity Enforcing
```

**Comment by AngusYang-82** [comment]
when can fix it?

**Comment by gg340th** [comment]
(for process mode) You have to whitelist svchost.exe. Problem is, if you do that and set a proxy, it will try to resolve the proxy host, and then it would then try to proxy that dns request over the proxy, and to do that it would try to resolve it again and ..... This is not implemented in the current version apparently
