### ISSUE TITLE
停止netch对某个进程的加速后，会连带关闭Clash for windows的代理开关

### ISSUE THREAD

**Issue by qaszxcwer** [netchx/netch#107]
**复现步骤**
1. 打开 Netch 软件和Clash for windwows
2. clash for windows 开启system proxy
3. Netch 启动对某个进程的加速
4. 停止Netch的加速
5. 回到clash for windows，将选项从general切换到proxies，再切换回来，可以看到system proxy的开关从on 变成了 off

**信息**
 - 操作系统：[Windows 10 家庭版 64 位 1903]
 - 软件版本：[Netch为1.2.0] [Clash for windows为0.7.6]

**Comment by ghost** [comment]
您好，BUG 是存在的，将会在近期处理

**Comment by BingLingGroup** [comment]
此 bug 已在 [1.2.8-BETA](https://github.com/NetchX/Netch/releases/tag/1.2.8-BETA) 中修复
