### ISSUE TITLE
进程模式扫描出的不准确

### ISSUE THREAD

**Issue by SynTaozi** [NetchX/Netch#1089]
### 功能描述

我想知道进程模式中的exe是如何得出的，我自己扫描出来exe后大部分游戏都加速不了

**Comment by SakuraChanNya** [comment]
The "扫描" function in process mode has been deprecated, please use "选择" to select the entire game root directory.

**Comment by SynTaozi** [comment]
> 处理模式下的“扫描”功能已被弃用，请使用“选择”选择整个游戏根目录。
我选择的就是游戏根目录，他会扫描出所有的exe文件进行加速，但是我实际测试基本没有作用

**Comment by SynTaozi** [comment]
> 处理模式下的“扫描”功能已被废弃，请使用“选择”选择整个游戏根目录。
我选择的就是游戏根目录但是，他会扫描出所有的exe文件进行加速，我实际测试基本没有作用

**Comment by SynTaozi** [comment]
我发现他内置的一些游戏进程规则却可以正常使用，比如：PUBG，但是我扫描PUBG出来的却和内置的不同且不能正常使用

**Comment by SakuraChanNya** [comment]
> > 处理模式下的“扫描”功能已被废弃，请使用“选择”选择整个游戏根目录。
> > 我选择的就是游戏根目录但是，他会扫描出所有的exe文件进行加速，我实际测试基本没有作用

Please do not use the 扫描 button,use 选择 button.

**Comment by SakuraChanNya** [comment]
> 我发现他内置的一些游戏进程规则却可以正常使用，比如：PUBG，但是我扫描PUBG出来的却和内置的不同且不能正常使用

Sorry, latest test results show that the 选择 button is broken.  Only the 扫描 button can be used. 
In addition, routing table modes can also be used, such as bylass lan (and china).

**Comment by SynTaozi** [comment]
> > 我发现他内置的一些但是游戏进程规则却可以正常使用，比如：PUBG，我扫描PUBG出来的却和内置的不同且不能正常使用
> 
> 抱歉，最新测试结果显示“选择”按钮已损坏。只能使用扫描按钮。 另外，还可以使用路由表模式，例如bylass lan（和china）。
我尝试了选择和扫描都不可以正常加速PUBG

**Comment by SynTaozi** [comment]
> > 我发现他内置的一些但是游戏进度规则却可以正常使用，比如：PUBG，我扫描PUBG出来的却和内置的不同且不能正常使用
> 
> 抱歉，最新测试结果显示“选择”按钮已损坏。只能使用扫描按钮。 另外，还可以使用路由表模式，例如bylass lan（和china）。
**我尝试了选择和扫描都不可以正常加速PUBG**

**Comment by SynTaozi** [comment]
> > 我发现他内置的一些但是游戏详情规则却可以正常使用，比如：PUBG，我扫描PUBG出来的却和内置的不同且不能正常使用
> 
> 抱歉，最新测试结果显示“选择”按钮已损坏。只能使用扫描按钮。 另外，还可以使用路由表模式，例如bylass lan（和china）。

**我尝试了选择和扫描都不能够正常加速PUBG**

**Comment by SakuraChanNya** [comment]
> > > 我发现他内置的一些但是游戏详情规则却可以正常使用，比如：PUBG，我扫描PUBG出来的却和内置的不同且不能正常使用
> > 
> > 
> > 抱歉，最新测试结果显示“选择”按钮已损坏。只能使用扫描按钮。 另外，还可以使用路由表模式，例如bylass lan（和china）。
> 
> **我尝试了选择和扫描都不能够正常加速PUBG**

Try "bypass lan and china", it doesn't hijack the process's traffic, it uses a virtual network card to proxy game and system traffic.

**Comment by SynTaozi** [comment]
> > > > 我发现他内置的一些但是游戏详情规则却可以正常使用，比如：PUBG，我扫描PUBG出来的却和内置的不同且不能正常使用
> > > 
> > > 
> > > 抱歉，最新测试结果显示“选择”按钮已损坏。只能使用扫描按钮。另外，还可以使用路由表模式，例如bylass lan（和china）。
> > 
> > 
> > **我尝试选择和扫描都不能够正常加速PUBG**
> 
> 尝试“绕过局域网和中国”，它不会劫持进程的流量，它使用虚拟网卡来代理游戏和系统流量。

**路由模式确实是可以的，但是我是想要二开netch, 所以想要搞清楚进程模式，想知道其他加速器是怎样获取到的进程**
