### ISSUE TITLE
游戏代理不上(1.2.4之后的版本)

### ISSUE THREAD

**Issue by VerryX** [netchx/netch#109]
**错误描述**
Netch 1.2.5-1.2.8版本
NatTypeTester测试似乎不走代理，测试之后nat类型是Symmetric，不显示节点ip。
用1.2.4版本可以Fullcone，游戏也正常。
[redirector.log](https://github.com/NetchX/Netch/files/3572823/redirector.log)
[shadowsocks.log](https://github.com/NetchX/Netch/files/3572833/shadowsocks.log)

极限竞速地平线4也无法加入在线游戏
同一节点在另一台Win10 1809 64位电脑用1.2.8开NatTypeTester测试，nat类型是portrestrict，可显示节点ip
![nattype](https://user-images.githubusercontent.com/42909782/64227809-796e9b00-cf17-11e9-85f9-eaf53ecab5e0.PNG)

**复现步骤**
1. 打开 Netch 软件
2. 运行NatTypeTester, 地平线4

**错误截图**

**信息**
 - 操作系统：[例如 Windows 10 1903 18362.295 专业版 64 位]
 - 软件版本：[例如 1.2.8-BETA 64 位]

**Comment by BingLingGroup** [comment]
将新版本里的 `bin/Redirector.exe` 更换为 1.2.5 及之前的可解，详见 readme 里的 [FAQ（刚刚加上）](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#%E8%BF%9B%E7%A8%8B%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%B8%B8%E6%88%8F%E6%97%A0%E6%B3%95%E4%BB%A3%E7%90%86%E6%88%90%E5%8A%9F)
