### ISSUE TITLE
请问这个软件能不能多次中转？

### ISSUE THREAD

**Issue by a8833461** [NetchX/Netch#1094]
### 功能描述

route table 好像不能实现。
比如我有两个ssr节点，一个在美国，一个在新加坡，
我要如何才能让本机的流量从美国转到新加坡然后再访问目标网站？
就像跳板一样，这个要怎么跳？

**Comment by Klosw** [comment]
> ### 功能描述
> route table 好像不能实现。 比如我有两个ssr节点，一个在美国，一个在新加坡， 我要如何才能让本机的流量从美国转到新加坡然后再访问目标网站？ 就像跳板一样，这个要怎么跳？

我觉得不行  ，逻辑上就不对 除非你能在你新加坡 的机器上写上 代理 才可以吧
