### ISSUE TITLE
订阅连接只有部分节点

### ISSUE THREAD

**Issue by swhoro** [netchx/netch#11]
使用某一订阅连接的时候只有部分节点，sstap和ssr订阅正常。
我的另一个订阅连接在netch里可以正常使用

**Comment by ghost** [comment]
更新订阅后不关闭 Netch，然后去看 `logging` 文件夹里的 `application.log` 文件

**Comment by ghost** [comment]
因为有一些不受支持的 加密方式、协议、混淆 在其中，所以没有被完全导入
