### ISSUE TITLE
Can’t connect to any IPv4 websites

### ISSUE THREAD

**Issue by Gmadokus** [NetchX/Netch#1111]
### Describe the bug

This has happened to me twice: one time on window 10 and one time on windows 11.
So when I try to connect to my vmess server, I get connected but it says: NoHTTP, NoUDP and I can only open websites that support ipv6. Only ipv4 websites don’t work.

I tried to reset network settings, reinstall network drivers, delete Netch and config in appdata, I tried to enable AllowInsecure in V2ray settings. None of this helped. Reinstalling windows helped. First time it happened on windows 10 Pro. I couldn’t find how to fix it. Then I installed Windows 10 ltsc and everything worked. But then I installed Windows 11 and Netch was broken again. I don’t understand why this happened. Besides Netch everything works fine. Even regular vpns (not vmess tho). But Netch is the only one having issues. I tried older versions but they all had issues

### To Reproduce

Open Netch and try to
Connect to the vmess server

### Log

-

### Environment

```txt
Windows
```

### Additional information

No

**Comment by keeptpa** [comment]
Hi!
Willing to share some info about the protocol you use in Netch?
Wondering if you're using any flow control etc. Don't forget to mask your address.
