### ISSUE TITLE
Netch无法对IPV6实现代理（使用Netch无法访问ChatGPT）

### ISSUE THREAD

**Issue by Pcyslist** [NetchX/Netch#1116]
### 错误描述

在访问ChatGPT时，发现被判定为VPN访问，通过检查IP，发现自己的IPV4地址是美国，IPV6地址却还是大陆，这才导致ChatGPT判定为限制区域。
解决办法：打开网络连接设置，修改网络适配器的属性，将属性中的"Internet 协议版本 6 (TCP/IPv6)勾选去掉，即可。

### 复现步骤

无

### 日志

无

### 操作环境

```txt
Win10 64
```

**Comment by good-bay** [comment]
禁用IPV6地址就可以了。

**Comment by Pcyslist** [comment]
@good-bay 谢谢，另外请问你知道如何解决在使用PPPOE连接的情况下，Netch代理失败的问题么？

**Comment by good-bay** [comment]
把PPPOE拨号放在光猫或路由器里进行,电脑再使用Netch来代理.
最新版Netch有问题,用1.9.4没问题.
Netch已经长久没有维护了,建议你换别的代理软件.

**Comment by RAINighty** [comment]
> 把PPPOE拨号放在光猫或路由器里进行,电脑再使用Netch来代理. 最新版Netch有问题,用1.9.4没问题. Netch已经长久没有维护了,建议你换别的代理软件.

请问还有什么其他同类型的软件嘛？能推荐一下吗

**Comment by good-bay** [comment]
> > 把PPPOE拨号放在光猫或路由器里进行,电脑再使用Netch来代理. 最新版Netch有问题,用1.9.4没问题. Netch已经长久没有维护了,建议你换别的代理软件.
> 
> 请问还有什么其他同类型的软件嘛？能推荐一下吗

https://github.com/MatsuriDayo/nekoray
https://github.com/2dust/v2rayN
https://github.com/clash-verge-rev/clash-verge-rev
https://github.com/hiddify/hiddify-next
