### ISSUE TITLE
缩放问题

### ISSUE THREAD

**Issue by meymself** [netchx/netch#112]
**错误描述**
缩放设置为125%时字体模糊

bypass lan and china正常
其余绕过大陆模式无法使用chrome访问需代理页面

**信息**
 - 操作系统：[例如 Windows 10 专业版 64 位]
 - 软件版本：[例如 1.2.8-beta64 位]

**Comment by BingLingGroup** [comment]
1. 字体模糊已经有类似问题提出 #65 
2. 经测试，bypass lan 和 TUN/TAP 也可以正常代理 chrome 浏览器，除此之外非系统代理的模式，需要 chrome 设置 SwitchyOmega 才能使用。你可以能对其他模式产生了什么误会，参见[模式介绍](https://github.com/NetchX/Netch/blob/master/docs/USAGE.zh-CN.md#模式介绍)
