### ISSUE TITLE
Netch freeze 

### ISSUE THREAD

**Issue by toobi57** [NetchX/Netch#1124]
### Describe the bug

Netch freeze and network stops so not only me having this issue some of my friends also having this issue 1 of my friend said when netch was running he open yt and launched a video and his entire lap crashes blue screen so after blue screen he turns on the lap again and when ever he starts the netch his entire lap lags his specs i7 10 gen 3060ti 16gb ram

### To Reproduce

open netch leave it on use it for like couple hours it will start to lag the entire pc 

### Log

..

### Environment

```txt
win 10 and 11
```

**Comment by deadash** [comment]
Connection Interruption in nfsdk Demo Version Due to TCP/UDP Limitations
