### ISSUE TITLE
默认规则中Discord客户度更新失败无法访问

### ISSUE THREAD

**Issue by zjqyf** [NetchX/Netch#1125]
### Describe the bug

使用默认规则中Discord的规则无法更新Discord客户端，打开时一直在重试更新，确定VPN是有效的，因为在网页版是可以使用的。最新版如果使用Tun/Tap Bypass LAN and China模式也不能正常打开Discord客户端（但是1.8.4版的可以），但我只希望使用Disocrd。
我尝试自己创建一个进程模式，添加Update.exe和Discord.exe或者使用\\Discord\\的方式添加整个Discord目录都不行

### To Reproduce

1.打开Netch
2.从订阅的地址更新VPN
3.使用Tun/Tap Bypass LAN and China或选择默认的Discord规则
4.启动
5.打开Discord的PC客户端
6.一直在重试更新Discord

### Log

[application.log](https://github.com/netchx/netch/files/14477876/application.log)
[V2Ray (SagerNet).log](https://github.com/netchx/netch/files/14477877/V2Ray.SagerNet.log)

### Environment

```txt
os:win11 23H2 内部版本22631.3155
netch:1.9.7
```

**Comment by pyhabyss** [comment]
同样的情况。测试1.9.2可以正常使用，之后的版本在我这里discord都不行，其他功能正常。

**Comment by 26z1a** [comment]
版本:1.9.7
使用以下mode,服务器是本地socks的时候dc可用
```json
{
  "type": "ProcessMode",
  "remark": {
    "zh-CN": "dc",
    "en-US": "dc"
  },
  "handle": [
    "DiscordHookHelper\\.exe",
    "DiscordHookHelper64\\.exe",
    "capture_helper\\.exe",
    "Discord\\.exe",
    "Update\\.exe"
  ],
  "bypass": [],
  "filterIntranet": true,
  "filterLoopback": false,
  "dnsHost": "1.1.1.1:53",
  "handleOnlyDNS": null,
  "icmpDelay": 10,
  "filterParent": true,
  "filterDNS": true,
  "filterUDP": null,
  "filterTCP": null,
  "filterICMP": null,
  "dnsProxy": null
}
```

PS:我也是进程模式对准dc文件夹scan了一下.. ~~这看上去和默认配置也没什么不同?~~ 是不是因为是我用socks的原因?
