### ISSUE TITLE
bin\default.acl 规则什么模式下会加载？

### ISSUE THREAD

**Issue by HonorWater** [netchx/netch#114]
由于Netch开启SSR服务后onenote无法正常更新，我自己尝试去更新bin\default.acl，但是发现不论是 (4,5,6)bypass LAN & China 还是 (4,5,6）Bypass LAN 都没有任何效果。
是不是我还有其他地方需要一起修改？谢谢。。。

**Comment by tindy2013** [comment]
@HonorWater TUN/TAP 模式使用内置规则列表而不使用该 ACL 文件。如果有需要，我们可在下一版本中对该规则列表进行更新。

**Comment by BingLingGroup** [comment]
只会在 shadowsocks-libev 和 shadowsocksr-libev Bypass China 的情况下使用，Bypass LAN 不会使用。相关代码 [SSController.cs](https://github.com/NetchX/Netch/blob/master/Netch/Controllers/SSController.cs#L54-L57)，[SSRContoller.cs](https://github.com/NetchX/Netch/blob/master/Netch/Controllers/SSRController.cs#L64-L67)

至于 onenote 无法更新，和跳过国内地址的规则有关系吗……是跳过了有影响，还是没跳过有影响……

**Comment by HonorWater** [comment]
我之前使用的Windows原版的ShadowsocksR，onenote也有问题，最后是用了下面方案解决掉的：
https://blog.csdn.net/MrBaymax/article/details/84869329

其实在原始的 default.acl  （你们直接用的是ALC4SSR维护的版本）中已经包含的onenote对应的域名：live.net, live.com，但是依然无法正常更新，但是由于Netch中没有user-rule.txt，没办法参照上面的解决办法。

**Comment by BingLingGroup** [comment]
`user-rule.txt` 指的是类似 `shadowsocks-windows` 的编辑用户规则吧，Netch 没有做 PAC 的功能，像 ALC 这种是因为可以在命令行里面直接加个参数启动所以内置了，`user-rule.txt` 这个估计工程量要大一些，得看有没有人愿意做了
