### ISSUE TITLE
学习求救 

### ISSUE THREAD

**Issue by weisiok365** [NetchX/Netch#1143]
### 功能描述

I can't intstall netch.git，please help for you ！！！
mikemsn98@outlook.com
thank you

**Comment by qixing-jk** [comment]
@weisiok365 Do you want to install "netch.git"? Do you want to develop netch?
If not, just download and install the files in the releases directly.

**Comment by weisiok365** [comment]
hello!
________________________________

**Comment by weisiok365** [comment]
Thank you ,you reply me when you're so busy
To be my heart,I am a very very beginner , it's very happy to me ,you invite me to join you
,only, I worry bout my ability affect your develoption.
First,can you teach me install "netch" for linux ?
________________________________

**Comment by weisiok365** [comment]
I hope you teach me to develop this project !! To constantly enhance my ability
Besides,how can i join you?

________________________________

**Comment by qixing-jk** [comment]
Officially only supports Windows, not Linux

**Comment by weisiok365** [comment]
oh
My ability is no
________________________________

**Comment by weisiok365** [comment]
Can you accept me ?
Need me what to do?

________________________________

**Comment by weisiok365** [comment]
I 'm from china
________________________________

**Comment by weisiok365** [comment]
I want to surf to internet ,but i can't to internet abroad .
Where're you from?
Welcome to tour in my country

________________________________

**Comment by weisiok365** [comment]
[cid:fbe04302-92d6-4284-8516-1e3dc033608b]
*
Tar.gz，how to install ?
________________________________
