### ISSUE TITLE
希望增加更直观的代理情况显示

### ISSUE THREAD

**Issue by imoldchen** [netchx/netch#115]
**功能描述**
1.在界面中直接查看实时日志（更直观代理使用情况，反馈也更精准）
2.显示当前代理了哪些进程（上行/下行/总流量，方便排除一些可不代理的进程）
3.查看当前代理的exe相关的进程（参考：有些韩国游戏是非exe也要添加到进程，但对新手来说无法获知）

**额外信息**
1和2可能需要的人会比较多；
3的话估计开发也很复杂（对个人来可有可无，看部分人反馈要全局代理，估计是以为全局代理了，有些不能被代理的也可以工作，这是个误区，有些游戏必须VPN才行。）

**Comment by BingLingGroup** [comment]
你指的是进程模式吧。

1. 这个现在已经在做了，而且最新版的 `Redirector.exe` 已经有这个功能了
2. 代理了哪些进程这个以前就有，详见 `logging/Redirector.log`
3. 我理解你的意思，大概是类似 Sockscap64 的代理方式，不过 `Netfilter SDK` 的底层原理应该和 Sockscap64 不太一样，这个得问 CR 了。另外如果你觉得新手无法获知，那你可以制作一个可用的规则，并上传到子项目 [NetchX/NetchMode](https://github.com/NetchX/NetchMode) 当中

**Comment by imoldchen** [comment]
> 你指的是进程模式吧。
> 
>     1. 这个现在已经在做了，而且最新版的 `Redirector.exe` 已经有这个功能了
> 
>     2. 代理了哪些进程这个以前就有，详见 `logging/Redirector.log`
> 
>     3. 我理解你的意思，大概是类似 Sockscap64 的代理方式，不过 `Netfilter SDK` 的底层原理应该和 Sockscap64 不太一样，这个得问 CR 了。另外如果你觉得新手无法获知，那你可以制作一个可用的规则，并上传到子项目 [NetchX/NetchMode](https://github.com/NetchX/NetchMode) 当中

感谢答复，是的，进程模式。
２.主要是不想去查看日志文件，而在程序界面显示更便捷直观一点。

**Comment by BingLingGroup** [comment]
我知道了，你大概指的是 `shadowsocks-windows` 那种有实时输出的显示界面，可以考虑

**Comment by xishijt** [comment]
其实3的话,可以通过手动编辑规则文件,添加绝对路径的方式,比如手动添加D:\black desert\bin64\abe.xem来解决.

**Comment by imoldchen** [comment]
哈哈，韩服黑沙。不添加绝对路径就不能代理吗？

**Comment by xishijt** [comment]
> 哈哈，韩服黑沙。不添加绝对路径就不能代理吗？

因为创建规则那边不能选EXE,所以只能手动添加,结果是居然有效.也不理解为什么棒子的某些可执行文件不用exe后缀.

**Comment by imoldchen** [comment]
我的意思是在规则里填 abe.xem 能代理吗？还是必须完整的路径

**Comment by xishijt** [comment]
> 我的意思是在规则里填 abe.xem 能代理吗？还是必须完整的路径

这个就不清楚了...
我用绝对路径是因为我之前设置了chrome.exe,结果连带着360chrome.exe也被代理了.所以后面一直都用绝对路径.
