### ISSUE TITLE
驱动更新失败

### ISSUE THREAD

**Issue by ouuuo** [netchx/netch#117]
![image](https://user-images.githubusercontent.com/18564287/64438938-8e0b8880-d0fb-11e9-8ce9-54696a03a7a1.png)
操作系统
![image](https://user-images.githubusercontent.com/18564287/64438997-a8456680-d0fb-11e9-8f44-5baf4611fece.png)
netch版本:
![image](https://user-images.githubusercontent.com/18564287/64439039-b85d4600-d0fb-11e9-9f5a-de762e490643.png)

**Comment by lw007** [comment]
应该是NF问题，我另外一台电脑可以

**Comment by ghost** [comment]
@lw007 是否安装 Win7 所需的补丁？已知 Win7 不打补丁会导致无法正常校验驱动的签名证书

**Comment by ouuuo** [comment]
@ConnectionRefused #14 这个问题的吗？需要手动打补丁？我看这个bug不是已经fix掉了

**Comment by BingLingGroup** [comment]
真是服了，那个是指在 doc 里面加入了关于这个 bug 的描述，从而修复了文档。Netch 怎么能修 windows 的 bug，我锁评论了，再有问题开新问题。
