### ISSUE TITLE
服务器是Socks5的情况下，模式二（黑名单模式）无法代理

### ISSUE THREAD

**Issue by CoderTyn** [netchx/netch#119]
服务器是Socks5的情况下，模式二（黑名单模式）无法代理

Win10 x64 
1.2.7 stable x64

**Comment by BingLingGroup** [comment]
你有修改模式文件吗，readme 里面说了模式二需要自己改文件。
另外底层 tun2socks 就是支持 Socks5 的，如果你的规则来源于 SSTap-rule，你需要检查 SSTap-rule 那边的规则是否有效。
你也可以通过在命令行中输入 `netstat -nr` 来查看路由表，我刚才看了路由表加得没什么问题。

**Comment by CoderTyn** [comment]
> 你有修改模式文件吗，readme 里面说了模式二需要自己改文件。
> 另外底层 tun2socks 就是支持 Socks5 的，如果你的规则来源于 SSTap-rule，你需要检查 SSTap-rule 那边的规则是否有效。
> 你也可以通过在命令行中输入 `netstat -nr` 来查看路由表，我刚才看了路由表加得没什么问题。

**Comment by CoderTyn** [comment]
@BingLingGroup  开发者你好，模式我改了，见下图，路由表信息对比sstap如下。sstap可以代理但是这个不行，我以为是dns的问题在路由表也加了两条，但还是不行
![image](https://user-images.githubusercontent.com/46312580/64576612-f84a5480-d3ab-11e9-9e55-a84718ae63ba.png)
上图是模式文件
![image](https://user-images.githubusercontent.com/46312580/64576731-6f7fe880-d3ac-11e9-8dcc-132e840f9a78.png)
上图是Netch的路由表
![image](https://user-images.githubusercontent.com/46312580/64576936-56c40280-d3ad-11e9-9ccd-0600da3221d4.png)
上图是SSTap路由表。

请问还需要提供哪些材料以供分析？我整理一下，感谢！

**Comment by BingLingGroup** [comment]
DNS 的话，你是否在 Netch 的设置里面选中并设置了自定义 DNS，如果没有设置，意味着 tun2socks 使用了本地的默认 DNS。

**Comment by CoderTyn** [comment]
@BingLingGroup 设置并勾选自定义dns了，但是chrome显示ERR_CONNECTION_RESET。SSTap能打开，我找不着问题在哪。。

**Comment by BingLingGroup** [comment]
如果是代理 chrome，不建议使用模式二，而应该使用模式三。我用模式三，chrome 浏览网页没问题，当然前提是在使用模式三时没有使用 SwtichyOmega 这些插件，不然会受到影响。

**Comment by CoderTyn** [comment]
@BingLingGroup 

> 如果是代理 chrome，不建议使用模式二，而应该使用模式三。我用模式三，chrome 浏览网页没问题，当然前提是在使用模式三时没有使用 SwtichyOmega 这些插件，不然会受到影响。

代理韩服dnf，但是得网页登陆游戏。。。请问模式3白名单是不是得设置这个ip以外所有ip

**Comment by BingLingGroup** [comment]
模式三都说是白名单模式了，名单内的是直连，当然不要把你需要代理的 IP 加到名单里了。另外这个网页访问的 IP 地址连不上，说明和规则可能还是有点关系，我对 SSTap 了解不多，SSTap 是不是在代理时有开 http 系统代理啊，目前 Netch 还没有同时开启多个模式的功能。DNF 这个登录是游戏内置浏览器还是用的外部浏览器啊，如果是内置浏览器，我建议你还是先试试模式一吧，在代理游戏方面，首先推荐的是模式一，模式一不管用，再考虑模式二和模式三，如果是对规则代理很在意的，尝试模式二，否则模式三。模式三全局可解一切疑难杂症。

**Comment by CoderTyn** [comment]
> 模式三都说是白名单模式了，名单内的是直连，当然不要把你需要代理的 IP 加到名单里了。另外这个网页访问的 IP 地址连不上，说明和规则可能还是有点关系，我对 SSTap 了解不多，SSTap 是不是在代理时有开 http 系统代理啊，目前 Netch 还没有同时开启多个模式的功能。DNF 这个登录是游戏内置浏览器还是用的外部浏览器啊，如果是内置浏览器，我建议你还是先试试模式一吧，在代理游戏方面，首先推荐的是模式一，模式一不管用，再考虑模式二和模式三，如果是对规则代理很在意的，尝试模式二，否则模式三。模式三全局可解一切疑难杂症。

@BingLingGroup 好的感谢解答

**Comment by CoderTyn** [comment]
> 模式三都说是白名单模式了，名单内的是直连，当然不要把你需要代理的 IP 加到名单里了。另外这个网页访问的 IP 地址连不上，说明和规则可能还是有点关系，我对 SSTap 了解不多，SSTap 是不是在代理时有开 http 系统代理啊，目前 Netch 还没有同时开启多个模式的功能。DNF 这个登录是游戏内置浏览器还是用的外部浏览器啊，如果是内置浏览器，我建议你还是先试试模式一吧，在代理游戏方面，首先推荐的是模式一，模式一不管用，再考虑模式二和模式三，如果是对规则代理很在意的，尝试模式二，否则模式三。模式三全局可解一切疑难杂症。

@BingLingGroup 模式3也不行，路由设置应该没问题的，我再看看其它条件。

**Comment by BingLingGroup** [comment]
说来说去，你为什么不用模式一呢

**Comment by CoderTyn** [comment]
模式1 OK了
