### ISSUE TITLE
tun2socks crash

### ISSUE THREAD

**Issue by 57a4c324e742** [netchx/netch#121]
**Describe the bug**
The tun2socks crashed.

**To Reproduce**
1. Open Netch
2. Start with TUN/TAP mode
3. Browser internet and wait process crash

**Environment:**
 - OS: Windows 10 Version 1903
 - Netch Version: 1.2.8-BETA (commit bb7896361e201f411fe2c2f809da88115eb5e31f )

**Additional context**
See attachment.
[tun2socks-truncated.txt](https://github.com/NetchX/Netch/files/3603607/tun2socks-truncated.txt)

**Comment by rc452860** [comment]
I hava same issue
OS: Windows 10 Version 1903
Netch Version: 1.3.3

**Comment by rc452860** [comment]
I think can use this [tun2socks](https://github.com/Jigsaw-Code/outline-client/blob/master/third_party/badvpn/windows/badvpn-tun2socks.exe) replace.

**Comment by ghost** [comment]
tun2socks updated at [002da1](https://github.com/NetchX/NetchBinaries/commit/8002da1a868e15d37f204bf5dece3ed8c7de26cb)

download it and try
