### ISSUE TITLE
进程加速模式,流量统计不是很准

### ISSUE THREAD

**Issue by magiclu** [netchx/netch#122]
**Screenshots**

![image](https://user-images.githubusercontent.com/3338197/64858430-ef7eaa80-d659-11e9-92f1-a81a01314661.png)
这个是物理网卡,只有这两个选项是勾着的
![image](https://user-images.githubusercontent.com/3338197/64858526-3d93ae00-d65a-11e9-8c28-832835ceb031.png)
![image](https://user-images.githubusercontent.com/3338197/64858909-3f11a600-d65b-11e9-983e-c54d052af8f2.png)
![image](https://user-images.githubusercontent.com/3338197/64859015-a0397980-d65b-11e9-8c88-3f42be476869.png)
虚拟的网卡除了这几个没有勾选,别的都勾选了

**Environment (please complete the following information):**
 - OS:Windows 10 Pro 64-bit
 - Netch Version: 1.2.7-STABLE.x64

**Additional context**
我开了几个hyperv的虚拟机,用的External Virtual Switch,主机win10,开了bt下载器时,流量统计会把我bt下载器上传的流量算进去,下载的不算进去,bt下载器没有加入netch的进程列表里,进程列表里只有游戏

然后1天后看了一下机场的流量,并没有消耗多少,bt肯定没走netch,那么应该是netch误报了流量
这个误报挺吓人的,万一因为bt被机场封号就麻烦了

假如多个网卡,那么这个软件是怎么工作的?我是就一个物理网卡接口,别的都是虚拟的

**Comment by ghost** [comment]
1. 不太准是正常的
2. Netch 的进程代理模式不工作于网卡层，目前是在驱动层次劫持进程操作
3. 多个网卡，看你路由跃点数，哪个优先就是哪个出去

**Comment by VictorQR** [comment]
我的直接就不统计了。

**Comment by tindy2013** [comment]
@2670135311 流量统计暂时未加入

**Comment by chsbuffer** [comment]
1.4.11 流量统计回归,
请求再次测试

一周无响应此问题将关闭
