### ISSUE TITLE
最新版本对Minecraft的代理貌似有点问题

### ISSUE THREAD

**Issue by iPixelOldC** [netchx/netch#123]
1.代理方案是先开ssd，然后在netch里面添加127.0.0.1:1080的本地socks代理
2.在1.2.3的版本下，开启代理后，使用HMCL启动mc 1.8.9+labymod3会正常运行。但是在1.2.8中，会卡在loading条的labymod init（进度条是75%)阶段，无法响应。只能强杀进程。

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Netch Version: 正常代理版本1.2.3 无法代理版本1.2.8
 - Minecraft 版本 1.8.9 labymod3最新版

**Additional context**
日志：
- 1.2.3 [redirector.log](https://github.com/NetchX/Netch/files/3612712/redirector.log)
- 1.2.8 [redirector.log](https://github.com/NetchX/Netch/files/3612711/redirector.log)
- mc启动日志 https://textuploader.com/10m4b

**Comment by BingLingGroup** [comment]
请先参考 readme 里 [FAQ 这一节](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#%E8%BF%9B%E7%A8%8B%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E8%BF%9B%E5%85%A5%E6%B8%B8%E6%88%8F--%E6%97%A0%E6%B3%95%E6%88%90%E5%8A%9F%E4%BB%A3%E7%90%86)对 redirector 问题的解决方法，如果使用 redirector 稳定版后问题解决，可以确定就是 redirector 的问题了。注意，老版本 redirector 没有流量统计和速度统计的功能。这个问题已经有人在修了，稍安勿躁。

**Comment by iPixelOldC** [comment]
1. 使用的是内置的minecraft java模式
2.老版本都没问题，那应该不是ssd参数和代理进程名的问题

明白了，我继续用老版本吧（在替换为稳定版本后,使用1.2.8，mc启动成功）

**Comment by iPixelOldC** [comment]
最新版本1.3.2的也还是有问题，卡在LabyMod::init阶段，直接无响应了

**Comment by BingLingGroup** [comment]
建议到置顶 issue 去讨论，置顶 issue 负责讨论 Redirector.exe 的问题 #152

**Comment by iPixelOldC** [comment]
> 
> 
> 建议到置顶 issue 去讨论，置顶 issue 负责讨论 Redirector.exe 的问题 #152

嘛，只是提供一下我这边的测试结果，因为看到日志里面说更新了嘛。并且老版本的也一直可以用，也不是很在意2333
