### ISSUE TITLE
所有代理都无法使用

### ISSUE THREAD

**Issue by Smoovsky** [netchx/netch#124]
系统: win10 pro x64 1903

应该是我机器的问题
从某个时间节点开始sockscap64, proxfier, win2socks, kkcap以及Netch均无法使用

有管理员权限

redirector.log:
[Application][WSAStringToAddress] failed: 10022
Usage: None

application.log:
[16-Sep-19 9:51:30 PM] 当前系统语言：en-US
[16-Sep-19 9:51:30 PM] 当前程序语言：en_US
[16-Sep-19 9:52:14 PM] NF 进程启动失败
[16-Sep-19 9:52:44 PM] NF 进程启动失败
[16-Sep-19 9:52:45 PM] NF 进程启动失败

**Comment by ghost** [comment]
既然您已经觉得是自己机器的问题了，那请自行查找解决方案

**Comment by Smoovsky** [comment]
> 既然您已经觉得是自己机器的问题了，那请自行查找解决方案

今天查找了下原因，是因为机器在解析localhost的时候默认使用了ipv6（服务器是本地）

解决方法：
https://superuser.com/questions/586144/disable-ipv6-loopback-on-windows-7-64-bit
