### ISSUE TITLE
1.2.9 无法加速

### ISSUE THREAD

**Issue by iceJourney** [netchx/netch#126]
**Describe the bug**
自1.2.7覆盖升级为1.2.9，驱动升级文件已经运行，运行程序，流量统计为0，游戏未见加速。

**Screenshots**
1.2.9：
![image](https://user-images.githubusercontent.com/18734597/65050689-638eba80-d99a-11e9-9fa2-fe685d37572f.png)
![image](https://user-images.githubusercontent.com/18734597/65050737-7b663e80-d99a-11e9-905e-7fffe06e8c0e.png)
默认设置，无改动，流量统计为0，游戏无法连接至服务器

1.2.7：
![image](https://user-images.githubusercontent.com/18734597/65050823-9cc72a80-d99a-11e9-8383-a112a24dcb5c.png)
启动后即有网络流量，游戏正常运行

**Environment (please complete the following information):**
 - OS: Microsoft Windows [版本 10.0.18362.356]
 - Netch Version: 1.2.9
 - Clash 0.7.8，运行netch前已经取消system proxy选项并且关闭软件

**Comment by ghost** [comment]
@iceJourney 看看频道 https://t.me/Netch

**Comment by ghost** [comment]
@iceJourney 另附：Clash 老版本不支持 UDP 转发

**Comment by ghost** [comment]
@iceJourney 写错频道了，是这个 https://t.me/NetchX

**Comment by iceJourney** [comment]
emm 运行前我已经关闭了clash啊，跟clash的udp转发没关系吧
今晚新版本（1.2.9）完全不能登录，我回退回1.2.7就能使用了

tele的频道我有加入，看了下最新版本下面说的是redirector的事？
我尝试替换了还是无法加速（apex with origin）

**Comment by iceJourney** [comment]
[redirector.log](https://github.com/NetchX/Netch/files/3624216/redirector.log)
刚才又试了下，tele频道下载的1.2.9 x64版本，clash进程直接关闭，运行，log里面的上传下行都是0，不知道是什么原因造成
然后使用1.2.7 x64，代理正常

**Comment by ghost** [comment]
你要被代理的程序放在中文路径下嘛？（或者程序名是中文嘛？）

**Comment by iceJourney** [comment]
没有，apex和origin安装都是全英文目录

**Comment by ghost** [comment]
那还请使用 1.3.0 最新版本试试

**Comment by iceJourney** [comment]
吼

**Comment by ghost** [comment]
从日志里，我都没看到 Apex Legends 的进程有 tcpConnectRequest 出来，Origin 倒是全是 HANDLE 的

**Comment by iceJourney** [comment]
[redirector.log](https://github.com/NetchX/Netch/files/3625909/redirector.log)
这个是1.2.7正常的log，里面r5apex和origin都有

上份日志没有apex是因为origin就没被代理上，我直接就卡在平台登录的一步了hhh 所以没有apex进程

**Comment by iceJourney** [comment]
1.3.0还是不行
log: 
[redirector.log](https://github.com/NetchX/Netch/files/3625950/redirector.log)
![Snipaste_2019-09-18_18-47-14](https://user-images.githubusercontent.com/18734597/65142285-f97f1f80-da44-11e9-8be3-0138dd742c74.png)
橘子平台就没有被代理上，直接线上不可用，无法登陆

**Comment by BingLingGroup** [comment]
先关了，参见 #152
