### ISSUE TITLE
新版本Redirector似乎影响Xboxlive 服务器连接

### ISSUE THREAD

**Issue by VerryX** [netchx/netch#127]
**Describe the bug**
新版本Redirector似乎会影响Xboxlive 服务器连接，测试了1.2.4，1.2.8，1.3.0的，其中1.2.4的正常，用后面的版本检查会显示服务器连接已阻止，会导致游戏无法进入线上。不知道是否是个例。

**To Reproduce**
1. Open Netch
2. 打开Win10设置->游戏->Xbox网络，检查。检查完毕关掉再打开继续检查，共3次

**Screenshots**
替换了1.2.4版本的Redirector
![22](https://user-images.githubusercontent.com/42909782/65110345-5fe74c00-da0b-11e9-8493-256724d6fdcd.PNG)
1.2.8-1.3.0版本
![33](https://user-images.githubusercontent.com/42909782/65110422-6d9cd180-da0b-11e9-8885-97d695889cc7.PNG)

Log
1.2.4
[1.2.4 redirector.log](https://github.com/NetchX/Netch/files/3624386/1.2.4.redirector.log)
1.2.9
[1.2.9 redirector.log](https://github.com/NetchX/Netch/files/3624388/1.2.9.redirector.log)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 1903 Pro 64-bit 18362.295]
 - Netch Version: [Netch 1.2.9.x64]

**Comment by ghost** [comment]
我们发布了 1.3.0 最新版本，请重新测试一下

**Comment by VerryX** [comment]
试了还是不行呀，游戏(地平线4提示无法解析服务器地址，请检查DNS。)
dns改成谷歌的了还是不行，xbox live那里检查服务器连接还是显示已阻止。

**Comment by BingLingGroup** [comment]
先关了，参见 #152
