### ISSUE TITLE
我记得之前在你们这边曾经见到一个SS的项目

### ISSUE THREAD

**Issue by perfect-network** [netchx/netch#128]
大概两个月前，从你们这里（可能是readme或者NetchX的其他项目，NetchX star的项目等）点击跳转到一个项目，项目大概是shadowsocks for sspanel，但是我现在怎么都找不到了！！！请问有没有知道的大佬？

**Comment by ghost** [comment]
请上 Telegram 查找 `Kuroha の 资源聚合` 频道，那里有最新的代码压缩包

**Comment by perfect-network** [comment]
> 请上 Telegram 查找 `Kuroha の 资源聚合` 频道，那里有最新的代码压缩包

为啥再GitHub下线了？不维护了吗？如果不维护了  那也没什么意思了

**Comment by BingLingGroup** [comment]
应该是还在维护，不开源是因为怕被二改卖钱所以低调点？大概这样（揣摩上意

**Comment by ghost** [comment]
那你关注这个吧：https://github.com/shadowsocks-server
