### ISSUE TITLE
建议增加一些功能

### ISSUE THREAD

**Issue by mudebug77** [netchx/netch#130]
希望能增加一个自动切换线路功能。
例如 当前ssr线路不能使用了，自动切换到其他可用线路，而不用停止然后再启动，可用线路最好能自己选择到一个待切换区域。订阅的ssr线路有些是10倍的，不划算。

希望能改变模式切换线路不断开socket 因为ShadowsocksR可以做到类似的。
可能ssr线路太拥挤了，我开5个游戏，其中3个游戏成功进入后，第4个游戏进入不了。我这时候切换线路就会导致已经进入游戏的3个号要掉线。

**Comment by miozx** [comment]
1.自动切换线路可能会触发某些游戏账户的安全检测，导致账号封禁或其他问题
2.切换线路相当于拔线，必然会导致游戏掉线
3.理论上讲很少有人会同时开5个游戏

主要还是看几位贡献者有没有需求

**Comment by NyanChanMeow** [comment]
@mudebug77 没有必要，建议前置Clash
