### ISSUE TITLE
新的图标以及全局代理置顶收藏

### ISSUE THREAD

**Issue by gongyoyo** [netchx/netch#131]
1.新的托盘以及应用图标改成单纯的小⚡
2.某些模式或者节点的收藏功能，避免每次翻
3.小闪电颜色在全局或单独代理某个进程（或者不同模式）颜色会变化

**Comment by miozx** [comment]
1.托盘图标问题请看 #100
2.目前会自动记录最后一次启动的模式与节点，不需要每次翻

**Comment by gongyoyo** [comment]
> 1.托盘图标问题请看 #100
> 2.目前会自动记录最后一次启动的模式与节点，不需要每次翻

还有能不能改进下新的界面，使用微软的flutedesign也行

**Comment by miozx** [comment]
又 不 是 不 能 用

**Comment by gongyoyo** [comment]
> 又 不 是 不 能 用

哈哈，建议而已，软件很棒，加油😘
