### ISSUE TITLE
加速无效了..uplay就没有加速上 虽然我能打开

### ISSUE THREAD

**Issue by Kirietoan** [netchx/netch#132]
加速无效了..uplay就没有加速上 虽然我能打开

![KHY7A% MDJM757E5(R3506Y](https://user-images.githubusercontent.com/42679669/65250358-09236480-db28-11e9-86ff-2de9cd9aaf87.png)

**Comment by Kirietoan** [comment]
对了 还有steam的

**Comment by miozx** [comment]
本地测试 Steam 与 Uplay 均正常，自我排查节点或上传 log

**Comment by Baalvon** [comment]
相同问题，回滚1.2.8beta相同节点正常加速

**Comment by BingLingGroup** [comment]
不提供 log 就视作无效 issue，现已关闭，请附上 log 后再提出来
