### ISSUE TITLE
DNS污染和IPV6

### ISSUE THREAD

**Issue by wysnxzm** [netchx/netch#133]
目前我在使用1.2.9 但是好像使用的是本地的dns解析然后再走的netch,这样本地的dns污染还是没有解决
还有就是ipv6貌似无法得到响应

**Comment by ghost** [comment]
DNS 是 AsIs 处理的
也就是，你当前走哪个网卡出，就跟随哪个网卡的 DNS 设置走远端查询

**Comment by ghost** [comment]
IPv6 方面，这里我是测试过的，不过最近我就不清楚了，之前加速过 Xshell 6 来访问我的 IPv6 服务器

**Comment by wysnxzm** [comment]
> IPv6 方面，这里我是测试过的，不过最近我就不清楚了，之前加速过 Xshell 6 来访问我的 IPv6 服务器

那可能是最近网络的问题叭,这几天你懂得

**Comment by chsbuffer** [comment]
请求使用新版再次测试
如果一周后没有响应将关闭此问题
