### ISSUE TITLE
常用游戏收藏夹与网络波动图

### ISSUE THREAD

**Issue by gongyoyo** [netchx/netch#134]
1.SSR是可以自定义托盘图标的，不过得自行压缩放到根目录
希望作者可以在软件中加入图形化的操作方式，自选本地图标
并且自动进行缩放然后替换所有的图标😘
2.推荐出一个收藏夹的功能，可以收藏常用的几个游戏，
然后托盘鼠标中键切换游戏，最好是不断开代理按钮切换
3.类似于UU加速器的网络波动统计图，最好可以保存此次连接后网络波动

**Comment by chsbuffer** [comment]
不会做自定义通知栏图标
快速配置
流量详情做不了
