### ISSUE TITLE
建议添加编辑模式的功能

### ISSUE THREAD

**Issue by ssyangchn** [netchx/netch#135]
已经添加的模式不能编辑很不方便啊，比如我想同时加速Steam和GTA5就做不到

**Comment by ghost** [comment]
@ssyangchn 自己到 mode 文件夹里找你的模式，用记事本编辑即可

**Comment by ghost** [comment]
@ssyangchn 暂且给个 Feature 标识，这个有待贡献者添加

**Comment by BingLingGroup** [comment]
@ConnectionRefused 是不是得改下模式文件的命名了，每次看到一串时间变量的命名还要手动改就很难受

**Comment by BingLingGroup** [comment]
除了编辑以外，其他功能要求的部分就是 #60 ，其实可以 Duplicated 。编辑这个功能其实意义不大，看有人想不想做了，我个人设想是加一个记事本启动和模式重载就完事了

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/commit/1a5572ae2d5be207659ec3502789ec990d1b9a61
