### ISSUE TITLE
建议添加使用代理更新订阅、每次修改配置后自动保存到磁盘以防止关机丢配置问题

### ISSUE THREAD

**Issue by minGGeMG** [netchx/netch#136]
有些订阅链接不挂代理就连不上订阅服务器（移动与长城用户的悲哀）
还有，BUG：

**不退出netch就关闭计算机会导致订阅链接和代理服务器全部丢失**

**Comment by NyanChanMeow** [comment]
@FANminiworld 不是Bug

**Comment by minGGeMG** [comment]
WHY？ssr客户端都没这事

**Comment by minGGeMG** [comment]
每次关机都得先退后台，真的很费事

**Comment by ghost** [comment]
因为没有做每次更新程序内部配置后直接保存到磁盘，所以有上述问题

**Comment by BingLingGroup** [comment]
已经在做了.jpg
