### ISSUE TITLE
端口占用导致进程加速启动失败

### ISSUE THREAD

**Issue by lspvic** [netchx/netch#138]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**
进程加速启动失败

**To Reproduce**
1. Open Netch
2. 选择服务器，选择类型为1的模式，如[1] Counter-Striker: Global Offensive
3. 点击启动，状态显示为：启动失败

**Screenshots**
![image](https://user-images.githubusercontent.com/4335658/65398600-d066e200-ddea-11e9-8b96-154692b46bcf.png)

**Environment (please complete the following information):**
 - OS: Windows 10 专业版 64位 1903 18362.356
 - Netch Version: 1.2.7-STABLE 和 1.3.0

**Additional context**

重启之后，可以成功启动一次，之后启动都会失败

`redirector.log`

```
[Application] Redirect to: 127.0.0.1:2801
[Application] Process name(s): AUEPLauncher.exe,AUEPMaster.exe,AUEPUF.exe,AUEPRyzenMasterAC.exe,amdow.exe,AMDRSServ.exe,AMDRSSrcExt.exe,AutoOverClockGFXCLK.exe,cncmd.exe,gpuup.exe,installShell64.exe,MMLoadDrv.exe,MMLoadDrvPXDiscrete.exe,QtWebEngineProcess.exe,RadeonSettings.exe,RSServCmd.exe,YoutubeAPIWrapper.exe,YoukuWrapper.exe,TwitterWrapperClient.exe,TwitchClient.exe,StreamableAPIWrapper.exe,SinaWeiboWrapper.exe,RestreamAPIWrapper.exe,QuanminTVWrapper.exe,MixerClient.exe,GfycatWrapper.exe,FacebookClient.exe,AMDCleanupUtility.exe,AMDInstallUEP.exe,AMDSplashScreen.exe,ATISetup.exe,InstallManagerApp.exe,RadeonInstaller.exe,Setup.exe,ccc2_install.exe
[Application] Failed to start TCP proxy[Application] Failed to initialize the event handler
```

**Comment by ghost** [comment]
使用命令 `netstat -an | findstr 8888` 查询 8888/TCP 端口是否被占用，现在的 Redirector 没有设置到其他端口上去

**Comment by lspvic** [comment]
@ConnectionRefused 谢谢 确实是8888端口的问题，8888这个端口确实被其他程序用掉了

**Comment by BingLingGroup** [comment]
以后会加入自定义端口功能，这个 issue 目前来看算是暂时解决了，我就关了。
