### ISSUE TITLE
【功能建议】可以通过代理更新订阅链接

### ISSUE THREAD

**Issue by ghost** [netchx/netch#140]
**Describe the feature you want**
SSR-windows客户端有一个通过代理更新订阅，希望Netch学过来，加一下这个功能。

**Additional context** (Optional)
虽然保持订阅链接的连通性是机场的义务，但是我就真的遇到订阅被墙却无动于衷的机场主......

**Comment by minGGeMG** [comment]
并且，移动与长城的网。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。你懂得；机场主用电信说更新顺利，用户（移动与长城）：无法更新，可怜又无助

**Comment by BingLingGroup** [comment]
提交 [667e858](https://github.com/NetchX/Netch/commit/667e858779ecf33a38d5738867d57125b3d4a5a8) 已添加此功能，已编译的版本放在附件中


[Netch.x64.zip](https://github.com/NetchX/Netch/files/3693852/Netch.x64.zip)
[Netch.x86.zip](https://github.com/NetchX/Netch/files/3693853/Netch.x86.zip)

**Comment by BingLingGroup** [comment]
注意需要至少选中一个服务器，如果服务器列表为空，那么程序会直接报错退出，这个问题会在接下来修复
