### ISSUE TITLE
对订阅链接与代理服务器的一点建议

### ISSUE THREAD

**Issue by minGGeMG** [netchx/netch#141]
可以在每个代理服务器上标注其所在的订阅链接的名称，订阅链接可以删除、修改，备注不强制性填写，可以直接从订阅链接上获取该订阅链接的备注
### **_学习一下这个项目，我觉得他做的很好_**

> https://github.com/HMBSbige/ShadowsocksR-Windows
![2019-09-23_17_53_090000](https://user-images.githubusercontent.com/49353343/65423909-d08fcd80-de3c-11e9-8fc4-36b9668047ad.jpg)
![2019-09-23_19_53_41](https://user-images.githubusercontent.com/49353343/65423912-d1286400-de3c-11e9-9e5c-9dbf74a9c261.jpg)
![未标题-1](https://user-images.githubusercontent.com/49353343/65423913-d1286400-de3c-11e9-8895-ed83c8353642.jpg)

图一：netch做的简洁得不能再简洁的订阅链接界面
图二与图三：  HMBSbige/ShadowsocksR-Windows  的部分界面

**Comment by BingLingGroup** [comment]
这边建议您先学习一下与他人沟通的正确方式。我认为通过 markdown 三级标题 + 斜体 + 粗体的样式将*无偿*地加强软件功能（而且是非必需功能）的方法说成是让开发者去*学习*是一种不太礼貌的行为，更何况对方用的也是 C#，移植过来并不是一件很难的事情，这件事如果您先发现了，您来亲自改进，我看也许会更好。

**Comment by xiaomoy** [comment]
@BingLingGroup 咱们这边是啥语言编的

**Comment by BingLingGroup** [comment]
@xiaomoy 鼠标点 github 中间那条亮条

**Comment by miozx** [comment]
### _该项目多数情况下秉着谁提出谁解决的原则更新，有需求请提pr_
