### ISSUE TITLE
当Proxifier启用基于UDP的DNS处理时，会导致无法正确的获得出口IP

### ISSUE THREAD

**Issue by CCnut** [netchx/netch#142]
当Proxifier启用基于UDP的DNS处理时，Client.LocalEndPoint会获取到错误的IP（127.0.0.1），导致在TUN/TAP模式下启动时卡死在正在启动中，其他模式无法正常找到出口

**Comment by ghost** [comment]
TUN/TAP 相关代码有待优化，目前从某加速器中拿了一些代码，有方案直接读取系统参数。不过暂时没空抄过来

**Comment by CCnut** [comment]
还有一个问题，在电脑使用PPP播号上网的时候，系统网关默认为空，从而导致获取的网关IP为0.0.0.0，实际网关IP即运营商分配的IP地址

**Comment by ghost** [comment]
@CCnut 这个问题，未来考虑一下。目前没有支持 PPPoE 拨号上网的想法

**Comment by ghost** [comment]
@CCnut 话说，进程模式，难道不好用吗 ... 非要跑全局这里来

**Comment by CCnut** [comment]
因为育碧的Steep不能正常用，用进程模式进游戏直接就变成离线模式了，只能用TUN/TAP模式

**Comment by CCnut** [comment]
而且TUN/TAP模式的兼容性最好

**Comment by ghost** [comment]
然而咱这里测试进程模式，一切都是 Work fine 的

**Comment by CCnut** [comment]
我只添加了steep.exe，并不能正常使用，你那的配置是怎么写的，是要把uplay客户端也加进去么？

**Comment by CCnut** [comment]
节点没问题，NatTypeTester测试为Symmetric，y2b正常观看，丢包率小于1%

**Comment by miozx** [comment]
@CCnut 不好意思，是节点问题，建议价钱

**Comment by CCnut** [comment]
Rixcloud的节点，应该不会差了吧，我自己的搬瓦工GIA也试过

**Comment by miozx** [comment]
@CCnut 您好，再说一次，是节点问题呢，建议换一家

**Comment by CCnut** [comment]
参阅项目内已有的issues，发现redirector内同样有[tcpConnectRequest][3685] bypass wrong process问题，将版本从最新降级为1.2.5，问题解决，steep使用进程模式可以正常联机，NatTypeTester的类型也从Symmetric变为FullCon

**Comment by CCnut** [comment]
测试到1.2.8没有问题，到1.2.9 NatTypeTester 测试类型为 FullCon 但是不能正常联网，1.3.0 NatTypeTester 类型为 Symmetric ，无法正常联网

**Comment by xiaomoy** [comment]
@CCnut 我1.2.9和1.3.0版本都不能联网，只有1.2.8等老版本能联网。似乎是软件的问题

**Comment by ghost** [comment]
这个问题应该已经修复了吧？现在用的是 Windows API 和一些 C# 代码配合查询
