### ISSUE TITLE
为进程代理模式增加绕过 IP 功能

### ISSUE THREAD

**Issue by MAWENN** [netchx/netch#143]
进程模式全局直连IP添加了一些内部IP或不想转发的IP，不生效，是进程模式没这个功能吗？进程模式最简单易用，强烈建议添加这个功能。

**Comment by BingLingGroup** [comment]
请告诉我进程模式添加直连 IP 的合理应用场景是什么，对于 Netch 而言，进程模式是服务于游戏的，几乎所有情况下游戏的代理都不希望有直连 IP 规则。如果是需要代理网页，请使用模式 4/5/6，如果是希望全局代理下有规则，请使用模式 2/3。详见[使用说明](https://github.com/NetchX/Netch/blob/master/docs/USAGE.zh-CN.md)。

**Comment by MAWENN** [comment]
一些韩国开发的游戏要用登录器启动游戏和更新游戏，如果想登录时处于代理但用直连更新会用到这个功能，直连下载速度快节省流量

**Comment by ghost** [comment]
要求接受，优先级低

**Comment by GreatFireWall** [comment]
@MAWENN Win2Socks 的强大规则系统可能可以满足你的需要.

**Comment by BingLingGroup** [comment]
@GreatFireWall 不知道您是否是 Win2Socks 的利益相关，但恕我直言 60 刀还是太贵了点
*参考昂贵的 Surge 售价也就 50 刀而已，你觉得 Win2Socks 比 Surge 还优秀吗

**Comment by GreatFireWall** [comment]
@BingLingGroup 拿10个IP刷一下访客就可以5折了... 🤔

**Comment by BingLingGroup** [comment]
@GreatFireWall 我又不是做传销的还二级代理🤔

**Comment by king4107** [comment]
模式中文的就好了，就像sstap那样

**Comment by AmazingDM** [comment]
https://github.com/AmazingDM/Netch-ForOwnUse
