### ISSUE TITLE
新的redirector在玩PSO2看剧情的时候会直接断线

### ISSUE THREAD

**Issue by beserah** [netchx/netch#144]
在看剧情CG以及挂在未登进游戏的页面等可能是没有数据传输的情况下，一段时间就会自动断线，看剧情就630，很屑
旧版不会，不过还是希望新版可以考虑一下这个问题？

**Comment by beserah** [comment]
啊，旧的似乎也会，但暂时具体是时间比新的久还是怎么的不明

**Comment by ghost** [comment]
看了多久的剧情？UDP 有超时的

**Comment by beserah** [comment]
新的可能两三分钟就630（指断线）了？
旧的可能能撑个五六分钟或者更久吧？
还有感觉丢包率好嗨高是我错觉吗

**Comment by BingLingGroup** [comment]
先关了，参见 #152
