### ISSUE TITLE
TUN/TAP模式下 新适配的DNS 被重置为自动获取

### ISSUE THREAD

**Issue by XTTGO** [netchx/netch#145]
如题，手都设置了dns，断开，再启用该模式，适配器上的dns 又被还原自动获取了。无法自定义dns

**Comment by BingLingGroup** [comment]
DNS 是交给 tun2socks 处理的，tun2socks 接受后去设置的适配器 DNS，至于 windows 适配器属性里面会不会显示这个 DNS，我就不太清楚了，总之显示不显示这个锅不在 netch 这边，netch 这边调用 tun2socks 的时候参数都有输入，详见[此处代码](https://github.com/NetchX/Netch/blob/master/Netch/Controllers/TUNTAPController.cs#L282-L294)

你还可以去研究 tun2socks 这部分处理的[代码](https://github.com/eycorsican/go-tun2socks/blob/master/cmd/tun2socks/main.go#L126-L127)

使用`ipconfig /all`可以看到 tap-windows 对应的 dns 被正确设置了
