### ISSUE TITLE
Win10使用TUN/TAP全局代理模式卡在正在启动？

### ISSUE THREAD

**Issue by leviathan0992** [netchx/netch#146]

**Comment by BingLingGroup** [comment]
没 log 没 bug，请附上 log

**Comment by leviathan0992** [comment]
还有个问题想确认一下，在socks5模式下，netch->server是以对应tcp/udp协议进行通信的吗?

**Comment by BingLingGroup** [comment]
请根据这个模板提交错误报告 https://github.com/NetchX/Netch/blob/fdefbe66c26b6ce4b3a91bff8feb4c62586d0e14/.github/ISSUE_TEMPLATE/%E9%94%99%E8%AF%AF%E6%8A%A5%E5%91%8A.md

至于所谓netch->server的交互，你说的那些没错

**Comment by leviathan0992** [comment]
**错误描述**:
Win10使用TUN/TAP全局代理模式卡在正在启动

**复现步骤:**

* 打开 Netch 软件
* 添加socks5服务器
* 选择模式 3 TUN/TAP （IP 白名单）全局代理模式， 不添加任何IP
* 启动
* 一直显示正在启动


操作系统：Windows 10 专业版 64 位
软件版本:  1.3.0 STABLE 64 位
TUN/TAP安装的是最新的OpenVPN

**Comment by BingLingGroup** [comment]
有没有试过重装驱动？我用的 sstap 带 tap-windows 驱动，没问题

**Comment by ghost** [comment]
TUN/TAP 不能用就先不要用，等优化

**Comment by leviathan0992** [comment]
@ConnectionRefused  那我全局代理TCP/UDP流量 选什么模式比较好?

**Comment by ghost** [comment]
@Leviathan1995 SSTap 请

**Comment by MAWENN** [comment]
@ConnectionRefused 同样windows10 使用过sstap，TUN/TAP一直显示正在启动，重装系统后就可以连接上，但两台电脑都使用TUN/TAP，都显示已启动，一台可以代理另一台代理不上，一直查不到原因
