### ISSUE TITLE
代理dmmgameplayer.exe无法成功

### ISSUE THREAD

**Issue by fei5seven** [netchx/netch#147]
尝试过TUN-TAP，创建进程和替换dll文件都不能正确代理，用proxifier单独代理dmmgameplayer.exe可以正常进入。有点奇怪...

**Comment by BingLingGroup** [comment]
请根据这个模板提供信息 https://github.com/NetchX/Netch/blob/fdefbe66c26b6ce4b3a91bff8feb4c62586d0e14/.github/ISSUE_TEMPLATE/%E9%94%99%E8%AF%AF%E6%8A%A5%E5%91%8A.md

**Comment by fei5seven** [comment]
错误描述:
Win10使用创建进程模式无法代理dmmgameplayer.exe

复现步骤:

打开 Netch 软件
更新v2ray订阅
添加进程dmmgameplayer.exe
启动，出现地域错误（代理失败）
![0](https://user-images.githubusercontent.com/12988636/65670240-8a727e00-e077-11e9-980c-fc4aa89552cf.png)

操作系统：Windows 10 教育版版 64 位
软件版本: 1.3.0 STABLE 64 位（已替换稳定版 bin/Redirector.exe x64 版）

额外信息


程序下载链接：http://dl-gameplayer.dmm.com/admin/win/installer/DMMGamePlayerSetup.exe

**Comment by BingLingGroup** [comment]
看日志盲猜游戏 exe 路径名中有非中文和非英文字符，估计其路径名里有日文字符，可能的原因是新版本`Redirector.exe`未能正确处理日文字符路径名，建议按照 [Readme](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#%E8%BF%9B%E7%A8%8B%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E8%BF%9B%E5%85%A5%E6%B8%B8%E6%88%8F--%E6%97%A0%E6%B3%95%E6%88%90%E5%8A%9F%E4%BB%A3%E7%90%86) 中所说方法将`Redirector.exe`替换为稳定版，或者修改该游戏 exe 所在路径，确保路径名中仅有中文或英文的字符

**Comment by fei5seven** [comment]
> 看日志盲猜游戏 exe 路径名中有非中文和非英文字符，估计其路径名里有日文字符，可能的原因是新版本`Redirector.exe`未能正确处理日文字符路径名，建议按照 [Readme](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#%E8%BF%9B%E7%A8%8B%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E8%BF%9B%E5%85%A5%E6%B8%B8%E6%88%8F--%E6%97%A0%E6%B3%95%E6%88%90%E5%8A%9F%E4%BB%A3%E7%90%86) 中所说方法将`Redirector.exe`替换为稳定版，或者修改该游戏 exe 所在路径，确保路径名中仅有中文或英文的字符

![6](https://user-images.githubusercontent.com/12988636/65671583-14234b00-e07a-11e9-9c48-b2beef79fc6f.png)
实际是纯英文字符目录。Redirector.exe使用的也是readme里提供的稳定版。但是exe启动方式为强制管理员模式，但是看到Netch也是管理员模式运行，应该不是权限问题吧

**Comment by fei5seven** [comment]
> 看日志盲猜游戏 exe 路径名中有非中文和非英文字符，估计其路径名里有日文字符，可能的原因是新版本`Redirector.exe`未能正确处理日文字符路径名，建议按照 [Readme](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#%E8%BF%9B%E7%A8%8B%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E8%BF%9B%E5%85%A5%E6%B8%B8%E6%88%8F--%E6%97%A0%E6%B3%95%E6%88%90%E5%8A%9F%E4%BB%A3%E7%90%86) 中所说方法将`Redirector.exe`替换为稳定版，或者修改该游戏 exe 所在路径，确保路径名中仅有中文或英文的字符

回退一下1.2.9版本。测试结果，1.2.9且未替换Redirector.exe可以正常代理1.3.0有问题的所有exe程序。

**Comment by BingLingGroup** [comment]
可以附一下 1.2.9 的 log 吗

**Comment by fei5seven** [comment]
> 可以附一下 1.2.9 的 log 吗

[Application] Redirect to: 127.0.0.1:2801
[Application] Name: dmmgameplayer.exe
[Application] Started
[udpClosed][31][24184][::]
[udpClosed][32][4420][192.168.31.113:55891]
[Application][Bandwidth] UP: 0,DL: 0
[tcpConnectRequest][281][BYPASS] C:\Chrome\chrome.exe
[udpClosed][34][4420][192.168.31.113:55021]
[tcpConnectRequest][282][BYPASS] C:\Chrome\chrome.exe
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][35][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][36][0][192.168.31.113:60198]
[udpClosed][37][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][33][24184][0.0.0.0]
[udpClosed][38][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][39][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][40][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][41][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][42][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][43][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][44][24184][::]
[tcpConnectRequest][283][BYPASS] C:\Chrome\chrome.exe
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][45][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[tcpConnectRequest][284][BYPASS] C:\Chrome\chrome.exe
[udpClosed][46][4420][192.168.31.113:64888]
[tcpConnectRequest][285][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][287][BYPASS] None
[tcpConnectRequest][288][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][293][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][298][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][303][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][308][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][313][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][318][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][323][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][328][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][333][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][338][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][343][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][348][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][353][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][358][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[udpClosed][47][4420][192.168.31.113:61899]
[tcpConnectRequest][360][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][364][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[tcpConnectRequest][370][HANDLE] E:\DMMGamePlayer\DMMGamePlayer.exe
[udpClosed][48][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][49][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
[udpClosed][50][24184][::]
[Application][Bandwidth] UP: 0,DL: 0
![11](https://user-images.githubusercontent.com/12988636/65743634-0a582100-e128-11e9-9e00-59a230d27d65.png)


没记错的话，1.3.0出问题的程序都是只有UDP连接没有tcp连接。包括wargameing center这个平台

**Comment by BingLingGroup** [comment]
先关了，参见 #152
