### ISSUE TITLE
关于引入kcp协议

### ISSUE THREAD

**Issue by leviathan0992** [netchx/netch#148]
游戏加速器最主要是解决丢包，延迟两个问题. 除了socks5，ss，ssr本质上不是用于游戏加速的协议，现在Netch利用socks5协议传输还是利用对应的tcp/udp，所以建议考虑引入kcp网络协议，在某些网络环境下， kcp的效果要比tcp好很多，我自己有一个基于kcp的socks5的server，假如socks5有一个可选项kcp，可以与Netch无缝对接.

**Comment by BingLingGroup** [comment]
可以但是没必要，你说的这个能用脚本运行 https://github.com/BingLingGroup/run-udp2raw-batch

**Comment by leviathan0992** [comment]
把基于kcp的socks5再部署一个client在本地，将Netch的端口指向本地，也可以解决这个问题，但体验毕竟不如只启动一个Netch好.

**Comment by nxtreaming** [comment]
KCP 是加速TCP的，游戏是绝大部分使用UDP， 请问怎么用KCP加速？

**Comment by leviathan0992** [comment]
udp报文塞到kcp报文里.

**Comment by BingLingGroup** [comment]
udpspeeder 可以加速 udp，分流时使用 tinyportmapper 进行转发，详见我前面附的脚本，当然理论上也可以运行两个 shadowsocks 客户端实例来实现，`-U`就是仅 udp，不输`-u`就是仅 tcp

**Comment by nxtreaming** [comment]
> udp报文塞到kcp报文里.

这样有个问题：你kcp服务端也要定制吧？这样不通用了

**Comment by nxtreaming** [comment]
游戏加速为啥非要和shadowsocks， v2ray这类翻墙实现扯在一起？
游戏加速不是翻墙吧，直接用最普通的VPN实现的tap/tun的方式为啥不行？

**Comment by leviathan0992** [comment]
@nxtreaming  socks5协议可以区分TCP/UDP.  
他们用ss, v2ray这些主要是通用服务端.

**Comment by BingLingGroup** [comment]
@nxtreaming VPN 目前还没看到有非全局的客户端，另外像 wireguard 这种是用 udp 承载和服务器之间的连接的，也是需要 udp2raw 和 udpspeeder 的

**Comment by nxtreaming** [comment]
> @nxtreaming VPN 目前还没看到有非全局的客户端，另外像 wireguard 这种是用 udp 承载和服务器之间的连接的，也是需要 udp2raw 和 udpspeeder 的

我一直用OpenVPN方式的将我们后台的几十台分布各地的主机连在一个10.100.0.0/16的网段，是可以不修改本地路由表的(即不全局），当然了你可以自己通过修改路由表让某些IP(例如国外IP和各种公众DNS）走tun.

**Comment by BingLingGroup** [comment]
@nxtreaming 我知道你指的是路由选择特定 IP 转发，但是 windows 自带的路由表好像有性能问题，而且维持一份游戏服务器的规则是很麻烦的。实际上 Netch 的[模式二](https://github.com/NetchX/Netch/blob/master/docs/USAGE.zh-CN.md#%E6%A8%A1%E5%BC%8F-2%E9%9C%80%E8%A6%81%E8%87%AA%E5%B7%B1%E6%96%B0%E5%BB%BA%E6%A8%A1%E5%BC%8F%E6%96%87%E4%BB%B6-tuntap-ip-%E9%BB%91%E5%90%8D%E5%8D%95%E4%BB%A3%E7%90%86%E6%A8%A1%E5%BC%8F)就是你所说的这种，但是我们并不推荐大家使用这种方法

另外关于翻墙的协议是否适合游戏，像 vmess 这种据说因为使用了 udp 转 tcp 的技术导致 udp 连接性能下降，那确实是有些影响，其他带加密的协议在大流量状态下对 CPU 性能和网络延迟会有影响，但玩游戏根本达不到那么高的速度，大体上我觉得在现在这种环境下用翻墙协议玩游戏对于公网出国的服务器线路是有加成的，当然对于中转线路就有点杀鸡用牛刀般的多余了

**Comment by nxtreaming** [comment]
@BingLingGroup 你说的对
