### ISSUE TITLE
请问一下 Microsoft outlook 用哪种模式才问发gmail邮件啊？

### ISSUE THREAD

**Issue by lgq0416** [netchx/netch#149]
请问一下 Microsoft outlook 用哪种模式才问发gmail邮件啊 
添加新应用  outlook.exe 也不走代理 还是发不出去

麻烦有人告知吗

**Comment by BingLingGroup** [comment]
如果是 UWP 应用，请先使用[这个方法](https://nekosc.com/technology/uwp_fiddler.html)确保 UWP 应用走代理，然后再考虑用什么模式

**Comment by ghost** [comment]
在 Windows 上使用 Outlook 客户端发 Gmail 右键？可能走的是 SMTP 类的协议吧，你先问问你机场有没有屏蔽 SMTP 啥的

**Comment by lgq0416** [comment]
机场没屏蔽  用sockscap64  添加 Microsoft outlook  可以发邮件

**Comment by lgq0416** [comment]
不是  UWP 应用     是  Microsoft outlook.exe  程序 sockscap64 设置后可以发

**Comment by BingLingGroup** [comment]
具体请按照格式附上 log，否则视作无效的 issue
