### ISSUE TITLE
1.2.7之上的版本 进程模式无效果

### ISSUE THREAD

**Issue by lunhuil** [netchx/netch#150]
**错误描述**
使用版本 1.3.1
之前的版本我都加入了浏览器进程 打开浏览器查看IP 验证是否启用成功
1.2.7版本之后 软件启动成功后 打开浏览器查询IP 显示的是本地IP
（Redirector.exe 文件替换成旧版后就正常了）

**日志**
[redirector.log](https://github.com/NetchX/Netch/files/3661975/redirector.log)
[shadowsocks.log](https://github.com/NetchX/Netch/files/3661976/shadowsocks.log)

**信息**
- 操作系统：[Windows 7 旗舰版64 位 ]
- 软件版本：[1.3.1]

**Comment by ghost** [comment]
![Windows 10 x64](https://user-images.githubusercontent.com/52200558/65760750-2bcd0300-e150-11e9-8236-4f73633585c9.png)

我自己的 Windows 10 x64 测试没有问题

**Comment by BingLingGroup** [comment]
参见 #152
