### ISSUE TITLE
自从1.28版本后都无法加速

### ISSUE THREAD

**Issue by Kirietoan** [netchx/netch#151]
附上uplay截图
![D4BJQ SJNYGOF7Z0O9VAJ7P](https://user-images.githubusercontent.com/42679669/65762008-97b06b00-e152-11e9-8b94-3c6af51f2857.png)

**Comment by BingLingGroup** [comment]
不按照模板提，也没有 log，我先关了
另外 CR 把旧的 Redirector 代码删了，现在在写新的，估计几百年内不会更新了，这类 issue 暂时不需要提了
