### ISSUE TITLE
代理不上问题综合讨论区 

### ISSUE THREAD

**Issue by BingLingGroup** [netchx/netch#152]
如果在新版本中有问题的，可以先到 [README.md](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#binredirectorexe-问题) 里自行寻找能用的 `Redirector` 替换上

发评论需要参照这个发：
```
**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. ...

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志（把日志放在附件里，将文件拖入回复框上传即可，不要直接复制粘贴到回复内容里，以免影响观看）

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**
```

**Comment by ghost** [comment]
已经更新 Redirector 并发布 1.3.2 新版本

**Comment by BingLingGroup** [comment]
所以是可以问 Redirector 的问题了吗，可以问的话我就把这个 issue 撤了

**Comment by ghost** [comment]
@BingLingGroup 有代理不上的问题，在这个 issue 里讨论即可，不用关

**Comment by xiaomoy** [comment]
@ConnectionRefused 你的1.3.2里说的找人测试的群是TG还QQ群。共享一下

**Comment by BingLingGroup** [comment]
tg群，私聊 @ConnectionRefused 即可

**Comment by ghost** [comment]
@BingLingGroup ¿ 暂时不开放群组邀请

**Comment by beserah** [comment]
[application.log](https://github.com/NetchX/Netch/files/3668258/application.log)

[shadowsocksr.log](https://github.com/NetchX/Netch/files/3668260/shadowsocksr.log)
1.32玩PSO2还是看没一会剧情CG就断线，UDP超时设置得太短了之类的？旧版似乎就还能撑比较长的时间
能不能尝试一下推出UDP超时断线时间自定义或者可以干脆关掉这个功能的设置项呢orz,对于随时可能挂机和进入剧情之类的MMO玩家来说真的很不友好

**Comment by beserah** [comment]
[redirector.txt](https://github.com/NetchX/Netch/files/3668265/redirector.txt)
强行说不支持，重新上传一下

**Comment by lobecai** [comment]
[application.log](https://github.com/NetchX/Netch/files/3789014/application.log)
[shadowsocksr.log](https://github.com/NetchX/Netch/files/3789015/shadowsocksr.log)
代理参数配置好了以后点启动提示失败
![221aa1](https://user-images.githubusercontent.com/57182036/67860509-fce3eb80-fb58-11e9-965f-0a9ef20a711c.png)
win7 64位系统

机器上有SSTAP（是否冲突？）

**Comment by BingLingGroup** [comment]
@lobecai log 里面说了注册驱动失败了，建议查看一下 readme 里面关于启动失败部分的 [FAQ](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#%E6%97%A0%E6%B3%95%E8%BF%90%E8%A1%8C)，安装完补丁之后再看能不能启动

**Comment by sage1717** [comment]
> 如果在新版本中有问题的，可以先到 [README.md](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#binredirectorexe-%E9%97%AE%E9%A2%98) 里自行寻找能用的 `Redirector` 替换上
> 
> 发评论需要参照这个发：
> 
> ```
> **错误描述**
> 无法代理上，模式SSR，线路正常，电脑里有一个SSR开着，端口1080，NETCH设置1080/1083均无法使用，测试游戏COD16 台服卡巴拉岛 DISCORD，后面干脆关掉飞机然后直接代理IE，也无法打开任何外网。
> 
> **复现步骤**
> 1. 打开 Netch 软件
> 2. 创建进程模式
> 3.扫描COD16文件夹
> 4.根据日志指引，先代理了4个进程，3个在文件夹下，游戏主程序，游戏Launcher，战网的WEBBROSWER，失败
> 5,重新创建进城代理模式，手动输入游戏Launcher并仅代理，无效，手动输入游戏主程序并仅代理，无效。
> **日志**
> 强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

[application.log](https://github.com/NetchX/Netch/files/3883327/application.log)
[redirector.log](https://github.com/NetchX/Netch/files/3883328/redirector.log)
[shadowsocks.log](https://github.com/NetchX/Netch/files/3883329/shadowsocks.log)

（下次请把log放在附件里，不要直接复制粘贴到回复内容里，影响观看）

> **错误截图**
> 如果适用，请添加屏幕截图以帮助解释您的问题
> 
> **信息**
> - 操作系统：[Windows 10 专业版 64 位 1909 18363.476]
> - 软件版本：[例如 1.3.4 x64 位]
> 
> **额外信息**
> 折腾了非常久，软件已经删了。。。曾经一度兴奋但是多番尝试均无果，但是本着白嫖的也要给你点个赞的想法来这里反馈问题QVQ，如果能解决的话我一定会肥来的

**Comment by BingLingGroup** [comment]
@sage1717 旧版本 `bin/redirector.exe` 可用吗，或者说，旧版本的 Netch 可用吗

**Comment by chewnglow** [comment]
Warframe无法连接官方服务器（无法更新、无法登录），但可以peer到队友，多地线路均无效
版本1.2.7 x64 stable + 1.3.4 x64
系统windows 10 x64
[redirector.log](https://github.com/NetchX/Netch/files/3883305/redirector.log)

**Comment by ghost** [comment]
@chewnglow 

- 自行将电脑的 DNS 设置为 8.8.8.8
- 我自己没有问题

**Comment by xynu617** [comment]
进程代理模式将vmnat.exe加入，VMware虚拟机无法打开被墙的网站，可以正常打开境内网站，但是查询本机IP显示的是架设v2ray服务器的vps地址。之前用proxycap64代理vmnat.exe就会代理虚拟机的所有流量
[redirector.log](https://github.com/NetchX/Netch/files/3883541/redirector.log)

**Comment by ghost** [comment]
@xynu617 在虚拟机内，把 DNS 设置到 8.8.8.8

**Comment by xynu617** [comment]
> @xynu617 在虚拟机内，把 DNS 设置到 8.8.8.8

多谢，设置完DNS就可以了

**Comment by SCUTJcfeng** [comment]
**错误描述**
steam 彩虹六号进入游戏后一直无法连接服务器

**复现步骤**
1. 打开 Netch 软件, 模式选择(Tom Clancy's Rainbow Six Siege (with Uplay)), 成功启动
2. 打开彩虹六号游戏
3. 进入游戏界面后提示无法连接服务器, 且Netch软件下方速度一栏为0

**日志**

[redirector.log](https://github.com/NetchX/Netch/files/3897849/redirector.log)
[v2ray.log](https://github.com/NetchX/Netch/files/3897850/v2ray.log)

**错误截图**

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：1.3.4

**额外信息**

**Comment by Remawater** [comment]
> **错误描述**
> steam 彩虹六号进入游戏后一直无法连接服务器
> 
> **复现步骤**
> 
> 1. 打开 Netch 软件, 模式选择(Tom Clancy's Rainbow Six Siege (with Uplay)), 成功启动
> 2. 打开彩虹六号游戏
> 3. 进入游戏界面后提示无法连接服务器, 且Netch软件下方速度一栏为0
> 
> **日志**
> 
> [redirector.log](https://github.com/NetchX/Netch/files/3897849/redirector.log)
> [v2ray.log](https://github.com/NetchX/Netch/files/3897850/v2ray.log)
> 
> **错误截图**
> 
> **信息**
> 
> * 操作系统：[例如 Windows 10 专业版 64 位 1903]
> * 软件版本：1.3.4
> 
> **额外信息**

### 我也出现了同样的情况 
####  我把 bin/Redirector.exe 替换成 1.0.9-STABLE - 1.2.4-STABLE 的版本 √
#### 没有流量统计有点难受 ×_×
[这里有说明](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#binredirectorexe-%E9%97%AE%E9%A2%98)

**Comment by FolStone** [comment]
**错误描述**
进程代理模式无法代理命运2

**复现步骤**
使用任何版本和更换Redirector后都无法使用模式1代理命运2，包括手动查找进程
但是相同配置代理apex无任何问题，同时即使成功代理后的1.3.4版也无法正常统计流量
使用谷歌dns没有变化，另外不使用代理时可以正常进入命运2但不太稳定

**日志**
[redirector.txt](https://github.com/NetchX/Netch/files/3903178/redirector.txt)

**信息**
- 操作系统：Win10 1909
- 软件版本：1.3.4及所有推荐版本

**Comment by SettingDust** [comment]
@FolStone 根据你说的情况“不使用代理时可以正常进入命运2”，我认为是你的节点问题

**Comment by xiaoxi654** [comment]
@FolStone 如果你可以使用这个节点登入命运2，可以进入设置检查一下NAT状态
如果不行，那么你应该检查一下你所使用的代理节点
关于流量统计，目前确实是不可用，显示为0是正常现象

**Comment by FolStone** [comment]
> @FolStone 根据你说的情况“不使用代理时可以正常进入命运2”，我认为是你的节点问题

相同节点可以进入apex，并且sstap相同节点也可以进入命运2

**Comment by SettingDust** [comment]
@FolStone 命运2

**Comment by iLemonra1n** [comment]
@FolStone 玄学问题

**Comment by iLemonra1n** [comment]
@FolStone 暂时的解决方案，先选择好加速线路和模式，然后不要先加速，打开游戏登录，之后在 正在连接-正在登录-正在检查更新-正在检查存储空间 这些流程结束后，开始读条连线前，启动加速即可（也就是说，不要太早，也不要太晚）

顺便，命运2是个混合架构的游戏（中心服务器+玩家之间P2P连接，参考Warframe），直连的稳定性会表现在会不会频繁在下方弹出重连提示以及更多的闪断错误代码，还有NAT状态（开放/中等/严格）也会影响到匹配对战的稳定性和成功率

**Comment by adventurer** [comment]
>  进程代理模式无法代理命运2

看起来并没有报错，你的socks5服务器对这个游戏支持不好吧兄弟

**Comment by adventurer** [comment]
> 
> 
> **错误描述**
> 进程代理模式无法代理命运2
> 
> **复现步骤**
> 使用任何版本和更换Redirector后都无法使用模式1代理命运2，包括手动查找进程
> 但是相同配置代理apex无任何问题，同时即使成功代理后的1.3.4版也无法正常统计流量
> 使用谷歌dns没有变化，另外不使用代理时可以正常进入命运2但不太稳定
> 
> **日志**
> [redirector.txt](https://github.com/NetchX/Netch/files/3903178/redirector.txt)
> 
> **信息**
> 
>     * 操作系统：Win10 1909
> 
>     * 软件版本：1.3.4及所有推荐版本

另外请问下你玩apex的时候指定的哪些进程，我连apex都玩不了，进入游戏的时候会黑屏返回大厅。

**Comment by sage1717** [comment]
> @sage1717 旧版本 `bin/redirector.exe` 可用吗，或者说，旧版本的 Netch 可用吗

没有试过旧版本，我接触到NETCH就是这个版本，所以没办法告诉你QVQ，总之觉得用意是非常非常好的，可惜的是在我的电脑上是无法适配，后来我又试了CHROME和IE，都是无效，没法连接任何外网

**Comment by Roy-Kid** [comment]
**错误描述**
代理后仍然无法登录游戏

**复现步骤**
1. 打开 Netch 软件
2. 选择服务器和模式然后start，测试过命运2 和COD Modern warfare均不行

**日志**
[redirector.log](https://github.com/NetchX/Netch/files/3932703/redirector.log)
[shadowsocksr.log](https://github.com/NetchX/Netch/files/3932704/shadowsocksr.log)
[application.log](https://github.com/NetchX/Netch/files/3932705/application.log)


**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：1809 education
- 软件版本：1.3.5

**额外信息**

我不能确定是否是我的服务器的问题。如有需要我可以提供订阅链以供测试。还有就是我现在使用SSTAP的话所有的服务器UDP转发均不通过，但是提供商告诉我应该是都可以进行UDP转发。最后昨天的的话命运登上去了，不知道是不是因为开了Netch还是因为校园网抽了。

**Comment by BingLingGroup** [comment]
@Roy-Kid 如果 sstap 的 udp 转发测试都无法通过，就可以确定不是 netch 的问题了。玩游戏基本上都是需要 udp 的。不排除是校园网的问题。你可以考虑使用 udp2raw，或者 v2ray 那种 udp over tcp

**Comment by Roy-Kid** [comment]
谢谢回复！我会换个网络环境再测试一下！
    	
    	

    	获取 Outlook for iOS
    
  




On Sun, Dec 8, 2019 at 9:10 AM +0800, "BingLingGroup" <notifications@github.com> wrote:












@Roy-Kid 如果 sstap 的 udp 转发测试都无法通过，就可以确定不是 netch 的问题了。玩游戏基本上都是需要 udp 的。不排除是校园网的问题。你可以考虑使用 udp2raw，或者 v2ray 那种 udp over tcp

**Comment by orekiqian** [comment]
win10  1909 1.3.5进程模式无效，已经更换redirector，1.29和1.24都试过，经测试chrome浏览器和自带的lol日服均无法代理。但全局模式有效，并且直接将这一份软件复制到另一台win7系统可以正常运作

[redirector.log](https://github.com/NetchX/Netch/files/3966809/redirector.log)
[application.log](https://github.com/NetchX/Netch/files/3966810/application.log)
[shadowsocksr.log](https://github.com/NetchX/Netch/files/3966811/shadowsocksr.log)

**Comment by reycn** [comment]
@orekiqian 我好像也有这个问题

**Comment by BingLingGroup** [comment]
@orekiqian win10有时有玄学情况，我上次遇到玄学后重装了显卡驱动，并未解决问题，后来过了段时间就好了，原因不明

**Comment by orekiqian** [comment]
我没记错的话应该是在win10 最近一次更新重启之后就出现这种情况了，但就算我卸载了更新还是不能恢复 @BingLingGroup

**Comment by orekiqian** [comment]
你这个问题是什么时候开始的 @reycn

**Comment by reycn** [comment]
@orekiqian 我应该是 9 月之后开始的。但因为我最近一直在写论文没有用 netch 玩游戏，所以具体什么时候也不知道。😟

**Comment by BingLingGroup** [comment]
@orekiqian 我也不知道是怎么恢复的，我并没有卸载更新……就放了几天忙别的事，等闲了再开的时候突然就好了
还有就是注意折腾不同版本的 netch 或者 `bin/redirector.exe` 的时候，要记得在菜单栏里先卸载服务/驱动（指 Netfilter SDK 的驱动），再启动加速

**Comment by chewnglow** [comment]
> @chewnglow
> 
> * 自行将电脑的 DNS 设置为 8.8.8.8
> * 我自己没有问题

设置后仍存在，数台设备都有此问题

**Comment by CODE-7z** [comment]
Bypass LAN and China导致整个网络崩溃(软件，所有网页(closed))

**Comment by AmazingDM** [comment]
> Bypass LAN and China导致整个网络崩溃(软件，所有网页(closed))

先确定你节点没问题

**Comment by CODE-7z** [comment]
我用bypass lan又没事，就bypass lan and China有时候会这样

**Comment by CODE-7z** [comment]
[shadowsocksr.log](https://github.com/NetchX/Netch/files/4565091/shadowsocksr.log)
走的是(TUN/TAP)普通模式下没事

**Comment by bbhxwl** [comment]
好像这个软件经常别人打开，要不就是一直在连接中，不能停止，只能结束进程。要不就是连上udp都是未开放，关了重新连，有时候就可以

**Comment by dcb9** [comment]
**错误描述**
Trojan TLS 连接失败，trojan.log 里的错误内容为：

```
SSL handshake failed with my-domain:443: tlsv1 alert internal error
```

**复现步骤**
1. 打开 Netch 软件
2. 选择 Trojan 服务器
3. 模式 PlayerUnknown's Battlegrounds
4. 启动

**信息**
- 操作系统：Windows 10 专业版 64 位 1903 18362.900
- 软件版本：v1.4.11

**Comment by KiWinger** [comment]
**错误描述**
①.Trojan偶尔开启失败
②.开启代理后游戏依然进不去（测试R6，Uplay可进）

**复现步骤**
①：
1. 打开 Netch 软件
2. 选择Trojan节点，选择模式，启动
②：
1. 同上（模式为[1] Tom Clancy's Rainbow Six Siege (with Uplay)）
2. 使用快捷方式打开游戏
3. 连接失败

**日志**
[trojan.log](https://github.com/NetchX/Netch/files/5044661/trojan.log)
[v2ray.log](https://github.com/NetchX/Netch/files/5044662/v2ray.log)
[application.log](https://github.com/NetchX/Netch/files/5044663/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/5044664/NTT.log)
[redirector.log](https://github.com/NetchX/Netch/files/5044665/redirector.log)


**错误截图**
![Trojan偶尔开启失败](https://user-images.githubusercontent.com/49084827/89702441-eaae9d80-d973-11ea-926f-6d306b871533.png)
![R6连接失败](https://user-images.githubusercontent.com/49084827/89702520-c69f8c00-d974-11ea-9cca-b7e0712ba011.jpg)
![R6连接配置](https://user-images.githubusercontent.com/49084827/89702530-dcad4c80-d974-11ea-8c32-81b2027486be.png)



**信息**
- 操作系统：[ Windows 10 专业版 64 位 1909]
- 软件版本：[ 1.4.11 64 位]

**额外信息**

**Comment by arcjet-zz** [comment]
请问如何用gfwlist设置代理规则？研究了很久都没搞明白。

**Comment by Villxx** [comment]
丢包~求大佬帮忙看一下是什么问题
[application.log](https://github.com/NetchX/Netch/files/5079852/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/5079853/NTT.log)
[redirector.log](https://github.com/NetchX/Netch/files/5079854/redirector.log)
[shadowsocksr.log](https://github.com/NetchX/Netch/files/5079855/shadowsocksr.log)

**Comment by wuusn** [comment]
我和 @KiWinger  问题一样；另外我apex with origin能代理上；彩六with uplay的时候，uplay正常，菜6不6；
打开了RainbowSix.exe，Redirector里面就是没有它的记录，像是漏了没扫到的样子似的。

**Comment by ogura-tsukiko** [comment]
1.4.12这边主要问题是代理是正常的。但就是不能绕行局域网和中国大陆。就算选了这规制也没用。只能换回1.4.11来用。1.4.11一切正常。

**Comment by SongZihuan** [comment]
出现了NAT: symmetric [HK] 或者出现 UdpBlocked[unknown]的错误问题

**复现步骤**
1. 打开 Netch 软件
2. 从管理订阅服务器中添加服务器
3. 更新订阅
4. 选择了一个服务器点击启动

**日志**
[Redirector.log](https://github.com/NetchX/Netch/files/5125292/Redirector.log)
[V2Ray.log](https://github.com/NetchX/Netch/files/5125293/V2Ray.log)
[application.log](https://github.com/NetchX/Netch/files/5125294/application.log)

**错误截图**
![image](https://user-images.githubusercontent.com/42832734/91206069-1cc44b80-e739-11ea-8d47-8d271d98affb.png)
![image](https://user-images.githubusercontent.com/42832734/91205945-f8686f00-e738-11ea-961f-38a4cb4fa730.png)


**信息**
- Windows 10 家庭版 64 位
- Netch 1.4.12

**额外信息**
我用旧版本(应该是1.3的版本)时并未出错。
但是我再更新的时候是将原版本删除掉后在解压新版的
