### ISSUE TITLE
建议测速可以选用youtube视频

### ISSUE THREAD

**Issue by joshatt** [netchx/netch#153]
建议增加选项: 测速可以选用youtube视频来测速

**Comment by miozx** [comment]
没有意义，锁了吧

**Comment by BingLingGroup** [comment]
youtube 视频测速对游戏没有太大参考意义，Netch 首先是游戏加速器，测速请使用 [SSRSpeed](https://github.com/NyanChanMeow/SSRSpeed)

**Comment by tindy2013** [comment]
@BingLingGroup 居然不推我的，太不厚道了（

**Comment by BingLingGroup** [comment]
@tindy2013 平时没翻你个人主页，大佬我错了
