### ISSUE TITLE
1.3.1版本 剪贴板导入不了SS链接

### ISSUE THREAD

**Issue by VerryX** [netchx/netch#156]
**错误描述**
剪贴板导入不了SS链接(带插件)，可以导入SSR链接

**复现步骤**
1. 打开 Netch 软件
2. 从剪贴板导入服务器

没生成Log呢…

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.3.1 64 位]

**Comment by tindy2013** [comment]
Fixed after commit [#757ba0c](https://github.com/NetchX/Netch/commit/757ba0c06c8e5b2542b3a3ca2f77446059615ffa).

The compiled version is in the attachment.
[Netch.x64.zip](https://github.com/NetchX/Netch/files/3693862/Netch.x64.zip)
[Netch.x86.zip](https://github.com/NetchX/Netch/files/3693863/Netch.x86.zip)
