### ISSUE TITLE
發送更新訂閲請求希望能添加自定的Header

### ISSUE THREAD

**Issue by gizmo-ds** [netchx/netch#157]
部分订阅地址服务器会做User-Agent的判定.
使用的不是白名单中的User-Agent会返回教学网页之类的东西.  
使用"curl/7.21.3 (i686-pc-linux-gnu)"之类的User-Agent才会返回订阅内容.

**功能描述**
希望能通过设置页面或者修改配置文件自定的Header或者是自定的User-Agent之类的.

**Comment by BingLingGroup** [comment]
这是什么订阅，只给 linux 用户用吗（小声
这个加起来不难，会加入

**Comment by BingLingGroup** [comment]
不着急关，等加完以后再关

**Comment by ghost** [comment]
@BingLingGroup 要不你直接现在做了这个功能吧

**Comment by ghost** [comment]
@BingLingGroup 很好办的

**Comment by BingLingGroup** [comment]
是的，我看了代码，很好做的，我明天加

**Comment by ghost** [comment]
@BingLingGroup 在？你为什么要推迟到明天？

**Comment by BingLingGroup** [comment]
我要睡了，再不睡就gg了

**Comment by BingLingGroup** [comment]
提交 [fab0757](https://github.com/NetchX/Netch/commit/fab0757f5a768a337b094ecc8b7694f8e8fca00b) 已添加自定义 User-Agent 的功能，已编译的版本放在附件中

[Netch.x64.zip](https://github.com/NetchX/Netch/files/3693055/Netch.x64.zip)
[Netch.x86.zip](https://github.com/NetchX/Netch/files/3693056/Netch.x86.zip)
