### ISSUE TITLE
1.3.2 测试节点功能无效

### ISSUE THREAD

**Issue by cnetst** [netchx/netch#158]
版本1.3.2
起因是加速游戏后却连不上服务器，查了半天发现是节点协议之前改了，Netch还没改过来。
发现Netch测试节点功能好像没用，随便编了一个节点，也会显示测试完成，如下图，希望可以修复这个功能；希望有类似SSTAP那样可以显示测试信息的功能。

![1](https://user-images.githubusercontent.com/34930270/65958502-1888a300-e482-11e9-9c79-f4108af0a30d.png)
![2](https://user-images.githubusercontent.com/34930270/65958503-19213980-e482-11e9-851e-c82fe054eab6.png)

**Comment by BingLingGroup** [comment]
自己看原理 [Server.cs#L147-L203](https://github.com/NetchX/Netch/blob/master/Netch/Models/Server.cs#L147-L203)，目前的延迟测试只是一个简单的 TCP 连接耗时测试，这个用于测试你到服务器的 TCP 延迟已经足够了，并不不是那种通过代理去 ping google.com 之类的延迟测试，何况后者对于游戏而言参考价值也不大，因为后者加入了从服务器到 google.com 的延迟
所以测试里面没有包括通过服务器代理之类的操作，当然你一通乱填，只要对面端口上跑了可以建立 TCP 连接的程序，那都可以测试出延迟的
