### ISSUE TITLE
能不能单独提供一个 TAP-Windows的安装包啊

### ISSUE THREAD

**Issue by kkbbzjh** [netchx/netch#159]
能不能单独提供一个 TAP-Windows的安装包啊，很多朋友都没有装OPENVPN或者sstap，就没办法安装Tap-windows了。网站上也很难找到这个驱动的安装

**Comment by ghost** [comment]
@kkbbzjh https://build.openvpn.net/downloads/releases/latest/tap-windows-latest-stable.exe

**Comment by BingLingGroup** [comment]
考虑接下来加入 readme 全家桶
