### ISSUE TITLE
延迟测试功能问题

### ISSUE THREAD

**Issue by laoasl** [netchx/netch#161]
延迟测试功能无法检测配有国内中转服务器的海外节点的真实连通性. 由于和v2rayN的问题一样 , 所以不在赘述 , 参考这个https://github.com/2dust/v2rayN/issues/110

**Comment by BingLingGroup** [comment]
别问，问就是你打钱，我们做，或者你做，我们合并

**Comment by ghost** [comment]
@BingLingGroup ¿

**Comment by BingLingGroup** [comment]
~~另外关于海外节点，因为每个人的需求不同，访问的外网服务器不同，只是以访问某个服务器的延迟作为真实延迟不具备参考价值，首先 Netch 是游戏加速器，不说别的，只是考虑做一下内置模式里的游戏服务器的延迟检测，这抓包找游戏服务器的工作量就够夸张的了~~

~~一是不具备普适的参考价值，二是工作量太大不可能是我们这几个人维护得了的~~

好的我成功偏题了，以楼下回复为准

当然如果有别的方法请 CR 指出

**Comment by ghost** [comment]
@BingLingGroup 没有实际意义，端内延迟应该由机场那边自己标注。而且，都是个中转了，稳定性没保障的嘛

**Comment by ghost** [comment]
如果使用真实连通性测试，在你节点多起来的情况下，肯定会增加测试时间以及资源使用量。再者你们机场也有个什么客户端数量限制，同时连接多个节点，炸不炸我不清楚
