### ISSUE TITLE
问一下netfilter2.sys这个文件有没有流量限制?进程模式有没有可能被封号什么的

### ISSUE THREAD

**Issue by magiclu** [netchx/netch#162]
1.我看了下netfilter2.sys的官方网站,貌似demo版是有一些流量限制的,不过貌似有的正规的国产加速器也有这个文件,那就是说基本没封号危险?这个项目是用的无流量限制的版本还是demo版,是不是可以直接到正规的国产加速器的安装目录里借一个?

2.还有进程模式,增加一个规则时,能否记录下完整的文件路径,而不是只记下exe的名字,比如有的游戏里有个文件叫Update.exe,我只能手动修改mode文件夹里的txt文件(看了下别人的issus,可以手动加完整的文件路径),不然可能别的软件里也有同名的文件,也叫Update.exe,这样就产生浪费流量的问题了

3.能否一个进程用代理1,另一个进程用代理2,比如我的代理1流量很贵,代理2流量很便宜

**Comment by ghost** [comment]
1. 不作解释
2. 可以直接使用完整路径
3. 不想做（我没这个要求）
