### ISSUE TITLE
添加：Bypass LAN and China(TUN/TAP)模式

### ISSUE THREAD

**Issue by ghost** [netchx/netch#163]
**功能描述**
(TUN/TAP)很好用，但是目前只有Bypass LAN(TUN/TAP)，希望能添加Bypass LAN and China(TUN/TAP)。

**Comment by BingLingGroup** [comment]
提交 [f5a6a7b](https://github.com/NetchX/Netch/commit/f5a6a7bf42f224f60318bcfd01c6fc03bb742f56) 已修复该问题
