### ISSUE TITLE
希望添加开机自启动和自动开启服务的选项

### ISSUE THREAD

**Issue by JohnRowton** [netchx/netch#164]
希望可以作为平时用来浏览网页使用，玩游戏再自己去换模式的日用软件

**Comment by wingsrabbitgoogle** [comment]
您好，Netch的初衷是游戏加速。

**Comment by JohnRowton** [comment]
好吧，感谢回复 :)

**Comment by JohnRowton** [comment]
好的，感谢回复 :)

**Comment by BingLingGroup** [comment]
开机启动不会做，自动启动服务已添加，已编译的版本在附件中，替换旧版的 Netch.exe 即可
[Netch.x64.zip](https://github.com/NetchX/Netch/files/3694325/Netch.x64.zip)
[Netch.x86.zip](https://github.com/NetchX/Netch/files/3694326/Netch.x86.zip)
