### ISSUE TITLE
为什么单端口多用户节点无法显示

### ISSUE THREAD

**Issue by ghost** [netchx/netch#165]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Temporarily don't accept any issues about `bin/Redirector.exe`. Because its codes is refactoring now. Perhaps the issues you encountered will be solved in new version.**

**Describe the bug**

**To Reproduce**

1. Open Netch
2. ...

**Log**
Attaching any log files in the folder `Netch\logging` is strongly recommended.

**Screenshots**

**Environment (please complete the following information):**
- OS: [e.g. Windows 10 Pro 64-bit 1903]
- Netch Version: [e.g. 1.0.0-STABLE.x64]

**Additional context**

**Comment by BingLingGroup** [comment]
格式不是说让你随便点一下就是，如果你看不懂英文的这份请使用中文版的 https://github.com/NetchX/Netch/issues/new?assignees=&labels=Status%3A+Review+Needed&template=bug_report.zh-CN.md
