### ISSUE TITLE
为什么单端口多用户节点无法显示

### ISSUE THREAD

**Issue by ghost** [netchx/netch#166]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**暂时不允许新建关于 `bin/Redirector.exe` 的新 issue，详见 [readme](../../docs/README.zh-CN.md#binRedirector.exe-问题)**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. ...

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**

**Comment by ghost** [comment]
![捕获](https://user-images.githubusercontent.com/52115777/66266861-48390180-e81a-11e9-95e0-8e9502c9fcc7.PNG)

**Comment by ghost** [comment]
![捕获](https://user-images.githubusercontent.com/52115777/66267831-db2b6900-e825-11e9-89e4-67a475259f33.PNG)

**Comment by tindy2013** [comment]
@zyh13146 这是机场订阅的问题，将协议填到混淆字段里去了。请联系机场主以解决问题。
