### ISSUE TITLE
进程扫描扫不到防挂软件xigncode

### ISSUE THREAD

**Issue by willbeevil** [netchx/netch#167]
在进程中，xigncode的进程后缀是.xem
文件（进程）名称 xxd-0.xem
代理不到导致xigncode加载时间很长
sstap全局（非中国ip）代理则加载时间正常
希望能添加对.xem的扫描

**Comment by BingLingGroup** [comment]
不会做任何非 .exe 扫描的支持，你可以扫描界面手动输入添加，或者编辑模式文件，或者自己改并编译一个版本，相关代码在 https://github.com/NetchX/Netch/blob/master/Netch/Forms/Mode/Process.cs#L47-L50
