### ISSUE TITLE
希望添加本地代理功能

### ISSUE THREAD

**Issue by marcosteam** [netchx/netch#17]
主要想用它给NS之类主机的联机和下游戏方面加速。
~~虽然腾讯加速NS免费2333333~~

**Comment by BingLingGroup** [comment]
暂时还不太清楚腾讯加速器代理NS的细节，而且我没有NS，如果能提供更多的细节给ConnectionRefused大佬更好，不过估计不会是当前最优先开发功能。

**Comment by ghost** [comment]
是开一个 HTTP 代理么？还是 Socks5 的代理？如果是 Socks5 的代理，你在启动 Netch 直接去 NS 上设置代理到 IP:2801 即可

**Comment by ghost** [comment]
HTTP 代理的话，我需要加一个 HTTP2Socks 的东西

**Comment by ghost** [comment]
Fixed in [8cf289c8ad1887d1e91b7341c8f6941bdb7d13aa](https://github.com/netchx/Netch/commit/8cf289c8ad1887d1e91b7341c8f6941bdb7d13aa)

Set proxy to IP:2802

**Comment by marcosteam** [comment]
> 是开一个 HTTP 代理么？还是 Socks5 的代理？如果是 Socks5 的代理，你在启动 Netch 直接去 NS 上设置代理到 IP:2801 即可

目前NS应该是只能使用HTTP代理的，这个可能要麻烦大佬了

**Comment by ghost** [comment]
@marcosteam Socks5 2801 HTTP 2802

**Comment by ghost** [comment]
@marcosteam 需要使用最新版，以及 [4] 开头的模式任意一个

**Comment by BingLingGroup** [comment]
> > 是开一个 HTTP 代理么？还是 Socks5 的代理？如果是 Socks5 的代理，你在启动 Netch 直接去 NS 上设置代理到 IP:2801 即可
> 
> 目前NS应该是只能使用HTTP代理的，这个可能要麻烦大佬了

@marcosteam 说明一下，http代理不能代理联机游戏，类似腾讯加速器那种代理目前没有开发计划。

**Comment by Rakau** [comment]
现在手机UU也出给NS代理了,不占用VPN通道，不知道是怎么做到的能让NS的NAT到A，只需要设置代理服务器6.6.6.6和端口8088就行了,难道是网关模式?
