### ISSUE TITLE
下一阶段Netch开发路线图建议

### ISSUE THREAD

**Issue by ghost** [netchx/netch#170]
（TUN/TAP）模式目前还是在偷懒阶段，需要用户手动安装和配置......
接下来应该参考SSTAP安装包，以exe文件格式发布Netch安装包，里面包括像sstap一样安装时释放出来tap虚拟网卡安装自动配置过程，这样就可以让很多没有被写进规则的游戏通过（TUN/TAP）Bypass LAN and China模式代理（甚至可以说很多游戏规则都没必要加了（UWP另说））

**Comment by BingLingGroup** [comment]
1. 安装包版不可能做的吧，既然开机启动都不可能做
2. 虚拟网卡驱动自己安装，readme 里面都给链接了
3. 另外 TUNTAP 规则和是否是安装包版没有必然联系
