### ISSUE TITLE
socks5 mode after few mins

### ISSUE THREAD

**Issue by malikshi** [netchx/netch#173]
socks5 mode with bypass lan(tun/tap) not redirect? its back to my ISP ip address.

**Comment by BingLingGroup** [comment]
Please submit your issue in the format like attaching the logs, screenshots or something useful.

**Comment by malikshi** [comment]
i will updates this issue if occur again,
ask fake dns? still leaking when testing in ipleak.net /dnsleaktest.com

**Comment by BingLingGroup** [comment]
Fake DNS is the feature from [go-tun2socks](https://github.com/eycorsican/go-tun2socks/issues/32). Netch just starts the instance through [command line arguments](https://github.com/NetchX/Netch/blob/master/Netch/Controllers/TUNTAPController.cs#L284-L287). We don't recommend using it.
