### ISSUE TITLE
windows defender 爆木马。。。

### ISSUE THREAD

**Issue by adaaaaaa** [netchx/netch#175]
还没开始使用呢。。。扫一下就提示说有木马。。。肿么办？？😂😂😂😂😂😂😂😂😂😂

**Comment by ghost** [comment]
不会自己加白嘛？不会那你就别用了

**Comment by ghost** [comment]
> 还没开始使用呢。。。扫一下就提示说有木马。。。肿么办？？😂😂😂😂😂😂😂😂😂😂

下载火绒，让火绒接管。
