### ISSUE TITLE
Support Anothers Protocols ?

### ISSUE THREAD

**Issue by Whibelf2** [netchx/netch#176]
Hello sir i suggest support for another protocols like:
SOCKS4, SOCKS4a, HTTP Proxy, HTTPS Proxy, SSL Proxy and SSH2.

I have i issue using SOCKS5 with authentication using mode TUN TAP, can't get internet browsing, TAP Adapter start successfully but not get internet Connection.

**Comment by ghost** [comment]
Socks5 with authentication does not work in TUN/TAP mode

**Comment by Whibelf2** [comment]
> Socks5 with authentication does not work in TUN/TAP mode

Oh, and yours have plan in near future put new proxies protocols ?

**Comment by ghost** [comment]
Priority: Low
Status: Accepted
Type: Enhancement
