### ISSUE TITLE
从1.27以后,gta5 ol就开始疯狂掉线了,不知道为啥.

### ISSUE THREAD

**Issue by senioi** [netchx/netch#177]
1.27以前的版本,选择gta5 后,正常使用,而且在界面上还显示速度,从1.27至1.33版本.界面上不显示速度,而且游戏里一直掉线,我也不知道是否代理成功.

**Comment by senioi** [comment]
包含了所有进程,应该不是进程未选中问题.

> # Grand Theft Auto V
> Launcher.exe
> LauncherPatcher.exe
> RockstarService.exe
> RockstarSteamHelper.exe
> GTA5.exe
> GTAVLanguageSelect.exe
> GTAVLauncher.exe
> PlayGTAV.exe
> Social-Club-Setup.exe
> SocialClubHelper.exe

**Comment by tindy2013** [comment]
@senioi 进程模式流量统计由于存在一些问题 目前暂时移除 将在未来的版本中重新加入

**Comment by senioi** [comment]
@tindy2013 感谢你的回复,目前我换会1.27了,没有出现掉线情况,希望有时间麻烦你看看是什么问题引起的

**Comment by BingLingGroup** [comment]
这个也是不按照模板填 issue 的，模板里面写了错误报告类 issue 的要求，按格式填 issue 很难吗，你就不能先好好看看格式要求？关了

点击 New issue
![步骤 1](https://user-images.githubusercontent.com/42505588/66709895-e0496480-ed9f-11e9-98e2-ecbae56c32a8.png)

如果你是错误报告类问题，点击错误报告，然后按照格式填写
![步骤 2](https://user-images.githubusercontent.com/42505588/66709894-dfb0ce00-ed9f-11e9-8312-11ab4269ccfa.png)
