### ISSUE TITLE
TUN啟動失敗

### ISSUE THREAD

**Issue by kckelvin** [netchx/netch#179]
![批注 2019-10-13 200543](https://user-images.githubusercontent.com/56507256/66715350-ea498280-edf4-11e9-9d6d-915a515eddff.png)
![批注 2019-10-13 200619](https://user-images.githubusercontent.com/56507256/66715351-eae21900-edf4-11e9-815b-ee8cdac5fcf8.png)

**Comment by PUBGLITE** [comment]
这是Netch不是sstap

**Comment by ghost** [comment]
这是 Netch，又不是 SSTap 项目，你说啥呢
