### ISSUE TITLE
项目可以生成解决方案但是无法调试?

### ISSUE THREAD

**Issue by SmRiley** [netchx/netch#180]
RT,拉下来后直接调试显示,不知道是不是我的打开方式有问题?
![image](https://user-images.githubusercontent.com/45205313/66716668-f50b1400-ee02-11e9-8719-c9582a3be39d.png)

**Comment by BingLingGroup** [comment]
可以生成调试的，你安装了.NET 4.8框架开发者套件没（会提醒安装），另外大概是需要放在纯英文路径？
反正我当时只是安装了那个开发者套件之后就能调试了

**Comment by BingLingGroup** [comment]
看了一下`项目属性——生成事件——生成后事件命令行`里的内容，你可能是忘记克隆子模块了，建议用根目录下的`UPDATE.BAT`来拉取子模块
