### ISSUE TITLE
VMess 使用非基于 TCP 的传输协议时延迟检测无法正常工作

### ISSUE THREAD

**Issue by magicalz** [netchx/netch#181]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**

Netch客户端里kcp协议的VMess服务器一直是1000延迟
Netch客户端里VMess服务器显示的上传和下载流量始终为0

**复现步骤**
1. v2ray服务器端新建两个VMess配置，对应ws和kcp协议，不同端口   

2. Netch客户端新建两个VMess配置，ws的延迟正常显示且正常使用，kcp的则一直显示1000延迟
补充说明：v2ray客户端V2rayN新建两个VMess配置，对应ws和kcp协议，两个都能正常使用

3. Netch客户端选择kcp协议的服务器，可以启动，用命运2游戏测试可以进入游戏，进游戏后中断Netch客户端，游戏也会中断，所以可能实际上是成功连接了的，只是延迟测试存在问题
补充说明：部署v2ray的服务器可以直接ping通，两个端口也都是开放的

4. 不管是ws协议还是kcp协议的VMess服务器，Netch客户端里显示的上传和下载流量始终为0

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

application.log为空

redirector.log里有updcreated信息
[udpCreated][200][8824][127.0.0.1:49353] E:\Steam\steamapps\common\Destiny 2\destiny2.exe

v2ray.log里有v2ray启动信息
2019/10/16 18:15:44 [Warning] v2ray.com/core: V2Ray 4.19.1 started

**错误截图**
![tokyows](https://user-images.githubusercontent.com/11372247/66909018-a34ecd80-f03e-11e9-862b-c2784563996f.JPG)
![tokyokcp](https://user-images.githubusercontent.com/11372247/66909040-aea1f900-f03e-11e9-9845-525bea15762d.JPG)
![localsocks](https://user-images.githubusercontent.com/11372247/66911053-5967e680-f042-11e9-9e6e-427255506b45.JPG)

**信息**
- 操作系统：[Windows 10 专业版 64 位 1903]
- 软件版本：[1.3.3-STABLE 64 位]

**额外信息**

**Comment by ghost** [comment]
1. 延迟检测这里，我们采用的是简单的 TCP 握手测试。目前没有针对 VMess 的非基于 TCP 的传输协议做出特殊处理。所以使用 VMess 非基于 TCP 的传输协议的时候，延迟检测会一直超时
2. 新版本把流量统计功能砍了，请等待以后的版本再度推出

**Comment by magicalz** [comment]
感谢解答，其实这几天实际使用下来，看不到延迟并不影响使用，我用v2ray的kcp协议的服务器玩命运2游戏很稳定，原来是用SSR+UDPSpeeder+UDPraw，现在v2ray直接用kcp协议更方便，省去了UDPSpeeder和UDPraw的配置，速度反而感觉更快了。这是个非常好的开源项目，以后我会多研究研究提PR的

**Comment by ghost** [comment]
:)

**Comment by ghost** [comment]
tcp被阻断了，玩不了命运2了，看到能用kcp能用终于安心了

**Comment by AmazingDM** [comment]
已修复
