### ISSUE TITLE
厚颜无耻的脸红请求作者能在测试栏目增加测试成功或者失败提示，而不是只有状态：测试完成

### ISSUE THREAD

**Issue by mengyalei** [netchx/netch#182]
**确保已经看过 readme，也搜索并阅读过和遇到的情况相关的问题。**

**功能描述**
在测试功能那里，新增测试结果显示。
1.1 如果所选节点线路可用，测试完成之后，提示『状态：测试连接成功，可用』
1.2 如果所选节点线路不可用，测试完成之后，提示『状态：测试连接失败，不可用』

**额外信息**
2.1 目前软件节点测试功能，不管节点是否可用，点击测试之后，均显示『 状态：测试完成』，对于节点线路是否可用不是很直观的表现出来。
![netch](https://user-images.githubusercontent.com/33970561/67073760-5d1e7900-f1ba-11e9-8b35-5c4b3f2142bc.png)
2.2 选择到无法使用的SSR节点线路，点击“启动”按钮后，提示『状态：已启动』，但是节点确实无法使用。希望在选择不可用的SSR节点线路后，点击启动之后，新增提示『状态：启动失败』
2.3 选择到无法使用的SS节点线路，点击“启动”按钮后，提示『状态：启动失败』，这个就很直观了

最后，感谢全体作者为此做出的巨大贡献，感谢你们。谢谢！

**Comment by NyanChanMeow** [comment]
@mengyalei 目前的测试功能仅测试到服务器的TCP Ping，不具备测试节点可用性的功能

**Comment by mengyalei** [comment]
好的，感谢大佬的辛勤付出！
