### ISSUE TITLE
Netch的功能缺陷

### ISSUE THREAD

**Issue by zz1616611** [netchx/netch#184]
Netch不创建自己的网卡，
导致大部分游戏不走代理，
不使用Steam服务器的游戏根本代理不了，
可以代理csgo，却代理不了用蒸汽账号登陆的地下城与勇士
![Capture](https://user-images.githubusercontent.com/44898919/67160142-60636180-f380-11e9-995a-036eba3bee28.JPG)

**Comment by tindy2013** [comment]
@zz1616611 请先仔细阅读 Readme 并确认无法解决问题以后再提出 issue，否则将被直接关闭

**Comment by miozx** [comment]
1.你说得对，Netch确实不创建网卡，有需求自己装
2.游戏走不走代理和使用方法有关，与 Netch 关系不大
3.请使用之前仔细查看 Readme
