### ISSUE TITLE
玩完一局之后程序会假死

### ISSUE THREAD

**Issue by Comah** [netchx/netch#187]
用来玩战争雷霆国际服 ，第一次进游戏完全没问题 一切正常 速度和延迟也很好，但是每次只能玩一局，玩完一局之后wt程序就卡死/假死了。需要强制结束战雷进程才能回到桌面 不知道这是什么原因呢？谢谢

**Comment by ghost** [comment]
游戏问题

**Comment by BingLingGroup** [comment]
完全没问题，刚才还玩了两盘，也是 n3，没有闪退的问题，说明不是战雷的问题。你得看看你的系统是不是有问题

Netch 1.3.3
Windows 10 1903

**Comment by Comah** [comment]
> 完全没问题，刚才还玩了两盘，也是 n3，没有闪退的问题，说明不是战雷的问题。你得看看你的系统是不是有问题
> 
> Netch 1.3.3
> Windows 10 1903

我觉得也不是wt的问题 系统应该也没问题啊 我用其他加速器玩却一点问题都没有（sstap之类的）。很奇怪 
明天更新的到1.34试试。
我的系统也是win10 1903 
netch 1.33

**Comment by BingLingGroup** [comment]
@Comah 我今天试了几局，还是很流畅，没有死机的问题
死机问题建议重装系统
或者像战雷这种对 NAT 不敏感的，直接 sstap 得了

**Comment by Comah** [comment]
> @Comah 我今天试了几局，还是很流畅，没有死机的问题
> 死机问题建议重装系统
> 或者像战雷这种对 NAT 不敏感的，直接 sstap 得了

我昨天更新到了1.34 1.34的驱动重新安装之后正常了   不知道是战雷更新到1.93的原因不？

**Comment by BingLingGroup** [comment]
@Comah 可能是你之前的驱动就有点问题吧……我前面用的不也是1.3.3吗，驱动出现问题，通过菜单选择卸载驱动即可，因为启动时检测到没有驱动会自动安装，这时安装的就是新版的了，相当于更新驱动

**Comment by Comah** [comment]
> @Comah 可能是你之前的驱动就有点问题吧……我前面用的不也是1.3.3吗，驱动出现问题，通过菜单选择卸载驱动即可，因为启动时检测到没有驱动会自动安装，这时安装的就是新版的了，相当于更新驱动

现在还是偶尔会假死 。。我想也应该是驱动问题  我删了sstap的虚拟网卡安装netch的驱动 但你已启动sstap 就又会自动安装会sstap的驱动。

**Comment by miozx** [comment]
请直接使用SSTAP

**Comment by BingLingGroup** [comment]
@Comah netch 的驱动不是 sstap 的那个好吧……看下 [readme](https://github.com/NetchX/NetchMode/blob/master/docs/README.zh-CN.md#模式-1-进程代理模式) 先

**Comment by ghost** [comment]
Netch 有两种驱动的

**Comment by ghost** [comment]
1. 进程加速用的 NetFilter 驱动
2. TUN/TAP 模式用的 TAP-Windows 驱动（SSTap）
