### ISSUE TITLE
作者有没有考虑加入linux版本?

### ISSUE THREAD

**Issue by guang19** [netchx/netch#188]
希望能加入linux版本

**Comment by ghost** [comment]
去做 Linux 的话，我拿什么写呢 ... 如果你现在需要在 Linux 上代理的话，建议上 [SSTP](https://github.com/zfl9/ss-tproxy) 吧

**Comment by BingLingGroup** [comment]
¿ linux 不会去用 proxychains 吗

**Comment by justcopy** [comment]
大胸弟 你在linux上玩游戏？

**Comment by ghost** [comment]
我自己的虚拟机编译机器都是配置 [SSTP](https://github.com/zfl9/ss-tproxy) 来代理的

**Comment by NyanChanMeow** [comment]
@YangGuang19 加钱什么都有

**Comment by BingLingGroup** [comment]
@justcopy 你别说，现在做了 linux 适配的游戏挺多的，还有那个 proton 工具

**Comment by ghost** [comment]
废话少说，直接上 [SSTP](https://github.com/zfl9/ss-tproxy) 就完事了
