### ISSUE TITLE
希望加入记录上次模式（MOD）选择的功能

### ISSUE THREAD

**Issue by Askwind** [netchx/netch#19]
现状：
每次进入都直接选择Apex模式，即第一条模式规则
期望：
记录上次选择的模式规则，下次进入则直接选择这条用过的模式

**Comment by FoggyIce** [comment]
已经在做了.jpg

**Comment by BingLingGroup** [comment]
最近的PR里面( #22 )已经添加了这个功能，你可以选择等待release或者自己编译一个版本。
