### ISSUE TITLE
能否增加一个功能，能够查看服务器是否有错误、超时以及空连的数据包

### ISSUE THREAD

**Issue by che006** [netchx/netch#191]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
就是ShadowsocksR中服务器连接统计窗口里面的信息，能够打印到log里或者显示在netch窗口中都行。

**额外信息**

**Comment by ghost** [comment]
并不能
