### ISSUE TITLE
请求添加  black desert游戏   gamezbd服务器

### ISSUE THREAD

**Issue by jungeshiyong** [netchx/netch#192]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
简明扼要地描述需要的功能

**额外信息**
游戏网站是http://www.gamezbd.net/login.php    谢谢您的帮助

**Comment by miozx** [comment]
可以确定你没看过 Readme，有需求自己加，关了

**Comment by tindy2013** [comment]
@miozx 没有规则就自己贡献 欢迎发送 PR 至规则仓库 [NetchMode](https://github.com/NetchX/NetchMode)
