### ISSUE TITLE
Netch是否会引入多倍发包的支持?

### ISSUE THREAD

**Issue by SmRiley** [netchx/netch#193]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
简明扼要地描述需要的功能
类似的项目中node-tap中有支持UDP多倍发包的说,既然是游戏加速,请问有这方面的支持吗?
**额外信息**

**Comment by ghost** [comment]
不会有，有时候不是上行丢包，多数时候都是下行丢包，单纯的客户端多倍发包没啥用
