### ISSUE TITLE
tun/tap模式的cpu占用率100%

### ISSUE THREAD

**Issue by mydy2020** [netchx/netch#194]
[shadowsocksr.log](https://github.com/NetchX/Netch/files/3782253/shadowsocksr.log)
[tun2socks.log](https://github.com/NetchX/Netch/files/3782254/tun2socks.log)
[application.log](https://github.com/NetchX/Netch/files/3782255/application.log)
![QQ截图20191029154818](https://user-images.githubusercontent.com/57129927/67747884-b2814280-fa64-11e9-9379-5d01b20b58f1.jpg)

**Comment by ghost** [comment]
去找你 Microsoft 提意见

**Comment by miozx** [comment]
你好，找错软件了

**Comment by BingLingGroup** [comment]
windows 路由表就是这样的，规则一多占用就会特别大，要么你别用 tun/tap 模式

**Comment by ghost** [comment]
其实占用也就是几分钟的占用而已，我也不知道 Microsoft Windows 那几个软件在搞什么东西
