### ISSUE TITLE
能否实现udp over tcp

### ISSUE THREAD

**Issue by stardock** [netchx/netch#195]
[X] 未使用该软件
[X] 有使用其他VPN，anyconnect客户端 ocserv服务端

因为之前某些原因，国内运营商被玩坏了，到国外的udp会随机丢包，尤其联通最为严重。
这个软件能实现用tcp转发udp流量不？ 我知道ocserv里面可以设置强安全模式就会关闭udp传送(udp over tcp)。

**Comment by ghost** [comment]
使用 V2Ray

**Comment by BingLingGroup** [comment]
确切来讲，是 V2Ray 的 VMess 符合你的要求
如果你觉得 https 的流量更不容易被 qos，也可以使用 V2+ws/h2+tls 的方案
