### ISSUE TITLE
[bug]V2ray添加服务器无反应

### ISSUE THREAD

**Issue by rhotov** [netchx/netch#2]
SSR可以用分享链接导入，V2ray（VMess）使用链接导入也无效。

**Comment by ghost** [comment]
仔细看看 release 下的说明：[1.0.5-STABLE](https://github.com/netchx/Netch/releases/tag/1.0.5-STABLE)

**Comment by rhotov** [comment]
> 仔细看看 release 下的说明：[1.0.5-STABLE](https://github.com/netchx/Netch/releases/tag/1.0.5-STABLE)

谢谢回复，我以为V2ray支持表示可以添加服务器了（手动捂脸）
