### ISSUE TITLE
希望增加加密选项

### ISSUE THREAD

**Issue by firesky123** [netchx/netch#20]
SSR的auth_chain_a模式自带一个rc4-md5加密，所以算法那里一般都选的none,但是软件里加密那个选项下没有none这个选项

**Comment by ghost** [comment]
这是一个 BUG，已经在 [这个提交](https://github.com/netchx/Netch/commit/5576821d56f224d561fea2abb8ee17b8299f95a2) 中修复

我把 SS 的加密方式给 SSR 那边去了 ...

不过你可以通过分享链接、订阅导入的方式使用，这个只影响到了手动 添加、编辑
