### ISSUE TITLE
3模式（TUN/TAP）代理失败

### ISSUE THREAD

**Issue by thanksshu** [netchx/netch#203]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**
已看过并在issue区搜索。

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**
非此类问题

**错误描述**
3模式（TUN/TAP）代理失败，通过查找IP，代理前后未发生变化，删除第一条路由后可正常代理。

**复现步骤**
1. 打开 Netch 软件
2. 配置服务器，选择“[3]Bypass LAN (TUN/TAP)”
3. 启动代理

**错误截图**
![图片](https://user-images.githubusercontent.com/30020001/68016299-9532bb00-fc94-11e9-84eb-2299163e8a74.png)

**信息**
- 操作系统：Windows 10 企业版 64 位
- 软件版本：1.3.4.x64

**Comment by thanksshu** [comment]
问题补充：
还经常出现这种情况，需要断开重连数次才可以成功启动网卡：
![图片](https://user-images.githubusercontent.com/30020001/68017574-53efda80-fc97-11e9-96f4-0158b3fb95b1.png)

**Comment by ghost** [comment]
自行将其他网卡的跃点数拉高
