### ISSUE TITLE
TUN/TAP无法加速局域网设备

### ISSUE THREAD

**Issue by SolveThePro** [netchx/netch#205]
**错误描述**
对错误的清晰简洁描述
TUN/TAP模式无法对局域网设备进行加速
**复现步骤**
1. 打开 Netch 软件
2. 选择[3]bypass ....(TUN/TAP)
3.在手机上连接WIFI并根据NETCH提供的参数修改网络配置
4.没有网络

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

2019/11/01 18:27:56 new proxy connection for target: udp:239.255.255.250:1900
2019/11/01 18:28:08 new proxy connection for target: tcp:8.8.8.8:53
2019/11/01 18:29:06 new proxy connection for target: udp:10.0.236.255:137

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题
![PC](https://user-images.githubusercontent.com/57254468/68019396-9258ba00-fcd6-11e9-96f7-e6b7b1be29f6.png)
![ip](https://user-images.githubusercontent.com/57254468/68019474-d0ee7480-fcd6-11e9-97ec-9a3c66c06de3.png)

![1](https://user-images.githubusercontent.com/57254468/68019403-971d6e00-fcd6-11e9-8448-a4159ba46eaf.jpg)
![2](https://user-images.githubusercontent.com/57254468/68019405-984e9b00-fcd6-11e9-8787-ffdb2be63351.jpg)
![3](https://user-images.githubusercontent.com/57254468/68019408-997fc800-fcd6-11e9-8253-54e366eda590.jpg)

**信息**
- 操作系统：Windows 7 旗舰版 64 位 版本6.1 内部版本7601 Service Pack 1
- 软件版本： 1.3.4-STABLE 64 位

**额外信息**
我看到国内某加速器加速PS4加速时也是提供了IP、掩码、网关、DNS等信息让用户在PS4上填写，和Netch tun/tap模式很像，所以想试一试，结果没有网络，用手机试也没有网络。请问我是不是哪里没有弄对，或者对TUN/TAP功能理解有误。（不太懂网络方面的知识）

**Comment by ghost** [comment]
你可能对 TUN/TAP 有什么误解

**Comment by shikkoku** [comment]
你填错了，应该在HTTP PROXY填你PC的IP，然后填NETCH上的HTTP端口号吧……

**Comment by SolveThePro** [comment]
好吧，谢谢你们的回复。那请问NETCH可以加速PS4吗？或者以后可能会加入这一功能吗？

**Comment by shikkoku** [comment]
我大概知道为什么你会这么填了，你是看了其他加速器的主机加速教程吧。

**Comment by SolveThePro** [comment]
是的是的，我看到这个TUN和某加速器加速主机提供的东西很像，就以为也能加速，看来是我太天真xDDDD

**Comment by LuckyJoker** [comment]
这个的解决办法应该是在win的网络连接中找到netch建立的虚拟网卡，在属性的共享选项卡中勾选“允许其他网络用户通过此计算机的Internet连接来连接“。

**Comment by lylyo** [comment]
配置错误，按楼上所说在tap虚拟网卡设置中勾选共享选项，共享网卡选择本地网络的网卡，然后在其他设备网络设置中选择静态/手动ip，其他设备ip地址需要填写本地局域网非冲突ip，网关/路由器填写电脑本地局域网ip，dns写任意知名的。比如设置ip前电脑本地ip为192.168.0.2，手机本地ip为192.168.0.3，设置网卡共享后将手机网关填写为192.168.0.2，dns随意知名dns即可，ip一般不用改，因为很少冲突。共享设置与虚拟网卡的ip地址和网关无关。

**Comment by illfool** [comment]
> 配置错误，按楼上所说在tap虚拟网卡设置中勾选共享选项，共享网卡选择本地网络的网卡，然后在其他设备网络设置中选择静态/手动ip，其他设备ip地址需要填写本地局域网非冲突ip，网关/路由器填写电脑本地局域网ip，dns写任意知名的。比如设置ip前电脑本地ip为192.168.0.2，手机本地ip为192.168.0.3，设置网卡共享后将手机网关填写为192.168.0.2，dns随意知名dns即可，ip一般不用改，因为很少冲突。共享设置与虚拟网卡的ip地址和网关无关。

我按照楼上的说法，把tap虚拟网卡设置共享之后，电脑就上不了网了。我在想，是不是需要双网卡才行，一个用来上网，一个用来连接局域网设备。

**Comment by chsbuffer** [comment]
1. 启用 Netch 设置-TUNTAP-TAP 网络共享
2. 启动 [TUN/TAP] 绕过局域网模式
3. 将你要代理的设备的IP按以下设置 (假设你电脑 ip 192.168.0.200)
 IP 192.168.0.xxx(不要和其他设备重复)
 子网掩码 255.255.255.0 / CIDR 24
 网关 192.168.0.200（开Netch的电脑的IP）
 DNS 1.1.1.1 等

**Comment by lylyo** [comment]
> > 配置错误，按楼上所说在tap虚拟网卡设置中勾选共享选项，共享网卡选择本地网络的网卡，然后在其他设备网络设置中选择静态/手动ip，其他设备ip地址需要填写本地局域网非冲突ip，网关/路由器填写电脑本地局域网ip，dns写任意知名的。比如设置ip前电脑本地ip为192.168.0.2，手机本地ip为192.168.0.3，设置网卡共享后将手机网关填写为192.168.0.2，dns随意知名dns即可，ip一般不用改，因为很少冲突。共享设置与虚拟网卡的ip地址和网关无关。
> 
> 我按照楼上的说法，把tap虚拟网卡设置共享之后，电脑就上不了网了。我在想，是不是需要双网卡才行，一个用来上网，一个用来连接局域网设备。

忘记说了，设置共享之后windows很大可能会把本地网卡ip设置成手动获取别的（192.168.137.1），进入本地网卡选择自动获取ip就行。

**Comment by illfool** [comment]
连是能连上了，不过速度很慢，NS连接测试只有有2~7Mbps，手机更是连网页都打不开。。。电脑上的速度倒是正常的

**Comment by lylyo** [comment]
> 连是能连上了，不过速度很慢，NS连接测试只有有2~7Mbps，手机更是连网页都打不开。。。电脑上的速度倒是正常的

有线网卡可以尝试将网卡配置-高级-中断调整选项改为关闭，还是可以使用但是有速度问题建议考虑更换路由器。
