### ISSUE TITLE
1.3.4版本流量不统计了

### ISSUE THREAD

**Issue by lidg080** [netchx/netch#206]
用以前的版本都可以正常显示流量，1.3.4不显示了

**Comment by lidg080** [comment]
> 用以前的版本都可以正常显示流量，1.3.4不显示了

**Comment by BingLingGroup** [comment]
请查看 [Netch.1.3.2 的更新日志](https://github.com/NetchX/Netch/blob/master/docs/CHANGELOG.zh-CN.md#132---2019-09-29)
