### ISSUE TITLE
能否添加一个基于IP段的代理方式，并且也能编辑规则

### ISSUE THREAD

**Issue by Battlecraft369** [netchx/netch#208]
![image](https://user-images.githubusercontent.com/57539801/68992238-d4235c00-08a3-11ea-91a1-6d1e335bfcc4.png)
像这样的规则。因为嘞，有的游戏的部分地址需要代理中转，也有些地址的延迟不用代理直连效果会更好。就像这个warthunder。登录服务器需要代理中转，如果不中转会登陆不上。但是，进了游戏以后我直连是最好的。不知道你能明白我的意思不？

**Comment by BingLingGroup** [comment]
你可以使用模式二，建议看下[readme](https://github.com/NetchX/NetchMode/blob/master/docs/README.zh-CN.md#模式-2需要自己新建模式文件-tuntap-ip-黑名单代理模式)
当然可以改下界面，这个不难

**Comment by miozx** [comment]
@BattleCraft777 你可能需要看一下readme，不知道你能明白我的意思不？

**Comment by Battlecraft369** [comment]
刚看了，感谢解答。
但是又出了个问题，看一下截图：
![1573906375(1)](https://user-images.githubusercontent.com/57539801/68992992-ab07c900-08ad-11ea-91ab-f826f9f744b5.png)
帮确认下，这报警肯定没问题？？网络我还能应付。这病毒广告儿小程序啥的我很怕。不会出问题吧？还是说，会不会把我的服务器设置啥的给共享出去？？

**Comment by BingLingGroup** [comment]
你要是觉得star这个项目的2.1k的用户和本项目的开发者们都在传播病毒程序的话可以不用

**Comment by ghost** [comment]
有基于 IP 段的模式，但是没有做界面上的生成配置支持而已
