### ISSUE TITLE
我刚才问了个问题，被一个傻逼说我是没事找事儿？？？

### ISSUE THREAD

**Issue by Battlecraft369** [netchx/netch#209]
![1573908707(1)](https://user-images.githubusercontent.com/57539801/68993533-210f2e80-08b4-11ea-8d21-5d1a1f0f40d5.png)

我发了这么个图，让开发的人给我说一下是不是病毒或者广告后门啥的，是不是误报，具体解释说明一下有什么不对了吗？？你们至于这么像墙内的某些组织吗？？还删贴~

我还记得你说的是啥：你要觉得谁什么开发的软件不安全的话，你可以不用。。。。

我请问你啊，我骂你们说你们软件做恶意病毒了吗？？我这说什么过激的话了吗？？你这就开始说这种片儿汤话。你啥意思啊？？

我继续发帖继续问，说一下是因为啥导致的win10报病毒或者后门？

**Comment by ghost** [comment]
软件没有毒，误报而已

**Comment by BingLingGroup** [comment]
close issue不是删贴，删贴是delete issue，另外没人说你没事找事

**Comment by ghost** [comment]
看了下上一个 issue

1. Netch 是支持 IP 段规则的，但是没有做界面上生成配置，需要手动写模式文件
2. 软件没有问题，误报而已
