### ISSUE TITLE
不能缩小到右下角

### ISSUE THREAD

**Issue by f4nff** [netchx/netch#21]
不能缩小到右下角

**Comment by BingLingGroup** [comment]
不会添加这个功能233333 除非你自己PR

**Comment by ghost** [comment]
暂时不支持，计划中（懒）

**Comment by f4nff** [comment]
等你不懒,,,
不能缩到右下角,确实不怎么方便,

**Comment by aefan** [comment]
这个需求对与不想被其他人看到桌面上显示在用什么软件非常刚需。

**Comment by ghost** [comment]
其实你们可以这样

**Comment by ghost** [comment]
1. Win +TAB 去创建一个新的工作区
2. 把 Netch 放新的工作区
3. 回到原本的工作区

先这样顶着吧 ...

**Comment by tangkv** [comment]
建议用 https://github.com/benbuck/rbtray 解决所有不能最小化到 sys tray 的程序。

**Comment by s0urcelab** [comment]
我本来把代码拉下来给加了个系统托盘，准备提个PR，编译完卸载vs的时候顺手把代码一起给删了，很尴尬😭

**Comment by ghost** [comment]
@s0urcelab 再装一次 VS 写好先发 PR 再删

**Comment by s0urcelab** [comment]
> @s0urcelab 再装一次 VS 写好先发 PR 再删
我把误删代码之前编译的exe放上来吧，替换一下主程序就可以了，你要觉得不合适就把这条删了
[Netch.zip](https://github.com/netchx/Netch/files/3365797/Netch.zip)

**Comment by s0urcelab** [comment]
@ConnectionRefused 
我把误删代码之前编译的exe放上来吧，替换一下主程序就可以了，你要觉得不合适就把这条删了
[Netch.zip](https://github.com/netchx/Netch/files/3365797/Netch.zip)

**Comment by ghost** [comment]
@s0urcelab ...

**Comment by ljh0519** [comment]
提交了一个repo，看看能用不？

**Comment by ghost** [comment]
最新版 1.1.1-STABLE 已出
