### ISSUE TITLE
tun2socks 总会被杀毒软件删掉。。。。

### ISSUE THREAD

**Issue by battlecraft888** [netchx/netch#210]
tun2socks总会被杀毒软件删掉。。。。这导致了不能分享给一起玩游戏的，因为有的人不会去鼓捣杀毒设置，以及系统设置。但是又一起买了包年VPN。这可咋办？？大神们能想个招儿，解决一下不？？？

还有，为啥封我？不让我在开发组发言？？另一个号已经被封杀了发不了言。试了好几回了，别把墙内某组织的不良嗜好带到这里好不？这么做特没意思。解封一下吧，昨天骂了一个人是我不对。但是那个哥们儿明显不管不顾带特别语气说话。

![1573908707(1)](https://user-images.githubusercontent.com/57862123/69006961-334fa200-0972-11ea-8e51-17aea6118c9c.png)
![1573987801(1)](https://user-images.githubusercontent.com/57862123/69006962-334fa200-0972-11ea-8cf4-ac87f1f16a3b.png)

**Comment by BingLingGroup** [comment]
你可以去用sstap，或者下载原版[tun2socks](https://github.com/eycorsican/go-tun2socks/releases)覆盖即可，杀软误报是因为用了upx压缩，这些更新日志里都有写
另外开发者没有义务当你的客服，没人有义务管你
