### ISSUE TITLE
别那么快关闭问题啊。。。还是老问题，被杀毒软件总是干掉的tun2socks.exe

### ISSUE THREAD

**Issue by battlecraft888** [netchx/netch#211]
按照你说的我替换过了结果是启动失败。。。还是我下载错了？再次请教

**日志**
[tun2socks.log](https://github.com/NetchX/Netch/files/3856668/tun2socks.log)

**错误截图**
![1574047568(1)](https://user-images.githubusercontent.com/57862123/69022608-cc280100-09f6-11ea-9b37-39bda6e29d5d.png)

**信息**
- 操作系统：[例如 Windows 10 Workstation 64 位 1903]
- 软件版本：[例如 1.3.4-STABLE 64 位]

**额外信息**
我觉得你总误会我意思。你软件开发的好用，我才会有反馈，这是好事儿吧？？？我并没说让你当客服是你自己想歪了，从最开始我发帖你就往歪处理解。

真心觉得你这个做得不错，功能确实非常合我意，我才这一直和你有交流，别太高冷，没意义，我也不是搞做程序行业的，咱不是竞争对手。我是膜拜你的人啊！这软件出这点小问题如果能彻底解决了不挺好么。

**Comment by battlecraft888** [comment]
根据你的提示，我已经让它不报病毒了。
[tun2socks.zip](https://github.com/NetchX/Netch/files/3857235/tun2socks.zip)
这是把UPX的壳给去掉了就好了。我把去过壳的上传上来，有同样问题困扰的小伙伴可以替换。
但是这么搞我也不知道算不算个办法。。。毕竟不是编程人员。。。

**Comment by ghost** [comment]
建议自己看看日志吧，这个问题，我不好说，TUN/TAP 不是我做的

先 Close 了

**Comment by shikkoku** [comment]
Duplicate of https://github.com/NetchX/Netch/issues/210#issue-523974262 https://github.com/NetchX/Netch/issues/209#issue-523842529
