### ISSUE TITLE
Socks5 with authentication in TUN/TAP Mode ?

### ISSUE THREAD

**Issue by Whibelf2** [netchx/netch#212]
Hello sir

The most proxies current require Authentication user:pass

You have plan to put this enhancement in future ?

Thank you

**Comment by ghost** [comment]
In the plan, I have a lot of things at the moment and may need to wait for a while.

**Comment by Whibelf2** [comment]
Sir you project is so beautiful, we love this tool

You need to add donation method end of project Cryptocurrencies sounds good

Man thanks for this great project, you are saving lifes S2.
