### ISSUE TITLE
切换成模式3(TUN/TAP)下的网速非常慢，慢到不可接受

### ISSUE THREAD

**Issue by Daya-Jin** [netchx/netch#214]
梯子是YTOO的全v2ray节点，所有都试了，在```[3] XXX(TUN/TAP)```模式下网速贼慢，并且打不开谷歌首页，显示隐私错误。能打开YouTube，但是视频缓冲不出来。在模式[4]下没问题，正常表现

**Comment by ghost** [comment]
TUN/TAP 可能确实有问题，但是我的机器上没有，无法调试

**Comment by shikkoku** [comment]
我有Ytoo，TAP模式下正确配置应该没有问题。按照下图改下虚拟网卡的跃点数。
![Annotation 2019-11-21 184334](https://user-images.githubusercontent.com/4697177/69330996-f4ca2800-0c8e-11ea-9732-ca0797b980af.jpg)
