### ISSUE TITLE
关于游戏错误

### ISSUE THREAD

**Issue by 2601355074** [netchx/netch#215]
游戏是失落的方舟-RPG游戏，指定游戏目录会出现放大镜登陆不了游戏，所以是用全局来玩的，切回游戏大区选择界面就会出现如下图 这个情况一般只有在其他电脑 登陆相同账号才会出现   我想切到其他大区角色 就出现这个 这游戏判断账号有风险就会锁游戏不让上 第一次10分钟 往后更久，求解决啊
![UO16FMA5}F4WKY6E~(3Q4B5](https://user-images.githubusercontent.com/58133478/69492550-8fbd3f00-0ee7-11ea-93a1-057d25ade4ea.png)
![4AZZ`TPICP26KU2~~9{AB6W](https://user-images.githubusercontent.com/58133478/69492551-977ce380-0ee7-11ea-81b2-3275d02d457d.png)

**Comment by 2601355074** [comment]
韩服和俄服都试过了 都有这种情况

**Comment by 2601355074** [comment]
不知道其他内部需要选区的游戏有没有这种情况

**Comment by 2601355074** [comment]
用SSTAP没有这种情况出现

**Comment by miozx** [comment]
@2601355074 请使用SSTAP

**Comment by ghost** [comment]
我不玩这个游戏，没法进行测试，Netch 支持 TUN/TAP 模式，可以试试
