### ISSUE TITLE
使用带协议参数+混淆参数的节点时会连线失败

### ISSUE THREAD

**Issue by jitdor** [netchx/netch#216]
**错误描述**
使用带协议参数+混淆参数的节点时会连线失败

**复现步骤**
1. 打开 Netch 软件
2. 连线 (socks5模式)
3. 打开浏览器，把proxy设定为127.0.0.1:2801
4. 打开网页

**日志**
`2019-11-25 17:31:07 INFO: initializing ciphers... aes-256-cfb`
`2019-11-25 17:31:07 INFO: udprelay enabled`
`2019-11-25 17:31:07 INFO: listening at 127.0.0.1:2801`
`2019-11-25 17:31:08 ERROR: client_post_decrypt`
`2019-11-25 17:31:09 ERROR: remote invalid password or cipher`
`2019-11-25 17:31:11 ERROR: remote invalid password or cipher`
`2019-11-25 17:31:12 ERROR: remote invalid password or cipher`
`2019-11-25 17:31:25 ERROR: remote invalid password or cipher`

**错误截图**
不能打开任何网页

**信息**
- 操作系统：Windows 10 64-bit 1909
- 软件版本：1.3.4 x64

**额外信息**
协议参数格式: 12345:6A7bCd
混淆参数: xxxxx.support.apple.com

**Comment by BingLingGroup** [comment]
看起来像是 readme 中 FAQ [加入更多的 SSR 参数支持](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#加入更多的-ssr-参数支持)已经提到的的问题，建议查看 readme 后再进行提问
