### ISSUE TITLE
无法代理gmod

### ISSUE THREAD

**Issue by sonyjams** [netchx/netch#222]
**错误描述**
无法加速游戏，即开启服务后进入gmod搜索不到服务器且Netch窗口的流量记录没有变化

**复现步骤**
1. 打开 Netch 软件
2. 选择Gmod目录并选择相应节点
3.开启服务并打开GMOD
4.点击 寻找多人游戏

**日志**
[redirector.log](https://github.com/NetchX/Netch/files/3910753/redirector.log)
[shadowsocksr.log](https://github.com/NetchX/Netch/files/3910755/shadowsocksr.log)

**错误截图**
![issue](https://user-images.githubusercontent.com/58423306/69952419-17cbc600-1532-11ea-9f74-f0897a9b23b6.JPG)
![issue2](https://user-images.githubusercontent.com/58423306/69952471-3b8f0c00-1532-11ea-95b0-b57050d49c60.JPG)

**信息**
- 操作系统：[Windows 10 家庭版 64 位 1709]
- 软件版本：[1.3.4-STABLE 64 位]

**额外信息**
疑似不支持订阅节点的混淆模式，但不敢确定

**Comment by xiaoxi654** [comment]
建议使用nattypetester进行测试
另：目前的流量记录处于不可用状态，没有变化属正常现象

**Comment by sonyjams** [comment]
我现在又有点怀疑是使用的节点本身不支持UDP转发
![new](https://user-images.githubusercontent.com/58423306/69965727-d4805000-154f-11ea-912d-b00fe14c22a3.JPG)

**Comment by ghost** [comment]
那不就是了嘛，自己的节点都不支持 UDP 转发
