### ISSUE TITLE
[Feature] Add Fake DNS

### ISSUE THREAD

**Issue by Whibelf2** [netchx/netch#223]
Hello sir

You removed option "Fake DNS" Its temporary  or definitely ?
Its very usefull feature, Some Proxies dint work whithout Remote DNS Feature
Consider put back this feature in new releases Please Please Please Sir

How to donate money for this project ? You have Paypal ? Bitcoin ? Litecoin ? or any other cryptocurrency ?

**Comment by ghost** [comment]
a. Remote DNS ? Always is
b. It is now locally converting UDP DNS requests to TCP DNS requests for remote query
c. For some reason we had to remove Fake DNS functionality

**Comment by Whibelf2** [comment]
Any plan to put back in future ?

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/commit/6375407d53533ed693041a3992c34b86323a3ec9
