### ISSUE TITLE
请求添加本地代理以及一些本人的疑问

### ISSUE THREAD

**Issue by SilentFlower** [netchx/netch#224]
我看过readme，很久前也有人提出本地代理功能，但我衷心希望加这个功能来帮助主机平台加速（我知道tx加速器还在免费加速，但毕竟不是长久之计）。

我试过ssr的本地代理来解除nat限制，奈何都是严格nat，虽然主机网速拉满但就是没办法联机。之后也试了sstap也是同样没用。

之后我听人介绍netch能够解除限制，我通过实践后确实发现很有效果（指warframe）。

然后我在想能不能用来解除主机的nat限制。通过【3】Bypass Lan(tun/tap)确实实现了FullCone。在通过手机热点，更改ns网络和pc网络同一网段，同一子网掩码，网关为pc的ip内网地址。

但问题来了，ns不是显示dns无法解析就是服务器未响应，改了好几次网关（不管是虚拟网卡的还是其他的都试了）都没用。
但说巧不巧，有一次我在电脑上插了类似无线wifi发射器的东西，ns居然连上了而且nat也是开放的，联机也测试了完全没问题。

我试了很多次，只要插上去就能让ns连上去，而且拔掉也不会影响（一段时间内，隔很久第二次连就又需要插一次）。

现在我很纳闷，网上的一些相关内容也看了，没能找到答案，希望能解惑。
最后希望加个本地代理啊orz

**Comment by NormanBB** [comment]
@SilentFlower 看来你手机具有同时接收和发射wifi的功能。

个人认为手机热点不行可行和wifi发射器可行的原因在于设置上。手机热点涉及到一个网段的变化以及不能设置dhcp，也许是这个引起ns的网络功能无法使用。而也许wifi发射器解决了这个问题。

建议添加设置的图片说明。

而且你可以找找netch以外的本地代理的工具。

**Comment by SilentFlower** [comment]
https://www.sockscap64.com/forums/topic/%E5%B0%86sstap%E8%99%9A%E6%8B%9F%E7%BD%91%E5%8D%A1%E5%85%B1%E4%BA%AB%E7%BB%99%E5%90%8C%E5%B1%80%E5%9F%9F%E7%BD%91%E5%85%B6%E5%AE%83%E7%9A%84%E4%B8%BB%E6%9C%BA%E3%80%81%E6%8E%8C%E6%9C%BA%E3%80%81/
设置过程大概如上，我没有将虚拟网卡的网络共享给本地，因为好像不能上网

额今天早上起来试了下，将虚拟网卡的网络共享给本地热点的网络就实现了，等了一会能连上网。。
猜测这个随身wifi的作用是共享网络？

另外你说的其他代理工具其实我一直在找，几乎没有解决nat type问题的。

**Comment by Evilmass** [comment]
#34

**Comment by xiahualiu** [comment]
我试了一下，目前的TUN/TAP虽然是nat open，但是只能供电脑一个终端使用，共享给主机的话，显示ip依旧是本地ip，并没有加速。加速器应该是将所有的包都转给了电脑。
如果将这个稍作修改，通过网络共享，转发的数据包不提供给电脑，而是将所有的转发数据都提供给同一局域网下，某一个ip的终端，应该就可以达到uu或tx主机通过局域网设置网关加速nat open的效果。
很期待能够加入此功能。

**Comment by BingLingGroup** [comment]
问题看来解决了，先关了，https://github.com/NetchX/Netch/issues/224#issuecomment-561944324 是个好东西，可以研究下
关于分享代理给局域网设备，已经有类似 issue 了
