### ISSUE TITLE
程序卡在正在启动中

### ISSUE THREAD

**Issue by kkbbzjh** [netchx/netch#226]
**错误描述**
W10和W7都出现程序卡在正在启动中

**复现步骤**
1. 打开 Netch 软件
2. 设置了节点
选了模式TUN/TAP或者进程模式
启动
然后就一直等，等了几分钟，依旧正在启动中

**Comment by kkbbzjh** [comment]
![image](https://user-images.githubusercontent.com/17746225/70342650-6cec3c80-1890-11ea-9da4-a18c78e012e6.png)

**Comment by laoasl** [comment]
一样的问题 , 最新的1.3.5版只要用TUN/TAP模式就卡在"正在启动中" , 而且关不掉 , 只能用任务管理器杀掉才行.  1.3.2版在TUN/TAP模式提示"启动失败" , 可以正常退出.

**Comment by frustreated** [comment]
初步猜测是，驱动问题，或者是驱动排序，或者是其他。我新安装机器，一个可以正常使用，一个不行。原因就是驱动顺序，或者驱动安装的哪儿不太如意。

**Comment by frustreated** [comment]
我这儿也是相同问题，初步猜测，问题出在启动服务那儿。

**Comment by frustreated** [comment]
一点新发现，刚开始用netch不行，虚拟网卡启动不了。然后用的sstap，可以运行。接着关闭sstap，netch开启，仍旧不行。最后，直接用sstap，用了一段时间，安装了一些软件，调整了点其他东西，一直没动netch。最后，关闭sstap，直接用netch，竟然可以用了。
另外，我只用的一个模式：全局代理。

**Comment by laoasl** [comment]
> 一点新发现，刚开始用netch不行，虚拟网卡启动不了。然后用的sstap，可以运行。接着关闭sstap，netch开启，仍旧不行。最后，直接用sstap，用了一段时间，安装了一些软件，调整了点其他东西，一直没动netch。最后，关闭sstap，直接用netch，竟然可以用了。
> 另外，我只用的一个模式：全局代理。

冲喜吗👍

**Comment by frustreated** [comment]
嘿嘿，不知道原因哈，我自己编译了下，结论一样。

**Comment by frustreated** [comment]
> > 一点新发现，刚开始用netch不行，虚拟网卡启动不了。然后用的sstap，可以运行。接着关闭sstap，netch开启，仍旧不行。最后，直接用sstap，用了一段时间，安装了一些软件，调整了点其他东西，一直没动netch。最后，关闭sstap，直接用netch，竟然可以用了。
> > 另外，我只用的一个模式：全局代理。
> 
> 冲喜吗👍

最终解决办法就是，先使用sstap一点时间，然后重新回来使用netch，一切就OK了

**Comment by kkbbzjh** [comment]
> > > 一点新发现，刚开始用netch不行，虚拟网卡启动不了。然后用的sstap，可以运行。接着关闭sstap，netch开启，仍旧不行。最后，直接用sstap，用了一段时间，安装了一些软件，调整了点其他东西，一直没动netch。最后，关闭sstap，直接用netch，竟然可以用了。
> > > 另外，我只用的一个模式：全局代理。
> > 
> > 
> > 冲喜吗👍
> 
> 最终解决办法就是，先使用sstap一点时间，然后重新回来使用netch，一切就OK了

还有这种说法？先使用一段时间，在换回来？进程模式有效吗？

**Comment by frustreated** [comment]
没有使用进程的方式，只使用的全局。挺OK的

**Comment by frustreated** [comment]
> > > > 一点新发现，刚开始用netch不行，虚拟网卡启动不了。然后用的sstap，可以运行。接着关闭sstap，netch开启，仍旧不行。最后，直接用sstap，用了一段时间，安装了一些软件，调整了点其他东西，一直没动netch。最后，关闭sstap，直接用netch，竟然可以用了。
> > > > 另外，我只用的一个模式：全局代理。
> > > 
> > > 
> > > 冲喜吗👍
> > 
> > 
> > 最终解决办法就是，先使用sstap一点时间，然后重新回来使用netch，一切就OK了
> 
> 还有这种说法？先使用一段时间，在换回来？进程模式有效吗？

没有使用进程的方式，只使用的全局，最后发现是这个结论。
