### ISSUE TITLE
V2Ray mux mode issue

### ISSUE THREAD

**Issue by arimitx** [netchx/netch#229]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**All issues about `bin/Redirector.exe` should be discussed at [issue #152](https://github.com/NetchX/Netch/issues/152).**

**Describe the bug**
V2Ray配置中mux默认为true而且无法修改，在服务端mux配置为false时无法连接使用对应节点。

**To Reproduce**
见[VMess.cs](https://github.com/NetchX/Netch/blob/master/Netch/Models/Information/VMess.cs)中OutboundMux类。

**Log**
不适用

**Screenshots**
不适用

**Environment (please complete the following information):**
- OS: 不适用
- Netch Version: 1.3.4

**Additional context**
建议在配置中添加是否启用mux的选项，或者默认mux=false。

**Comment by arimitx** [comment]
看了一下mux在服务端是自动适配的，但是仍存在开启mux时无法连接或者断流等情况，建议默认关闭mux或添加用户自定义选项。

**Comment by ghost** [comment]
@zyc199847 @tindy2013

**Comment by ghost** [comment]
就交给 @tindy2013 处理啦

**Comment by arimitx** [comment]
@ConnectionRefused 实际上我刚才改了一下，加入了mux选项，正准备发pr来着。。

**Comment by ghost** [comment]
那么，PR 吧，谢谢了，最近实在是没有空来维护Netch 了

**Comment by arimitx** [comment]
@ConnectionRefused build脚本总是失败，不清楚问题在哪，想先测试一下再发的，，我先把我改过的部分发一个pr吧，麻烦您review一下了。

**Comment by ghost** [comment]
编译失败？截图看一下？

**Comment by ghost** [comment]
1. 是不是忘记初始化 Git 子模块了
2. 那个脚本要用 Visual Studio Developer Console 的（因为需要调用 MSBuild，然而这个东西默认不在 PATH 环境变量中，必须手动开 Visual Studio Developer Console 才能跑这个脚本）

**Comment by arimitx** [comment]
@ConnectionRefused 我猜是没有初始化 Git 子模块，我再看看。

**Comment by ghost** [comment]
`git submodule update --init`

**Comment by arimitx** [comment]
@ConnectionRefused 确实是子模块的问题，第一次弄带子模块的项目，没有经验，然后网又不太好，折腾半天才把子模块都处理好。简单测试了一下，我的v2ray节点目前能用了，但是手里没有能开启多路复用的节点，所以开启mux的情况暂未测试。再就是i18n仓库里zh-TW需要添加mux对应汉化文本。

**Comment by ghost** [comment]
2333，我现在看一下 PR 吧

**Comment by ghost** [comment]
OK，简单看了下，应该是没有啥问题的，直接合并了

**Comment by ghost** [comment]
谢谢您为 Netch 项目的贡献

**Comment by arimitx** [comment]
不客气，应该的。
