### ISSUE TITLE
不求其它 只求全局

### ISSUE THREAD

**Issue by xhqpp** [netchx/netch#23]
可以隐藏起来，输入代码才能全局，或者让用户自己可以设置全局

**Comment by ycfnzz** [comment]
这个方法不错

**Comment by efaun** [comment]
为啥要有加密码这种操作，直接提供有风险？

**Comment by ghost** [comment]
Fixed in [8cf289c8ad1887d1e91b7341c8f6941bdb7d13aa](https://github.com/netchx/Netch/commit/8cf289c8ad1887d1e91b7341c8f6941bdb7d13aa)

**Comment by GreatFireWall** [comment]
@xhqpp 可以试试 win2socks.
