### ISSUE TITLE
能不能加入trojan的支持呢?

### ISSUE THREAD

**Issue by MurasameCyan** [netchx/netch#259]
目前使用trojan的也有不少人了  我自己用来玩游戏感觉也还行  不知道能不能直接加入支持呢?

**Comment by AmazingDM** [comment]
虽然在计划之中，但是因为没有节点而且咱也不常用所以一直搁置着~欢迎pr

**Comment by Colinwood11** [comment]
@AmazingDM 节点我能提供  等我自己客户端先支持上先23333  咕

**Comment by 837278709** [comment]
强烈支持trojan 哈哈哈

**Comment by chenzhekl** [comment]
看到这个 issue 已经关闭了，但 README 里没有提到 Trojan 协议。请问现在的状态是怎么样的呢。

**Comment by AmazingDM** [comment]
> 看到这个 issue 已经关闭了，但 README 里没有提到 Trojan 协议。请问现在的状态是怎么样的呢。

你确定你下载使用过最新版Netch???

**Comment by chenzhekl** [comment]
?? 还没有下载试过，就好奇逛到了这个项目。既然支持了更新一下 README 不好么

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/88506865-8c95c800-d00d-11ea-950d-c9d62ae3abe6.png)
README 早咕了，等一个有缘人来更新
