### ISSUE TITLE
降低.Net Framework版本以兼容更多环境

### ISSUE THREAD

**Issue by CreateAndInject** [netchx/netch#260]
可降为.Net 4.7而不用修改任何代码
另外程序对.Net4.7的依赖仅限于`Netch.ControllersNTTController.NTTController.Start`的返回值ValueTuple，而事实上该函数的所有调用均未使用其返回值，所以可改为void，这样可直接降为.Net4.5

由于.Net4.x是覆盖安装，所以即便编译为.Net4.5/.Net4.7，对于安装了4.8的系统来说，仍会运行在4.8的环境下，不会有任何副作用

**Comment by huangfengye** [comment]
赞同，4.8好像对游戏有点问题。时常导致游戏崩溃，我只能卸载了4.8，用回旧版本的1.3.9
