### ISSUE TITLE
计算机从睡眠状态恢复后，TAP 连接自动断开

### ISSUE THREAD

**Issue by kenvix** [netchx/netch#264]
**错误描述**
计算机从睡眠状态恢复后，TAP 虚拟网卡连接自动断开（网络电缆被拔出），但是 Netch 仍然显示为“已连接”并且不会自动重连网卡。

**复现步骤**
1. 打开 Netch 软件
2. 连接为 TUN/TAP 模式
3. 睡眠
4. 恢复

**日志**
无相关日志

**错误截图**
![image](https://user-images.githubusercontent.com/4546175/80276097-bf7fa580-8718-11ea-9c9a-7ab3dd057ff4.png)

**信息**
- 操作系统：Windows 10 专业版 64 位 1909
- 软件版本：1.4.2

**额外信息**     
**建议**：
 * 监听 Windows 电源事件
 * 定时检查 TAP 网卡状态，在网卡状态不正确时重新连接

**Comment by AmazingDM** [comment]
:bug:

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/commit/141db8ad63d434d0e5a018ead34da511396ef67f
