### ISSUE TITLE
新版本TUN/TAP模式对于节点NAT类型为UpdBlocked处理时有问题

### ISSUE THREAD

**Issue by LeslieYon** [netchx/netch#265]
如下图 之前旧版本（1.4.1）在使用TUN/TAP模式代理虚拟机时没有任何问题，可以直接使用
![image](https://user-images.githubusercontent.com/43743875/80368446-59815280-88bf-11ea-8a6c-28d7d721ade1.png)
![image](https://user-images.githubusercontent.com/43743875/80369259-8e41d980-88c0-11ea-86b7-7cff2885fb81.png)

新版本则会出现无法使用的情况
![image](https://user-images.githubusercontent.com/43743875/80368483-69993200-88bf-11ea-904b-4e03cd17658d.png)
![image](https://user-images.githubusercontent.com/43743875/80369267-94d05100-88c0-11ea-86a0-eed3a78ee27f.png)

经过观察，节点NAT类型为FullCone时新版本也没有问题
![image](https://user-images.githubusercontent.com/43743875/80368629-99483a00-88bf-11ea-88de-f862cfe9208b.png)
![image](https://user-images.githubusercontent.com/43743875/80369292-9e59b900-88c0-11ea-8b07-d328fb38b59e.png)

也就是说，新版本在TUN/TAP模式且NAT类型为UpdBlocked时代理虚拟机有问题。

麻烦大佬看一下具体什么情况

已排除节点问题，DNS缓存问题，已选择过重装TAP驱动，新旧版本的设置都没有动过，均保持默认

虚拟机系统也没有添加任何与代理有关的配置 所有网络设置均保持默认，虚拟机网络类型为NAT模式

**Comment by Brightmbsh** [comment]
虚拟机系统没有添加任何与代理有关的配置 所有网络设置均保持默认

**Comment by AromanRon** [comment]
我也是几天都连不上了，老是提示UpdBlocked

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/80436653-32179d80-8932-11ea-92df-54590a89e274.png)
无法复现，仍不排除节点问题。建议开启后检查路由表跃点及防火墙设置

**Comment by LeslieYon** [comment]
我看了看，应该是这个虚拟机的dns请求用的是udp，而节点不支持upd，从而导致的所有dns请求均查询失败。
不清楚netch是否有dns请求的tcp转发功能

Amazing_DM <notifications@github.com> 于 2020年4月28日周二 上午9:31写道：
