### ISSUE TITLE
1.4.1-1.4.3版本存在SSR、SS启动超时问题

### ISSUE THREAD

**Issue by emmy470** [netchx/netch#266]
相同节点使用 1.4.0 或者更早版本的 Netch，以及 ClashR for windows、SSTap 可以正常使用，但使用 1.4.1-1.4.3 无法成功启动，已尝试卸载服务，重装依赖均无效果。
Log 文件重复显示内容如下：
    application.log：SSR 进程启动超时
    shadowsocksr.log：INFO: initializing acl...

**Comment by AmazingDM** [comment]
请尝试手动使用命令行启动ssr
