### ISSUE TITLE
模式下拉框过滤时按ESC键软件崩溃

### ISSUE THREAD

**Issue by xbblog95** [netchx/netch#268]
模式下拉框过滤时按ESC键软件崩溃 版本1.4.3
1、正常启动netch
[![JoarA1.png](https://s1.ax1x.com/2020/04/29/JoarA1.png)](https://imgchr.com/i/JoarA1)
2、模式下拉框输入字符串过滤模式
[![Joastx.png](https://s1.ax1x.com/2020/04/29/Joastx.png)](https://imgchr.com/i/Joastx)
3、按下ESC键，程序崩溃
[![Joayh6.png](https://s1.ax1x.com/2020/04/29/Joayh6.png)](https://imgchr.com/i/Joayh6)

**Comment by AmazingDM** [comment]
老彩蛋了，等一波pr
