### ISSUE TITLE
tap-windows显示网络电缆被拔出

### ISSUE THREAD

**Issue by ghost** [netchx/netch#269]
我能启动啊，可是tap-windows显示网络电缆被拔出。
进游戏后，延迟1000，原本200的，昨天刚更新win10。
今天也重装了sstap，sstap可以连接那个网络，可是netch，显示网络电缆被拔出。
也用了新版本netch，显示网络电缆被拔出。
也在里面重装了tap驱动，显示网络电缆被拔出。
该怎么做呢。

![无标题](https://user-images.githubusercontent.com/48499768/80683128-473d2980-8af6-11ea-8960-ff5badff6ae5.png)

**Comment by AmazingDM** [comment]
进程模式不会启动tap网卡
