### ISSUE TITLE
增加动态获取ip， 并且仅代理其中一部分地址的功能

### ISSUE THREAD

**Issue by rpwtsama** [netchx/netch#280]
街霸5连接的服务器每次登录都不一样， 是随机分配的， 如果使用模式1代理进程或者模式2全局代理， 则无法搜到其他玩家，无法对战， 如果不加入代理， 由于需要连接美国ec2服务器，普通家用宽带基本上半小时左右就会被运营商断连，导致强制下线，所以需要限定仅代理部分地址。

街霸5的连接流程大约是以下步骤：
1. 访问某指定域名获取服务地址， 
2 .客户端与这些地址（一般是4个）建立tcp连接， 整个游戏过程中这几个连接一断则立刻强制下线， 没有重试逻辑。
3. 在游戏界面上选择搜索对手，搜索时访问的ip也不固定， 但是这些ip都不能走代理， 否则无法搜到人。
4. 搜到对手后与对手直接连接，这里也不能走代理。

**功能描述**
希望能在进程模式中加入查看当前已连接ip的界面， 并指定某几个连接之外全部不走代理。 这样就可以在进入游戏后由代理来保持不掉线， 同时又可以搜到人。

**额外信息**
1. 我尝试了魔改版的udp不走代理功能， 可以不掉线， 但是一样搜不到人。
2. 服务器都是amazon 的ec2，全部地址可以从这里获取到https://ip-ranges.amazonaws.com/ip-ranges.json， 目前监听到的全部都是"us-west-2"区域的，大约280多个段。
3. 不能把全部"us-west-2"段的加入到代理， 否则一样搜不到人。

**Comment by AmazingDM** [comment]
https://github.com/AmazingDM/Netch-ForOwnUse 
已支持 来试试

**Comment by rpwtsama** [comment]
重点不在IPFillter, 重点在于应用模式启动后能显示应用连接的ip (打出log也可以), 并在保持不断连的情况下重新刷新并加载模式. 建议最好能加入显示已代理连接的目标ip.
另外问下这个IPFillter可以在全局模式下使用吗?

**Comment by AmazingDM** [comment]
已代理目标IP在设置中可开启打印，日志在Redirector.log中。 IPFillter支持全局进程模式使用（不过可能有BUG）
