### ISSUE TITLE
使用netch加速游戏时失败，网页代理正常

### ISSUE THREAD

**Issue by CobraraRA** [netchx/netch#282]
**错误描述**
使用v2ray转发游戏时失败，而在使用网页代理时功能正常

**复现步骤**
1. 打开 Netch 软件
2. 启动加速"r6s",无法正常连接

**日志**
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 windows/amd64)
A unified platform for anti-censorship.
2020/06/14 10:52:30 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  ..\data\last.json
2020/06/14 10:52:30 [Warning] v2ray.com/core: V2Ray 4.23.1 started
2020/06/14 10:52:40 [Warning] [2159516114] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://domain.domain/path/):  > dial tcp ipv4:443 operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://domain.domain/path/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/06/14 10:52:40 [Warning] [1330210201] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://domain.domain/path/):  > dial tcp ipv4:443: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://domain/path/):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2020/06/14 10:52:41 [Warning] [1802937727] v2ray.com/core/app/dispatcher: non existing tag: direct

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[win10 专业版]
- 软件版本：[1.4.7]

**额外信息**

**Comment by AmazingDM** [comment]
请尝试最新版
