### ISSUE TITLE
找不到别名带小于号的vmess链接

### ISSUE THREAD

**Issue by w311ang** [netchx/netch#290]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. 复制`vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiI2NCIsImhvc3QiOiIiLCJpZCI6ImlkIiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiIxMDA4NiIsInBzIjoiXHUwMDNjLSIsInRscyI6IiIsInR5cGUiOiJub25lIiwidiI6IjIifQ==`
 3. 从剪贴板添加链接
 4. 提示找不到链接

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**

**Comment by w311ang** [comment]
别名包含小于号提示无链接可添加：`vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiI2NCIsImhvc3QiOiIiLCJpZCI6ImlkIiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiIxMDA4NiIsInBzIjoiXHUwMDNjLSIsInRscyI6IiIsInR5cGUiOiJub25lIiwidiI6IjIifQ==`
去除小于号后成功添加：`vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiI2NCIsImhvc3QiOiIiLCJpZCI6ImlkIiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiIxMDA4NiIsInBzIjoiLSIsInRscyI6IiIsInR5cGUiOiJub25lIiwidiI6IjIifQ==`

**Comment by chsbuffer** [comment]
请注明操作系统和软件版本
1.4.11 未能复现
