### ISSUE TITLE
给warframe加速时，epic平台的流量也会通过代理

### ISSUE THREAD

**Issue by 7yues** [netchx/netch#294]
[**错误描述**]
使用自带warframe加速规则（未勾选创建/管理进程），给warframe加速时，epic平台的流量也会通过代理

**日志**
[application.log](https://github.com/NetchX/Netch/files/4883560/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/4883561/NTT.log)
[redirector.log](https://github.com/NetchX/Netch/files/4883563/redirector.log)
[shadowsocksr.log](https://github.com/NetchX/Netch/files/4883564/shadowsocksr.log)

**信息**
- 操作系统：Windows 10 专业版 64 位 1909
- 软件版本：1.4.11

**Comment by chsbuffer** [comment]
符合程序逻辑

进程代理下, 进程完整路径**含有**规则就会被代理
warfame 规则 (warfame.txt)
```
# Warframe
Launcher.exe
RemoteCrashSender.exe
Warframe.x64.exe
```

`EpicGamesLauncher.exe` 包含 `Launcher.exe`, 所以会被代理

将 `Launcher.exe` 改为 `\Launcher.exe` 即可

**Comment by 7yues** [comment]
感谢
