### ISSUE TITLE
请问有计划支持mac吗？

### ISSUE THREAD

**Issue by mixj93** [netchx/Netch#3]

**Comment by hacking001** [comment]
有这个想法，但是很不实际。我没有 MacBook ... 没法研究开发

**Comment by mixj93** [comment]
> 有这个想法，但是很不实际。我没有 MacBook ... 没法研究开发

不知道类似Electron的跨平台技术可以实现这个功能吗

**Comment by hacking001** [comment]
但是技术核心又没法上去测试

**Comment by hacking001** [comment]
而且，现有技术并不能工作于 MacOS ... （Windows only）

**Comment by mixj93** [comment]
> 而且，现有技术并不能工作于 MacOS ... （Windows only）

明白
