### ISSUE TITLE
sni写为null会造成nginx中转的trojan的udp不通

### ISSUE THREAD

**Issue by Mxy123h** [netchx/netch#301]
**错误描述**
sni写为null会造成nginx中转的trojan的udp不通

**复现步骤**
1.nginx中转的trojan 
2. 打开 Netch 软件

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志（把日志放在附件里，将文件拖入回复框上传即可，不要直接复制粘贴到回复内容里，以免影响观看）

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**
```"sni": "",```这样可以
```"sni": null,```这样udpblock

**Comment by freedoor230** [comment]
怎么修改

**Comment by Mxy123h** [comment]
已pr
