### ISSUE TITLE
建议增加一个新功能，自动更新订阅链接！

### ISSUE THREAD

**Issue by LiSheng2099** [netchx/netch#306]
作者大大，
您好，很高兴您能在百忙之中看到我的这个Issues，也许已经有人提过了，不过我真的觉得这款优秀的软件需要一个【自动更新订阅链接】的功能，因为有些“机场”并不稳定，时常会需要更新链接才能正常使用。具体功能可以有，每周更新，每日更新，每次启动更新等。
谢谢！

**Comment by OneHappyForever** [comment]
我也觉得这个非常重要。

目前进程如何？

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/commit/a47395cc6cd9404812ed0e5240af987ccf8f1945
