### ISSUE TITLE
扫描chrome目录后,添加chrome.exe,但是发现连带着360chrome也被代理了

### ISSUE THREAD

**Issue by xishijt** [netchx/netch#31]
如题

**Comment by ghost** [comment]
@xishijt 可以在程序名前面加一些具体的路径，假设 chrome.exe 在 C:\Program Files\Google Chrome 下

可以这么写：
Google Chrome\chrome.exe

**Comment by xishijt** [comment]
> @xishijt 可以在程序名前面加一些具体的路径，假设 chrome.exe 在 C:\Program Files\Google Chrome 下
> 
> 可以这么写：
> Google Chrome\chrome.exe

还有这种操作啊...话说现在的流氓软件默认目录已经是AppData不是Program Files了.
还有一点就是规则无法编辑,就连删除都做不到,我创建一个chrome规则已经用了好几个命名了....

**Comment by ghost** [comment]
@xishijt 对了，可能要双斜杠，你自己测测吧
