### ISSUE TITLE
软件UI错误

### ISSUE THREAD

**Issue by nita0318** [netchx/netch#312]
**错误描述**
软件UI出错

**复现步骤**
不知道，用TUN/TAP全局加速时突然出现的错误
重启后消失

**日志**
不适用

**错误截图**

![1](https://user-images.githubusercontent.com/49789145/87543781-ddd1bd80-c6d7-11ea-9aea-25b1c31f58da.PNG)

出错时UI如下

![2](https://user-images.githubusercontent.com/49789145/87543819-f641d800-c6d7-11ea-9235-1eb8015e3438.PNG)

**信息**
- 操作系统：Windows 10 企业版 64 位 2004 19041.329]
- 软件版本：1.4.11

其他
tg群组不能加入了，能解锁一下吗

**Comment by nita0318** [comment]
另外tg群组不能加入了，能解锁一下吗

**Comment by AmazingDM** [comment]
请尝试actions最新编译，另外tg群组没问题 除非你被管理员封禁

**Comment by chsbuffer** [comment]
没有确定的复现方法
没有进一步补充
请尝试最新 Release
如果一周内未响应将关闭此问题
