### ISSUE TITLE
使用V2Board的订阅地址更新成功但是没有添加服务器

### ISSUE THREAD

**Issue by wxmuma** [netchx/netch#323]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. 添加V2Board的订阅地址
https://v2board.com/api/v1/client/subscribe?token=1944a3ac76575e5cc56028b72d0bb102
3. 更新订阅

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。
无日志产生
**错误截图**
![image](https://user-images.githubusercontent.com/68687497/88271584-f199a700-cd09-11ea-8410-2346f0976462.png)

**Comment by chsbuffer** [comment]
![image](https://user-images.githubusercontent.com/33744752/88284936-da19e880-cd20-11ea-8f4a-524468698bce.png)
不能复现, 无法定位错误
