### ISSUE TITLE
界面改进请求

### ISSUE THREAD

**Issue by CarbonPool** [netchx/netch#324]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
现在的代理游戏或程序列表非常不友好，希望能与Proxifier那样方便管理游戏模式，或者可以添加一个快速搜索游戏模式进程的功能

**额外信息**

**Comment by chsbuffer** [comment]
能否详细描述 **Proxifier那样方便管理游戏模式** 具体是什么样的

**快速搜索游戏模式进程** 一直有, 在 菜单栏-模式-创建进程模式-扫描

**Comment by chsbuffer** [comment]
可能与 #115 重复

**Comment by CarbonPool** [comment]
> 能否详细描述**Proxifier那样方便管理游戏模式**具体是某种的
> 
> **快速搜索游戏模式**进展一直有，在菜单栏-模式-创建进展模式-扫描

![TIM截图20200723213149](https://user-images.githubusercontent.com/26106045/88292262-05ee9b80-cd2c-11ea-9d9a-8b74300051ba.png)
这样的管理进程模式比较直观
