### ISSUE TITLE
同一个订阅v2rayN可以获取到服务器netch获取不到

### ISSUE THREAD

**Issue by wxmuma** [netchx/netch#326]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**
对错误的清晰简洁描述
同一个订阅v2rayN可以获取到服务器netch获取不到
**复现步骤**
1. 同时打开 Netch 软件和v2rayN
2. 添加订阅地址
3.更新订阅
https://www.wxbns.cn/api/v1/client/subscribe?token=429b65302673335d604c8e816946aad1

![image](https://user-images.githubusercontent.com/68687497/88449313-6b4fa300-ce78-11ea-9911-58f364d3272f.png)
![image](https://user-images.githubusercontent.com/68687497/88449323-7aceec00-ce78-11ea-87c7-d8e7932a522c.png)
![image](https://user-images.githubusercontent.com/68687497/88449334-8c17f880-ce78-11ea-8d13-10c91ad2ee2d.png)
![image](https://user-images.githubusercontent.com/68687497/88449338-989c5100-ce78-11ea-9cb6-4bea58316e59.png)
v2rayN更新出订阅地址了，但是netch没有
**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：Windows 7 专业版 64 位 7601
- 软件版本：1.4.11

**额外信息**
后台是v2board，订阅和之前sspanel的订阅稍微有点不一样是sspanel订阅先下载一个txt文本，文本里面是订阅的信息，V2BOARD是直接在网页上显示，不知道是不是因为这个问题，另外订阅链接因为我全站做了301跳转来实现强制https，这个有影响吗？

**Comment by chsbuffer** [comment]
```
$ curl https://www.wxbns.cn/api/v1/client/subscribe?token=429b65302673335d604c8e816946aad1
{
    "message": "token is error"
}
```

**Comment by chsbuffer** [comment]
订阅错误通知制作中
