### ISSUE TITLE
绕过局域网和中国大陆 模式下绕过局域网无效

### ISSUE THREAD

**Issue by mengzonefire** [netchx/netch#328]
**错误描述**
"[网页代理] 绕过局域网和中国大陆" 模式下浏览器打开局域网ip无法直连（例如网关ip），报错如下：
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included components.

"[网页代理] 绕过局域网" 模式则可以正常绕过局域网。

**信息**
- 操作系统：Windows 10 专业版 64 位 1909
- 软件版本：1.4.12

**日志**
application.log：
[2020/7/27 7:56:20][INFO] 加密代理已启动
[2020/7/27 7:56:20][INFO] 流量统计进程:(1976)v2ray

V2Ray.log：
V2Ray 4.25.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.4 windows/amd64)
A unified platform for anti-censorship.
2020/07/27 07:56:20 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  ..\data\last.json
2020/07/27 07:56:20 [Warning] v2ray.com/core: V2Ray 4.25.1 started

data/privoxy.conf：
listen-address 127.0.0.1:2802
toggle 0
show-on-task-bar 0
activity-animation 0
forward-socks5 / 127.0.0.1:2801 .
max-client-connections 4096
hide-console

**Comment by chsbuffer** [comment]
请按照问题模板提交问题
一周后未正确修改将关闭此问题

**Comment by chsbuffer** [comment]
请上传日志

**Comment by chsbuffer** [comment]
上传 data/privoxy.conf 看一下

**Comment by chsbuffer** [comment]
以前版本有这个问题吗

**Comment by mengzonefire** [comment]
使用1.4.11出现此问题，升级到1.4.12-Beta3问题依旧，旧版本未测试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NetchX/Netch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 凌晨5:00
收件人:&nbsp;"NetchX/Netch"<Netch@noreply.github.com&gt;;
抄送:&nbsp;"　"<mengzonefire@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NetchX/Netch] 绕过局域网和中国大陆 模式下绕过局域网无效 (#328)





 
以前版本有这个问题吗

**Comment by chsbuffer** [comment]
请尝试最新自动构建

**Comment by mengzonefire** [comment]
最新版自动构建中问题已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChsBuffer"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 上午6:20
收件人: "NetchX/Netch"<Netch@noreply.github.com&gt;; 
抄送: "　"<mengzonefire@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NetchX/Netch] 绕过局域网和中国大陆 模式下绕过局域网无效 (#328)





 
请尝试最新自动构建
