### ISSUE TITLE
v2ray的quic+tls协议udp端口延迟无法正常显示

### ISSUE THREAD

**Issue by sola97** [netchx/netch#329]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**
为绕过tcp限速使用quic+tls，希望支持udp协议的延迟测试

**复现步骤**
1. 打开 Netch 软件
2. ...

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题
![image](https://user-images.githubusercontent.com/17388849/88535462-80752f00-d03c-11ea-9cfa-03a60c7465ee.png)

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**

**Comment by chsbuffer** [comment]
转移至 #349
