### ISSUE TITLE
有没有真-全局代理，局域网也代理的那种。就类似sstap内置的全局代理规则那种

### ISSUE THREAD

**Issue by lusunx** [netchx/netch#330]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
简明扼要地描述需要的功能

**额外信息**

**Comment by chsbuffer** [comment]
你可以下载源码去除[相关代码](https://github.com/NetchX/Netch/blob/c9396bd6b2a51da43c0ea8d4324cdbcf6804b22e/Netch/Controllers/Mode/TUNTAPController.cs#L86~L87)自行编译
