### ISSUE TITLE
大佬能不能把这个软件移植到OPENWRT上呢

### ISSUE THREAD

**Issue by falcon9000** [netchx/netch#332]
对于主机玩家来说这个还是很有用的，传统的酸酸乳插件能用但是感觉没这个稳定，希望能增加该插件，谢谢。另外想问下，假如路由器上开了酸酸乳，电脑上开了netch，那玩游戏的时候到底是走酸酸乳的线路还是netch上选的线路呢？酸酸乳是否会影响到netch的加速效果？

**Comment by chsbuffer** [comment]
1. 没有计划移植到其他平台

2. 客户端→Netch→路由→游戏服务器
需要视具体路由，会或不会走路由器代理

3. 不影响

**Comment by billy1991830** [comment]
同求
