### ISSUE TITLE
希望能增加在添加进程界面拖入快捷方式就可以加速，以及同一个配置不同软件走不同规则，比如谷歌浏览器走gfw，游戏走全局

### ISSUE THREAD

**Issue by rogercc116** [netchx/netch#334]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the feature you want**

**Additional context** (Optional)

**Comment by chsbuffer** [comment]
不会去做
