### ISSUE TITLE
安装依了赖包，依旧无法代理

### ISSUE THREAD

**Issue by wlfzsd** [netchx/netch#336]
#
![Lily_Screenshot_1596865749](https://user-images.githubusercontent.com/16445054/89703518-16cf1c00-d97e-11ea-8b7b-ff126dd87ab8.png)
[2020/8/8 13:47:33][INFO] 当前语言：System
[2020/8/8 13:47:33][INFO] 版本:NetchX/Netch 1.4.12
[2020/8/8 13:47:33][INFO] 主程序创建日期:2020-8-8 11:16
[2020/8/8 13:47:35][INFO] 加密代理已启动
[2020/8/8 13:47:35][INFO] 内置驱动版本: 1.5.9.3
[2020/8/8 13:47:36][INFO] 流量统计进程:(1704)Redirector
----------------------------------------------------------
[APP] TO: 127.0.0.1:1080
[APP] PROC: DownloadSDKServer.exe,NTT.exe
[APP] TCP: 3901
[APP] Started
[udpCreated][8][0][192.168.1.4:4012] 
[udpCreated][11][4][192.168.1.4:59290] System
[udpCreated][14][7104][192.168.1.4:56934] C:\Windows\System32\svchost.exe
[udpCreated][15][7104][127.0.0.1:56935] C:\Windows\System32\svchost.exe
[udpCreated][16][7104][239.255.255.250:1900] C:\Windows\System32\svchost.exe
[udpCreated][18][8528][192.168.1.4:55153] C:\Program Files (x86)\360\360Safe\safemon\360tray.exe
[udpCreated][30][10284][127.0.0.1:56647] C:\Program Files (x86)\Google\Chrome Dev\Application\chrome.exe
[udpCreated][31][7460][127.0.0.1:18312] E:\Program Files (x86)\ADM\ADM.exe
[udpCreated][72][4][192.168.1.4:137] System
[udpCreated][73][1988][192.168.1.4:5353] C:\Windows\System32\svchost.exe
[udpCreated][74][1988][[ff02::fb]:5353] C:\Windows\System32\svchost.exe
[udpCreated][87][8972][192.168.1.4:5353] C:\Program Files (x86)\Google\Chrome Dev\Application\chrome.exe
[udpCreated][88][8972][[ff02::fb]:5353] C:\Program Files (x86)\Google\Chrome Dev\Application\chrome.exe
[udpCreated][143][10412][127.0.0.1:63871] C:\Program Files (x86)\sogoupinyin\9.8.0.3746\SogouCloud.exe
[udpCreated][160][10516][127.0.0.1:58436] C:\Program Files (x86)\sogoupinyin\9.8.0.3746\SGTool.exe
[udpCreated][228][1988][[2408:821a:a510:4940:fc38:4e1:1d01:343f]:58572] C:\Windows\System32\svchost.exe
[udpCreated][229][1988][[2408:821a:a510:4940:fc38:4e1:1d01:343f]:65056] C:\Windows\System32\svchost.exe
[udpClosed][229][1988][[2408:821a:a510:4940:fc38:4e1:1d01:343f]:65056]
[udpClosed][228][1988][[2408:821a:a510:4940:fc38:4e1:1d01:343f]:58572]
[udpCreated][230][10284][::] C:\Program Files (x86)\Google\Chrome Dev\Application\chrome.exe
[udpClosed][230][10284][::]
----------------------------------------------------------------------
4.11版本是可用的，自4.12就不可用了。
4.12第一个版本我记得点启动后，程序卡死或崩溃。 现在测试的beta3 就是红色未知错误。

全局模式没问题，进程模式才会出现此错误。 .net系统自带4.8删除相关补丁后重装，依旧提示此错误。

系统：win10 ltsc 2019版本

**Comment by frustreated** [comment]
这个和代理服务器也许有关系。我用的一个机场，不同版本的shadowsocksr结论不同。用netch也不能代理，估计和shadowsocksr有关。

**Comment by wlfzsd** [comment]
> 这个和代理服务器也许有关系。我用的一个机场，不同版本的shadowsocksr结论不同。用netch也不能代理，估计和shadowsocksr有关。

我不知道你说的不同版本是什么意思。  但是我那个是纯ss,也不是ssr. 而且4.1.1可以用， 4.12就不行。  .net4.8和vc运行库都重装了也不行。

**Comment by chsbuffer** [comment]
指示灯只是NAT类型参考，是否代理上请直接用代理的程序试试
