### ISSUE TITLE
关于1.4.12版本.TUN/TAP 绕过局域网和中国大陆 并不能绕过

### ISSUE THREAD

**Issue by ogura-tsukiko** [netchx/netch#337]
关于1.4.12版本。TUN/TAP 绕过局域网和中国大陆 并不能绕过。IP还是
还是代理服务器的IP。貌似之前有个版本也是这样的。还有。1.4.11一切正常。现在暂时换回1.4.11来用。

- 操作系统： Windows 10 专业版 64 位 1903
- 软件版本：Netch 1.4.12

**Comment by chsbuffer** [comment]
建议用 https://ip.skk.moe/ 测试IP

**Comment by AmazingDM** [comment]
https://ip.skk.moe/
![image](https://user-images.githubusercontent.com/10679055/89849400-06f04b80-dbbb-11ea-8ada-bf34882b072c.png)
