### ISSUE TITLE
增加 VLESS 支持

### ISSUE THREAD

**Issue by imoldchen** [netchx/netch#341]
1.v2ray 新增加了 VLESS 协议，期待跟进相关添加服务器功能
2.ss 的加密方式希望能增加 none 选项 (IPLC 没必要加密)

**Comment by ghost** [comment]
1. V2Ray 新增的 VLess 协议是可以增加的
2. 由于 shadowsocks-libev 不支持 none 加密，所以无法增加这个选项

**Comment by ghost** [comment]
@chsbuffer

**Comment by Cost11** [comment]
那现在最新版本是已经支持vless了吗？

**Comment by Rakau** [comment]
最好等分享规则出来，毕竟现在是公测，据说4.28会大更

**Comment by zyp997** [comment]
会支持trojan-go吗？

**Comment by ConnectionRefused** [comment]
@zyp997 
请问
- 为什么要支持 Trojan Go ？
- Trojan C++ 和 Trojan Go 有什么区别？
- Trojan Go 有什么好处

回答以上三个问题，我们再决定是否支持

**Comment by 1265578519** [comment]
VLESS 可以把性能发挥到极致，协议内不内置任何加密，全部调用TLS来进行加密传输。

**Comment by zyp997** [comment]
1.trojan-go和trojan的链接不同.
2.rojan-Go支持并且兼容原版Trojan的绝大多数功能，包括但不限于：
TLS/SSL隧道传输
透明代理 
UDP代理
对抗GFW被动/主动检测的机制
MySQL数据库支持
流量统计，用户流量配额限制
从数据库中的用户列表进行认证
同时，Trojan-Go还扩展了更多高效易用的功能特性：
简易模式，快速部署使用
Socks5/HTTP代理自动适配
基于tproxy的透明代理(TCP/UDP)
多平台和多操作系统支持，无特殊依赖
基于多路复用(smux)降低延迟，提升并发性能
自定义路由模块，可实现国内直连/广告屏蔽等功能
Websocket传输支持，用于实现CDN流量中转(基于WebSocket over TLS/SSL)和对抗GFW中间人攻击
自动化HTTPS证书申请，从Let's Encrypt自动申请和更新HTTPS证书
TLS指纹伪造，绕过GFW针对TLS Client Hello的特征识别
基于gRPC的API支持，支持动态用户管理和流量速度限制等
可插拔传输层，可将TLS替换为其他协议或明文传输。同时有完整的Shadowsocks混淆插件支持
支持对人类更友好的YAML配置文件格式
3.trojan-go就是trojan的升级版，就类似于ss和ssr。我认为既然能够同时支持ss和ssr，那同时支持trojan和trojan-go应该不会有太大的问题。对我来说好处就是就是支持了cdn加速。
