### ISSUE TITLE
UI底栏消失

### ISSUE THREAD

**Issue by HinataKato** [netchx/netch#342]
**错误描述**
底栏消失

**复现步骤**
无法复现

**日志**
关掉之后软件自己删了

**错误截图**
![image](https://user-images.githubusercontent.com/57648531/90138360-79268300-dda9-11ea-9b93-ff7d98d7c608.png)

**信息**
- 操作系统：Windows 10 专业版 64 位 2004
- 软件版本：1.4.11

**额外信息**

**Comment by chsbuffer** [comment]
已在1.4.12修复
