### ISSUE TITLE
进程模式备注名兼容

### ISSUE THREAD

**Issue by nita0318** [netchx/netch#343]
**功能描述**
进程模式备注名称支持包含英文冒号

**额外信息**
当前1.4.12版的进程模式备注名包含英文冒号时保存进程模式配置信息会失败并弹出错误日志
该错误不影响其他功能使用且不造成软件崩溃

相关错误日志如下
[2020/8/14 20:22:47][ERROR] System.NotSupportedException: 不支持给定路径的格式。
   在 System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   在 Netch.Forms.Mode.Process.ControlButton_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by chsbuffer** [comment]
@nita0318 已修复，请等待1.4.13
