### ISSUE TITLE
为尽可能多的VirtualBox虚拟机创建一个虚拟TAP适配器。

### ISSUE THREAD

**Issue by rabota07** [netchx/netch#346]
我需要在我的主电脑上创建一个虚拟的TAP适配器，并通过桥接适配器连接Socks5，这个定制的TAP适配器我想连接到VirtualBox。
我需要为VirtualBox上的虚拟计算机创建一个代理。这样你就可以连接多个虚拟机。

WebRTC替代Socks/SSH。
每个网络上的DNS是不同的
反ping - 减慢互联网速度（节省双向ping的时间）。
NTP服务器--NTP服务器是精确的时间服务器(可以通过UDP协议访问各个服务器)可配置IP功能，因为所有的安全服务器都不能开漏洞。

https://ibb.co/WH6TZ4c

**Comment by chsbuffer** [comment]
https://stackoverflow.com/questions/21210071/how-to-create-a-2nd-tap-adapter-for-openvpn-client-on-win7
