### ISSUE TITLE
在[3][TUN/TAP]绕过局域网和中国大陆的模式下，偶尔会强制代理百度

### ISSUE THREAD

**Issue by wlfzsd** [netchx/netch#348]
**错误描述**
在“绕过局域网和中国大陆”模式下，对同一解析ip有时候代理有时候不代理。

**复现步骤**
1.是在看百度的时候发现有点卡，然后ping了下不正常，才发现的
2.很少出现，挂机的话每天出现一两次左右，主要是用百度也很少

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。
https://wwa.lanzous.com/i0hRZfx3ljg
ip 61.135.185.32 ,日志我看到确实被代理了

**错误截图**
![Lily_Screenshot_1598073671](https://user-images.githubusercontent.com/16445054/90949453-aabede80-e47a-11ea-9e33-057ed96613d1.png)
第一个ping是被错误代理后的ping,延迟小，但是打开网页很卡（延迟小可能是由于有国内中转加速的原因吧，具体不清楚）
第二个ping是停止使用代理后的正常值，17左右，打开网页很快。

第二种测试：
由于上传截图一直报错，所以不上传了，直接文字说明下。
出现以上问题后，重新开启代理，并直接ping该ip和百度域名，延迟又都是正常的17左右了。

**信息**
- 操作系统：win10 LTSC 2019
- 软件版本：1.4.12

**额外信息**

**Comment by wlfzsd** [comment]
今天GitHub打开特别卡，我一开始以为是我节点问题。发现github.githubassets.com的相关css js的获取时间达到二十多秒。
然后ping了一下，时间在70ms左右，我一开始以为就这速度了。
1.停止加速后ping，依旧是70多
2.重新加速后ping,又变成10ms左右

我之前以为是dns查询问题，所以各种改dns设置，甚至替换了unbound.exe为最新版。  到最后才发现是netch本身问题，时好时坏。
请问能否改成类似于ssr那种绕过大陆，可以依靠大陆ip段来识别的，那个ip表还可以自己更新

**Comment by chsbuffer** [comment]
不建议使用TUN/TAP模式浏览网页

**Comment by wlfzsd** [comment]
> 不建议使用TUN/TAP模式浏览网页

请问为什么不建议啊？ 因为我主要用途就是翻墙，我这里还用的adguard，网页代理和它不兼容，真的没有别的办法了。

**Comment by chsbuffer** [comment]
Netch 有单独的网页代理模式

**Comment by wlfzsd** [comment]
> Netch 有单独的网页代理模式
网页代理模式和adguard不兼容，这个我很无奈。
我现在用的白名单模式，用的ipdeny的ip段，暂时没有出现上面我说的问题。（除了极少网站代理后打不开，跟软件也没关系）

**Comment by wlfzsd** [comment]
又出现了，github.githubassets.com相关资源打很慢或打不开，ping值在100左右。   重新开启一下，恢复为10.
也就是说，规则无缘无故失效了。

**Comment by 1265578519** [comment]
@wlfzsd https://github.com/NetchX/Netch/issues/339 下载tun2socks升级即可解决你的问题，或者等待新版本修复

**Comment by wlfzsd** [comment]
> @wlfzsd #339 下载tun2socks升级即可解决你的问题，或者等待新版本修复

十分感谢， 已升级到1.611版本，虽然ping显示不正常了，但是期待问题可以解决。

**Comment by wlfzsd** [comment]
> @wlfzsd #339 下载tun2socks升级即可解决你的问题，或者等待新版本修复

我很遗憾的说，不是他的问题。 我替换最新版，出现此问题后我测试了其他网址，发现变成了全局代理。
qq和baidu的ping都变成了1（最新版类似于bug一样的存在，被代理都是1）  百度查ip和ip138都是代理的地址。

**Comment by 1265578519** [comment]
> > @wlfzsd #339 下载tun2socks升级即可解决你的问题，或者等待新版本修复
> 
> 我很遗憾的说，不是他的问题。 我替换最新版，出现此问题后我测试了其他网址，发现变成了全局代理。
> qq和baidu的ping都变成了1（最新版类似于bug一样的存在，被代理都是1） 百度查ip和ip138都是代理的地址。

你用远程dns的情况下，并且远程dns是国外的，自然就是被代理，这是正常的，你可以选择国内360dns作为远程dns，此时不会被代理

**Comment by wlfzsd** [comment]
> > > @wlfzsd #339 下载tun2socks升级即可解决你的问题，或者等待新版本修复


> > > @wlfzsd #339 下载tun2socks升级即可解决你的问题，或者等待新版本修复
> > 
> > 
> > 我很遗憾的说，不是他的问题。 我替换最新版，出现此问题后我测试了其他网址，发现变成了全局代理。
> > qq和baidu的ping都变成了1（最新版类似于bug一样的存在，被代理都是1） 百度查ip和ip138都是代理的地址。
> 
> 你用远程dns的情况下，并且远程dns是国外的，自然就是被代理，这是正常的，你可以选择国内360dns作为远程dns，此时不会被代理


1.不是dns问题，出现问题时，解析国内域名都是对应的国内ip
2.我用的白名单模式，导入的国内ip段，所以正常情况下国内ip不可能被代理（但是却发生了）
3.时好时坏，刚开始是好的，开了一段时间可能就变成全局代理。

unbound.exe最新版tun2socks.exe最新版

**Comment by wlfzsd** [comment]
解决了......
发现tun2socks使用的是路由表，所以一定有什么鬼东西在启动的时候更改了路由表
最后发现是——360防火墙
