### ISSUE TITLE
proxy java process then gradle can not connect to daemon

### ISSUE THREAD

**Issue by komimoe** [netchx/netch#354]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**All issues about `bin/Redirector.exe` should be discussed at [issue #152](https://github.com/NetchX/Netch/issues/152).**

**Describe the bug**
proxy java process then gradle can not connect to daemon

**To Reproduce**

1. Open Netch
2. Proxy Minecraft(Java)
3. gradlew build
4. gradle can not connect to 127.0.0.1 daemon

**Log**
none

**Screenshots**
https://i.imgur.com/CAhw83a.jpg

**Environment (please complete the following information):**
- OS: Windows10 1809
- Netch Version: 1.5.0

**Additional context**
none

**Comment by fxzxmicah** [comment]
See if you need “`-Djava.net.preferIPv4Stack=true`”?

**Comment by komimoe** [comment]
> See if you need “`-Djava.net.preferIPv4Stack=true`”?

i added the arg. it works well now.
it seems that netch has poor compatibility with ipv6.

**Comment by fxzxmicah** [comment]
> > See if you need “`-Djava.net.preferIPv4Stack=true`”?
> 
> i added the arg. it works well now.
> it seems that netch has poor compatibility with ipv6.

Netch所使用的redirector.exe不支持IPv6导致，而且redirector.exe未开源，所以暂时无法解决。
