### ISSUE TITLE
Trojan does not seem to be split between mainland and outside

### ISSUE THREAD

**Issue by ghost** [netchx/netch#358]
(It happens when choose Trojan )
Enter Baidu type IP and get a US VPS IP address When I selected China's internal and external streaming.
ver 1.51

**Comment by chsbuffer** [comment]
Is it TUNTAP mode or system proxy mode?
If it’s the system proxy mode, it’s because Netch pass ACL file to encrypted proxy instead of using PAC script. Trojan doesn’t seem to support ACL.

**Comment by ghost** [comment]
Neither of them can be diverged, obviously the problem, you will find out in 10s.
