### ISSUE TITLE
剪切板批量导入

### ISSUE THREAD

**Issue by shermans** [netchx/netch#362]
剪切板导入只能一条一条导入, 如果剪切板有很多条, 就没反应了.

**Comment by chsbuffer** [comment]
不能重现

**Comment by AmazingDM** [comment]
@shermans 不能重现

**Comment by AmazingDM** [comment]
请确保你的导入链接格式符合标准

**Comment by shermans** [comment]
哦.我重试了一下.
我的格式是 SSR.......,SSR......,SSR.....这样的, 没有换行,用逗号间隔的.
然后我在SSR前面换行,就可以批量导入了.

**Comment by shermans** [comment]
哦.我重试了一下.
用逗号做分隔符的,没反应. 换行做分隔的,批量导入了.
SSR应该是支持逗号分隔符的.
我的格式是 SSR.......,SSR......,SSR.....这样的, 没有换行,用逗号间隔的.
然后我在SSR前面换行,就可以批量导入了.
lncn.org里面的SSR链接.
