### ISSUE TITLE
更新订阅的时候提示“请求被中止: 未能创建 SSL/TLS 安全通道”

### ISSUE THREAD

**Issue by ghost** [netchx/netch#364]
Windows 7 旗舰版 64位系统，每个月都有更新最新的系统补丁

同一个更新订阅链接，使用最新版v2rayN可以更新订阅
使用最新版 Netch 更新订阅会提示“请求被中止: 未能创建 SSL/TLS 安全通道”
我购买代理的站长在自己的Win10系统上，用相同的更新订阅链接在Netch上可以成功更新订阅

请问是因为我系统是Win7，所以才无法更新订阅吗？能否修复？

**Comment by chsbuffer** [comment]
应该是Win7的原因
目前我不关注此问题

**Comment by ghost** [comment]
也许在Win7的环境里编译，就可以解决这个问题，您有空的话希望能试试，毕竟用Win7的用户也很多

**Comment by chsbuffer** [comment]
我在Win7虚拟机里不能复现此问题

**Comment by ghost** [comment]
https://q.cnblogs.com/q/89507/
这个您看一下，有没有帮助？

**Comment by ghost** [comment]
https://github.com/2dust/v2rayN/issues/227
以前v2rayN也出过这个问题，现在的版本可以在Win7上更新订阅了

**Comment by chsbuffer** [comment]
@Timolol2012 好的感谢

**Comment by chsbuffer** [comment]
经过讨论，决定放弃此向后兼容请求

**Comment by HMBSbige** [comment]
https://support.microsoft.com/zh-cn/help/4528489/transport-layer-security-tls-connections-might-fail-or-timeout-when-co
