### ISSUE TITLE
Apex Legends配置文件是无效的

### ISSUE THREAD

**Issue by CaliInn-Li** [netchx/netch#365]
显示所有通往数据中心的连接延迟皆为-1，即不可达（其他有腾讯、UU规则的配置文件均可正常运行）

**Comment by chsbuffer** [comment]
不太明白是什么显示延迟-1

**Comment by CaliInn-Li** [comment]
> 不太明白是什么显示延迟-1

emm我多嘴了，总之就是apex那个配置文件应该是无效的，用了之后就还是连不上服务器，，希望能补充一些腾讯规则uu规则一类的，那种用着比较稳

**Comment by Lightmani** [comment]
不太明白具体是什么问题...
我个人用APEX规则是完全正常的,到各个数据中心的延迟也都有显示
