### ISSUE TITLE
笔记本断电程序退出

### ISSUE THREAD

**Issue by Flysky12138** [netchx/netch#366]
- 笔记本断电 Netch 会有一定概率停止运行（这个问题从我开始用的版本到现在都存在）
- Netch v1.5.1 当突然断电程序停止运行后，再次运行程序，会提示Socks端口被占用。发现是ShadowsocksR程序还在运行。

**Comment by chsbuffer** [comment]
不能复现

**Comment by Flysky12138** [comment]
- 开机自启后断电BUG100%出现 
https://h8cs-my.sharepoint.com/:v:/g/personal/ky034_365a1_me/EQr0l9ihPNRJtBeajId5g9YB9xGUanNOXjWslm0bVcCedA?e=PAzqa9
