### ISSUE TITLE
希望dns服务能换一个并且最先启动起来

### ISSUE THREAD

**Issue by muziling** [netchx/netch#369]
1。希望dns服务能换成 https://github.com/wolf-joe/ts-dns ，或者提供给用户自定义
2。希望dns服务（unbound）能在连接代理和stun服务器前就启动起来。

使用场景是自己电脑网卡的DNS设置为127.0.0.1，如果dns不先启动起来，就会解析不了代理和stun服务器的域名。
设置为 127.0.0.1目的是用 ts-dns 来抗污染

**Comment by ConnectionRefused** [comment]
@muziling @chsbuffer

**Comment by ghost** [comment]
有啥问题找 @chsbuffer 和 @AmazingDM  就完事了

**Comment by muziling** [comment]
试了AmazingDM , unbound不会自动启动，手工启动ts-dns，完美。

**Comment by AmazingDM** [comment]
¿?

**Comment by muziling** [comment]
tun/tap模式下 NetchX 会自动启动unbund进程,  AmazingDM的不会。我想要的就是不启动

**Comment by chsbuffer** [comment]
@muziling 开启自定义dns,设置为127.0.0.1不会启动unbound

**Comment by ghost** [comment]
https://github.com/aiocloud/aiodns

已经安排上，等 @chsbuffer 对接
