### ISSUE TITLE
Vscode模式文件改进

### ISSUE THREAD

**Issue by hathlife** [netchx/netch#370]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
1.现在的release里面有两个vscode的模式文件，感觉有点多余，下一个release里面可以简化
2.建议vscode模式内加入ssh.exe进程（新版本vscode仅代理winpty进程无法让远程模式走代理）（win10）

**额外信息**

**Comment by chsbuffer** [comment]
@hathlife 请直接向模式仓库提交合并请求
