### ISSUE TITLE
TUN/TAP 对 Connectify 桥接模式的支持

### ISSUE THREAD

**Issue by ghost** [netchx/netch#371]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
起因是好奇 Netch 能不能给 Switch 加速，通过 WIFI 热点分享下，NAT 类型还是 D。
后来想起 Connectify 有桥接模式，于是尝试了一下，发现 Switch 无法获取 IP 和 DNS。
在设置里找到 TUN/TAP 的 IP，IP 地址填了 10.0.236.100，连上了热点，可是 DNS 还是无效。尝试过打开 FakeDNS，也尝试过指定地址，仍然无法进行 DNS 查询……

**额外信息**
无

**Comment by liuliangyz** [comment]
目前最新版本还支持加速switch吗？
