### ISSUE TITLE
下个版本

### ISSUE THREAD

**Issue by ghost** [netchx/netch#372]
**功能描述**
- [x] 简化模式列表（Redirector 支持正则匹配，可用如 steamapps 代理所有 Steam 库内游戏）
- [x] 重构编辑服务器
- [x] 删除 Server 选择框内的地域显示（大多数线路都是经过国内服务器中转的，此功能无太大意义了）
- [x] Netch 运行设备作为网关代理局域网设备

**额外信息**
- 无

**Comment by Mattraks** [comment]
建议增加ACL开关,ACL有误杀
