### ISSUE TITLE
多个模式对应多个服务器

### ISSUE THREAD

**Issue by crazyde21** [netchx/netch#374]
**功能描述**
有这么一个需求，某应用(单文件应用)检测一个ip最多登录2个账号，我有多个服务器可以使用，但是每次使用netch只能使用其中一台服务器。我想复制多几个应用 1.exe, 2.exe ，每一个应用配置一个模式单独连不同一个服务器。

**Comment by chsbuffer** [comment]
Proxifier (不支持 udp)

**Comment by AmazingDM** [comment]
可以`期待`一下aiocloud商业版，计划参考Proxifer开发 支持udp
