### ISSUE TITLE
模式三使用不了

### ISSUE THREAD

**Issue by nzcool** [netchx/netch#379]
**错误描述**
启动后 无法上网

**复现步骤**
1. 打开 Netch 软件
2. 使用模式三 TUN/TAP 绕过局域网和国内

**日志**
```
[2020/10/5 9:16:06][INFO] 版本: NetchX/Netch@1.6.0-Beta1
[2020/10/5 9:16:06][INFO] 启动单实例
[2020/10/5 9:16:06][INFO] 主程序 SHA256: 0b3e8f7b2cb0ba329921ae7b64fd8a03db3298e756e41a9fdc398dc9c608a0af
[2020/10/5 9:16:08][INFO] Github 最新发布版本: 1.5.1
[2020/10/5 9:16:08][INFO] 目前是最新版本
[2020/10/5 9:16:11][INFO] 启动主控制器: SSR [2][TUN/TAP] 绕过局域网和中国大陆
[2020/10/5 9:16:12][INFO] TAP 适配器：本地连接 {4D5C8813-0C60-4742-94F6-E0E4CE7E08E4} TAP-Windows Adapter V9, index: 41
[2020/10/5 9:16:12][INFO] 收集路由表规则
[2020/10/5 9:16:12][INFO] 绕行 → 全局绕过 IP
[2020/10/5 9:16:12][INFO] 绕行 → 服务器 IP
[2020/10/5 9:16:12][INFO] 绕行 → 局域网 IP
[2020/10/5 9:16:12][INFO] 绕行 → 中国 IP
[2020/10/5 9:16:12][INFO] 绕行 → 规则 IP
[2020/10/5 9:16:12][INFO] 代理 → 全局
[2020/10/5 9:16:12][INFO] 设置路由规则
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: **********/32 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 10.0.0.0/8 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 172.16.0.0/16 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 192.168.0.0/16 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.0.1.0/24 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.0.2.0/23 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.0.8.0/21 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.0.32.0/19 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.1.0.0/24 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.1.2.0/23 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.1.4.0/22 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.1.8.0/21 metric 0
[2020/10/5 9:16:12][WARNING] Create Route on Gateway Adapter failed: 1.1.16.0/20 metric 0
```

**信息**
- 操作系统：Windows 10 专业版 64 位
- 软件版本：Netch 1.6.0-Beta1

**Comment by SusuDOS** [comment]
出现如上的相同的问题，相关信息也如上！

**Comment by SusuDOS** [comment]
TAP使用模式三，Passby 局域网与中国大陆！无法打开baidu.com，taobao.com，jd.com等国内网址！但是使用TAP下的passby 局域网可以正常打开，显示ip为代理服务器ip！

同时TAP模式下，访问YouTube速度异常，不使用TAP的代理情况下，YouTube正常速度访问！如图：
[url=https://sm.ms/image/D53MvhtalomNSq7][img]https://i.loli.net/2020/10/05/D53MvhtalomNSq7.png[/img][/url]
[url=https://sm.ms/image/YfQCAtgmJqhviM7][img]https://i.loli.net/2020/10/05/YfQCAtgmJqhviM7.png[/img][/url]

**Comment by SusuDOS** [comment]
## TAP Passby 局域网与中国大陆问题！

无法打开baidu.com，taobao.com，jd.com等国内网址！但是使用TAP下的passby 局域网可以正常打开，显示ip为代理服务器ip！

<font color="green">手动更新路由器DNS后可以正常PAC，不确定是否是该问题！</font>


## TAP模式下，访问YouTube速度异常问题！
TAP模式下，访问YouTube速度异常问题，不使用TAP的代理情况下，YouTube正常速度访问！如图：
<a href="https://sm.ms/image/D53MvhtalomNSq7" target="_blank"><img src="https://i.loli.net/2020/10/05/D53MvhtalomNSq7.png" /></a>
<a href="https://sm.ms/image/YfQCAtgmJqhviM7" target="_blank"><img src="https://i.loli.net/2020/10/05/YfQCAtgmJqhviM7.png" /></a>

## 其他说明

这种问题(问题二)不仅仅是在netch使用STAP模式下出现，所有使用TAP模式的软件也会出现问题二，不同的电脑--两台台式机+一台笔记本 也出现了这样的情况，不确定是否VPS还是浏览器(chrome)的问题！但是使用Firefox速度会有所提升，但是还是不到Proxy代理模式的50%！

**Comment by nzcool** [comment]
这要用tuntap就是不能上网，我看日子好像是路由配置没有成功！搞了半天了 没法用

**Comment by SusuDOS** [comment]
> 这要用tuntap就是不能上网，我看日子好像是路由配置没有成功！搞了半天了 没法用

我的可以正常使用，但是存在如上的两个问题。一：设置passby中国大陆+局域网，国内网址无法访问，但是可以“富强”。二：使用TAP的一切模式，都会有youtube速度异常，如上图一，不使用TAP，则速度正常，如图二！

**Comment by nzcool** [comment]
还有个问题，我自己的节点明明是NAT1但不能进程代理，后来好心群友给我一个也是NAT1，就可以。。。。。而且我也测试过节点，完全是没问题的！~节点是ssr的

**Comment by northtowertop** [comment]
我这里一样的问题，不管是SSR还是VMess设置了TUN/TAP模式就上不了网了,Netch log跟路由表如下。对比了一下隔壁还能正常使用的SSTAP，路由表貌似没问题？

**Log**

> [2020/10/6 20:00:30][INFO] 启动主控制器: VMess [2][TUN/TAP] Bypass LAN
> [2020/10/6 20:00:31][INFO] 出口 IPv4 地址：192.168.0.3
> [2020/10/6 20:00:31][INFO] 出口 网关 地址：fe80::1%25
> [2020/10/6 20:00:31][INFO] 出口适配器：以太网 {C10A1133-C353-479B-AC70-A815FF0B24E5} Killer E2500 Gigabit Ethernet Controller, index: 25
> [2020/10/6 20:00:31][INFO] TAP 适配器：SSTAP 1 {FFC7D0B5-DAAF-4B86-B882-6C7D99DF5ED3} TAP-Windows Adapter V9, index: 34
> [2020/10/6 20:00:31][INFO] 绕行 → 全局绕过 IP
> [2020/10/6 20:00:31][INFO] 绕行 → 服务器 IP
> [2020/10/6 20:00:31][INFO] 绕行 → 局域网 IP
> [2020/10/6 20:00:31][INFO] 绕行 → 规则 IP
> [2020/10/6 20:00:31][INFO] 代理 → 全局
> [2020/10/6 20:00:32][INFO] 移除 → 出口网卡路由
> [2020/10/6 20:00:32][WARNING] Failed Delete Route on Gateway Adapter: 0.0.0.0/0 metric 0
> [2020/10/6 20:00:32][INFO] 设置路由规则
> [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 113.212.91.0/24 metric 0
> [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 113.212.91.108/32 metric 0
> [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 10.0.0.0/8 metric 0
> [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 172.16.0.0/16 metric 0
> [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 192.168.0.0/16 metric 0
> [2020/10/6 20:00:32][INFO] 流量统计进程:(18056)v2ray
> [2020/10/6 20:00:48][INFO] [NTT] Other address is: 
> [2020/10/6 20:00:48][INFO] [NTT] Binding test: Fail
> [2020/10/6 20:00:48][INFO] [NTT] Local address: 
> [2020/10/6 20:00:48][INFO] [NTT] Mapped address: 
> [2020/10/6 20:00:48][INFO] [NTT] Nat filtering behavior: Unknown
> [2020/10/6 20:00:48][INFO] [NTT] Nat mapping behavior: Unknown
> [2020/10/6 20:00:48][INFO] [NTT] result: Unknown
> [2020/10/6 20:02:26][INFO] TAP 适配器：SSTAP 1 {FFC7D0B5-DAAF-4B86-B882-6C7D99DF5ED3} TAP-Windows Adapter V9, index: 34
> [2020/10/6 20:02:27][INFO] TAP 适配器：SSTAP 1 {FFC7D0B5-DAAF-4B86-B882-6C7D99DF5ED3} TAP-Windows Adapter V9, index: 34

**路由表**

> IPv4 路由表
> 
> 活动路由:
> 网络目标        网络掩码          网关       接口   跃点数
>           0.0.0.0          0.0.0.0      192.168.0.1      192.168.0.3    200
>           0.0.0.0          0.0.0.0       10.0.237.1      10.0.237.10      0
>        10.0.237.0    255.255.255.0            在链路上       10.0.237.10    256
>       10.0.237.10  255.255.255.255            在链路上       10.0.237.10    256
>      10.0.237.255  255.255.255.255            在链路上       10.0.237.10    256
>         127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
>         127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
>   127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
>       172.18.32.0    255.255.240.0            在链路上       172.18.32.1    271
>       172.18.32.1  255.255.255.255            在链路上       172.18.32.1    271
>     172.18.47.255  255.255.255.255            在链路上       172.18.32.1    271
>       172.20.64.0    255.255.240.0            在链路上       172.20.64.1   5256
>       172.20.64.1  255.255.255.255            在链路上       172.20.64.1   5256
>     172.20.79.255  255.255.255.255            在链路上       172.20.64.1   5256
>      172.21.240.0    255.255.240.0            在链路上      172.21.240.1   5256
>      172.21.240.1  255.255.255.255            在链路上      172.21.240.1   5256
>    172.21.255.255  255.255.255.255            在链路上      172.21.240.1   5256
>       172.23.32.0    255.255.240.0            在链路上       172.23.32.1   5256
>       172.23.32.1  255.255.255.255            在链路上       172.23.32.1   5256
>     172.23.47.255  255.255.255.255            在链路上       172.23.32.1   5256
>        172.24.0.0    255.255.240.0            在链路上        172.24.0.1   5256
>        172.24.0.1  255.255.255.255            在链路上        172.24.0.1   5256
>     172.24.15.255  255.255.255.255            在链路上        172.24.0.1   5256
>      172.26.144.0    255.255.240.0            在链路上      172.26.144.1   5256
>      172.26.144.1  255.255.255.255            在链路上      172.26.144.1   5256
>    172.26.159.255  255.255.255.255            在链路上      172.26.144.1   5256
>        172.28.0.0    255.255.240.0            在链路上        172.28.0.1   5256
>        172.28.0.1  255.255.255.255            在链路上        172.28.0.1   5256
>     172.28.15.255  255.255.255.255            在链路上        172.28.0.1   5256
>      172.28.112.0    255.255.240.0            在链路上      172.28.112.1    271
>      172.28.112.1  255.255.255.255            在链路上      172.28.112.1    271
>    172.28.127.255  255.255.255.255            在链路上      172.28.112.1    271
>       192.168.0.0    255.255.255.0            在链路上       192.168.0.3    356
>       192.168.0.3  255.255.255.255            在链路上       192.168.0.3    356
>     192.168.0.255  255.255.255.255            在链路上       192.168.0.3    356
>      192.168.33.0    255.255.255.0            在链路上      192.168.33.1    291
>      192.168.33.1  255.255.255.255            在链路上      192.168.33.1    291
>    192.168.33.255  255.255.255.255            在链路上      192.168.33.1    291
>     192.168.200.0    255.255.255.0            在链路上     192.168.200.1    291
>     192.168.200.1  255.255.255.255            在链路上     192.168.200.1    291
>   192.168.200.255  255.255.255.255            在链路上     192.168.200.1    291
>     192.168.208.0    255.255.240.0            在链路上     192.168.208.1   5256
>     192.168.208.1  255.255.255.255            在链路上     192.168.208.1   5256
>   192.168.223.255  255.255.255.255            在链路上     192.168.208.1   5256
>         224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
>         224.0.0.0        240.0.0.0            在链路上      192.168.33.1    291
>         224.0.0.0        240.0.0.0            在链路上     192.168.200.1    291
>         224.0.0.0        240.0.0.0            在链路上       10.0.237.10    256
>         224.0.0.0        240.0.0.0            在链路上       192.168.0.3    356
>         224.0.0.0        240.0.0.0            在链路上      172.26.144.1   5256
>         224.0.0.0        240.0.0.0            在链路上      172.21.240.1   5256
>         224.0.0.0        240.0.0.0            在链路上        172.28.0.1   5256
>         224.0.0.0        240.0.0.0            在链路上       172.20.64.1   5256
>         224.0.0.0        240.0.0.0            在链路上     192.168.208.1   5256
>         224.0.0.0        240.0.0.0            在链路上       172.23.32.1   5256
>         224.0.0.0        240.0.0.0            在链路上        172.24.0.1   5256
>         224.0.0.0        240.0.0.0            在链路上       172.18.32.1    271
>         224.0.0.0        240.0.0.0            在链路上      172.28.112.1    271
>   255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
>   255.255.255.255  255.255.255.255            在链路上      192.168.33.1    291
>   255.255.255.255  255.255.255.255            在链路上     192.168.200.1    291
>   255.255.255.255  255.255.255.255            在链路上       10.0.237.10    256
>   255.255.255.255  255.255.255.255            在链路上       192.168.0.3    356
>   255.255.255.255  255.255.255.255            在链路上      172.26.144.1   5256
>   255.255.255.255  255.255.255.255            在链路上      172.21.240.1   5256
>   255.255.255.255  255.255.255.255            在链路上        172.28.0.1   5256
>   255.255.255.255  255.255.255.255            在链路上       172.20.64.1   5256
>   255.255.255.255  255.255.255.255            在链路上     192.168.208.1   5256
>   255.255.255.255  255.255.255.255            在链路上       172.23.32.1   5256
>   255.255.255.255  255.255.255.255            在链路上        172.24.0.1   5256
>   255.255.255.255  255.255.255.255            在链路上       172.18.32.1    271
>   255.255.255.255  255.255.255.255            在链路上      172.28.112.1    271
> 
> 永久路由:
>   网络地址          网络掩码  网关地址  跃点数
>           0.0.0.0          0.0.0.0         10.0.0.0       1

**Comment by SusuDOS** [comment]
> 我这里一样的问题，不管是SSR还是VMess设置了TUN/TAP模式就上不了网了,Netch log跟路由表如下。对比了一下隔壁还能正常使用的SSTAP，路由表貌似没问题？
> 
> **Log**
> 
> > [2020/10/6 20:00:30][INFO] 启动主控制器: VMess [2][TUN/TAP] Bypass LAN
> > [2020/10/6 20:00:31][INFO] 出口 IPv4 地址：192.168.0.3
> > [2020/10/6 20:00:31][INFO] 出口 网关 地址：fe80::1%25
> > [2020/10/6 20:00:31][INFO] 出口适配器：以太网 {C10A1133-C353-479B-AC70-A815FF0B24E5} Killer E2500 Gigabit Ethernet Controller, index: 25
> > [2020/10/6 20:00:31][INFO] TAP 适配器：SSTAP 1 {FFC7D0B5-DAAF-4B86-B882-6C7D99DF5ED3} TAP-Windows Adapter V9, index: 34
> > [2020/10/6 20:00:31][INFO] 绕行 → 全局绕过 IP
> > [2020/10/6 20:00:31][INFO] 绕行 → 服务器 IP
> > [2020/10/6 20:00:31][INFO] 绕行 → 局域网 IP
> > [2020/10/6 20:00:31][INFO] 绕行 → 规则 IP
> > [2020/10/6 20:00:31][INFO] 代理 → 全局
> > [2020/10/6 20:00:32][INFO] 移除 → 出口网卡路由
> > [2020/10/6 20:00:32][WARNING] Failed Delete Route on Gateway Adapter: 0.0.0.0/0 metric 0
> > [2020/10/6 20:00:32][INFO] 设置路由规则
> > [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 113.212.91.0/24 metric 0
> > [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 113.212.91.108/32 metric 0
> > [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 10.0.0.0/8 metric 0
> > [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 172.16.0.0/16 metric 0
> > [2020/10/6 20:00:32][WARNING] Failed Create Route on Gateway Adapter: 192.168.0.0/16 metric 0
> > [2020/10/6 20:00:32][INFO] 流量统计进程:(18056)v2ray
> > [2020/10/6 20:00:48][INFO] [NTT] Other address is:
> > [2020/10/6 20:00:48][INFO] [NTT] Binding test: Fail
> > [2020/10/6 20:00:48][INFO] [NTT] Local address:
> > [2020/10/6 20:00:48][INFO] [NTT] Mapped address:
> > [2020/10/6 20:00:48][INFO] [NTT] Nat filtering behavior: Unknown
> > [2020/10/6 20:00:48][INFO] [NTT] Nat mapping behavior: Unknown
> > [2020/10/6 20:00:48][INFO] [NTT] result: Unknown
> > [2020/10/6 20:02:26][INFO] TAP 适配器：SSTAP 1 {FFC7D0B5-DAAF-4B86-B882-6C7D99DF5ED3} TAP-Windows Adapter V9, index: 34
> > [2020/10/6 20:02:27][INFO] TAP 适配器：SSTAP 1 {FFC7D0B5-DAAF-4B86-B882-6C7D99DF5ED3} TAP-Windows Adapter V9, index: 34
> 
> **路由表**
> 
> > IPv4 路由表
> > 活动路由:
> > 网络目标        网络掩码          网关       接口   跃点数
> > 0.0.0.0          0.0.0.0      192.168.0.1      192.168.0.3    200
> > 0.0.0.0          0.0.0.0       10.0.237.1      10.0.237.10      0
> > 10.0.237.0    255.255.255.0            在链路上       10.0.237.10    256
> > 10.0.237.10  255.255.255.255            在链路上       10.0.237.10    256
> > 10.0.237.255  255.255.255.255            在链路上       10.0.237.10    256
> > 127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
> > 127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
> > 127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
> > 172.18.32.0    255.255.240.0            在链路上       172.18.32.1    271
> > 172.18.32.1  255.255.255.255            在链路上       172.18.32.1    271
> > 172.18.47.255  255.255.255.255            在链路上       172.18.32.1    271
> > 172.20.64.0    255.255.240.0            在链路上       172.20.64.1   5256
> > 172.20.64.1  255.255.255.255            在链路上       172.20.64.1   5256
> > 172.20.79.255  255.255.255.255            在链路上       172.20.64.1   5256
> > 172.21.240.0    255.255.240.0            在链路上      172.21.240.1   5256
> > 172.21.240.1  255.255.255.255            在链路上      172.21.240.1   5256
> > 172.21.255.255  255.255.255.255            在链路上      172.21.240.1   5256
> > 172.23.32.0    255.255.240.0            在链路上       172.23.32.1   5256
> > 172.23.32.1  255.255.255.255            在链路上       172.23.32.1   5256
> > 172.23.47.255  255.255.255.255            在链路上       172.23.32.1   5256
> > 172.24.0.0    255.255.240.0            在链路上        172.24.0.1   5256
> > 172.24.0.1  255.255.255.255            在链路上        172.24.0.1   5256
> > 172.24.15.255  255.255.255.255            在链路上        172.24.0.1   5256
> > 172.26.144.0    255.255.240.0            在链路上      172.26.144.1   5256
> > 172.26.144.1  255.255.255.255            在链路上      172.26.144.1   5256
> > 172.26.159.255  255.255.255.255            在链路上      172.26.144.1   5256
> > 172.28.0.0    255.255.240.0            在链路上        172.28.0.1   5256
> > 172.28.0.1  255.255.255.255            在链路上        172.28.0.1   5256
> > 172.28.15.255  255.255.255.255            在链路上        172.28.0.1   5256
> > 172.28.112.0    255.255.240.0            在链路上      172.28.112.1    271
> > 172.28.112.1  255.255.255.255            在链路上      172.28.112.1    271
> > 172.28.127.255  255.255.255.255            在链路上      172.28.112.1    271
> > 192.168.0.0    255.255.255.0            在链路上       192.168.0.3    356
> > 192.168.0.3  255.255.255.255            在链路上       192.168.0.3    356
> > 192.168.0.255  255.255.255.255            在链路上       192.168.0.3    356
> > 192.168.33.0    255.255.255.0            在链路上      192.168.33.1    291
> > 192.168.33.1  255.255.255.255            在链路上      192.168.33.1    291
> > 192.168.33.255  255.255.255.255            在链路上      192.168.33.1    291
> > 192.168.200.0    255.255.255.0            在链路上     192.168.200.1    291
> > 192.168.200.1  255.255.255.255            在链路上     192.168.200.1    291
> > 192.168.200.255  255.255.255.255            在链路上     192.168.200.1    291
> > 192.168.208.0    255.255.240.0            在链路上     192.168.208.1   5256
> > 192.168.208.1  255.255.255.255            在链路上     192.168.208.1   5256
> > 192.168.223.255  255.255.255.255            在链路上     192.168.208.1   5256
> > 224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
> > 224.0.0.0        240.0.0.0            在链路上      192.168.33.1    291
> > 224.0.0.0        240.0.0.0            在链路上     192.168.200.1    291
> > 224.0.0.0        240.0.0.0            在链路上       10.0.237.10    256
> > 224.0.0.0        240.0.0.0            在链路上       192.168.0.3    356
> > 224.0.0.0        240.0.0.0            在链路上      172.26.144.1   5256
> > 224.0.0.0        240.0.0.0            在链路上      172.21.240.1   5256
> > 224.0.0.0        240.0.0.0            在链路上        172.28.0.1   5256
> > 224.0.0.0        240.0.0.0            在链路上       172.20.64.1   5256
> > 224.0.0.0        240.0.0.0            在链路上     192.168.208.1   5256
> > 224.0.0.0        240.0.0.0            在链路上       172.23.32.1   5256
> > 224.0.0.0        240.0.0.0            在链路上        172.24.0.1   5256
> > 224.0.0.0        240.0.0.0            在链路上       172.18.32.1    271
> > 224.0.0.0        240.0.0.0            在链路上      172.28.112.1    271
> > 255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
> > 255.255.255.255  255.255.255.255            在链路上      192.168.33.1    291
> > 255.255.255.255  255.255.255.255            在链路上     192.168.200.1    291
> > 255.255.255.255  255.255.255.255            在链路上       10.0.237.10    256
> > 255.255.255.255  255.255.255.255            在链路上       192.168.0.3    356
> > 255.255.255.255  255.255.255.255            在链路上      172.26.144.1   5256
> > 255.255.255.255  255.255.255.255            在链路上      172.21.240.1   5256
> > 255.255.255.255  255.255.255.255            在链路上        172.28.0.1   5256
> > 255.255.255.255  255.255.255.255            在链路上       172.20.64.1   5256
> > 255.255.255.255  255.255.255.255            在链路上     192.168.208.1   5256
> > 255.255.255.255  255.255.255.255            在链路上       172.23.32.1   5256
> > 255.255.255.255  255.255.255.255            在链路上        172.24.0.1   5256
> > 255.255.255.255  255.255.255.255            在链路上       172.18.32.1    271
> > 255.255.255.255  255.255.255.255            在链路上      172.28.112.1    271
> > 永久路由:
> > 网络地址          网络掩码  网关地址  跃点数
> > 0.0.0.0          0.0.0.0         10.0.0.0       1

我的Socks5以及Vmess协议正常！
---
自建VMess如图：
<a href="https://sm.ms/image/pZwvhKaNl2zGMfi" target="_blank"><img src="https://i.loli.net/2020/10/06/pZwvhKaNl2zGMfi.png" /></a>

机场SSR如图：
<a href="https://sm.ms/image/w8SgoqNVp2uUjiL" target="_blank"><img src="https://i.loli.net/2020/10/06/w8SgoqNVp2uUjiL.png" /></a>

目前尽量让状态 "显示灯" (右下角)为绿色，橙色状态，不能为灰色，灰色(NTT测试存在问题为灰色.)的情况下，清理DNS，点击 start确定状态正常！

**Comment by eiyooooo** [comment]
同样的情况，我是从1.5.1更新到1.6.0后TUN/TAP模式才不能用的
![image](https://user-images.githubusercontent.com/52876220/95285117-9734cf00-0892-11eb-9ab4-32293afcbe25.png)

log一样是
Failed Create Route on Gateway Adapter
Failed Delete Route on Gateway Adapter

**Comment by SusuDOS** [comment]
> 同样的情况，我是从1.5.1更新到1.6.0后TUN/TAP模式才不能用的
> ![image](https://user-images.githubusercontent.com/52876220/95285117-9734cf00-0892-11eb-9ab4-32293afcbe25.png)
> 
> log一样是
> Failed Create Route on Gateway Adapter
> Failed Delete Route on Gateway Adapter

是这样的，因为你有一些netch进程启动而未完全的关闭，再启动启动netch，则会出现这样的问题！该问题我遇到过....用完全重置端口的方法+关闭netch所调用的有关进程后，重启netch可以解决的！

还有一种情况是：该节点不可用了，请用SSTap测试一下！netch测试不出问题，可能只是测试的ping.

**Comment by huxxx123** [comment]
> 同样的情况，我是从1.5.1更新到1.6.0后TUN/TAP模式才不能用的
> ![image](https://user-images.githubusercontent.com/52876220/95285117-9734cf00-0892-11eb-9ab4-32293afcbe25.png)
> 
> log一样是
> Failed Create Route on Gateway Adapter
> Failed Delete Route on Gateway Adapter

1.6.1版本解决了，现在能用了

**Comment by eiyooooo** [comment]
> > 同样的情况，我是从1.5.1更新到1.6.0后TUN/TAP模式才不能用的
> > ![image](https://user-images.githubusercontent.com/52876220/95285117-9734cf00-0892-11eb-9ab4-32293afcbe25.png)
> > log一样是
> > Failed Create Route on Gateway Adapter
> > Failed Delete Route on Gateway Adapter
> 
> 是这样的，因为你有一些netch进程启动而未完全的关闭，再启动启动netch，则会出现这样的问题！该问题我遇到过....用完全重置端口的方法+关闭netch所调用的有关进程后，重启netch可以解决的！
> 
> 还有一种情况是：该节点不可用了，请用SSTap测试一下！netch测试不出问题，可能只是测试的ping.

1.6.1版本解决了，现在能用了

**Comment by eiyooooo** [comment]
> 这要用tuntap就是不能上网，我看日子好像是路由配置没有成功！搞了半天了 没法用

1.6.1应该能用了，你试试

**Comment by chsbuffer** [comment]
请下载最新自动构建再次测试并报告

**Comment by ghost** [comment]
由于已经出了新版，此 issue 没有新的回复，暂且关闭
