### ISSUE TITLE
彩虹六号加速不能使用语音

### ISSUE THREAD

**Issue by LoveMyself546** [netchx/netch#383]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
彩虹六号加速不能使用语音功能，with Uplay和without uplay均尝试过。这个是游戏问题还是netsh问题呢？如果是netsh问题能否尝试改进一下呢，感谢。

**额外信息**

**Comment by ghost** [comment]
请到 netsh 那里去反馈问题，我们这里是 Netch，不要搞错了
