### ISSUE TITLE
订阅链接只保留一个的问题啥时候解决下

### ISSUE THREAD

**Issue by xiaowenlv** [netchx/netch#385]
一直这样，当有多个订阅链接的时候，只会保留最后一个更新链接的节点

**Comment by chsbuffer** [comment]
版本，日志

**Comment by chsbuffer** [comment]
1.6.0 不能复现，请检查你的订阅链接可用

**Comment by xiaowenlv** [comment]
之前几个版本也是一样的，只要订阅有多个链接，那最后一个更新的就会覆盖前面的，这样始终只能保留一个订阅的节点

**Comment by chsbuffer** [comment]
请描述更新订阅时弹出的通知并附上日志

**Comment by minGGeMG** [comment]
> 请描述更新订阅时弹出的通知并附上日志

同一个代理提供商下多个不同的账户可以复现此问题

**Comment by xiaowenlv** [comment]
是不同的提供商，通知就提示从x更新xx个服务器，日志：
[2020/10/9 11:41:39][INFO] 版本: NetchX/Netch@1.6.1
[2020/10/9 11:41:39][INFO] 启动单实例
[2020/10/9 11:41:39][INFO] 主程序 SHA256: cf0a0db75043a0366662aa79757093c7fe76de618ae1788bf88fe7d6ea40f297
[2020/10/9 11:41:40][ERROR] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String text)
[2020/10/9 11:41:40][ERROR] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String text)

顺便问下，设置自定义DNS可以绕过服务商的网站屏蔽吗，以前可以的，现在不知怎么不行了。

**Comment by chsbuffer** [comment]
应该是 vmess链接 不符合 v2rayN 格式标准。
请你将订阅内的字符base64解码为 json ，替换掉服务器域名和密码等隐私信息，附上 json
如果你不明白但是信任我的话，可以直接 Telegram 私聊我 [@ChsBuffer](https://t.me/chsbuffer)

**Comment by chsbuffer** [comment]
请下载最新自动构建再次测试并报告

**Comment by xiaowenlv** [comment]
我确实不明白要怎么做，你的电报多少呢，好像我使用所有的服务商都会出现这问题，至少五六家都会
