### ISSUE TITLE
关于当前启动模式的显示问题！

### ISSUE THREAD

**Issue by SusuDOS** [netchx/netch#387]
环境：Windows10 64 教育版，netch最新版本1.6.0.
## 将某一配置方式保存到快捷位置后，显示异常，但不影响连接！使非保存的方式启动的则不会影响，1.6-beta1版本没有此问题！
如图：正常的应该是如图一，显示异常的如图二（无论是否管理员方式运行都会出现！）

图一
<a href="https://sm.ms/image/Ao3CtM19BOTmKPw" target="_blank"><img src="https://i.loli.net/2020/10/07/Ao3CtM19BOTmKPw.jpg" /></a>

图二
<a href="https://sm.ms/image/hcM9L12SBvdwapo" target="_blank"><img src="https://i.loli.net/2020/10/07/hcM9L12SBvdwapo.png" /></a>

## 网卡 的显示有一点问题，正常的如图三，异常的如图四.

图三

<a href="https://sm.ms/image/NuGp4XcWjJgCIsz" target="_blank"><img src="https://i.loli.net/2020/10/07/NuGp4XcWjJgCIsz.png" /></a>
<a href="https://sm.ms/image/hQlcvZ6NAJ1Y7oE" target="_blank"><img src="https://i.loli.net/2020/10/07/hQlcvZ6NAJ1Y7oE.png" /></a>
----
图四
<a href="https://sm.ms/image/f5Oe7uW2sBJ3Ly8" target="_blank"><img src="https://i.loli.net/2020/10/07/f5Oe7uW2sBJ3Ly8.png" /></a>
<a href="https://sm.ms/image/GbrTJ7pckxw3qKz" target="_blank"><img src="https://i.loli.net/2020/10/07/GbrTJ7pckxw3qKz.jpg" /></a>

**Comment by chsbuffer** [comment]
显示不下了没办法
TAP 模式网络连接问题调查中，重复
