### ISSUE TITLE
从 1.6 开始进程模式无法正常代理 DMM 商店

### ISSUE THREAD

**Issue by ghost** [netchx/netch#391]
![1 5 1](https://user-images.githubusercontent.com/45543164/95443753-ee709780-0997-11eb-9578-66ca62dde43a.png)
![1 6 1](https://user-images.githubusercontent.com/45543164/95443761-f2041e80-0997-11eb-986b-f38311aac988.png)

- 操作系统：[Windows 10 专业版 64 位 2004]

**Comment by ghost** [comment]
1.5.1
[application.log](https://github.com/NetchX/Netch/files/5346962/application.log)
[Redirector.log](https://github.com/NetchX/Netch/files/5346963/Redirector.log)
[V2Ray.log](https://github.com/NetchX/Netch/files/5346966/V2Ray.log)

**Comment by ghost** [comment]
1.6.1
[application.log](https://github.com/NetchX/Netch/files/5346973/application.log)
[V2Ray.log](https://github.com/NetchX/Netch/files/5346974/V2Ray.log)

**Comment by chsbuffer** [comment]
请附上你创建的规则。
注意新版本进程模式规则遵循正则表达式语法
请留意并修改规则

**Comment by ghost** [comment]
1.5.1
[DMMGamePlayer.txt](https://github.com/NetchX/Netch/files/5347039/DMMGamePlayer.txt)

1.6.1
[DMM GAME.txt](https://github.com/NetchX/Netch/files/5347040/DMM.GAME.txt)

**Comment by ghost** [comment]
![1 6 1(2)](https://user-images.githubusercontent.com/45543164/95446079-c8002b80-099a-11eb-86a8-5aaf3000c02b.png)
[application.log](https://github.com/NetchX/Netch/files/5347085/application.log)
[tun2socks.log](https://github.com/NetchX/Netch/files/5347086/tun2socks.log)
[V2Ray.log](https://github.com/NetchX/Netch/files/5347087/V2Ray.log)
TUN/TAP可以用但是网卡会变成这样
![Snipaste_2020-10-08_19-17-35](https://user-images.githubusercontent.com/45543164/95446210-f0882580-099a-11eb-8cfd-5e42bc511366.png)

**Comment by ghost** [comment]
不要 assign 我，这玩意不关我事，你先把日志做好 @chsbuffer

**Comment by Brouzy** [comment]
遇到同一个问题。

**Comment by Shercoolcool** [comment]
MapleStory国际服也有一样的问题。

**Comment by ghost** [comment]
`4731e27d2e93db84bc573bbcfde9fb5788891f25`

**Comment by Brouzy** [comment]
1.6.3已测试，未修复。

**Comment by ghost** [comment]
> 1.6.3已测试，未修复。

Won't fix
