### ISSUE TITLE
能不能别排除192.168网段吗

### ISSUE THREAD

**Issue by yinzhefuyun** [netchx/netch#397]
能不能别排除192.168网段吗，我像用这个软件做回家代理用来回自己家读取文件，还有把explorer.exe加入后ftp://192.168.1.1可以打开 \\192.168.1.1却不能打开，是支持者ftp不支持samba吗？

**Comment by chsbuffer** [comment]
启动加速后管理员权限终端执行 ``route DELETE 192.168.0.0``
