### ISSUE TITLE
希望增加全局代理选项

### ISSUE THREAD

**Issue by liuminglm** [netchx/netch#4]
软件内置了一些游戏代理规则，但是推出游戏后还需要更换代理软件，很不方便，希望增加全局代理，如果能支持按照域名代理那就更好了

**Comment by ycfnzz** [comment]
永远不会，放心吧，专心只做游戏

**Comment by BingLingGroup** [comment]
全局已经在做了，但不会是最优先添加的功能。

**Comment by ghost** [comment]
Fixed in [8cf289c8ad1887d1e91b7341c8f6941bdb7d13aa](https://github.com/netchx/Netch/commit/8cf289c8ad1887d1e91b7341c8f6941bdb7d13aa)
