### ISSUE TITLE
软件开启后被代理应用无法连接网络

### ISSUE THREAD

**Issue by kylyzhh** [netchx/netch#401]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
软件开启后被代理应用无法连接网络，流量计无流量走动，模式：进程代理

**复现步骤**
1. 打开 Netch 软件
2. 选中任意被代理进程
3. 启动

**日志**
[Redirector][aio_dial][clrName] DONE
[Redirector][aio_dial][addName] eve.exe
[Redirector][aio_dial][addName] exefile.exe
[Redirector][aio_dial][addName] LogServer.exe
[Redirector][aio_dial][addName] evelauncher.exe
[Redirector][aio_dial][addName] fixpermissions.exe
[Redirector][aio_dial][addName] LogLite.exe
[Redirector][aio_dial][addName] QtWebEngineProcess.exe
[Redirector][aio_dial][addName] updater.exe
[Redirector][aio_dial][addName] NTT.exe
[Redirector][aio_dial][tcpHost] 127.0.0.1:2801
[Redirector][aio_dial][udpHost] 127.0.0.1:2801
[Redirector][eh_init] IsCoreLoaded => FALSE
[Redirector][eh_init] filterLoopback => FALSE
[Redirector][eh_init] filterTCP => TRUE
[Redirector][eh_init] filterUDP => TRUE
[Redirector][eh_init] tcpHost => 127.0.0.1:2801
[Redirector][eh_init] udpHost => 127.0.0.1:2801
[Redirector][eh_init] aList => eve.exe
[Redirector][eh_init] aList => exefile.exe
[Redirector][eh_init] aList => LogServer.exe
[Redirector][eh_init] aList => evelauncher.exe
[Redirector][eh_init] aList => fixpermissions.exe
[Redirector][eh_init] aList => LogLite.exe
[Redirector][eh_init] aList => QtWebEngineProcess.exe
[Redirector][eh_init] aList => updater.exe
[Redirector][eh_init] aList => NTT.exe
[core][tools.String] Copied from 0xc0000503e0 to 0xc0000503f0
[core][tools.String] Copied from 0xc000050400 to 0xc000050410
[core][srn_init] TCP Type => Socks
[core][srn_init] TCP Addr => 127.0.0.1:2801
[core][srn_init] UDP Type => Socks
[core][srn_init] UDP Addr => 127.0.0.1:2801
[core][srn_init] Client => 3080
[Redirector][udpCreated][1][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][1]
[Redirector][udpCreated][2][!this->checkHandleName] Unknown
[Redirector][udpCreated][3][HANDLE] D:\Program Files\Netch - 162\bin\NTT.exe
[core][udpHandle] 127.0.0.1:54583 → [::]:54585 → 127.0.0.1:2801
[Redirector][udpCreated][7][!this->checkHandleName] D:\Program Files\Netch - 162\bin\v2ray.exe
[Redirector][tcpConnectRequest][2][!this->checkHandleName] D:\Program Files\Netch - 162\bin\v2ray.exe
[Redirector][udpCreated][8][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][8]
[Redirector][tcpConnectRequest][6][!this->checkHandleName] D:\Program Files (x86)\Tencent\QQ\Bin\QQ.exe
[Redirector][tcpConnectRequest][7][!this->checkHandleName] D:\Program Files (x86)\Tencent\QQ\Bin\QQ.exe
[Redirector][tcpConnectRequest][28][!this->checkHandleName] D:\Program Files\ShadowsocksR-Portable-Win64-5.1.9\ShadowsocksR.exe
[Redirector][tcpConnectRequest][33][!this->checkHandleName] D:\Program Files\ShadowsocksR-Portable-Win64-5.1.9\ShadowsocksR.exe
[Redirector][tcpConnectRequest][53][!this->checkHandleName] D:\Program Files\Netch - 162\bin\v2ray.exe
[Redirector][tcpConnectRequest][54][!this->checkHandleName] D:\Program Files\Netch - 162\bin\v2ray.exe
[Redirector][udpClosed][3]
[Redirector][tcpConnectRequest][55][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][tcpConnectRequest][56][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][tcpConnectRequest][59][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][udpCreated][9][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][9]
[Redirector][tcpConnectRequest][68][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][tcpConnectRequest][70][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][udpCreated][10][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpCreated][11][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][11]
[Redirector][tcpConnectRequest][72][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][tcpConnectRequest][74][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][udpCreated][12][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][12]
[Redirector][tcpConnectRequest][75][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][10]
[Redirector][tcpConnectRequest][77][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][tcpConnectRequest][80][!this->checkHandleName] C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\SearchUI.exe
[Redirector][udpCreated][13][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpCreated][14][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][14]
[Redirector][tcpConnectRequest][81][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][81][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200000 to 0xc000200010
[Redirector][udpClosed][13]
[Redirector][tcpConnectRequest][84][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][84][TARGET] 203.208.40.65:443
[core][tools.String] Copied from 0xc000200020 to 0xc000200030
[Redirector][tcpConnectRequest][89][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][89][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200040 to 0xc000200050
[Redirector][udpCreated][15][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpCreated][16][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][15]
[Redirector][tcpConnectRequest][92][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][92][TARGET] 99.84.227.56:443
[core][tools.String] Copied from 0xc000200060 to 0xc000200070
[Redirector][udpClosed][16]
[Redirector][tcpConnectRequest][93][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][93][TARGET] 99.84.227.65:443
[core][tools.String] Copied from 0xc000200080 to 0xc000200090
[Redirector][tcpConnectRequest][98][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][98][TARGET] 99.84.227.56:443
[core][tools.String] Copied from 0xc0002000a0 to 0xc0002000b0
[Redirector][tcpConnectRequest][101][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][101][TARGET] 99.84.227.56:443
[core][tools.String] Copied from 0xc0002000c0 to 0xc0002000d0
[Redirector][tcpConnectRequest][104][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][104][TARGET] 99.84.227.56:443
[core][tools.String] Copied from 0xc0002000e0 to 0xc0002000f0
[Redirector][tcpConnectRequest][108][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][108][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200100 to 0xc000200110
[Redirector][tcpConnectRequest][112][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][112][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200120 to 0xc000200130
[Redirector][tcpConnectRequest][117][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][117][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200140 to 0xc000200150
[Redirector][tcpConnectRequest][121][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][121][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200160 to 0xc000200170
[Redirector][tcpConnectRequest][125][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][125][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200180 to 0xc000200190
[Redirector][udpCreated][17][!this->checkHandleName] Unknown
[Redirector][tcpConnectRequest][130][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][130][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002001a0 to 0xc0002001b0
[Redirector][udpCreated][18][!this->checkHandleName] C:\Windows\System32\svchost.exe
[Redirector][udpClosed][18]
[Redirector][tcpConnectRequest][134][!this->checkHandleName] D:\Program Files (x86)\SogouInput\9.5.0.3517\SGTool.exe
[Redirector][tcpConnectRequest][135][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][135][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002001c0 to 0xc0002001d0
[Redirector][tcpConnectRequest][138][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][138][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002001e0 to 0xc0002001f0
[Redirector][udpCreated][19][!this->checkHandleName] Unknown
[Redirector][tcpConnectRequest][141][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][141][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200200 to 0xc000200210
[Redirector][tcpConnectRequest][144][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][144][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200220 to 0xc000200230
[Redirector][tcpConnectRequest][150][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][150][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200240 to 0xc000200250
[Redirector][udpCreated][20][!this->checkHandleName] Unknown
[Redirector][tcpConnectRequest][153][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][153][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200260 to 0xc000200270
[Redirector][tcpConnectRequest][158][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][158][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200280 to 0xc000200290
[Redirector][tcpConnectRequest][161][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][161][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002002a0 to 0xc0002002b0
[Redirector][tcpConnectRequest][164][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][164][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002002c0 to 0xc0002002d0
[Redirector][tcpConnectRequest][167][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][167][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002002e0 to 0xc0002002f0
[Redirector][tcpConnectRequest][170][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][170][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200300 to 0xc000200310
[Redirector][tcpConnectRequest][174][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][174][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200320 to 0xc000200330
[Redirector][tcpConnectRequest][177][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][177][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200340 to 0xc000200350
[Redirector][tcpConnectRequest][180][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][180][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200360 to 0xc000200370
[Redirector][tcpConnectRequest][183][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][183][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200380 to 0xc000200390
[Redirector][tcpConnectRequest][187][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][187][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002003a0 to 0xc0002003b0
[Redirector][tcpConnectRequest][194][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][194][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002003c0 to 0xc0002003d0
[Redirector][tcpConnectRequest][197][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][197][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc0002003e0 to 0xc0002003f0
[Redirector][tcpConnectRequest][200][HANDLE] E:\Steam\steamapps\common\Eve Online\Launcher\evelauncher.exe
[Redirector][tcpConnectRequest][200][TARGET] 13.35.123.34:443
[core][tools.String] Copied from 0xc000200400 to 0xc000200410

**错误截图**
软件界面显示一切正常

被代理软件无法联网

**信息**
- 操作系统：Windows 10 专业版 64 位 1909
- 软件版本：1.6.2  64 位

**额外信息**
无

**Comment by ghost** [comment]
`4731e27d2e93db84bc573bbcfde9fb5788891f25`
