### ISSUE TITLE
是否考虑加入v2ray

### ISSUE THREAD

**Issue by Sdator** [netchx/netch#408]
我尝试用netch加入本地socks服务器，如127.0.0.1:10800 此端口是我在 v2ray 中所监听的socks入口，我从v2ray的日志反馈中得到一些错误，netch似乎无法转发到v2ray中处理
```
2020/10/15 22:29:44 tcp:127.0.0.1:9517 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
2020/10/15 22:29:46 tcp:127.0.0.1:9519 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
2020/10/15 22:29:46 tcp:127.0.0.1:9520 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
```
我想如果能加入v2ray可以利用v2ray的均衡负载分流功能。

**Comment by EKyero** [comment]
@Sdator 游戏用负载均衡是嫌太稳定了吗?

**Comment by Sdator** [comment]
> @Sdator游戏用负载均衡是嫌太稳定了吗？

先不考虑是不是用于加速游戏，但如果是针对游戏来说，我们都知道一个游戏的服务器并不止一台，它可实现对不同的游戏服务器进行分流以选择最佳的节点，我认为这是加速器必备的功能。 除此之外我们也可以使用v2ray的配置文件来集中管理对于开发者来说我觉得是个不错的选择。
