### ISSUE TITLE
tun2socks在连接一个小时后爆cpu

### ISSUE THREAD

**Issue by imtipi** [netchx/netch#411]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. 连接节点（tuntap绕过局域网+大陆ip模式）
3.游玩一个小时游戏后发生爆cpu现象（csgo占用40%，tun2socks占30%，总cpu使用占满）

**日志**
[logging.zip](https://github.com/NetchX/Netch/files/5397577/logging.zip)
[WARNING] 写入 tun2socks 日志错误：
索引超出范围。必须为非负值并小于集合大小。
参数名: chunkLength

**错误截图**
无，当时已经接近死机边缘，只能快速杀死netch全部进程
**信息**
- 操作系统：win10企业版 1909
- 软件版本：1.6.2

**额外信息**
已经查看过之前的issue，但是这次是连接一个小时后爆cpu，不是开始连接时爆

**Comment by ghost** [comment]
这是 tun2socks 的 BUG 吧。等等会有新的（

**Comment by imtipi** [comment]
问题暂时解决。应该是我开着clash的原因，可能clash的tap没卸载干净导致和tun2socks冲突了
