### ISSUE TITLE
tun/tap模式无法设置自定义dns

### ISSUE THREAD

**Issue by ghost** [netchx/netch#420]
![image](https://user-images.githubusercontent.com/57820613/96908545-5e6e3a00-14cf-11eb-88f3-bf5f8a90dc6b.png)

**Comment by chsbuffer** [comment]
@kirin10000 已修复

**Comment by ghost** [comment]
> 已修复
@chsbuffer 
哪里下载呢？我已经下载的最新版了

**Comment by chsbuffer** [comment]
@kirin10000 此下载 Actions 自动构建或等待下一个正式版本
