### ISSUE TITLE
请求增加dns分流功能

### ISSUE THREAD

**Issue by OnlyCharacter** [netchx/netch#421]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
在解析国外域名时可以指定dns，在解析国内域名时指定另一个dns，并且可以选择dns请求是否通过代理。
（类似mellow）
**额外信息**
另外，1.6.4的dns设置好像有问题，不能自定义dns。

**Comment by ghost** [comment]
该功能早就有了，是 @chsbuffer 没有做选项吧
