### ISSUE TITLE
按进程代理，无法代理部分http请求

### ISSUE THREAD

**Issue by maplebeats** [netchx/netch#425]
我用按进程扫描模式+ss协议代理nexon国际版，登陆的时候界面能出来，但是点击登陆发现请求并没有走代理导致登陆请求异常，最终失败。
单独打开ss的pac模式之后，请求正常，有流量走单独的ss，登陆成功后游戏功能一切正常，说明有一部分http请求走了系统web，没有走netch，登陆后的流量又走到netsh了。
这种情况有啥好办法解决吗？

**Comment by ghost** [comment]
那就这样用
