### ISSUE TITLE
如果能增加回国模式就无敌了

### ISSUE THREAD

**Issue by yigeni** [netchx/netch#426]
这个客户端使用了1年，确实非常好用，唯一遗憾的是没有回国模式，如果补全了，其它那些市面乱七八糟的客户端都可以忽略了！感谢作者无私的开发和更新，不知道是否以后会增加回国模式，期待...

**Comment by chsbuffer** [comment]
你自己创建一个这个模式，你无敌了

**Comment by chsbuffer** [comment]
你可以在把 TUN/TAP 跳过大陆的规则 从 2 （跳过规则IP）改为 1 （代理规则IP），但是模式引用仅针对相同的模式，所以你需要删除第二行对跳过局域网模式的引用。
对于这样创建出的规则，不保证其能够准确包括你所需要使用的国内服务。

**Comment by ghost** [comment]
![](https://user-images.githubusercontent.com/52200558/97182922-19e8e400-17d8-11eb-9608-1ac9c543cd2f.png)
