### ISSUE TITLE
[网页代理]绕过局域网和中国大陆并不能绕过中国大陆

### ISSUE THREAD

**Issue by stcdf** [netchx/netch#427]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**
1.6.2版本以后，[网页代理]绕过局域网和中国大陆的效果和[网页代理]绕过局域网的效果一样，并没有绕过中国大陆。
**复现步骤**
1. 打开 Netch 软件
2. 
**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[ Windows 10 专业版 64 位 2004]
- 软件版本：[1.6.3-1.6.6]

**额外信息**

**Comment by A-little-bit-of-data** [comment]
感觉netch和sstap很像，但是没有那种内置的规则，虽然下载的时候有这个规则显示，可以选择，但是里面什么都没写，希望作者能搞搞，加上就完美了

**Comment by chsbuffer** [comment]
![image](https://user-images.githubusercontent.com/33744752/97807262-ccb6b780-1c9a-11eb-8579-3719c1e639cf.png)
https://github.com/NetchX/Netch/blob/master/docs/Advanced_Usage.zh-CN.md#%E6%A8%A1%E5%BC%8F-4-http-%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86
