### ISSUE TITLE
似乎没有解决 DNS 污染问题

### ISSUE THREAD

**Issue by smounives** [netchx/netch#43]
Netch 代理的软件会受到 DNS 污染的影响，例如在 Netch 里添加 Google Chrome 并尝试访问 Google 会因为 DNS 污染而收到错误的证书（如*.facebook.com）导致无法正常打开。

**Comment by ghost** [comment]
进程代理（模式一）没有对 DNS 问题做出特殊处理

- 如果有必要，可以本地自建 dnscrypt-proxy 这种东西
- 或者可以把 DNS 修改至 8.8.8.8 的 DNS 看看

**Comment by smounives** [comment]
有其他模式选吗？

**Comment by ghost** [comment]
有两个模式 `[4]` 吧（Browser only）

而且有 BUG，貌似 CPU 莫名高

**Comment by ghost** [comment]
TUN/TAP 支持已经有了，但是我没有亲自测试 ( PR by @tindy2013 )

**Comment by smounives** [comment]
看了下 Bypass LAN and China 和 Bypass LAN 里面的内容是空的，选上之后也没任何效果，应该是还没做完吧，期待以后的效果

**Comment by tindy2013** [comment]
@smounives TUN/TAP支持有另外的mode文件，开头TUN/TAP那个

**Comment by ghost** [comment]
空的很正常 ... 规则直接内置写死的 ... 而且说了：browser only

**Comment by ghost** [comment]
点错 ... close 掉了，再开

**Comment by ghost** [comment]
已经有对应的处理方案了（经过实测）

等我有时间就搞上

**Comment by smounives** [comment]
好！多谢大佬
