### ISSUE TITLE
socks5配置信息中地址使用服务器计算机名时tun2sock启动失败

### ISSUE THREAD

**Issue by EjiHuang** [netchx/netch#432]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**所有关于 `bin/Redirector.exe` 的问题，请在 [issue #152](https://github.com/NetchX/Netch/issues/152) 中讨论**

**错误描述**
socks5配置信息中地址使用服务器计算机名时tun2sock启动失败，使用服务器IP时，则加速正常。

**复现步骤**
1. 打开 Netch 软件
2. 启动加速

**日志**
tun2socks.log
2020/11/07 00:05:25 TAP device component ID: {B214E744-3826-42A4-872C-546690C44F5A}
2020/11/07 00:05:25 TAP device name: 本地连接
2020/11/07 00:05:25 Set 本地连接 with net/mask: 10.0.236.10/255.255.255.0 through DHCP
2020/11/07 00:05:25 Set 本地连接 with DNS: 127.0.0.1 through DHCP
2020/11/07 00:05:25 invalid proxy server address: address fe80::dc38:ac12:99c3:1ec2%19:65500: too many colons in address

**错误截图**
![image](https://user-images.githubusercontent.com/10510947/98387999-1cc3be80-208d-11eb-988d-8c759a343730.png)

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**

**Comment by chsbuffer** [comment]
关闭 设置-解析服务器主机名 or 用你的服务器 IP

**Comment by Xiaojuziaimeiqiu** [comment]
提示tun2socks start failed,如何解决呀，百度都百度不出来。
