### ISSUE TITLE
tup/tap模式与VMware冲突导致高CPU占用

### ISSUE THREAD

**Issue by libxing** [netchx/netch#434]
如图，开启tup/tap模式后，系统有一个服务一直占用cpu，请问怎么解决？
![1](https://user-images.githubusercontent.com/30516698/98437420-f0f01980-211c-11eb-9145-b1d951a51677.png)
![2](https://user-images.githubusercontent.com/30516698/98437421-f3527380-211c-11eb-96c7-8a269bcece86.png)

**Comment by chsbuffer** [comment]
https://netch.org/#/docs/zh-CN/faq?id=%e5%bc%80%e5%90%af-tuntap-%e6%a8%a1%e5%bc%8f%e5%90%8e-cpu-%e5%8d%a0%e7%94%a8%e9%ab%98

**Comment by libxing** [comment]
> https://netch.org/#/docs/zh-CN/faq?id=%e5%bc%80%e5%90%af-tuntap-%e6%a8%a1%e5%bc%8f%e5%90%8e-cpu-%e5%8d%a0%e7%94%a8%e9%ab%98

已解决 感谢！！！
