### ISSUE TITLE
netch 保留配置升级到1.6.6后，不能修改配置

### ISSUE THREAD

**Issue by ghost** [netchx/netch#437]
初次使用netch自动升级，从netch 1.6.5升级到1.6.6，其他都正常，就是不能修改配置。

修改配置点击保存，没有任何反应。

**Comment by chsbuffer** [comment]
@fengzhongyun1992 上个版本中把 RedirectorTCP 搞错了，这个版本会检查设置里的端口是否重复，请修改 RedirectorTCP 端口

**Comment by ghost** [comment]
确实，修改了 RedirectorTCP  端口 就可以了
