### ISSUE TITLE
MCAFEE 将1.5.X之后版本的v2ray plugin 识别为木马， 导致无法安装。 

### ISSUE THREAD

**Issue by dioshu** [netchx/netch#438]
下载之后就被MCAFEE删除， 无法打开。 无法更新。 

MCAFEE日志：  
运行的 C:\Program Files (x86)\Google\Chrome\Application\chrome.exe 试图访问 C:\Users\xxxx\AppData\Local\Google\Chrome\User Data\Default\Cache\f_00035d\v2ray-plugin.exe。 已检测到并删除了名为 Artemis!OIIIEJ3752 的 特洛伊木马程序。

**Comment by chsbuffer** [comment]
duplicate #403
