### ISSUE TITLE
TUN/TAP模式下，Office軟體無法連線至伺服器

### ISSUE THREAD

**Issue by fs910175** [netchx/netch#441]
TUN/TAP模式下，Office軟體無法連線至伺服器。
但其他程式有成功連線。
使用SSTAP的時候也發生一樣的問題。

註：網頁登入微軟沒有問題，僅有軟體發生錯誤

**Comment by xepher** [comment]
我记得UWP是要处理下的, 可以试着用Fiddler提供的EnableLoopback.exe设置下

**Comment by fs910175** [comment]
> 我记得UWP是要处理下的, 可以试着用Fiddler提供的EnableLoopback.exe设置下

使用失敗XD
可能設成直連IP比較快

**Comment by peaceshi** [comment]
https://github.com/NetchX/Netch/issues/453
