### ISSUE TITLE
关于大陆屏蔽raw.githubusercontent.com无法更新大部分订阅的提议

### ISSUE THREAD

**Issue by jumwhi** [netchx/netch#442]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**
raw.githubusercontent.com，在大陆被屏蔽，但是公共订阅基本都是用raw.githubusercontent.com网址的，能否开发一个功能在更新订阅前，先连接某个节点，或者连接节点下更新订阅，就如同更新acl一样
Thank
**功能描述**
简明扼要地描述需要的功能

**额外信息**

**Comment by chsbuffer** [comment]
看管理订阅左下角。

**Comment by jumwhi** [comment]
ok,has been deal,
前天发现的，忘了回复
thank
