### ISSUE TITLE
功能请求：对使用web网关登录的游戏进程进行代理的模式

### ISSUE THREAD

**Issue by Autliety** [netchx/netch#445]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
日本Nexon公司的部分网络游戏，使用Web登录、唤起本地进程的方式启动游戏。因此需要使用特定域名（开启游戏登录网页）+特定进程（游戏进程）的某种意义上的“混合模式”。是否可能在软件中实现？

**额外信息**
eg.  https://arad.nexon.co.jp

**Comment by Autliety** [comment]
Well, 抓取所有IP后使用TAP确实可以解决。但是不够优雅（笑

**Comment by AmazingDM** [comment]
使用进程模式网页出现问题时请尝试在设置中打开以下选项
![image](https://user-images.githubusercontent.com/10679055/100184050-7a9f3580-2ed8-11eb-9562-75de44878c7a.png)
