### ISSUE TITLE
功能请求：增加排除部分程序的代理功能

### ISSUE THREAD

**Issue by OXERIS** [netchx/netch#446]
**功能描述**
希望在开启tun/tap模式后能选择排除对部分程序的代理，

 比如：在开启代理后，我的bt下载也会被代理，但是很多机场禁止bt下载，但是bt下载时，会随机连接上来自不同地方的用户，无法通过分流的方式解决这个问题。

所以我希望netch在运行时，能选择排除对某个应用所有流量和连接的代理。

**Comment by chsbuffer** [comment]
建议使用 proxifier

**Comment by ghost** [comment]
虽然 TUN/TAP 不会实现这种功能，但是进程模式可以有

@chsbuffer
