### ISSUE TITLE
TUN/TAP模式极大概率无效

### ISSUE THREAD

**Issue by ipcjs** [netchx/netch#448]
**错误描述**
TUN/TAP模式极大概率无效，小概率正常。。。

**复现步骤**
1. 打开 Netch 软件
2. 导入v2ray服务器
3. 选择 [TUN/TAP]绕过局域网和中国大陆
4. baidu.com能正常打开，google.com不能打开

**日志**
[tun2socks.log](https://github.com/NetchX/Netch/files/5602719/tun2socks.log)
[VMess.log](https://github.com/NetchX/Netch/files/5602721/VMess.log)
[application.log](https://github.com/NetchX/Netch/files/5602722/application.log)

**错误截图**

**信息**
- 操作系统：Windows 10 教育版 64 位 2004
- 软件版本：1.6.7

**额外信息**

**Comment by chsbuffer** [comment]
你可能将 `设置-TUN/TAP-DNS` 设置为了当地 ISP DNS,
建议设置为 1.1.1.1 或禁用自定义 DNS
