### ISSUE TITLE
更新到1.6.7出现无法加载指定模块情况。

### ISSUE THREAD

**Issue by FreeRolled** [netchx/netch#450]
![image](https://user-images.githubusercontent.com/74105070/100530780-20340b00-3231-11eb-9b75-24c9afaead7e.png)

更新到1.6.7出现无法加载指定模块情。
无法加载DLL"NetchCore".找不到指定的模块。（来自HRESULT：0X800700E）
缺少文件或运行库。

**Comment by AmazingDM** [comment]
请解压后使用:D
