### ISSUE TITLE
can i use netch on openwrt VM for ps4

### ISSUE THREAD

**Issue by isslam95** [netchx/netch#454]
hello,

can i accelerate connection for ps4 maybe using openwrt VM ??

**Comment by chsbuffer** [comment]
Netch is Windows only.
If you wana proxy other device, recommend using
https://github.com/zhxie/pcap2socks/

ps: pcap2socks latest commit Windows build here
https://github.com/zhxie/pcap2socks/issues/8#issuecomment-719584264
