### ISSUE TITLE
TCP Ping

### ISSUE THREAD

**Issue by OneHappyForever** [netchx/netch#456]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**
[Searched already]

**Describe the feature you want**
[Use TCP instead of ICMP ping]

**Additional context** (Optional)
[ Some servers block ICMP requests. It would be beneficial to have an option in Settings to change the PING type from ICMP to TCP ping in those circumstances (i.e. port check). This would also check if the port is open and working.]

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/blob/7b9d9a6d570d8da6acd7b03f8f772d088ad3eacd/Netch/Utils/Utils.cs#L39
