### ISSUE TITLE
希望能增加多路链接支持

### ISSUE THREAD

**Issue by miaopasimiao** [netchx/netch#458]
![image](https://user-images.githubusercontent.com/35228123/101428607-06cf4500-393c-11eb-899e-043d2d9467d7.png)
请问能增加多路支持么，我路由器上总共拨了三个号，但是只能使用到其中一路，如果能同时使用多个的话就好了

**Comment by AmazingDM** [comment]
这河里吗？

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/101433150-23e72200-3902-11eb-9a33-32dc60a2acea.png)
![image](https://user-images.githubusercontent.com/10679055/101433173-2b0e3000-3902-11eb-9458-178b15eb5b3e.png)
