### ISSUE TITLE
SSR服务器显示参数有误

### ISSUE THREAD

**Issue by Askwind** [netchx/netch#46]
使用版本1.1.1 系统win10

现象：
SSR服务器的加密模式设置为rc4-MD5 保存后，再次打开服务器设置竟然显示为none。
选择其他加密模式 会出现显示值为空的情况。
希望：
能正确的显示SSR服务器的加密模式。

**Comment by ghost** [comment]
@Askwind #39

**Comment by ghost** [comment]
@Askwind 暂时不会发布新版本，请耐心等待。或者可以加入 Telegram 群组获取最新的编译版本
