### ISSUE TITLE
「DPI scale」Icon is very small

### ISSUE THREAD

**Issue by gongyoyo** [netchx/netch#460]
**Describe the bug**
Windows 4k175% scale, icon is very small and not clearly~

**Screenshots**
![2020-12-10_17-40-14](https://user-images.githubusercontent.com/36725275/101771248-96374c80-3b24-11eb-8e2e-79f156eb7401.png)

**Environment (please complete the following information):**
- OS: [e.g. Windows 10 Pro 64-bit 2004]
- Netch Version: [e.g. 1.6.7-STABLE.x64]

**Additional context**
Need new feature for custom all icon just like Clash.
Or unpack all UI elements @Installdir folder named "icon".
Users just need to replace any icon if they wanted.
Support picture format “jpg、png、svg” are enough.
![2020-12-10_17-41-03](https://user-images.githubusercontent.com/36725275/101772024-ca5f3d00-3b25-11eb-9cdb-5843f296d981.png)

In the last word: Thanks for develop Netch~💌
It's a really good Booster & Proxy client !!!

**Comment by testermania** [comment]
6 engines detected this file

https://www.virustotal.com/gui/file/1f61fdbb1734da995b63b46c13e93bbccb36140907fcd6dd4094feed0295ec26/detection

**Comment by AmazingDM** [comment]
@testermania 👍
