### ISSUE TITLE
[Feature request]Custom proxy mode for UWP applications

### ISSUE THREAD

**Issue by sino1641** [netchx/netch#463]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the feature you want**

Sincerely requesting custom proxy mode for UWP applications like Microsoft Store.
I have googled that UWP is not with a suffix as `.exe`, and I don't know how to create a custom policy for it.

**Additional context** (Optional)

**Comment by chsbuffer** [comment]
UWP application file suffix is exe

**Comment by chsbuffer** [comment]
execute Netch with -console parameter and start a process mode, then you can see which programs have sent network packages
