### ISSUE TITLE
请求：能添加支持Xray核心吗？或者做一个手动安装或更新内核的功能？

### ISSUE THREAD

**Issue by Battlecraft369** [netchx/netch#467]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
简明扼要地描述需要的功能：

能添加支持Xray核心吗？或者添加一个手动copy文件安装或更新内核的功能？

**额外信息**

这些做基础通讯内核的团体已经有三个了，搞不清是怎么回事。最好用的Vless+tcp+Xtls的功能已经被v2fly给删掉了。现在，Xray倒是支持这个。已经把vps更新了，所以发此请求。

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/103143453-37431b80-4751-11eb-9213-5413a7211802.png)
Xtls协议设计不符合传输规范，v2ray官方开发者已经不维护所以移除了，所以Xtls协议的开发者单独做了个项目为Xray进行维护。

**Comment by Fhokud** [comment]
这个表述不对，怎么叫不符合传输规范所以移除呢，完全不是这么回事
移除的导火索：许可证
移除的原因：大家都不想再说了......
xtls的不同：去除了tls包内的冗余重复加密，以及使用内核0copy，大幅节约CPU算量和内存消耗。外层仍然是合法的tls。安全性和tls无区别（比如trojan-go）

如果希望自己的数据内容最大限度层层套娃加密、不在乎损失延迟和速度，就不要用xtls。

希望释放自己硬件最大速度的就用xtls。

这本来就是用户自己权衡取舍的一件很简单的事情，没有人非说要用哪个。但是这种不明就里还胡说八道散布错误信息我就接受不了。

**Comment by badO1a5A90** [comment]
> ![image](https://user-images.githubusercontent.com/6442439/103143453-37431b80-4751-11eb-9213-5413a7211802.png)
> Xtls协议设计不符合传输规范，v2ray官方开发者已经不维护所以移除了，所以Xtls协议的开发者单独做了个项目为Xray进行维护。
> 

什么叫不符合传输规范?
请详细说明，不要随口就来。

之所以移除和单独维护的原因楼上大致已经说了，更多详细内情你可以慢慢自行研究判断。

v2也不存在什么官方，都是社区维护，有能力就维护没人力就不维护。

Xray现在保持着活跃的更新，一直在提升性能，增加功能，修复v2的历史包袱，同时也保持着社区的亲和力。

你可以到tg群，github仓库，project X关注一下，然后判断。

**Comment by RPRX** [comment]
@1265578519 不懂能不能就不要乱讲话？这位对 xtls 的误解是自古以来的了，建议看一遍个人主页。

此外，Xray 的 Shadowsocks 和 Trojan 已实现 FullCone，并且 Xray 有 VMess 的 AEAD 和 VLESS 的 XTLS，对主流科学协议的支持是最完整的，同时包含客户端与服务端，大多数场景下 Xray 即可解决问题。

Shadowsocks 的 UDP 多倍发包、长度混淆，与通用的 UDP over TCP 聚合隧道也不远了，这两项增强将使 Xray 成为最适合打游戏的多协议平台，敬请期待。

**Comment by 1265578519** [comment]
@rprx 了解，感谢解答

**Comment by imoldchen** [comment]
还是建议把xray替代v2ray，因为前者是兼容后者的，并且最近准备增加 vless 的 fullcone nat 支持，v2ray 因为去掉了 xtls，速度和对游戏优化上已经没有任何优势了。

**Comment by Fzygs** [comment]
自己手动替换内核不就行了 改文件名 2秒钟搞定

**Comment by AndersonGhost** [comment]
> 
如何手动替换？将xray的最新内核“xray.exe”替换成为“v2ray-sn.exe”，并命名为“v2ray-sn.exe”吗？系统为win10

**Comment by HamiltionBert** [comment]
> 自己手动替换内核不就行了 改文件名 2秒钟搞定

如何手动替换？将xray的最新内核“xray.exe”替换成为“v2ray-sn.exe”，并命名为“v2ray-sn.exe”吗？系统为win10

**Comment by xhqpp** [comment]
> 自己手动替换内核不就行了 改文件名 2秒钟搞定

还2秒钟搞定 你个傻鸟要编译的🙂
