### ISSUE TITLE
启动提示 no internet connection/更新订阅提示"WebUtil 的类型初始值设定项引发异常"

### ISSUE THREAD

**Issue by ChewJ404** [netchx/netch#468]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**
 打开程序保存

**To Reproduce**

1. 打开 Netch
2.  弹出 no internet connection

**Log**
[2020/12/21 19:58:48][INFO] 启动主控制器: VMess [3][Web Proxy] Bypass LAN and China
[2020/12/21 19:58:50][WARNING] System.TypeInitializationException: “Netch.Utils.WebUtil”的类型初始值设定项引发异常。 ---> System.NotSupportedException: 不支持请求的安全协议。
   在 System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   在 System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   在 Netch.Utils.WebUtil..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Netch.Utils.WebUtil.CreateRequest(String url, Nullable`1 timeout, String userAgent)
   在 Netch.Controllers.UpdateChecker.<Check>d__19.MoveNext()
[2020/12/21 19:58:50][ERROR] System.TypeInitializationException: “Netch.Utils.WebUtil”的类型初始值设定项引发异常。 ---> System.NotSupportedException: 不支持请求的安全协议。
   在 System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
   在 System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
   在 Netch.Utils.WebUtil..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Netch.Utils.WebUtil.CreateRequest(String url, Nullable`1 timeout, String userAgent)
   在 Netch.Utils.Subscription.UpdateServer(SubscribeLink item, String proxyServer)

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows 10 企业版LTSC  1809  x64
- Netch Version:  1.6.8

**Additional context**

**Comment by ssr20001** [comment]
我也是这样，报错了

**Comment by CODE-7z** [comment]
+1

**Comment by chsbuffer** [comment]
1.6.8 有启动/更新问题的手动下载 1.6.9 覆盖更新

**Comment by ChewJ404** [comment]
已经验证修复 成功 yes :smile:
