### ISSUE TITLE
请求添加不代理TCP流量功能

### ISSUE THREAD

**Issue by z826540272** [netchx/netch#471]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
请求添加不代理TCP流量功能
如同现在的进程模式不代理UDP一样
其次,请求添加 TCP UDP 使用不同节点的功能
部分游戏只验证TCP ip归属地,强制要求家庭宽带等,但是 UDP 可以选择其他节点获得更好的稳定性
**额外信息**

**Comment by chsbuffer** [comment]
在做了在做了(检出分支)

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/commit/ce15e9468e6fc4f151f0bed14c57d0602b1672b9
