### ISSUE TITLE
gta5 UU规则出现莫名自行下载bug

### ISSUE THREAD

**Issue by jinbasex** [netchx/netch#474]
开启之后 并未游玩gta 也没有进行翻墙的行为   准备关闭电脑时发现netch一直在进行满速下载
【也可能是我本身游玩环境出现问题，这里更多是给流量不多的同学提个醒并进行讨论】
【也可能是我本身游玩环境出现问题，这里更多是给流量不多的同学提个醒并进行讨论】
【也可能是我本身游玩环境出现问题，这里更多是给流量不多的同学提个醒并进行讨论】

[NTT.log](https://github.com/NetchX/Netch/files/5742211/NTT.log)
[tun2socks.log](https://github.com/NetchX/Netch/files/5742212/tun2socks.log)
[application.log](https://github.com/NetchX/Netch/files/5742213/application.log)

**Comment by jinbasex** [comment]
加速行为过程  本地开启V2N 使用netch代理S5 进行游戏加速

**Comment by jinbasex** [comment]
@chsbuffer 
不好意思 萌新一枚 请问我的提问方式有问题吗？
还是我操作错误才导致这个一直离奇下载的结果？

**Comment by chsbuffer** [comment]
GTAOL TUNTAP 模式很久都没有更新
模式问题不属于 Netch 问题

**Comment by jinbasex** [comment]
> GTAOL TUNTAP 模式很久都没有更新
> 模式问题不属于 Netch 问题

感谢回答
麻烦了
