### ISSUE TITLE
Netch 检测 NAT 类型的方式需要修正

### ISSUE THREAD

**Issue by RPRX** [netchx/netch#479]
需要跟进 NatTypeTester 的更新，以前它也存在问题，经历了一些大更新后，现在没问题了（指最新版 3.3）
具体来说，并不是所有 STUN Server 都是准确的，尤其是 Google 那几个完全不标准，所以可以看到现在默认只留了五个
主要是因为 v2 系列普遍存在“能收到包但源地址认定错误”的问题，如果没有严格判断，就会导致错误的认定
比如由于这个神奇的特性，加上 VMess 协议设计上的不足，VMess 的 NAT 不该属于任何类型，但最接近 Symmetric

**Comment by AmazingDM** [comment]
https://github.com/NetchX/Netch/commit/ca0870889a573a3390ae15d801b0d419b5f3abc1
