### ISSUE TITLE
1.67更新提示进程仅支持代理TCP的疑问

### ISSUE THREAD

**Issue by wlfzsd** [netchx/netch#483]
那么他是不代理UDP,还是把UDP包装成了TCP?
游戏ping值是会变低,但是不明白具体指什么?

**Comment by AmazingDM** [comment]
进程模式不代理UDP

**Comment by chsbuffer** [comment]
仅代理TCP（不代理UDP）的设置选项，更新日志没写全

**Comment by wlfzsd** [comment]
> 进程模式不代理UDP
我测试了下游戏. 进程模式下是有很多tcp流量,但是也走直连udp.
tun模式下只走udp,不走tcp .
是游戏自身的加速技术?

**Comment by NinjaUmbra** [comment]
@wlfzsd 提供进程模式只代理tcp 适用于一些和国内人联机就可以玩的游戏 这个情况下不代理udp和国内人连延迟会比较低
