### ISSUE TITLE
支持 DoT/DoH 查询

### ISSUE THREAD

**Issue by kurdsvv** [netchx/netch#491]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the feature you want**

**Additional context** (Optional)

**Comment by ghost** [comment]
Maybe

**Comment by honwen** [comment]
recommend repo: https://github.com/AdguardTeam/dnsproxy

**Comment by honwen** [comment]
Functional Repo: https://github.com/honwen/aiodns

BlackList Mode(default): `aiodns -l=:53`

Example Usage of white-list mode:
```bash
aiodns -u tls://dns.google -U 114.114.114.114 -L china_site_list.txt
aiodns -u https://cloudflare-dns.com/dns-query -U tls://223.6.6.6 -L china_site_list.txt

aiodns -u https://cloudflare-dns.com/dns-query -u tls://dns.google -U tls://223.6.6.6 -U tls://dns.pub -U 114.114.114.114 -L china_site_list.txt
```

**Comment by honwen** [comment]
But I'm `NOT` familiar with C#, need help to develop using it

**Comment by SekiBetu** [comment]
DOH will greatly increase delay, not good for gaming

**Comment by ghost** [comment]
已完成 DoT 支持，设置项待 @chsbuffer 添加

**Comment by wyjtm** [comment]
> DOH will greatly increase delay, not good for gaming

但是doh解析更安全和准确  如果能支持tcp+端口 还有其他更稳定的dns可以用
