### ISSUE TITLE
希望可以增加trojan的Mux多路复用功能

### ISSUE THREAD

**Issue by zchazc** [netchx/netch#493]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**
看了下 readme、在 issue 中搜索过 “trojan-go” “mux”关键词，貌似没有重复的内容。
**功能描述**
希望可以直接支持[trojan-go](https://github.com/p4gefau1t/trojan-go)或增加[mux多路复用](https://p4gefau1t.github.io/trojan-go/advance/mux/)功能，mux对游戏加速来说挺有用的，希望可以有。

**额外信息**
现在得中间加了个trojan-qt5的sock5

**Comment by zchazc** [comment]
呃，我刚翻了下代码发现 Netch 都是直接调用的可执行文件开个 client 然后用 socks，这样的话直接替换可执行文件就可以了啊，trojan-go 完全兼容向下兼容 trojan，命令不用改直接在这儿加点儿配置选项就行啊。
https://github.com/NetchX/Netch/blob/135ff642bd1df12eb6651e75114461d774d2f1bc/Netch/Servers/Trojan/Models/TrojanConfig.cs#L42

**Comment by chsbuffer** [comment]
PR Welcome!

**Comment by zchazc** [comment]
> PR Welcome!

呃，Trojan-go 虽然自适应 mux，但是 Trojan 不是，还得改下设定页面，这方面得开坑 C# ，IDE 直接 VS 就可以吗？还有哪些插件和文档要查阅，我抽空折腾下。
