### ISSUE TITLE
拨号上网时，无法使用TUN/TAP模式

### ISSUE THREAD

**Issue by jsyzdej** [netchx/netch#500]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**
我已看过readme，并且搜索过相关问题，但是并未找到解决方案。

**错误描述**
当电脑使用拨号上网（PPPOE）时，NETCH 的 TUN/TAP 模式无法使用，其他模式使用正常。
为了确保是拨号上网造成的问题，我尝试将网线直接插在路由器上，其他环境不变的前提下启动TUN/TAP模式，可正常使用。

**复现步骤**
1. 打开 Netch 软件
2. 模式选择"[3] [TUN/TAP] 绕过局域网"
3. 点击启动，并有已启动的字样
4. 打开浏览器，通过ipip.net或者ip.gs获取ip地址，均为国内ip，图片附在错误截图栏目中

**日志**
日志已附上，ip数据经过部分脱敏，并同时用括号标出
[logging.zip](https://github.com/NetchX/Netch/files/5853876/logging.zip)

**错误截图**
![Snipaste_2021-01-22_13-54-49](https://user-images.githubusercontent.com/13121137/105452612-8f6e2e80-5cb9-11eb-885b-48245dd4fcf1.png)

**信息**
- 操作系统：Windows 10 专业版 20H2
- 软件版本：[1.7.2](https://github.com/NetchX/Netch/releases/tag/1.7.2)

**额外信息**

**Comment by ghost** [comment]
暂不处理此问题。除非有开发者用电脑直接拨号上网，等一个 PR
