### ISSUE TITLE
TUN/TAP模式无法代理特殊UDP流量

### ISSUE THREAD

**Issue by HydrogenKing** [netchx/netch#501]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**
yes
**错误描述**
对错误的清晰简洁描述
TUN/TAP模式无法代理特殊UDP流量
**复现步骤**
1. 打开 Netch 软件
2. TUN/TAP模式 net1
3. 无法代理以下流量：
Direct UDP over ports 49152 through 65535
UDP over port 50000 via a TURN server
TCP over port 3478 via a TURN server
TLS over port 443 over TCP via a TURN server

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题
![image](https://user-images.githubusercontent.com/77837849/105487173-a37e5400-5cea-11eb-9b94-8d16330adb1c.png)

**信息**
- 操作系统：Windows 10 专业版 64 位 20H2
- 软件版本：1.72
信息参见https://blackboard.secure.force.com/publickbarticleview?id=kA770000000Cbtt
https://help.blackboard.com/Collaborate/Ultra/Administrator/Networking

**Comment by testermania** [comment]
vmess websocket + CDN（cloudflare）udp被阻止。

我尝试开/关多路复用器和其他电击服务器没有任何变化。

没有CDN, 黄色的udp标志出现

ntt.log
```
Other address is 
Binding test: Fail
Local address: 
Mapped address: 
Nat mapping behavior: Unknown
Nat filtering behavior: Unknown
result: Unknown
```
