### ISSUE TITLE
提示DNS（53）端口已被占用

### ISSUE THREAD

**Issue by ccicnce113424** [netchx/netch#509]
图片：![image](https://user-images.githubusercontent.com/30774232/106449745-425f3900-64bf-11eb-8c37-5282e6742dcd.png)

日志：[logging.zip](https://github.com/NetchX/Netch/files/5903519/logging.zip)

**Comment by xianzheTM** [comment]
同样出现了此问题,可能的原因是是启动模式3时,程序被异常终止.解决方法是在服务中手动关闭Host Network Service(或者只有中文名,叫主机网络服务),然后关闭Internet connection share服务.

**Comment by Seas0** [comment]
也可能是Windows本地DNS缓存DNS Client占用53端口，但这个服务关了问题很大😂
