### ISSUE TITLE
希望后续加入的功能,希望软件越做越好

### ISSUE THREAD

**Issue by xishijt** [netchx/netch#51]
1.针对游戏加速启动之前和启动之后,提供手动ping该节点的功能,测试节点是否正常.(划重点手动,不需要断开连接也可以ping)
2.实时连接速度显示.
3.规则文件可以编辑,删除

**Comment by BingLingGroup** [comment]
[1.2.6-STABLE](https://github.com/NetchX/Netch/releases/tag/1.2.6-STABLE)已经做到了在进程模式下实时显示连接速度

**Comment by miozx** [comment]
1.等人接坑
2.版本 1.2.6 已添加模式一实时显示速度
3.规则文件目录在 Netch\mode 下，可自行打开编辑
  格式(模式一)为：

```
#[空格][规则名称], 0
进程1.exe
进程2.exe
```

**Comment by Comah** [comment]
> [1.2.6-STABLE](https://github.com/NetchX/Netch/releases/tag/1.2.6-STABLE)已经做到了在进程模式下实时显示连接速度
![image](https://user-images.githubusercontent.com/20982819/66540274-d89a7d80-eb5d-11e9-9d67-0b5b40ab4d4d.png)
你好，我的版本是1.33 但是流量统计一直都是0kb 的 不知道是什么原因呢？谢谢

**Comment by miozx** [comment]
@Comah 1.3.3 的 Redirector 暂未加入流量显示和统计，后面会加回来

**Comment by Comah** [comment]
> @Comah 1.3.3 的 Redirector 暂未加入流量显示和统计，后面会加回来

原来如此！谢谢
