### ISSUE TITLE
最新release的1.7.3 被微软判断为病毒文件

### ISSUE THREAD

**Issue by oneshu** [netchx/netch#513]
![屏幕截图 2021-02-07 173327](https://user-images.githubusercontent.com/45453410/107142596-2a7a3000-696b-11eb-8eee-09925aacc01d.jpg)
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. ...

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**

**Comment by ghost** [comment]
@oneshu 日常誤判，2333
