### ISSUE TITLE
跳过验证证书

### ISSUE THREAD

**Issue by l3617** [netchx/netch#520]
用xray核心安装vless+ws+tls，v2rayN和qv2ray可以使用，因为他们可以选择跳过验证证书或者允许不安全证书，Netch就是连不上，还是我不会使用

**Comment by l3617** [comment]
![QQ拼音截图20210222213823](https://user-images.githubusercontent.com/36853760/108716172-bb99fb00-7556-11eb-8b56-99185e8675b6.png)
![QQ拼音截图20210222214400](https://user-images.githubusercontent.com/36853760/108716499-2b0fea80-7557-11eb-9235-2d8dcbf6ef7a.png)
就是这个功能

**Comment by chsbuffer** [comment]
设置-V2ray-TLS AllowInsecure

**Comment by l3617** [comment]
> 设置-V2ray-TLS AllowInsecure

好的，找到了，谢谢

**Comment by RPRX** [comment]
刚刚测试了一下，默认会勾选 `TLS AllowInsecure`，这样设置不安全，且绝大多数节点是有效证书，建议改为默认不勾选。
