### ISSUE TITLE
Why it doesn't work ? [Netch Version 1.7.6]

### ISSUE THREAD

**Issue by shayandavoodii** [netchx/netch#524]
Just Check this image, i pressed the start button but it doesn't transfer any data at all !
i was okey with version 1.7.3

![Screenshot 2021-02-24 175320](https://user-images.githubusercontent.com/52105833/109014664-97aaf680-76c9-11eb-9687-d084d998edd8.jpg)

**Comment by chsbuffer** [comment]
start Netch in command line with `Netch.exe -console`. paste outputs in comment after start proxy your game.

**Comment by shayandavoodii** [comment]
@chsbuffer how can i find Command line ?

**Comment by chsbuffer** [comment]
NAT test won't cost much traffic, open your game and test whether it works.

**Comment by shayandavoodii** [comment]
> NAT test won't cost much traffic, open your game and test whether it works.

in my country, 'Telegram app' is censored and i use Netch for censored stuffs like that (i mean i use Netch like a proxy app).
when I start Netch, and then I go to ' Telegram app ' the traffic counter doesn't change ever!

**Comment by chsbuffer** [comment]
send `Netch\logging\application.log` file

**Comment by shayandavoodii** [comment]
> send `Netch\logging\application.log` file

[application.log](https://github.com/NetchX/Netch/files/6036836/application.log)
Thanks for your help.

**Comment by chsbuffer** [comment]
i can't reproduction the issue.
are you sure you are using the socks5 proxy `127.0.0.1:2801` instead of MTPROTO in telegram?

**Comment by shayandavoodii** [comment]
> i can't reproduction the issue.
> are you sure you are using the socks5 proxy `127.0.0.1:2801` instead of MTPROTO in telegram?

Yes I'm sure about that ! if you need ''record screen to reproduce it step by step'', tell me. then I'll update issue with a record screen.

**Comment by shayandavoodii** [comment]
Issue Solved !
i should set mode on '[TUN/TAP] Bypass LAN'
