### ISSUE TITLE
我开启了代理而IP依旧在中国

### ISSUE THREAD

**Issue by 2773281213** [netchx/netch#525]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**
我在昨天还可以正常使用netch，今天我像往常一样开启了代理[4]绕过局域网和中国大陆，但是IP显示我依旧在中国，而Fackbook，twitter，YouTube等也无法正常访问（在之前我是可以正常访问的）使用流量显示0kb（我已经开启代理很长时间），并不是服务器的问题，换了很多个都不行，而延迟显示不大
**To Reproduce**

1. Open Netch
2. 选择服务器
3. 选择模式[4]绕过局域网和中国大陆
4. 打开网站

**Log**
Attaching any log files in the folder `Netch\logging` is strongly recommended.
[application.log](https://github.com/NetchX/Netch/files/6048723/application.log)
[ShadowsocksR.log](https://github.com/NetchX/Netch/files/6048724/ShadowsocksR.log)
[Trojan.log](https://github.com/NetchX/Netch/files/6048725/Trojan.log)
[Xray.log](https://github.com/NetchX/Netch/files/6048726/Xray.log)

**Screenshots**
![好家伙呀](https://user-images.githubusercontent.com/66734006/109287872-1e450c80-785f-11eb-8234-e10bb1c4c901.PNG)

**Environment (please complete the following information):**
- OS: [e.g. Windows 10 Pro 64-bit 1903]
- Netch Version: [e.g. 1.0.0-STABLE.x64]

**Additional context**

**Comment by chsbuffer** [comment]
请启动模式后前往 系统设置-网络-代理 确认 手动设置代理 被设定为 127.0.0.1:2802 ，如果不是，请排查是否已运行其他代理软件
