### ISSUE TITLE
遊戲代理不完全

### ISSUE THREAD

**Issue by YouHaveGone** [netchx/netch#53]
有些遊戲的外掛檢測並不是  .exe 的應用程序  就我所玩過的兩個 劍靈的是以.des爲後綴的文件。  而黑色沙漠的是以.xem爲後綴的文件  入關不把他們代理的話會造成經常性的掉線。所以希望能夠解決一下非exe文件的代理

**Comment by Handsnow** [comment]
附议

**Comment by BingLingGroup** [comment]
自己改改代码都能解决的问题，几行的功夫。

**Comment by govmoe** [comment]
@YouHaveGone 这Issues可以关了233

**Comment by Handsnow** [comment]
@GoodLazer704  求解怎么解决的

**Comment by YouHaveGone** [comment]
@BingLingGroup 不知道指的改代码指的是直接写在mode文件里(虽然我已经这么做了，还是会经常掉线，换成sstap的全局就不会)，还是要改项目代码。

**Comment by BingLingGroup** [comment]
> @BingLingGroup 不知道指的改代码指的是直接写在mode文件里(虽然我已经这么做了，还是会经常掉线，换成sstap的全局就不会)，还是要改项目代码。

@YouHaveGone 掉线是别的问题，并不是游戏代理后缀名不完全的问题，你可以通过查看logging文件夹下面的redirector.log来了解底层的代理情况，如果代理上了还掉线，估计是线路/服务器或者游戏的问题。

**Comment by YouHaveGone** [comment]
看了下log文件，里面所有的[tcpConnectRequest]都是bypass wrong process。
1. 线路问题应该可以排除。在使用sstap时候挂一下午都很少出现掉线情况，现在用netch就是登录游戏不超10分钟就会断。
2. 游戏问题。之后我又用软件自带的steam mod使用steam，或者设置只代理chrome.exe，log里面还是同样地问题。

不知道是什么原因导致的，还有我只是个小白啊看不懂代码啊，反正这就是我碰到的问题，还是希望能搞好吧毕竟相比tap不用抓规则简单好用多了。

**Comment by BingLingGroup** [comment]
> 看了下log文件，里面所有的[tcpConnectRequest]都是bypass wrong process。
> 
> 1. 线路问题应该可以排除。在使用sstap时候挂一下午都很少出现掉线情况，现在用netch就是登录游戏不超10分钟就会断。
> 2. 游戏问题。之后我又用软件自带的steam mod使用steam，或者设置只代理chrome.exe，log里面还是同样地问题。
> 
> 不知道是什么原因导致的，还有我只是个小白啊看不懂代码啊，反正这就是我碰到的问题，还是希望能搞好吧毕竟相比tap不用抓规则简单好用多了。

@YouHaveGone 你是否尝试过重新下载netch，从新的位置而非覆盖旧版本的方式启动netch。以及你是否尝试过`选项-卸载服务`和`DriverUpdater`。

**Comment by YouHaveGone** [comment]
@BingLingGroup 试了这三个方法，还是不行。这是启动浏览器打开油管产生的日志
[Application] Redirect to: 127.0.0.1:2801
[Application] Process name(s): chrome.exe
[Application] Started[udpCreate][1] pid=11960 local=:: Process: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[udpClosed][1] pid=11960 local=::
[tcpConnectRequest][10] bypass wrong process
[tcpConnectRequest][14] bypass wrong process
[udpCreate][2] pid=11960 local=:: Process: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[udpClosed][2] pid=11960 local=::
[tcpConnectRequest][21] bypass wrong process
[tcpConnectRequest][26] bypass wrong process
[tcpConnectRequest][29] bypass wrong process
[tcpConnectRequest][38] bypass wrong process
[tcpConnectRequest][40] bypass wrong process
[tcpConnectRequest][42] bypass wrong process
[tcpConnectRequest][43] bypass wrong process
[tcpConnectRequest][46] bypass wrong process
[udpCreate][3] pid=0 local=239.255.255.250:1900
[udpCreate][4] pid=11960 local=:: Process: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[udpClosed][4] pid=11960 local=::
[tcpConnectRequest][56] bypass wrong process
[tcpConnectRequest][69] bypass wrong process
[tcpConnectRequest][70] bypass wrong process
[tcpConnectRequest][77] bypass wrong process
[tcpConnectRequest][78] bypass wrong process
[tcpConnectRequest][79] bypass wrong process
[tcpConnectRequest][80] bypass wrong process
[tcpConnectRequest][84] bypass wrong process
[udpCreate][5] pid=7436 local=192.168.123.31:52943 Process: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[udpCreate][7] pid=11432 local=127.0.0.1:2801 Process: D:\netch\bin\ShadowsocksR.exe
[udpCreate][8] pid=11432 local=192.168.123.31:52945 Process: D:\netch\bin\ShadowsocksR.exe
[udpCreate][9] pid=11960 local=:: Process: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[udpClosed][9] pid=11960 local=::
[tcpConnectRequest][89] bypass wrong process
[tcpConnectRequest][93] bypass wrong process
[tcpConnectRequest][97] bypass wrong process
[udpCreate][10] pid=11960 local=:: Process: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[udpClosed][10] pid=11960 local=::
[tcpConnectRequest][101] bypass wrong process
[udpCreate][11] pid=11960 local=:: Process: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[udpClosed][11] pid=11960 local=::

**Comment by BingLingGroup** [comment]
@YouHaveGone 我突然想到一个问题，如果你使用的是进程模式，请注意不要添加和Netch运行文件夹内`bin`文件夹下的同名文件，否则可能会产生代理回环。

**Comment by YouHaveGone** [comment]
@BingLingGroup 沒有呀，看日誌第二行`[Application] Process name(s): chrome.exe`我代理的只有這一個。

**Comment by BingLingGroup** [comment]
@YouHaveGone 代理chrome的话只代理一个是不行的，而且你还会遇到DNS的问题，建议网页代理不要用进程模式。
网页代理可以试一下模式四 Bypass Lan and China。

**Comment by BingLingGroup** [comment]
@YouHaveGone 我个人建议是你用glass wire或者别的能看到进程的网络使用情况的工具将使用网络的执行文件全部代理上，我这里反正没遇到代理不上游戏的问题。

**Comment by NormanBB** [comment]
@BingLingGroup 游戏：Warframe.
使用一个星期后，出现`[tcpConnectRequest][764] bypass wrong process`
`然后无法代理上游戏，原本能联机。但现在失败。

[redirector.log](https://github.com/NetchX/Netch/files/3509639/redirector.log)
log：`[udpCreate][139] pid=12220 local=192.168.1.165:4985 Process: D:\SteamLibrary\steamapps\common\Warframe\Warframe.x64.exe
[udpCreate][140] pid=12220 local=192.168.1.165:4980 Process: D:\SteamLibrary\steamapps\common\Warframe\Warframe.x64.exe
[udpCreate][142] pid=5328 local=192.168.1.165:50808 Process: C:\Users\Administrator\Downloads\Programs\Netch.1.2.1-STABLE.x64\bin\ShadowsocksR.exe
[udpCreate][144] pid=5328 local=192.168.1.165:50810 Process: C:\Users\Administrator\Downloads\Programs\Netch.1.2.1-STABLE.x64\bin\ShadowsocksR.exe
[tcpConnectRequest][717] bypass wrong process
[tcpConnectRequest][718] bypass wrong process
[tcpConnectRequest][729] bypass wrong process
[tcpConnectRequest][742] bypass wrong process
[tcpConnectRequest][753] bypass wrong process
[tcpConnectRequest][764] bypass wrong process
[udpClosed][133] pid=5328 local=192.168.1.165:52286`

**Comment by ghost** [comment]
@NormanBB 1. 重启电脑
2. 使用 Netch 选项内的重启服务按钮（点完重开一下 Netch）
3. 设置 DNS 到 8.8.8.8 这种国外的 DNS 去（Netch 当前不会对 DNS 做特殊处理，电脑是多少就是把 DNS 通过代理转发到多少）

**Comment by NormanBB** [comment]
@ConnectionRefused  
改dns是不是在这里改？
![批注 2019-08-16 210927](https://user-images.githubusercontent.com/18748504/63172228-ca554700-c06f-11e9-834d-a9f153d53165.jpg)
如果是的话，三个方法均无效。
日志：
[redirector.log](https://github.com/NetchX/Netch/files/3509874/redirector.log)

warframe需要udp协议的4985以及4980端口进行联网。而netch并没有代理成功。

**Comment by ghost** [comment]
请尝试 1.2.5-STABLE，现在有详细的日志记录

如果还有问题请新开一个 issue 出来
