### ISSUE TITLE
恢复 Internet选项 代理设置的 “自动检测设置” 设置

### ISSUE THREAD

**Issue by devnakx** [netchx/netch#530]
可否使不启用某个订阅时（在“管理订阅链接”里取消勾选该订阅“状态”）删除这个订阅下的所有代理服务器。虽然可以手动删，但是一个一个删非常麻烦。
以及退出软件时，不要更改系统设置里“自动检测设置”，因为我发现每次我退出软件后，都会把“自动检测设置”给打开，即便我已经多次自己手动关掉。

**Comment by chsbuffer** [comment]
右键订阅项可以删除改组下的服务器
你需要关掉自动检测设置是有什么特别的原因吗？

**Comment by devnakx** [comment]
> 右键订阅项可以删除改组下的服务器
> 你需要关掉自动检测设置是有什么特别的原因吗？

谢谢，原来可以删除呀，没注意。

> 自动检测设置适用于使用ISA等企业内部网络环境下使用特别方便，能够自动检测ISA代理，配合WPAD自动下载配置文件。自动检测设置是IE的默认设置，但当用户环境没有使用代理服务器这类上网方式，勾选自动检测设置会让打开第一个网页变的非常之慢。

主要是我没这个需求，而且勾选这个设置可能会导致负面影响，所以关了比较好。
