### ISSUE TITLE
开机启动出现报错

### ISSUE THREAD

**Issue by devnakx** [netchx/netch#538]
**错误描述**
开机启动出现报错，重新打开软件后正常

**日志**
[2021/3/2 20:32:52][INFO] 版本: NetchX/Netch@1.7.6
[2021/3/2 20:32:52][INFO] 启动单实例
[2021/3/2 20:32:53][INFO] 启动主控制器: SSR [5][Non Web Proxy] Bypass LAN
[2021/3/2 20:32:53][INFO] 主程序 SHA256: f03771aec4f446ede7c2c87d5d6597f8dd6eac5e82a85c768c5ffad4b1ae0a31
[2021/3/2 20:32:55][ERROR] System.Exception: ShadowsocksR 控制器启动失败
   在 Netch.Controllers.Guard.StartInstanceAuto(String argument, ProcessPriorityClass priority)
   在 Netch.Servers.ShadowsocksR.SSRController.Start(Server& s, Mode& mode)
   在 Netch.Controllers.MainController.StartServer(Server server, Mode mode, IServerController& controller)
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Netch.Controllers.MainController.<Start>d__19.MoveNext()

**信息**
- 操作系统：Windows 10 专业版 64 位 20h2
- 软件版本：1.7.6

**Comment by chsbuffer** [comment]
请附上 ShadowsocksR.log

**Comment by devnakx** [comment]
ShadowsocksR.log是空的，当时我开机就给我打开了两个log，application就是这个，ShadowsocksR是空的

**Comment by chsbuffer** [comment]
https://github.com/NetchX/Netch/actions/runs/613631212
试一下 Action 构建

**Comment by devnakx** [comment]
谢谢，没有复现了
