### ISSUE TITLE
日志文件大小高达4GB！

### ISSUE THREAD

**Issue by ymcoming** [netchx/netch#539]
１、没找到有关掉日志的开关。
２、因我使用了一个便携加密盘只有10G，所以日志占用太大空间不可接受。
３、细节：使用的是trojan协议，单个Trojan.log文件的大小就高达4GB。

**Comment by ymcoming** [comment]
补充：
4、使用版本1.7.6
5、单位电脑用，下班后断网，第二天早上才联网。这种情况是否会导致Trojan.log不断增大？

**Comment by chsbuffer** [comment]
你关机啊
