### ISSUE TITLE
1.2.0-PRE-RELEASE 经常出现正在停止~ 无响应

### ISSUE THREAD

**Issue by lib-xdown** [NetchX/Netch#54]
1.2.0-PRE-RELEASE 之前那个版本也会出现, 但是概率小,
1.2.0-PRE-RELEASE 这个版本很不稳定,常常出现正在停止,但是无响应.

**Comment by 4679** [comment]
1.2.1也有这个情况
![Snipaste_2019-08-10_16-17-42](https://user-images.githubusercontent.com/2030404/62819639-6ec81c80-bb8a-11e9-91d3-5adda17b7dcc.png)

**Comment by ConnectionRefused** [comment]
V2Ray 啊，别找我，这个要让增加支持的人（ @tindy2013  ）来

**Comment by tindy2013** [comment]
![image](https://user-images.githubusercontent.com/49061470/62819808-ed25be00-bb8c-11e9-86d4-0efcd11913ae.png)
![image](https://user-images.githubusercontent.com/49061470/62819778-97e9ac80-bb8c-11e9-967e-c7f920eaf11d.png)
实测正常 未出现无法停止问题  环境 Windows 10 Pro 1803

**Comment by 4679** [comment]
Socks5和SS也是一样的
![Snipaste_2019-08-10_16-34-13](https://user-images.githubusercontent.com/2030404/62819787-b64fa800-bb8c-11e9-917b-a7e068a81b01.png)
![Snipaste_2019-08-10_16-38-30](https://user-images.githubusercontent.com/2030404/62819843-789f4f00-bb8d-11e9-9b5b-74d0825b724a.png)

log里面也没什么信息

**Comment by 4679** [comment]
卸载服务删除重装之后貌似好了

**Comment by lib-xdown** [comment]
好像不能覆盖之前的文件,我把之前的文件夹删除,创建新的,暂时没发现问题,可能跟之前的配置文件冲突
