### ISSUE TITLE
点击停止按钮,报错异常

### ISSUE THREAD

**Issue by kurdsvv** [netchx/netch#542]
[2021/3/5 17:43:31][ERROR] System.ArgumentException: 解码的字符串不是有效的 IDN 名称。
参数名: unicode
   在 System.Globalization.IdnMapping.GetAsciiUsingOS(String unicode)
   在 WindowsProxy.ProxyService.StringToMem(String managedString)
   在 WindowsProxy.ProxyService.ToOptions(ProxyStatus status)
   在 WindowsProxy.ProxyService.Set(ProxyStatus status)
   在 Netch.Controllers.HTTPController.<Stop>b__6_0()
   在 System.Threading.Tasks.Task.Execute()

**Comment by weiShaoY** [comment]
您好，请问这个bug多久能够修复呢
