### ISSUE TITLE
彩虹六号无法连接到语音服务器

### ISSUE THREAD

**Issue by remmmmi** [netchx/netch#547]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
彩虹六号可被正常加速，但无法连接到语音服务器导致无法使用语音，症状为TAB面板里队友与自己的麦克风图标
消失，无法接收与发送语音

**复现步骤**
1. 打开 Netch 软件
2. 启动TUN/TAP模式(绕过局域网) 或 创建进程模式
3. 启动UPLAY STEAM 与 R6 (DX与vulkan版本有同样问题)

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。
[application.log](https://github.com/NetchX/Netch/files/6096502/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/6096503/NTT.log)
[ShadowsocksR.log](https://github.com/NetchX/Netch/files/6096504/ShadowsocksR.log)
[tun2socks.log](https://github.com/NetchX/Netch/files/6096505/tun2socks.log)

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[Windows 10 专业版 64 位 20H2 19042.630]
- 软件版本：[Netch 1.8.1]

**额外信息**
裸连或使用SSTap是可以正常使用语音的，另外在较早版本的Netch中也可以使用语音，记得应该是1.2.X版本？后来某个版本后语音就失效了
感谢

**Comment by AmazingDM** [comment]
@remmmmi 试下actions最新构建，然后再到设置里打开dns转发及子进程捕获

**Comment by remmmmi** [comment]
> @remmmmi 试下actions最新构建，然后再到设置里打开dns转发及子进程捕获

不行，还是无法使用语音
~~补充：刚刚尝试了几个旧版本的Redirector，1.0.0可正常加速与语音（就是连接速度较慢），1.0.1版本无法加速（卡连接服务器），1.0.2与1.0.3可加速但无语音~~
对不起判断出现了错误orz，实际上1.0.0版本Redirector也无法加速R6，是裸连状态，因为早上的网络环境好点裸连连接的快让我误以为1.0.0可用orz

**Comment by remmmmi** [comment]
如果有需要，这是正式版1.8.1+1.0.0Redirector下使用创建进程模式可加速并且使用语音的log（TUN/TAP模式依旧不行）
[application.log](https://github.com/NetchX/Netch/files/6096721/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/6096723/NTT.log)
[ShadowsocksR.log](https://github.com/NetchX/Netch/files/6096724/ShadowsocksR.log)

**Comment by BlueSkyXN** [comment]
经过测试，不存在影响语音的情况，请尝试使用好的线路，电脑，路由器，公网等，关闭防火墙
直连：https://img02.sogoucdn.com/app/a/100540022/2021030814595581824626.png
专线：https://img01.sogoucdn.com/app/a/100540022/2021030815002458336620.jpg
规则表：【自建R6.txt】
# R6
UbisoftGameLauncher.exe
UbisoftGameLauncher64.exe
Uninstall.exe
upc.exe
Uplay.exe
UplayCrashReporter.exe
UplayService.exe
UplayWebCore.exe
BEService_x64.exe
RainbowSix.exe
RainbowSix_Vulkan.exe
RainbowSix_BE.exe
Cleaner.exe
FirewallInstall.exe
UplayInstaller.exe
UbisoftConnect.exe
UbisoftGameLauncher.exe
UbisoftGameLauncher64.exe
upc.exe
UplayCrashReporter.exe
UplayService.exe
UplayWebCore.exe
\\steamapps\\
html5app_steam.exe
steamwebhelper.exe
gldriverquery.exe
gldriverquery64.exe
secure_desktop_capture.exe
steamservice.exe
steam_monitor.exe
x64launcher.exe
x86launcher.exe
GameOverlayUI.exe
steam.exe
steamerrorreporter.exe
steamerrorreporter64.exe
streaming_client.exe
WriteMiniDump.exe

**Comment by BlueSkyXN** [comment]
> 经过测试，不存在影响语音的情况，请尝试使用好的线路，电脑，路由器，公网等，关闭防火墙
> 直连：https://img02.sogoucdn.com/app/a/100540022/2021030814595581824626.png
> 专线：https://img01.sogoucdn.com/app/a/100540022/2021030815002458336620.jpg
> 规则表：【自建R6.txt】
> 
> # R6
> UbisoftGameLauncher.exe
> UbisoftGameLauncher64.exe
> Uninstall.exe
> upc.exe
> Uplay.exe
> UplayCrashReporter.exe
> UplayService.exe
> UplayWebCore.exe
> BEService_x64.exe
> RainbowSix.exe
> RainbowSix_Vulkan.exe
> RainbowSix_BE.exe
> Cleaner.exe
> FirewallInstall.exe
> UplayInstaller.exe
> UbisoftConnect.exe
> UbisoftGameLauncher.exe
> UbisoftGameLauncher64.exe
> upc.exe
> UplayCrashReporter.exe
> UplayService.exe
> UplayWebCore.exe
> \steamapps\
> html5app_steam.exe
> steamwebhelper.exe
> gldriverquery.exe
> gldriverquery64.exe
> secure_desktop_capture.exe
> steamservice.exe
> steam_monitor.exe
> x64launcher.exe
> x86launcher.exe
> GameOverlayUI.exe
> steam.exe
> steamerrorreporter.exe
> steamerrorreporter64.exe
> streaming_client.exe
> WriteMiniDump.exe

除了之前的测试，还做了补充测试
使用TUNTAP绕过局域网和大陆模式
开局延迟爆炸，直接200ms，打一把后恢复，语音正常

https://img01.sogoucdn.com/app/a/100540022/2021030815201288733782.png
https://img01.sogoucdn.com/app/a/100540022/2021030815200286809878.png

综上所述，NETCH对语音有负面影响的情况应该没有广泛存在

我使用的版本为NETCH 1.8.1【目前最新版】

如果有人始终不行，请尝试使用旧版，尤其是X86还在的1.4版本
当然，个人认为垃圾节点的可能性也不小，别说什么IPLC，怕是也是垃圾IPLC

另外我进程模式NAT1，TUNTAP时候NAT4，不知道怎么回事
电信公网，但是多级桥接过，光猫拨号，猫本身没有UPNP，中转的华为路由，有UPNP，没有设置端口转发
节点由于相关法律法规，不能公开提供，有需要的自行私聊【自己学会怎么联系人】
以上仅供参考

**Comment by ghost** [comment]
@BlueSkyXN 2333

**Comment by remmmmi** [comment]
使用正式版1.8.1+楼上给的规则，但还是一样的问题emmm
![rules](https://user-images.githubusercontent.com/43727126/110298696-d6c53a00-802f-11eb-80e7-5d8fad3246d2.png)
![netch-1](https://user-images.githubusercontent.com/43727126/110298773-efcdeb00-802f-11eb-98b0-814747d667c5.png)
![netch-2](https://user-images.githubusercontent.com/43727126/110298784-f2304500-802f-11eb-8b9e-b4b230dd2531.png)
![netch-3](https://user-images.githubusercontent.com/43727126/110298792-f52b3580-802f-11eb-9c72-1b766ba73221.png)

这是SSTap的情况：
![SSTap-1](https://user-images.githubusercontent.com/43727126/110298901-0d9b5000-8030-11eb-88fe-e12b8ff27d45.png)
![SSTap-2](https://user-images.githubusercontent.com/43727126/110298908-10964080-8030-11eb-985d-3c28d3d594b7.png)

两个加速器选用的是同一条线路(两个软件里也只添加了这一条线路)
裸连刚刚未测，开头转圈过久我选择死亡orz，有时间再试试
测试环境，路由器，电脑设置等等都没有变化，win自带防火墙早已关闭，测试顺序是netch、sstap、netch(netch测了两次)

等会旧版本及x86版本试试看看。。。

**Comment by AmazingDM** [comment]
试下netch的tuntap？

**Comment by remmmmi** [comment]
netch的tuntap也是一样的情况，1楼里也说了，1楼的log也是tuntap模式的log
刚刚试了也不行
就不贴游戏的图了：
![netch-tun](https://user-images.githubusercontent.com/43727126/110306619-fc0a7600-8038-11eb-9b97-0157034780d4.png)
刚刚的log
[application.log](https://github.com/NetchX/Netch/files/6100541/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/6100542/NTT.log)
[ShadowsocksR.log](https://github.com/NetchX/Netch/files/6100543/ShadowsocksR.log)
[tun2socks.log](https://github.com/NetchX/Netch/files/6100544/tun2socks.log)

关于线路：这家几月前被打过炸了一两天，期间我换了另一家也还不错的，不过同样也是没语音，所以大概率不是线路问题？

1.3.5版本无语音，这也是releases里最早的版本了，话说有没有1.2.7左右的旧版。。。

**Comment by BlueSkyXN** [comment]
根据作者给我提供的育碧关于端口的说明
[官方说明](https://support.ubisoft.com/en-GB/Article/000078839/Troubleshooting-connectivity-issues-in-Rainbow-Six-Siege-PC/)
简要如下
路由和ISP尽量支持UPnP
TCP：13000，13005，13200，14000，14001，14008，14020，14021，14022，14023，14024
UDP：6015
[NAT问题](https://support.ubisoft.com/en-US/Article/000064373)
【自带NAT检测不一定准确】
在连接游戏进入对局后，用TCP和UDP端口检查根据检测端口是否可用

当然我看你SSTAP是可用的，直连听说也行？
那你的本身网络环境和代理的网络环境理论上是过关的

不过育碧的这个一直比较迷就是
同时，不能稳定复现说明并非程序固有缺陷，毕竟网络环境错综复杂
另外作者自己也一直掉语音哈哈哈
原则上：NETCH没代理到语音，如果你直连可以一般没啥问题，NETCH代理到语音，如果SSTAP可以那理论上也可以
不过也有可能是连接不稳定，毕竟国际网络也有丢包，比如说人家代理到国外，你语音没代理到，照样可能掉
同时掉麦重启游戏应该是不能解决的吧，我一般是要重启育碧套件+游戏才行

个人建议：尝试老版本NETCH，从1.4往前试

**Comment by BlueSkyXN** [comment]
另外，我刚刚查了下我的网盘备份，我最早使用过的版本是1.4.3，自带R6规则，那时候就完全没问题
同时你要注意，育碧近几个月把Uplay服务换成U-C了，旧规则应该没覆盖到，所以你一直往前试可能也没用，你用IPsb查一下落地IP吧

**Comment by remmmmi** [comment]
关于什么IE设置，路由端口什么的，百度啊贴吧上也很多提到，都试过没用。。照贴吧说法以为是自己网的问题也没多管，最近清理软件找到以前装的sstap发现没这问题才来报issues(主要还是懒)
裸连昨天试过是OK的，为了排除移不动的影响我把网卡禁掉用手机usb共享流量(电信卡)试了下：
裸连——转圈折磨人，去洗个澡回来终于转完了。。。语音可用
netch——转圈很快，语音不行（

1.3.5测试我是把上面的规则txt直接丢过去的，并且tuntap也试过，不行，估计1.3.5-1.4都一样= =
我最早用netch是1.2.X版本，那时候语音是没问题的，所以至少要试试1.2.X版本

关于ip，好像也看不出啥。。
![ip](https://user-images.githubusercontent.com/43727126/110316511-ccae3600-8045-11eb-8e42-f2b17f73e76d.png)
