### ISSUE TITLE
更新订阅出错

### ISSUE THREAD

**Issue by ymmz** [netchx/netch#549]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. ...

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**
[2021/3/7 20:35:49][INFO] 版本: NetchX/Netch@1.8.1
[2021/3/7 20:35:49][INFO] 启动单实例
[2021/3/7 20:35:50][INFO] 主程序 SHA256: c158b182242e3aa3dc8d9f45e5dad102a4d0d9ee56be781588ca4bd42ee472ef
[2021/3/7 20:36:23][INFO] Github 最新发布版本: 1.8.1
[2021/3/7 20:36:23][INFO] 目前是最新版本
[2021/3/7 20:36:30][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 99. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:30][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 107. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:30][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 117. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:30][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 73. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:30][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 88. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:30][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 82. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 102. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 90. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 90. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 90. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 86. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 83. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 101. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 83. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 79. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 79. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/7 20:36:31][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.port | LineNumber: 0 | BytePositionInLine: 104. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)

**Comment by testermania** [comment]
Netch CI #665

我昨天发布，经理删除了它。 v2ray和ss订阅链接不起作用

#535

**Comment by chsbuffer** [comment]
> Netch CI #665
> 
> 我昨天发布，经理删除了它。 v2ray和ss订阅链接不起作用
> 
> #535

send your shadowsocks subscription content (not link) to https://t.me/ChsBuffer , i will check it.
pleases stop post the log to random issues and open a new one
