### ISSUE TITLE
请回退不支持不规范的订阅格式的更改，这造成了很多不便

### ISSUE THREAD

**Issue by lvzhenbo** [netchx/netch#553]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
我们大部分使用者并不是机场主，更多的是机场用户，无法要求去规范订阅格式。此次更新造成了很多不便，除了无法更新订阅之外，配置还得重新配。请求退回更改！

**额外信息**

**Comment by lvzhenbo** [comment]
前面是表面话，这个是直接说明我的想法。
作者的这波操作实属SB。规范当然很重要，能遵循就遵循。但也得尊重现实，V2是个开放生态，和安卓很像但又不一样，你不可能去要求所有机场去遵循规范，只能推荐。你这样强制更改就导致了很多人无法使用订阅，我看了，好几个issues。而且这个软件功能专一，用的人比V2rayN少，大部分机场并不可能去做专门的适配。

**Comment by AmazingDM** [comment]
https://github.com/Anankke/SSPanel-Uim/pull/1216

**Comment by BlueSkyXN** [comment]
傻逼用户可以用旧版，并没有强制你升级
傻逼机场A面板学不会规范订阅
傻逼用户也学不会订阅转换
傻逼用户也无法理解规范的重要性

另外你也没有付费，你需要定制功能可以捐赠1W·USDT给作者，我相信作者是乐意接受你的建议
另外可以用的软件很多，你可以选择用其他的，也可以用旧版
但请注意：
**作者无论如何都没有义务和责任免费提供相应工具
同时，作者已经是冒着违反中华人民共和国相关法律法规来给你们开发工具，不要不知好歹**

最简单的解决方法：
不用垃圾机场
学会自己转换（包括符合规范的订阅转换，导入V2N整理后导出<-我一般选这个）
不用垃圾NETCH，爱用啥用啥
用旧版本，又没不让你用


我是NETCH卫兵，了解一下啊XD

最后赠言一句：既然没有本事改变环境，那就应该老实去适应环境

**Comment by lvzhenbo** [comment]
你说的确实很有道理。但那也只是你这方面的看法，我也只是从我这方面表达我的看法。我呢是从只知道一键订阅，并不知道怎么去改格式，用的是你所谓的几块钱一个月的垃圾机场，更新也不会去看更新日志的方面去考虑，是从跟着教程一键搭建机场的机场主的方面去考虑。
这么大的一个更改，你觉得很好，有规范，一下子就更新上去了，然后呢，新更改才发布三天，机场更不更是一回事，甚至有没有看到都不一定，导致了用着垃圾机场更新Netch的人无法更新订阅。软件是个好软件，为什么不缓冲一下呢，给个临时的开关，缓冲个一个月两个月，当大部分机场看到了更新了，你这个软件再进行更改。
而且写完这段话我还想到去年发生的QQ大范围误冻结的事件，这个事件据说是和weishu管理的一个库有关，QQ引入了这个库，而这个库的一次更新导致了QQ的大范围误冻结。
我们两个是从两个方面去看待这个问题，并没有谁对谁错，应该取其中。
嗯~ o(*￣▽￣*)o，谷歌天天喊安卓的规范，但又有多少软件遵循了呢？

**Comment by NinjaUmbra** [comment]
@lvzhenbo 用旧版 或者你自己写

**Comment by crossfw** [comment]
哪有开倒车的？

作为一个真·白嫖机场 机场主，我已向sspanel仓库提交PR来修复不标准订阅的问题

作为用户，我看下了，是 [这个更新](https://github.com/NetchX/Netch/commit/5225a98581f38ee03c1b7e52d7932228c110e351#diff-ebb41c75d838d9b0e75f79c71d6dcffbac3776d6a57f3387d138a646ff11cb73) 造成了无法适配旧的订阅，这里主要还是改了json解析器从 一个第三方的 Newtonsoft.Json 到 原生的 System.Text.Json。

你可以手动把 V2rayNSharing 中的 “v” “port” “aid” 改成int类型就可以强制适配不标准订阅了
