### ISSUE TITLE
点击停止提示异常日志,并无法停止

### ISSUE THREAD

**Issue by ICLXL** [netchx/netch#554]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. 点击一个节点连接
3. 
![image](https://user-images.githubusercontent.com/30027321/110309514-653fb880-803c-11eb-8e38-465a7d51e2cd.png)
点击停止
4.

5.程序卡死,只能从任务管理器停止

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]

**额外信息**

**Comment by ICLXL** [comment]
4.
![image](https://user-images.githubusercontent.com/30027321/110309975-f31ba380-803c-11eb-80c2-d2817b86e9c8.png)

**Comment by ICLXL** [comment]
系统版本:Windows 10 专业版64位19042.804

**Comment by HMBSbige** [comment]
Duplicate of #542

**Comment by AAxjcy** [comment]
这个问题我也遇到了，现在解决了吗
<img width="548" alt="image" src="https://github.com/user-attachments/assets/b71f2bed-5b5c-4c5c-83e8-d35b3ea903b8" />

**Comment by Jie-alt** [comment]
> 这个问题我也遇到了，现在解决了吗 <img alt="image" width="548" src="https://private-user-images.githubusercontent.com/72637727/400637719-b71f2bed-5b5c-4c5c-83e8-d35b3ea903b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA0MDYwMzAsIm5iZiI6MTc1MDQwNTczMCwicGF0aCI6Ii83MjYzNzcyNy80MDA2Mzc3MTktYjcxZjJiZWQtNWI1Yy00YzVjLTgzZTgtZDM1YjNlYTkwM2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIwVDA3NDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ODA1ZjYwN2IzZTNkMTJmYmI4ZTJhMDQ4YjIxYzVlNWNjOWI0MWEwNWFmMTA1NWZhMGVhNGYxMDBlNDg1YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IuBV-OoeBur1KjAhNumSbfaDempDOoMwCSrbMK_Pv24">

same here
