### ISSUE TITLE
现在打开netch就断网

### ISSUE THREAD

**Issue by biuboompa** [netchx/netch#556]
现在打开netch之后 啥也不干 立马就会打不开网页等等 能ping通网页 但是什么都无法访问 钉钉微信QQ包括数据库链接全部挂掉 重置网络重启之后不打开netch就好了

**Comment by chsbuffer** [comment]
打开 Netch 就上不了网呢。
还有这种事呢。
为什么呢。
不知道呢。

请详细描述步骤并附上必要信息如软件版本、系统版本 **等** ，
不要让开发人员占卜

**Comment by myfenix** [comment]
确实如此。我一直用Mode3 TUN/TAP模式（绕过局域网和中国大陆），同时开着Qv2ray和v2rayN为Telegram和Dropbox提供其他vps的代理。现在版本的Netch启动并连接后，Chrome直连墙外墙内都正常，Qv2ray和v2rayN的代理为Telegram提供代理正常，但Dropbox只要开启Netch无论通过哪个代理都无法连接，也无法通过Netch直连。这个情况自从更新Netch最新版之后就开始出现，甚至刚才发现只要开启Netch，局域网所有其他机器都连不上。停止Netch连接后全部立即恢复正常。系统是WIN10 2020H2，这两三个星期唯一的网络环境变化就是Netch的升级，其他软件的版本和设置都没变过。

**Comment by chsbuffer** [comment]
@myfenix 无法复现，希望能补充更多细节，如网络环境是否有 IPv6, 安装了哪些网卡，建议附上 `ipconfig /all` 输出

问题创建者是否也是使用 TAP 模式？

**Comment by myfenix** [comment]
关掉了Qv2ray和v2rayN，只使用Netch测试。Chrome正常，Telegram正常，但Dropbox死活不行，我在Netch内设置的5个VPS之间切换，在切换的瞬间Dropbox都会显示连接成功状态，Netch切换连接完成后Dropbox就立即变灰色。难道是目前版本的Dropbox客户端一检测到TAP网卡就立即罢工？

局域网连接问题：工作需要平时基本上24小时开着Netch。平时也要登录局域网几个服务器，开着Netch时基本上是3秒左右进入远程桌面，也一直没在意，昨天和今天特意测试了关闭Netch后连接局域网，都是在1秒就可以进入远程桌面。但昨天出现过这样的情况：工作用某软件开启一个比较重度的运算任务，在正常连接到4个局域网服务器并正常交换数据一段时间后（中间在用Netch直连Chrome做其他事情），开始频繁报错，从局域网收发数据变得极其困难，这时候用远程桌面RDP已经进不了局域网机器了。关掉Netch后立即恢复正常。因为是第一次出现，反复切换开关Netch很多次进行确认。

很长时间以来工作和生活（我不是游戏用户）中能够顺畅使用网络，主要是靠Netch，尤其是我工作中用到的个别国外小众软件，Netch简直是救星。向开发者表示衷心感谢。后续如果有什么其他发现我会及时反馈。



ipconfig输出：


   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

未知适配器 本地连接:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-D7-20-97-0D
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::7da9:49de:7b46:6ae5%14(首选)
   IPv4 地址 . . . . . . . . . . . . : 10.0.236.10(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2021年3月10日 18:27:07
   租约过期的时间  . . . . . . . . . : 2089年3月28日 21:26:01
   默认网关. . . . . . . . . . . . . : 10.0.236.1
   DHCP 服务器 . . . . . . . . . . . : 10.0.236.1
   DHCPv6 IAID . . . . . . . . . . . : 402718679
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-27-19-44-C4-40-8D-5C-B6-2A-D8
   DNS 服务器  . . . . . . . . . . . : 127.0.0.1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Realtek PCIe GbE Family Controller
   物理地址. . . . . . . . . . . . . : 40-8D-5C-B6-2A-D8
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : 240e:388:902f:500:456d:a45f:449e:fefd(首选)
   临时 IPv6 地址. . . . . . . . . . : 240e:388:902f:500:d088:5bb2:11ea:caac(首选)
   本地链接 IPv6 地址. . . . . . . . : fe80::456d:a45f:449e:fefd%13(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.2(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2021年3月10日 18:12:03
   租约过期的时间  . . . . . . . . . : 2021年3月17日 18:12:02
   默认网关. . . . . . . . . . . . . : fe80::1%13
                                       192.168.1.1
   DHCP 服务器 . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 104893788
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-27-19-44-C4-40-8D-5C-B6-2A-D8
   DNS 服务器  . . . . . . . . . . . : fe80::1%13
                                       192.168.1.1
                                       fe80::1%13
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

**Comment by biuboompa** [comment]
@chsbuffer  一直使用的是Mode3 TUN/TAP模式（绕过局域网和中国大陆） 我的是只要打开软件 不管有没有启动代理直接断网 也是更新以后出现的 明天拍视频补图 反正很奇葩 软件都不可打开 打开不到一分钟必断网

**Comment by myfenix** [comment]
自己的几个VPS全部是用v2ray而不是xray架设，所以刚才回退到v2ray核心的1.73版本Netch测试，竟然是同样的故障，那可能真的是最新版Dropbox客户端的问题？局域网连接故障的情况目前还没有出现。Windows版微信客户端我这里倒是一直正常，没出现过无法连接的情况。

**Comment by Seele0oO** [comment]
可能是DNS问题？之前我遇到过，，手动设置DNS后正常
