### ISSUE TITLE
请使用 [符合规范] (分享链接格式说明(ver 2)) 的订阅 ,强行改了 导致原来好多机场的订阅无法更新 了

### ISSUE THREAD

**Issue by ChewJ404** [netchx/netch#557]
请使用 [符合规范](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)) 的订阅

SSPanel-Uim 2021/3/5 提交
https://github.com/Anankke/SSPanel-Uim/commit/4ccec3c9132c4cba498ce588653aa44302efe55c

_Originally posted by @chsbuffer in https://github.com/NetchX/Netch/issues/540#issuecomment-790709201_

up 能不能 **先兼容下老的呗**,  再说
根据 JSON 标准, JSON规范, JSON RFC 4627 为啥 非要把数字 转成 字符串 ,有点不太理解 JSON can represent four primitive types (strings, numbers, booleans,
and null) and two structured types (objects and arrays).

**Comment by chsbuffer** [comment]
v2rayN 订阅规范就是那么写的都是字符串，
Netch 订阅结构是直接从 v2rayN 拷贝过来的。
v2rayN 订阅规范里加上允许兼容数字的条目 Netch 就去做兼容。

**Comment by ChewJ404** [comment]
@chsbuffer  好吧 那我只能先和机场反馈下 看能不能先改改 ,或者 倒回老版本Netch 用着 ,
主要是 手残点了更新订阅,结果啥都没了, 请问能不能加个历史记录啥的功能吗,可以看到以前订阅过的
