### ISSUE TITLE
希望添加负载均衡的功能

### ISSUE THREAD

**Issue by qiandun** [netchx/netch#559]
节点情况不定，没及时切换，导致慢或404

**Comment by ghost** [comment]
@lifestep 打游戏切换节点可能导致掉线

**Comment by qiandun** [comment]
> 
> 
> @lifestep 打游戏切换节点可能导致掉线

所以有个可选项就比较好了，上网就可以用，玩游戏就关了
hope

**Comment by ghost** [comment]
@lifestep 话说 负载均衡 != 故障转移
