### ISSUE TITLE
代理命运2（destiny2）无法进入游戏。。

### ISSUE THREAD

**Issue by LockVer** [netchx/netch#56]
一直在登入中，然后就提示没有可用的服务器。
用sstap是可以的。

**Comment by ghost** [comment]
- 天命 2 由 @AmazingDM 测试的
- 请提供更多的信息（日志文件）

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/62623831-61c1e800-b954-11e9-9654-3c67f172ce1a.png)

经测试1.2版本可正常使用

**Comment by ExhaustiveMethod** [comment]
同样遇到这个问题，使用sstap可以登陆，只不过Nat类型是严格Nat（这个应该是sstap的BUG？）。用了Netch就一直卡在登陆中了……1.2.1 ，1.2.0stable，1.2.0pre都用了，好像都不行😟

**Comment by bennylii** [comment]
这里发现netch好像在vmess下更有几率出现连接问题，目前的解决是使用ss连接方法并顺便把sstap的规则合并进来，emmmm有待进一步测试OTZ
