### ISSUE TITLE
更新订阅报错

### ISSUE THREAD

**Issue by yudar1024** [netchx/netch#562]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. 添加订阅地址，进行跟新

**日志**
强烈建议附上任何在 `Netch\logging` 文件夹下面的日志。
[2021/3/11 18:35:16][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.v | LineNumber: 0 | BytePositionInLine: 6. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/11 18:35:16][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.v | LineNumber: 0 | BytePositionInLine: 6. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/11 18:35:16][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.v | LineNumber: 0 | BytePositionInLine: 6. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/11 18:35:16][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.v | LineNumber: 0 | BytePositionInLine: 6. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/11 18:35:16][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.v | LineNumber: 0 | BytePositionInLine: 6. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
[2021/3/11 18:35:16][ERROR] System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.v | LineNumber: 0 | BytePositionInLine: 6. ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   在 System.Text.Json.Utf8JsonReader.GetString()
   在 System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   在 System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   在 System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   在 System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   在 System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   在 Netch.Servers.VMess.VMessUtil.ParseUri(String text)
   在 Netch.Utils.ShareLink.ParseUri(String& text)
   在 Netch.Utils.ShareLink.ParseText(String text)
**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
- 操作系统：[例如 Windows 10 专业版 64 位 1903]
- 软件版本：[例如 1.0.0-STABLE 64 位]
1.8.1

**额外信息**

**Comment by ioliu** [comment]
大概是因为订阅链接不符合规范，我已经退回旧版用了
