### ISSUE TITLE
《彩虹六号：围攻》等游戏无语音的原因及解决方案

### ISSUE THREAD

**Issue by R3pl4c3r** [netchx/netch#565]
> 太长不看：使用其他协议的代理服务器 或 使用 `Bypass LAN and Vivox` 模式不代理 Vivox 语音服务。
> `Bypass LAN and Vivox` 可能只对《彩虹六号：围攻》有效，欢迎补充 Vivox 语音服务器域名和 IP 段。

# 原因
部分机场使用 Xray/V2Ray 时，通过 sniffing 探测数据以 禁止 BT 或网络审计，此功能破坏了与 Vivox 语音聊天服务器的连接。

[已知使用 Vivox 语音服务的游戏列表](https://en.wikipedia.org/wiki/Vivox#Integrations)
#### 摘要
- 辐射76
- 守望先锋
- 绝地求生
- EVE Online
- 堡垒之夜
- 彩虹六号：围攻
- 英雄联盟
- 坦克世界
- 战舰世界
- 人间地狱

# 针对《彩虹六号：围攻》 的研究和解决方案

通过在 [virustotal](https://www.virustotal.com/gui/domain/vivox.com/relations) 以及 [AbuseIPDB](https://www.abuseipdb.com/whois/74.201.106.174) 的查询，，并凭借已知的彩虹六号语音服务器域名 rbspsxp.www.vivox.com （来源：[XTLS/Xray-core#250](https://github.com/XTLS/Xray-core/issues/250#issuecomment-778590896)）以及 rbswp.www.vivox.com （来源：[steamcommunity: Voice chat not working?](https://steamcommunity.com/app/359550/discussions/1/2524779067037299243/?l=english)），我们可以推测出彩虹六号的语音服务器域名应该以“rbs”开头，可能意为“rainbow six”，并得到以下域名/IP对：
```
rbsxbxp-mim.vivox.com	    74.201.106.190
rbsxbxp.www.vivox.com	    74.201.106.189
rbsxbxp-ws.vivox.com	    74.201.106.215
rbspsxp.www.vivox.com	    74.201.106.175
rbspsxp-mim.vivox.com	    74.201.106.174
rbspsxp-ws.vivox.com        74.201.106.245
rbswxp.www.vivox.com        74.201.106.173
rbswxp-mim.vivox.com	    74.201.106.172
disp-rbspsp-5-1.vivox.com   70.42.196.186
disp-rbsxbp-5-1.vivox.com   70.42.196.185
```
并且通过 `nslookup` 发现以下域名无解析：
```
proxy.rbsxbp.vivox.com
proxy.rbspsp.vivox.com
proxy.rbswp.vivox.com
rbswp.vivox.com
rbsxbp.vivox.com
rbspsp.vivox.com
rbspsp.www.vivox.com
rbswp.www.vivox.com
rbsxbp.www.vivox.com
```
所以我们可以大致推测出彩虹六号使用的 Vivox 服务器 IP 段为 `74.201.106.0/24`。并且根据 [XTLS/Xray-core#250](https://github.com/XTLS/Xray-core/issues/250#issuecomment-778590896) 中的日志，不难发现语音使用的是 443 端口，亦即 TLS 流量，因此无法避免被服务端 sniffing 到。因此诞生了以下解决方案。

# 方案1 防止 sniffing 探测相关数据
**服务端和客户端都不得使用 sniffing 修改相关数据，需在服务端和客户端都应用更改**

如果为 v2ray-core ，请禁用 sniffing

如果为 Xray-core ，可以为 sniffing 添加 `"domainsExcluded"` 以排除语音服务器，示例如下：
```json
"sniffing": {
    "enabled": true,
    "destOverride": ["http", "tls"],
    "domainsExcluded": [
        "rbsxbxp-mim.vivox.com",
        "rbsxbxp.www.vivox.com",
        "rbsxbxp-ws.vivox.com",
        "rbspsxp.www.vivox.com",
        "rbspsxp-mim.vivox.com",
        "rbspsxp-ws.vivox.com",
        "rbswxp.www.vivox.com",
        "rbswxp-mim.vivox.com",
        "disp-rbspsp-5-1.vivox.com",
        "disp-rbsxbp-5-1.vivox.com",
        "proxy.rbsxbp.vivox.com",
        "proxy.rbspsp.vivox.com",
        "proxy.rbswp.vivox.com",
        "rbswp.vivox.com",
        "rbsxbp.vivox.com",
        "rbspsp.vivox.com",
        "rbspsp.www.vivox.com",
        "rbswp.www.vivox.com",
        "rbsxbp.www.vivox.com",
        "rbsxbxp.vivox.com",
        "rbspsxp.vivox.com",
        "rbswxp.vivox.com"
    ]
}
```

# 方案2
选择 `Bypass LAN and Vivox` 模式，该模式不代理语音服务。

## 效果

```
Host                DL      UL      DL Speed    UL Speed    Chains              Rule    Time        Source              Destination IP  Type
74.201.106.174:443  25.2 KB 7.09 KB 0 B/s       0 B/s       MATCH / US / vless  Match   3 minutes   192.168.0.166:11015 74.201.106.174  Redir(tcp)
```
![R6](https://user-images.githubusercontent.com/30682790/110901729-bb17a780-833f-11eb-9091-90500c3740a6.jpg)

**Comment by BlueSkyXN** [comment]
太长不看：垃圾机场V2系列线路的日经问题，用SS系列可有效解决
”由于部分机场使用 Xray/V2Ray 时，需要禁止 BT 或网络审计，在 inbound 开启了 sniffing，导致语音聊天服务器无法连接“

**Comment by R3pl4c3r** [comment]
> 太长不看：垃圾机场V2系列线路的日经问题，用SS系列可有效解决
> ”由于部分机场使用 Xray/V2Ray 时，需要禁止 BT 或网络审计，在 inbound 开启了 sniffing，导致语音聊天服务器无法连接“

事实上部分SS节点也不能有效解决问题，比如此前liying☁️使用深港CEN中转+香港HKIX落地，无论是SS或者是SSR都不能正常连接彩六语音服务器。这与机场垃圾不垃圾无关，是后端软件问题

**Comment by BlueSkyXN** [comment]
> > 太长不看：垃圾机场V2系列线路的日经问题，用SS系列可有效解决
> > ”由于部分机场使用 Xray/V2Ray 时，需要禁止 BT 或网络审计，在 inbound 开启了 sniffing，导致语音聊天服务器无法连接“
> 
> 事实上部分SS节点也不能有效解决问题，比如此前liying☁️使用深港CEN中转+香港HKIX落地，无论是SS或者是SSR都不能正常连接彩六语音服务器。这与机场垃圾不垃圾无关，是后端软件问题

那看来就是搭建的时候的问题了，每家的设置模板略有不同

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/discussions/364#discussioncomment-472824

**Comment by AmazingDM** [comment]
动动小手加到host也能用
74.201.106.190 rbsxbxp-mim.vivox.com
74.201.106.189 rbsxbxp.www.vivox.com
74.201.106.215 rbsxbxp-ws.vivox.com
74.201.106.175 rbspsxp.www.vivox.com
74.201.106.174 rbspsxp-mim.vivox.com
74.201.106.245 rbspsxp-ws.vivox.com
74.201.106.173 rbswxp.www.vivox.com
74.201.106.172 rbswxp-mim.vivox.com
70.42.196.186 disp-rbspsp-5-1.vivox.com
70.42.196.185 disp-rbsxbp-5-1.vivox.com

**Comment by ghost** [comment]
@AmazingDM 2333

**Comment by R3pl4c3r** [comment]
@AmazingDM 如果是xray的话不行，因为彩六语音是走TLS流量的。如果vmess/vless服务端inbound开启了sniffing，Xray/V2Ray的sniffing会通过SNI进行嗅探，此时再进行destOverride会无法使用语音。

**Comment by AmazingDM** [comment]
@R3pl4c3r host不一定对所有人有效，我玩着可以 。现在游戏已经卸载了╭(╯ε╰)╮

**Comment by swhoro** [comment]
请问下我用的openwrt上的luci-passwall软件
尝试将xray的sniffing按您的domainsExcluded设置，以及直接设置 "enabled": false，都会连不上六语音
设置方式是vless + tcp + XTLS
使用了一个中转，不知道有没有影响
另外问一下关闭sniffing会有什么坏处吗？
不是很理解sniffing用处

**Comment by RPRX** [comment]
@swhoro 很显然这是因为服务端开了 sniffing + destOverride，只改客户端是没用的

**Comment by swhoro** [comment]
> @swhoro 很显然这是因为服务端开了 sniffing + destOverride，只改客户端是没用的

上面说的更改sniffing是在服务端进行的，我自己搭的服务器，现在sniffing相关配置是这样的：
`"sniffing": {
                "enabled": false,
                "destOverride": [
                    "http",
                    "tls"
                ],
                "domainsExcluded": [
                    "rbsxbxp-mim.vivox.com",
                    "rbsxbxp.www.vivox.com",
                    "rbsxbxp-ws.vivox.com",
                    "rbspsxp.www.vivox.com",
                    "rbspsxp-mim.vivox.com",
                    "rbspsxp-ws.vivox.com",
                    "rbswxp.www.vivox.com",
                    "rbswxp-mim.vivox.com",
                    "disp-rbspsp-5-1.vivox.com",
                    "disp-rbsxbp-5-1.vivox.com",
                    "proxy.rbsxbp.vivox.com",
                    "proxy.rbspsp.vivox.com",
                    "proxy.rbswp.vivox.com",
                    "rbswp.vivox.com",
                    "rbsxbp.vivox.com",
                    "rbspsp.vivox.com",
                    "rbspsp.www.vivox.com",
                    "rbswp.www.vivox.com",
                    "rbsxbp.www.vivox.com",
                    "rbsxbxp.vivox.com",
                    "rbspsxp.vivox.com",
                    "rbswxp.vivox.com"
                ]
            }`
客户端是路由器上的luci-passwall，没有找到sniffing相关设置

**Comment by swhoro** [comment]
好像找到问题了，passwal自动生成的配置文件会打开sniffing，不知道有没有办法自动生成关闭sniffing的配置文件
netch用的是正常
但是还是想问一下sniffing作用是什么，以及为什么会影响彩六语音
之前好像看到过解释的issue，但是找不到了

**Comment by RPRX** [comment]
@swhoro https://github.com/XTLS/Xray-core/discussions/364#discussioncomment-474438

**Comment by swhoro** [comment]
> @swhoro [XTLS/Xray-core#364 (reply in thread)](https://github.com/XTLS/Xray-core/discussions/364#discussioncomment-474438)

请问一下彩六出问题是“不是流量的本意（比如特意发向某 IP、假的 TLS 头等）”哪一种情况呢？
大概理解了sniffing的作用，但是还是不懂语音服务器出问题的原因

**Comment by RPRX** [comment]
@swhoro 第一种情况，彩六语音使用的域名并没有被 DNS 解析到彩六语音使用的 IP，见此 issue 开头写的 Details
