### ISSUE TITLE
[功能请求]使用不符合规范的订阅时弹窗提示错误

### ISSUE THREAD

**Issue by MasterOfStar** [netchx/netch#581]
请求的功能:
使用不符合规范的订阅链接时弹出窗口提示"[XXX(自定义的备注)] 订阅链接不符合规范"
目前的方式是直接日志报异常，导致大量issue出现。

另外写点个人看法：
sspanel-uim的pr合并至今才短短几天，v2board的pr还没有通过，直接取消对不符合规范订阅的支持有些过于激进了。如果在设置里提供一个**默认不勾选**的"支持不符合规范的订阅"功能，然后在1~3个月的缓冲期后彻底取消可能更合理。毕竟不是所有机场都会第一时间同步dev分支代码的,更何况常见的不止sspanel一种，把错误的边成正确的总是需要时间的。

**Comment by chsbuffer** [comment]
支持回去了

**Comment by MasterOfStar** [comment]
> 支持回去了

向标准靠拢是好事，但是希望以后能别那么激进😂
留一段缓冲期是最合适的😂
