### ISSUE TITLE
RDR 运行时 代理服务器停止导致所有网络请求挂起

### ISSUE THREAD

**Issue by chsbuffer** [netchx/netch#582]
当此问题出现时，全部网络连接（ICMPing,TCPing,DNS Resolve）被挂起，特点为 Telegram 等软件也会随之挂起 (无响应)，点击 Netch 停止按钮陷入长时间等待直至队列所有连接超时。

**Comment by edwardchenchen** [comment]
最近一次更新直接从1.7.6，升级至1.8.2
进程模式一条规则C:\\Program Files \(x86\)\\duowan\\yy\\
启动后，整台电脑，所有网络请求都会失败
卸载NF服务，TUN /TAP服务
重启依旧
退回1.8.1版本，目前没有问题。
有问题会再来更新

**Comment by AmazingDM** [comment]
> 最近一次更新直接从 1.7.6，升级至 1.8.2
> 进程模式一条规则 C:\Program Files (x86)\duowan\yy\
> 启动后，整台电脑，所有网络请求都会失败
> 卸载 NF 服务，TUN /TAP 服务
> 重启依旧
> 退回 1.8.1 版本，目前没有问题。
> 有问题会再来更新

请贴出rdr日志。 https://github.com/NetchX/Netch/issues/524#issuecomment-785116745
```Netch.exe -console```

**Comment by edwardchenchen** [comment]
1.启动Netch
2.启动进程模式
3.打开LOL
4.LOL无法连接网络
5.关闭进程模式
6.LOL立刻恢复连接
**日志文件：**
[Logs.txt](https://github.com/NetchX/Netch/files/6170737/Logs.txt)
**设置截图**
无任何其他设置改动
![微信截图_20210319222118](https://user-images.githubusercontent.com/6397192/111773300-1deddd80-8902-11eb-8001-6fec7465bdc8.png)
![微信截图_20210319222129](https://user-images.githubusercontent.com/6397192/111773303-1e867400-8902-11eb-810d-eb8a22a50198.png)

![微信截图_20210319222232](https://user-images.githubusercontent.com/6397192/111773190-ef700280-8901-11eb-99b5-2219c85cf463.png)
![微信截图_20210319222320](https://user-images.githubusercontent.com/6397192/111773204-f72fa700-8901-11eb-9b73-a5ad02b97d5d.png)

**Comment by edwardchenchen** [comment]
同上操作。1.8.1
完全不影响LOL
日志：
[logs2.txt](https://github.com/NetchX/Netch/files/6170761/logs2.txt)
设置
![微信截图_20210319222848](https://user-images.githubusercontent.com/6397192/111773802-bedc9880-8902-11eb-8e78-ec0f0457d859.png)
![微信截图_20210319222843](https://user-images.githubusercontent.com/6397192/111773804-c00dc580-8902-11eb-98ee-a8943c3a37de.png)
![微信截图_20210319222928](https://user-images.githubusercontent.com/6397192/111773817-c3a14c80-8902-11eb-9f55-6772cc52e7ef.png)

**Comment by AmazingDM** [comment]
> 同上操作。1.8.1
> 完全不影响 LOL
> 日志：
> [logs2.txt](https://github.com/NetchX/Netch/files/6170761/logs2.txt)
> 设置
> ![微信截图_20210319222848](https://user-images.githubusercontent.com/6397192/111773802-bedc9880-8902-11eb-8e78-ec0f0457d859.png)
> ![微信截图_20210319222843](https://user-images.githubusercontent.com/6397192/111773804-c00dc580-8902-11eb-98ee-a8943c3a37de.png)
> ![微信截图_20210319222928](https://user-images.githubusercontent.com/6397192/111773817-c3a14c80-8902-11eb-9f55-6772cc52e7ef.png)
试下
[Redirector.zip](https://github.com/NetchX/Netch/files/6170882/Redirector.zip)

**Comment by edwardchenchen** [comment]
**日志：**
[Logs_new_Redirector.txt](https://github.com/NetchX/Netch/files/6171064/Logs_new_Redirector.txt)

依旧不行，这次Log里，啥都看不到了

**Comment by edwardchenchen** [comment]
> **日志：**
> [Logs_new_Redirector.txt](https://github.com/NetchX/Netch/files/6171064/Logs_new_Redirector.txt)
> 
> 依旧不行，这次Log里，啥都看不到了

刚在全新的环境下重新测试了，问题依旧，
Win10 20H2，VMWare， OBS录了完整操作，需要的话，我可以上传一下
1.8.2无法连接
[LogsVM_1.8.2.txt.txt](https://github.com/NetchX/Netch/files/6171161/LogsVM_1.8.2.txt.txt)
1.8.1 可连接
[LogsVM_1.8.1.txt](https://github.com/NetchX/Netch/files/6171162/LogsVM_1.8.1.txt)
1.8.2 使用上面的Redirector.zip
[Logs_new_redirector.txt](https://github.com/NetchX/Netch/files/6171163/Logs_new_redirector.txt)

**Comment by edwardchenchen** [comment]
> > **日志：**
> > [Logs_new_Redirector.txt](https://github.com/NetchX/Netch/files/6171064/Logs_new_Redirector.txt)
> > 依旧不行，这次Log里，啥都看不到了
> 
> 刚在全新的环境下重新测试了，问题依旧，
> Win10 20H2，VMWare， OBS录了完整操作，需要的话，我可以上传一下
> 1.8.2无法连接
> [LogsVM_1.8.2.txt.txt](https://github.com/NetchX/Netch/files/6171161/LogsVM_1.8.2.txt.txt)
> 1.8.1 可连接
> [LogsVM_1.8.1.txt](https://github.com/NetchX/Netch/files/6171162/LogsVM_1.8.1.txt)
> 1.8.2 使用上面的Redirector.zip
> [Logs_new_redirector.txt](https://github.com/NetchX/Netch/files/6171163/Logs_new_redirector.txt)

FYI,希望能有帮助
人在国外，上传阿里云OSS香港比较方便
https://cc-hk.oss-cn-hongkong.aliyuncs.com/1.8.2.mp4
490MB 2:43
https://cc-hk.oss-cn-hongkong.aliyuncs.com/1.8.1.mp4
327MB 1:49
https://cc-hk.oss-cn-hongkong.aliyuncs.com/Video.Redirector.mp4
324MB 1:48

**Comment by AmazingDM** [comment]
@edwardchenchen 复现不能XD

**Comment by edwardchenchen** [comment]
> @edwardchenchen 复现不能XD

没事，辛苦了，这种疑难杂症是不好搞，我先用旧版本

**Comment by edwardchenchen** [comment]
补充，我多尝试了几次，
想起来之前1.7.2版本也有这个问题
之前只是偶发，这个用LOL可以稳定触发，用别的软件不能稳定触发
我觉得，有可能是同时发起大量DNS能触发。
用Chrome同时打开10个左右网页也能触发

**Comment by edwardchenchen** [comment]
测试时，
设置Socks后端，但是127.0.0.1没有Socks服务器
设置进程代理，但是系统中没有被代理程序
也就是完全没有流量从进程代理进出

使用以下cmd 命令禁用DNS Cache
`REG add "HKLM\SYSTEM\CurrentControlSet\services\Dnscache" /v Start /t REG_DWORD /d 4 /f`

使用以下Python3 Code，让系统在测试期间一直发起请求，并保持高连接数

测试视频
https://cc-hk.oss-cn-hongkong.aliyuncs.com/ConcurrentTest.mp4

第一部分是 50个concurrent连接
max_workers=50
可以看到在Netch开启的时候，DNS查询响应下降明显
关闭Netch恢复

第二部分是 100个concurrent连接
max_workers=100
可以看到在Netch开启的时候，DNS查询响应绝大部分超时，多次重试才有概率通过，而且返回结果不完整
关闭Netch恢复



```
import requests
import concurrent.futures

def Task(i):
    r = requests.head('https://www.google.com')
    return r

if __name__ == '__main__':

    task_mapping = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=50) as executor:
        for i in range(1, 10000):
            task_mapping[executor.submit(Task, i)] = i

        for future in concurrent.futures.as_completed(task_mapping):
            r = task_mapping[future]
            try:
                r = future.result()
                print(r.status_code)
            except Exception as e:
                pass
```

**Comment by AmazingDM** [comment]
@edwardchenchen 看看cpu和内存变化

**Comment by edwardchenchen** [comment]
> @edwardchenchen 看看cpu和内存变化
我虚拟机分配了4C 8700K，8GB
使用率基本无变化，0%CPU，80-100MB 内存
