### ISSUE TITLE
[RDR 优化代办事宜] 低间隔重复连接使队列其他连接挂起/滞后/超时

### ISSUE THREAD

**Issue by chsbuffer** [netchx/netch#583]
复现方式：
https://github.com/NetchX/Netch/issues/582#issuecomment-802886861 , GTAOL(?), LOL(?)
RDR 日之内有大量低间隔重复连接，少有其他进程连接
ICMPing 无影响(?)

此议题可能于 #582 相似，但是 #582 针对可能的连接全部挂起问题，而不是队列优化

**Comment by AmazingDM** [comment]
try this https://github.com/NetchX/Netch/commit/7c0088cc7fbfcefc5c600d36b2d366691776a7e3
