### ISSUE TITLE
提供ARM64版本

### ISSUE THREAD

**Issue by hathlife** [netchx/netch#590]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**功能描述**
随着Windows ARM设备的增多，未来是否有必要提供一份ARM64的构建版本？
**额外信息**
考虑到所有代理协议均为跨平台实现，维护应该较为简单。

**Comment by ghost** [comment]
是挺简单的，不如你送几台 Windows ARM 设备给我们开发者？

**Comment by ice1000** [comment]
@cutecr 好家伙

**Comment by MasterOfStar** [comment]
短时间内应该没有必要。毕竟WoA64完全可以兼容运行Win32应用。
