### ISSUE TITLE
1.8.3-Beta2版本启动加速之后，停止加速，再启动出现报错弹窗 未处理异常 无法枚举进程模块 和log，加速无法启动

### ISSUE THREAD

**Issue by LuckyTain** [netchx/netch#591]
**Describe the bug**
启动加速之后，停止加速，再启动**有概率**会出现报错弹窗和log，加速无法启动，需要等待较长时间再启动才正常

**To Reproduce**

1. Open Netch
2. 点击启动
3. 点击停止
4. 点击启动（问题出现）

**Log**
![image](https://user-images.githubusercontent.com/8756469/112092519-a1455280-8bd2-11eb-9da9-c9173d44fc51.png)
因为我这会把Netch重启了，没法复现了，只有截图了。。。

**Screenshots**
![image](https://user-images.githubusercontent.com/8756469/112092575-c0dc7b00-8bd2-11eb-935f-f9fd22d1e99c.png)

**Environment (please complete the following information):**
OS: Windows 10 Pro 64-bit 20H2
Netch Version: 1.8.3-Beta2

**Additional context**
有概率出现。。不是每次都会这样。。。。

**Comment by My1dream** [comment]
我也遇到
