### ISSUE TITLE
内存使用问题

### ISSUE THREAD

**Issue by 26z1a** [netchx/netch#592]
netch 1.8.2
win10 pro n 20h2 19042.867

netch连接ss-libev节点 大概18小时后 占用了差不多3.5g的内存 请问合理么

![image](https://user-images.githubusercontent.com/15630912/112097811-f9fbf780-8ba0-11eb-828b-c255058b31b9.png)

**Comment by chsbuffer** [comment]
请展开进程组查看到底是哪个子进程

**Comment by chsbuffer** [comment]
请使用反馈 Bug 模板并按要求附上日志等相关信息
