### ISSUE TITLE
RDR 启用 重定向ICMP 导致除本地回环和覆写地址以外地址的 ICMP 请求都超时

### ISSUE THREAD

**Issue by chsbuffer** [netchx/netch#593]
**错误描述**
RDR 启用 重定向ICMP 导致除本地回环和覆写地址以外地址的 ICMP 请求都超时

**复现步骤**
1. 打开 Netch 软件
2. 启用设置内的 `转发 ICMP`
3. 启动任意进程模式

**日志**
不适用

**信息**
- 操作系统：Windows 10 专业版 64 位 20H2 19042.867
Windows 10 Insider 专业版 64 位 21322+
- 软件版本：1.8.2~1.8.3-Beta*

**额外信息**
Wireshark 显示有来自覆写地址的回应

**Comment by AmazingDM** [comment]
[Redirector.zip](https://github.com/NetchX/Netch/files/6198197/Redirector.zip)
如有遇到相同问题的人请下载此Redirector解压并手动替换Netch\bin文件夹Redirector.bin，在命令行使用`.\Netch.exe -console`启动Netch后收集日志信息然后回复到此issues以帮助解决问题。
注意：这个bug并非所有系统都存在
