### ISSUE TITLE
stuck at mode bypass LAN version beta 6

### ISSUE THREAD

**Issue by malikshi** [netchx/netch#604]
**Environment (please complete the following information):**
- OS: Windows 10 Pro 64-bit 2004
- Netch Version: 1.8.3-Beta6.x64
- NET 4.8 and NET 5.0 installed

**Additional context**
I am keep stuck after starting the tunnel which is while processing tun2socks like the picture below.
![Screenshot_1129](https://user-images.githubusercontent.com/9080737/113123384-bb200e80-923e-11eb-8f65-33856dbbfd1a.jpg)
it needs a handful to close everything related to Netch e.g xray.exe then and uninstall NF service also NF firewall removal if it's work then good to go but if tips don't work need to loop the step by step again.

**Comment by chsbuffer** [comment]
please run Netch by `Netch.exe -console` and post the standard output when stuck.
NF Service is for Process mode (`[1]` on UI, 0 in mode file, invoke Redirector), it has nothing to do with tun2socks.

**Comment by malikshi** [comment]
Thanks, I will reproduce the log/output when errors come up again

**Comment by malikshi** [comment]
After couple days no error again. I did test at my other laptop and it's work fine.
