### ISSUE TITLE
tun2socks.exe is missing from /bin in version 1.8.2

### ISSUE THREAD

**Issue by Heclalava** [netchx/netch#611]
### Describe the bug

It is present in the folder in 1.8.1

### To Reproduce

Start Netch and it informs that it is missing. Unless you first install 1.8.1 then upgrade to 1.8.2, version 1.8.2 won't start without tun2socks.exe

### CAPTCHA

I am human

### Log

```shell
NA
```

### Environment

Windows all

As above

**Comment by ghost** [comment]
Try use [1.8.3-Beta1145141919](https://github.com/NetchX/Netch/releases/tag/1.8.3-Beta1145141919)
