### ISSUE TITLE
最新1.8.3怎么web proxy模式没了??

### ISSUE THREAD

**Issue by ghost** [netchx/netch#615]
### Describe the bug

之前web proxy 有两个, 名字好像是bypass china and lan , 一种web模式一种全局模式;
 1.8.3更新后发现好像只有一个[3]bypass china and lan , 点击启动会显示 启动tun2...   应该是全局模式, 并且启动后显示wrong tun server, 网络也不通

### To Reproduce

 1.8.3更新后发现好像只有一个[3]bypass china and lan , 
点击启动会显示 启动tun2...   应该是全局模式, 
并且启动后显示wrong tun server, 网络也不通

### CAPTCHA

I am human

### Log

```shell
14
[2021/4/9 15:11:14][INFO] 自带 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/9 15:11:14][INFO] 系统 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/9 15:11:15][INFO] WinTUN 适配器：aioCloud {14EA48E9-69FA-409F-8752-22563978E802} WireGuard Tunnel, index: 42
[2021/4/9 15:11:15][INFO] 设置路由规则
[2021/4/9 15:11:15][INFO] 绕行 → 服务器 IP
[2021/4/9 15:11:15][INFO] 绕行 → 全局绕过 IP
[2021/4/9 15:11:15][INFO] 绕行 → 规则 IP
[2021/4/9 15:11:15][INFO] 代理 → 全局
[2021/4/9 15:11:15][INFO] 流量统计进程:(12044)Shadowsocks
```

### Environment

win10 x64

**Comment by alex4me** [comment]
好像是这个[Commit](https://github.com/NetchX/NetchMode/commit/ab8c9fadc15cd38ccf09e7f44ed94ce61b680c92)把一些模式删了，原因不清楚

**Comment by clift190** [comment]
也发现无web proxy模式。
用[1] Global全局模式，发现奇怪现象：可以代理比如github正常；可以进youtube主页，但点击youtube的视频却无法播放，无网络流量，流的问题？

**Comment by ADSWT518** [comment]
+1
奇怪现象：启动代理后，ip地址改变了，但是Google要么打不开，要么出现安全警告（浏览器为edge）

**Comment by MasterOfStar** [comment]
> +1
> 奇怪现象：启动代理后，ip地址改变了，但是Google要么打不开，要么出现安全警告（浏览器为edge）

同 谷歌打不开 但github可以。 升级前使用web proxy模式和tuntap均可以打开

**Comment by KKer711** [comment]
目前感觉1.81较为好用，1.83的网页模式和进程模式都感觉有问题,

**Comment by bixtx** [comment]
> +1
> 奇怪现象：启动代理后，ip地址改变了，但是Google要么打不开，要么出现安全警告（浏览器为edge）

![photo_2021-04-04_19-58-58](https://user-images.githubusercontent.com/81908696/114190066-76525100-997d-11eb-89ea-29c484f3f13f.jpg)

IPv4 DNS 服务器为空白的，默认是你当地的DNS服务器（当然在墙内），肯定出现DNS污染啊！

**Comment by ghost** [comment]
> +1
> 奇怪现象：启动代理后，ip地址改变了，但是Google要么打不开，要么出现安全警告（浏览器为edge）

![screenshots_1](https://user-images.githubusercontent.com/81908696/114190066-76525100-997d-11eb-89ea-29c484f3f13f.jpg)

IPv4 DNS服务器为空白，所以默认由你当地的DNS服务器（当然在墙内）解析，通过墙内的DNS服务器解析Google搜索的域名，肯定出现DNS污染啊！
<hr>
我退回1.8.3-Beta1版本了，虽然这一版也有奇奇怪怪的bug：

![screenshots_2](https://user-images.githubusercontent.com/81908696/114191594-296f7a00-997f-11eb-8824-4b6a293e8957.png)

```
[2021/4/9 21:34:49][INFO] 启动主控制器: VMess [2]Bypass LAN
[2021/4/9 21:34:49][ERROR] System.InvalidOperationException: 序列包含一个以上的匹配元素
   在 System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 Netch.Utils.PortHelper.GetProcessByUsedTcpPort(UInt16 port)
   在 Netch.Controllers.MainController.TryReleaseTcpPort(UInt16 port, String portName)
   在 Netch.Controllers.MainController.StartServer(Server server, Mode mode, IServerController& controller)
   在 Netch.Controllers.MainController.Start(Server server, Mode mode)
```

**Comment by WindsorMacmillan** [comment]
同问，TUN/TAP模式更新后也不再默认支持。

**Comment by aixiu** [comment]
已退回到1.8.1版本，用起来安逸。

**Comment by ice1000** [comment]
我回退了之后遇到奇怪的问题，只有最新版能启动但是也是没有 web proxy 模式

**Comment by bluerthanever** [comment]
我这边也是同样的问题。。。而且好像不开启HTTP服务器模式了。。。
我也退回好了~我之前用的1.8.2还行吧。。。
Edit:
最终退回了1.8.1。。。顺带我都是用的non web proxy模式

**Comment by BraveSail** [comment]
1.8.1还是TAP，TAP性能没TUN好，目前TUN模式没有dns，只能用系统的dns所以有污染

**Comment by liuhongzhe111** [comment]
1.8.3正式版无法打开谷歌，youtube无法播放视频。退回1.8.3-Beta4一切正常。

**Comment by testermania** [comment]
the new version (1.8.3) have a big problems. lot of errors. slow working. lost connection after 10-15 minutes etc. that's why I switched to this. https://github.com/AmazingDM/Netch-ForOwnUse

**Comment by ghost** [comment]
1. 在 1.8.3 中不支持 Web Proxy 模式
2. WinTUN 没有给网卡设定 DNS 地址，所以直接拿来上网会怪怪的
3. STUN 测试也炸了

**Comment by ice1000** [comment]
> 在 1.8.3 中不支持 Web Proxy 模式

以后还会有吗

**Comment by ghost** [comment]
会的
