### ISSUE TITLE
WinTUN 网卡 DNS 未正常设定

### ISSUE THREAD

**Issue by ghost** [netchx/netch#616]
### Describe the bug

![Snipaste_2021-04-09_16-04-31](https://user-images.githubusercontent.com/45543164/114145672-9ec45600-9951-11eb-9b98-b76e311a4f07.png)
![Snipaste_2021-04-09_16-05-36_(2)](https://user-images.githubusercontent.com/45543164/114145678-9ff58300-9951-11eb-9b0b-ce114524702a.png)

如题

### To Reproduce

1.打开Netch
2.启动Bypass LAN

### CAPTCHA

I am human

### Log

```shell
application.log
[2021/4/9 15:59:36][INFO] 版本: NetchX/Netch@1.8.3
[2021/4/9 15:59:36][INFO] 主程序 SHA256: a727e7c99c5c208cf97216ae59c6f640ad0fb73316ce61f7661ee885ef483495
[2021/4/9 15:59:42][INFO] 启动主控制器: VMess [2]Bypass LAN
[2021/4/9 15:59:47][INFO] 出口 网关 地址：192.168.77.177
[2021/4/9 15:59:47][INFO] 出口适配器：Ethernet 2 {E26A6D92-50FF-4F13-9F61-C85FB0CEDB3D} Intel(R) Ethernet Connection (2) I219-V, index: 25
[2021/4/9 15:59:47][INFO] 自带 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/9 15:59:47][INFO] 系统 wintun.dll Hash: 201c54efd6ef7dbfc752d4515461c8b49073d6b332ac68a30f0910f26f487b9b
[2021/4/9 15:59:48][INFO] WinTUN 适配器：aioCloud {14EA48E9-69FA-409F-8752-22563978E802} Wintun Userspace Tunnel, index: 41
[2021/4/9 15:59:48][INFO] 设置路由规则
[2021/4/9 15:59:48][INFO] 绕行 → 服务器 IP
[2021/4/9 15:59:48][INFO] 绕行 → 全局绕过 IP
[2021/4/9 15:59:48][INFO] 绕行 → 规则 IP
[2021/4/9 15:59:48][INFO] 代理 → 全局
[2021/4/9 15:59:51][INFO] 流量统计进程:(10192)xray
[2021/4/9 15:59:53][INFO] Github 最新发布版本: 1.8.3
[2021/4/9 15:59:53][INFO] 目前是最新版本
```

NTT.log
Other address is 188.166.128.84:3479
Binding test: Success
Local address: 10.0.236.10:60677
Mapped address: 40.115.184.43:56671
Nat mapping behavior: AddressAndPortDependent
Nat filtering behavior: EndpointIndependent
result: 2

Xray.log
 (Xray, Penetrates Everything.) Custom (go1.16.2 windows/amd64)
A unified platform for anti-censorship.
2021/04/09 15:59:44 [Info] infra/conf/serial: Reading config: ..\data\last.json
2021/04/09 15:59:44 [Warning] core: Xray 1.4.2 started
2021/04/09 15:59:57 [Warning] [1448361393] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:03 [Warning] [1723348177] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:06 [Warning] [4190126053] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:06 [Warning] [3664079851] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:06 [Warning] [1876259270] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:06 [Warning] [879784797] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:22 [Warning] [3730034505] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:32 [Warning] [2580020481] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:33 [Warning] [4019389082] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:00:34 [Warning] [1581945883] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:01:32 [Warning] [1347615173] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:01:54 [Warning] [3082610418] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:02 [Warning] [2873744856] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:02 [Warning] [3831952129] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:02 [Warning] [1532071705] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:02 [Warning] [2892946306] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:02 [Warning] [2770590640] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:11 [Warning] [420085753] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:13 [Warning] [185250476] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:37 [Warning] [38960856] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:37 [Warning] [147404781] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:37 [Warning] [1261369167] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:37 [Warning] [4236393603] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:37 [Warning] [321446673] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:44 [Warning] [3077766611] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:02:55 [Warning] [37357340] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:03:04 [Warning] [3758046065] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:03:24 [Warning] [2757770556] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:04:04 [Warning] [1014311043] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:04:07 [Warning] [2772408636] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
2021/04/09 16:06:26 [Warning] [3305475276] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > read tcp 192.168.77.165:3192->40.115.184.43:463: wsarecv: An existing connection was forcibly closed by the remote host.
2021/04/09 16:06:26 [Warning] [3109009073] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF

### Environment

WIN10 专业版 64位 20H2

**Comment by ghost** [comment]
[application.log](https://github.com/NetchX/Netch/files/6283959/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/6283960/NTT.log)
[Xray.log](https://github.com/NetchX/Netch/files/6283961/Xray.log)

**Comment by ghost** [comment]
SSR一切正常
![Snipaste_2021-04-09_16-45-12_(2)](https://user-images.githubusercontent.com/45543164/114147191-69b90300-9953-11eb-85b1-da19dd95ebee.png)

[NTT.log](https://github.com/NetchX/Netch/files/6284029/NTT.log)
[ShadowsocksR.log](https://github.com/NetchX/Netch/files/6284030/ShadowsocksR.log)
[application.log](https://github.com/NetchX/Netch/files/6284031/application.log)

日志里的新建文本文档是我不小心建的空文件

**Comment by ghost** [comment]
进程模式也是
[bate.txt](https://github.com/NetchX/Netch/files/6284084/bate.txt)
进程名随便填的
V2
![Snipaste_2021-04-09_16-59-40_（2）](https://user-images.githubusercontent.com/45543164/114149218-a2f27280-9955-11eb-9472-a5498bc2af89.png)
[NTT.log](https://github.com/NetchX/Netch/files/6284095/NTT.log)
[Xray.log](https://github.com/NetchX/Netch/files/6284097/Xray.log)
[application.log](https://github.com/NetchX/Netch/files/6284098/application.log)


SSR
![Snipaste_2021-04-09_17-01-05_(2)](https://user-images.githubusercontent.com/45543164/114149292-b69dd900-9955-11eb-9dfd-5d88d88aa9e4.png)
[NTT.log](https://github.com/NetchX/Netch/files/6284100/NTT.log)
[ShadowsocksR.log](https://github.com/NetchX/Netch/files/6284101/ShadowsocksR.log)
[application.log](https://github.com/NetchX/Netch/files/6284102/application.log)

**Comment by ghost** [comment]
https://github.com/NetchX/Netch/issues/615#issuecomment-816698226

DNS污染

**Comment by bixtx** [comment]
DNS污染

**Comment by ghost** [comment]
不知道是为什么，从1.8.3-Beta2开始Netch改用了新的虚拟网卡，名叫aioCloud。也就是从这一版本开始，IPv4 DNS服务器就是空的了。

**Comment by mboveiri** [comment]
> I don't know why, starting from 1.8.3-Beta2, Netch switched to a new virtual network card called aioCloud. That is, starting from this version, the IPv4 DNS server is empty.

Same here, Also in [TUN/TAP]Bypass LAN mode, the TAP will not start.

**Comment by wespochac** [comment]
Possibly DNS issue. So does it occur for shadowsocks nodes

**Comment by ghost** [comment]
> Possibly DNS issue. So does it occur for shadowsocks nodes

https://github.com/NetchX/Netch/issues/616#issuecomment-816489314

**Comment by ghost** [comment]
在 1.8.3 中没有给 WinTUN 网卡设定 DNS 地址，所以这样，等修

**Comment by chsbuffer** [comment]
a2326389db3dcea1940762763e71f47648ccf226
