### ISSUE TITLE
[Bypass LAN]当系统dns为局域网ip时，dns无法被代理

### ISSUE THREAD

**Issue by ghost** [netchx/netch#617]
### Describe the bug

[Bypass LAN]当系统dns为局域网ip时，dns无法被代理。手动设置系统dns为公共dns，才能正常使用。

### To Reproduce

1. 确保windows控制面板中系统dns为局域网ip。我是dhcp自动获取路由器分配的dns 192.168.x.x
2. 启动[Bypass LAN]
3. `nslookup 域名`，显示响应dns服务器为局域网dns，从响应结果看未被代理
4. `nslookup 域名 公共dns服务器`，显示响应dns服务器为aioCloud，从响应结果看成功被代理

### CAPTCHA

I am human

### Log

```shell
无
```

### Environment

win10最新版

**Comment by marierose147** [comment]
[Bypass LAN]下，系统dns不是局域网ip，nslookup查询，显示响应服务器是aioCloud，但是查询一些域名仍然返回被污染的结果。

比如查询`www.google.com`，返回ip为Facebook的ip。

**Comment by ghost** [comment]
在 1.8.3 中没有给 WinTUN 网卡设定 DNS 地址，所以这样，等修
