### ISSUE TITLE
导入自定义配置文件（VMess / VLess）

### ISSUE THREAD

**Issue by iamtrazy** [netchx/netch#620]
### Describe the feature you want

i think adding the server by netch or using clipboard is pretty limited . i want to add some advanced routing functions to the client json file. i tried modifyg the last.json file but it gets re written every time i start netch. so please implement the feature to manually add client xray config jsons into netch.

**Comment by BK8000L** [comment]
i agree

**Comment by ghost** [comment]
This feature is planned to be added in version 2.0
