### ISSUE TITLE
全局进程模式使用加密DNS后不能上网

### ISSUE THREAD

**Issue by nita0318** [netchx/netch#626]
### 错误描述

全局进程模式使用加密DNS（Cloudflare）后不能上网
使用DoH与DoT都不能正常联网

模式文件：
[@1.txt](https://github.com/NetchX/Netch/files/6350904/%401.txt)

### 复现步骤

1.打开Netch
2.打开设置—Process Mode—勾选“被代理进程DNS劫持”—填入"https://cloudflare-dns.com/dns-query"
3.选中模式“@1”
4.启动

### 验证

- [X] 确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。

### 日志

使用加密DNS（https://cloudflare-dns.com/dns-query）：
[NTT.log](https://github.com/NetchX/Netch/files/6350968/NTT.log)
[Xray.log](https://github.com/NetchX/Netch/files/6350970/Xray.log)
[application.log](https://github.com/NetchX/Netch/files/6350971/application.log)

使用普通DNS（1.1.1.1:53）：
[NTT.log](https://github.com/NetchX/Netch/files/6350991/NTT.log)
[Xray.log](https://github.com/NetchX/Netch/files/6350994/Xray.log)
[application.log](https://github.com/NetchX/Netch/files/6350995/application.log)

### 操作环境

```txt
系统：Win10 LTSC 1809 17763.316
版本：1.8.3
```

### 额外信息

不能联网
![5](https://user-images.githubusercontent.com/49789145/115560413-2497b800-a2e7-11eb-9056-d5eab3ba6785.PNG)

全局进程（规则".*"）如果使用不加密的DNS（1.1.1.1:53）就可以正常上网
只代理少量进程使用加密DNS可以正常上网
代理大量进程（规则"^C:\\"  "^D:\\"）效果和全局进程类似，加密DNS不能上网
可能是对加密DNS的支持还不完善

**Comment by ghost** [comment]
咱也没说支持 DNS over HTTPS

**Comment by ghost** [comment]
`tls://1.1.1.1:853`

**Comment by ghost** [comment]
等等，进程模式啊，都不支持的，别瞎填了
