### ISSUE TITLE
not stopping

### ISSUE THREAD

**Issue by testermania** [netchx/netch#629]
### Describe the bug

1. Open Netch
2. Start
3. Trying to stop it, it doesn't stop. it remains stuck. using end the process from the task manager.

### To Reproduce

https://i.imgur.com/95gQRpz.png

### CAPTCHA

- [X] Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.

### Log

[28.04.2021 16:06:04][INFO] 版本: NetchX/Netch@1.8.3
[28.04.2021 16:06:04][INFO] 主程序 SHA256: 665752c5abc6b973f05fd781cb4aefa3ae70233cfda7c7f26e6199993cba591b
[28.04.2021 16:06:09][INFO] 卸载 NF 驱动
[28.04.2021 16:06:37][INFO] 启动主控制器: VLESS [0]Global
[28.04.2021 16:06:38][INFO] 内置驱动版本: 1.6.0.7
[28.04.2021 16:06:38][INFO] 系统驱动版本: 
[28.04.2021 16:06:38][INFO] 安装 NF 驱动
[28.04.2021 16:06:38][INFO] 驱动安装成功
[28.04.2021 16:06:38][INFO] 流量统计进程:(6744)xray

### Environment

```txt
20H2 19042.867
Netch Build CI #793
```

### Additional information

all mode same

**Comment by chsbuffer** [comment]
This may be because you clicked on the Netch's command line and then it switched to selection mode. This will block Netch's operation.
Refocus to the Netch's command line and press `Enter` or `ESC` to exit the selection mode

**Comment by testermania** [comment]
@chsbuffer I have nothing to do with the command line. i'm just starting it and trying to stop.

https://i.imgur.com/Dkk1NCr.png

I pressed the stop button, but it doesn't work.
https://i.imgur.com/pBft2vR.png

**Comment by chsbuffer** [comment]
does mode 2,3(WinTUN),7(pcap2socks) won't stop too?

**Comment by chsbuffer** [comment]
![image](https://user-images.githubusercontent.com/33744752/116413136-ec095880-a869-11eb-8ba4-3aaf0d6f6d7c.png)
btw GitHub allows you to upload image

**Comment by testermania** [comment]
pcap2sock is not installed so I don't know.

reboot my pc seems no problem for now. mode 3 bypass lan wrong stun server. global mode nat black icon ok!
