### ISSUE TITLE
socks5代理地址域名解析

### ISSUE THREAD

**Issue by ranwen** [netchx/netch#63]
**功能描述**
使用socks5代理 若为域名 则将代理地址域名解析为ip

**额外信息**
当前版本无法使用域名作为地址

**Comment by ghost** [comment]
已经在 [4908d7b](https://github.com/NetchX/Netch/commit/4908d7bf49466117f1f21d3dd43f70012f32ba1f) 中修复这个问题，请等待下一个版本发布
