### ISSUE TITLE
提示安装.NET，可是我已经安装了

### ISSUE THREAD

**Issue by 7Azure** [netchx/netch#631]
### 错误描述

提示安装.NET，可是我已经安装了

### 复现步骤

1、管理员打开
2、报错

### 日志

无

### 操作环境

```txt
Windows 10 专业版 20H2 19042.928
软件v1.8.3
```

### 额外信息

![S_2021-05-01_12](https://user-images.githubusercontent.com/35513144/116776462-20b02680-aa9b-11eb-9226-b3e66b718b15.png)

**Comment by chsbuffer** [comment]
.NET 5 x64
