### ISSUE TITLE
希望Netch在使用Wintun接管流量时能够给虚拟网卡定义一个dns地址

### ISSUE THREAD

**Issue by HXHGTS** [netchx/netch#640]
### 功能描述

如题，希望Netch在使用Wintun接管vmess流量时能够给虚拟网卡定义一个dns地址，否则会导致部分国外游戏无法正常加速，节点连接本身并没有问题，在手动给虚拟网卡添加1.0.0.1作为dns就可以正常加速
![image](https://user-images.githubusercontent.com/38959826/117722492-b83c1480-b213-11eb-9f7b-2f53e3875f9d.png)

**Comment by ghost** [comment]
早已修复，下载最新的 actions 版本吧
