### ISSUE TITLE
怎么就没法设置 不进行自动代理

### ISSUE THREAD

**Issue by haodiao** [netchx/netch#644]
### 功能描述

以前的：[不设置代理] 绕过局域网和中国大陆，的选项怎么就没有了。     
新版本的不需要设置 TUNTAP 和 WebProxy 要怎么设置？

**Comment by NekoCompiler** [comment]
@haodiao ？

**Comment by chsbuffer** [comment]
网页代理 和 仅监听 模式暂时被移除，v2 会回归
