### ISSUE TITLE
真心想问下怎么全局，而不是某个进程

### ISSUE THREAD

**Issue by bbhxwl** [netchx/netch#645]
### 功能描述

想只加速国外，不只是网页的那种。不知道选择哪个。
有个模式叫Global 
连上nat 测试提示wrong stun server 不知道什么意思。但是任何网页都打不开。
但是连接  模式3的 TUN/TAP Bypass LAN and China，也是 NAT提示这个，wrong stun server 
但是缺能正常上网。不知道具体什么意思。还请大佬指点。

**Comment by ghost** [comment]
https://t.me/netch_group/8716
