### ISSUE TITLE
无法加速国服英雄联盟

### ISSUE THREAD

**Issue by lrz2010** [netchx/netch#647]
### 错误描述

使用软件加速英雄联盟后，大厅界面可正常加速，但是开始游戏后会出现无法连接。

### 复现步骤

打开软件

### 日志

[Xray.log](https://github.com/NetchX/Netch/files/6521003/Xray.log)
[application.log](https://github.com/NetchX/Netch/files/6521004/application.log)
[NTT.log](https://github.com/NetchX/Netch/files/6521005/NTT.log)
[ShadowsocksR.log](https://github.com/NetchX/Netch/files/6521006/ShadowsocksR.log)

### 操作环境

```txt
WIN10
```

**Comment by lrz2010** [comment]
测试外服正常加速，只有国服是这样

**Comment by ghost** [comment]
你可能没有在 WeGame 中关闭网络加速功能

**Comment by lrz2010** [comment]
> 你可能没有在 WeGame 中关闭网络加速功能

我关闭了
