### ISSUE TITLE
Proxycap代理无法进入英雄联盟台服

### ISSUE THREAD

**Issue by jcb0709** [netchx/netch#648]
### 错误描述

我是用Proxifier PE+Proxycap代理电脑 Proxycap我只用来代理台服 听说台服锁IP 请问有什么办法可以突破限制 我有腾讯加速器  VIP，但我希望平时能不用网游加速器来玩台服，还有就是经过我的多次尝试Proxycap会跟安装版的proxifier产生冲突，但不会跟PE产生冲突，所以这点可以排除掉

### 复现步骤

![QQ截图20210522181833](https://user-images.githubusercontent.com/84621723/119224053-42974900-bb2f-11eb-9a4d-972cb72fb44e.png)

### 日志

![QQ截图20210522181853](https://user-images.githubusercontent.com/84621723/119224059-475bfd00-bb2f-11eb-97c5-c1df25d817e3.png)

### 操作环境

```txt
win10
```

**Comment by ghost** [comment]
ProxyCap 管我们什么事
