### ISSUE TITLE
HiDPI 支持

### ISSUE THREAD

**Issue by AvailCat** [netchx/netch#65]
**功能描述**
支持HiDPI以避免界面模糊

**额外信息**
实现方式：https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

**Comment by ghost** [comment]
请尝试 1.2.9 新版本

**Comment by AvailCat** [comment]
@ConnectionRefused 你没打包 `Netch.exe.config`，所以 Release 里面下载到的版本解压出来是没有 HiDPI 支持的

**Comment by ghost** [comment]
@Meeeeow 放截图看看，说明自己是多少的 DPI

**Comment by AvailCat** [comment]
@ConnectionRefused 

**缺失 `Netch.exe.config`:**
![screenshot](https://user-images.githubusercontent.com/19658647/65027048-417e4380-d96c-11e9-83bb-aca46f3eb296.png)

**有 `Netch.exe.config`:**
![screenshot-2](https://user-images.githubusercontent.com/19658647/65027046-40e5ad00-d96c-11e9-9a6e-39239e916291.png)

开了 125% 缩放
