### ISSUE TITLE
VLess 传输协议缺少 gRPC 选项

### ISSUE THREAD

**Issue by wc7086** [netchx/netch#652]
### 功能描述

希望添加对gRPC协议的支持。

**Comment by testermania** [comment]
grpc support doesn't  work. v2rayng v2rayn working good with same server.

`Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 windows/amd64)
A unified platform for anti-censorship.
2021/06/30 11:28:07 [Info] infra/conf/serial: Reading config: ..\data\last.json
2021/06/30 11:28:07 [Warning] core: Xray 1.4.2 started
2021/06/30 11:28:17 [Warning] [2930530796] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:17 [Warning] [1409600338] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:17 [Warning] [4149458431] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [954579742] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [1252409957] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [3263566941] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [1830318961] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [1670146538] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:18 [Warning] [303596412] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [2068844434] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [3110458756] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [1115112384] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:19 [Warning] [2674411162] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed
2021/06/30 11:28:20 [Warning] [2380843839] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded" transport/internet/grpc: failed to dial gRPC > transport/internet/grpc: Cannot dial gRPC > rpc error: code = Canceled desc = context canceled] > common/retry: all retry attempts failed`
