### ISSUE TITLE
打开时闪退

### ISSUE THREAD

**Issue by skiinder** [netchx/netch#653]
### 错误描述

错误如题:
Netch版本: 1.8.5
Windows版本: 20H2
没有任何错误提示

### 复现步骤

1. 打开Netch
2. 闪退

### 日志

并没有产生相关日志

### 操作环境

```txt
操作系统：[Windows 10 x64 Professional Workstation 20H2 19042.928]
软件版本：[1.8.5]
```

**Comment by chsbuffer** [comment]
请安装 .NET 5 x64 运行时
