### ISSUE TITLE
关于xray-core下VLESS协议中XTLS和WS的证书问题

### ISSUE THREAD

**Issue by wc7086** [netchx/netch#654]
### Describe the bug

VLESS+XTLS
VLESS+WS+TLS
使用这两种组合时必须开启 `TLS AllowInsecure` ，否则无法链接服务器
证书为使用 `acme.sh` 申请的由 `let's encrypt` 颁发的域名证书

### To Reproduce

1. 服务端使用以下配置
2. Netch 客户端设置中不勾选 `TLS AllowInsecure`
<details><summary>Xray-server.conf</summary>

```json
{
    "log": {
        "loglevel": "none"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "${uuid}",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/${path}ws",
                        "dest": "@/dev/shm/xray/ws.sock"
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx_unixsocket/h2.sock"
                    },
                    {
                        "dest": "/dev/shm/nginx_unixsocket/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
                    "certificates": [
                        {
                            "certificateFile": "/certs/${domain}/fullchain.cer",
                            "keyFile": "/certs/${domain}/${domain}.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        },
        {
            "listen": "/dev/shm/xray_unixsocket/grpc.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "${uuid}"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "${path}grpc"
                }
            }
        },
        {
            "listen": "@/dev/shm/xray/ws.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "${uuid}"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/${path}ws"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```
</details>

<details><summary>nginx.conf</summary>

```nginx
server {
    listen 80 reuseport default_server;
    listen [::]:80 reuseport default_server;
    
    location / {
        return 301 https://${domain};
    }
}
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    location / {
        return 301 https://\$host\$request_uri;
    }
}
server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock default_server;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2 default_server;

    location / {
        return 301 https://${domain};
    }
}
server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2;
    server_name ${domain};

    root /usr/local/nginx/html;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;

    location /${path}grpc {
        grpc_pass grpc://unix:/dev/shm/xray_unixsocket/grpc.sock;
    }
}
```
</details>

### CAPTCHA

- [x] Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.

### Log

<details><summary>application.log</summary>

```
[2021/6/5 9:15:02][INFO] 启动主控制器: VLESS [0]Grand Theft Auto V
[2021/6/5 9:15:02][INFO] 内置驱动版本: 1.6.0.7
[2021/6/5 9:15:02][INFO] 系统驱动版本: 1.6.0.7
[2021/6/5 9:15:02][INFO] 流量统计进程:(12848)xray
```
</details>

<details><summary>NTT.log</summary>

```log
Other address is 
Binding test: Fail
Local address: 
Mapped address: 
Nat mapping behavior: Unknown
Nat filtering behavior: Unknown
result: Unknown
```
</details>

<details><summary>Xray.log</summary>

```log
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 windows/amd64)
A unified platform for anti-censorship.
2021/06/05 09:15:02 [Info] infra/conf/serial: Reading config: ..\data\last.json
2021/06/05 09:15:02 [Warning] core: Xray 1.4.2 started
```
</details>

### Environment

```txt
- OS: Windows 10 x64 专业版 21H1 19043.1023
- Netch version 1.8.5
```

### Additional information

原因：配置文件中的 `address` 被解析成IP了

**Comment by wc7086** [comment]
今天早上忘了去看一下 `Netch` 用来启动 `Xray` 的配置文件，现在看了一下，发现本应该是域名的地方被解析成IP了，不知道为什么要这样做。

**Comment by chsbuffer** [comment]
关闭 Netch-通用-解析服务器主机名
此设计是为了防止使用虚拟网卡模式时无法解析代理服务器 IP

**Comment by wc7086** [comment]
> 关闭 Netch-通用-解析服务器主机名
> 此设计是为了防止使用虚拟网卡模式时无法解析代理服务器 IP

现在默认关闭 `TLS AllowInsecure` ，实际上为了安全也该默认关闭 `TLS AllowInsecure`。所以我认为 `解析服务器主机名` 也应该默认关闭，并把这类问题加入常见问题集中进行解释也许是更好的办法？

**Comment by NinjaUmbra** [comment]
> > 关闭 Netch-通用-解析服务器主机名
> > 此设计是为了防止使用虚拟网卡模式时无法解析代理服务器 IP
> 
> 现在默认关闭 `TLS AllowInsecure` ，实际上为了安全也该默认关闭 `TLS AllowInsecure`。所以我认为 `解析服务器主机名` 也应该默认关闭，并把这类问题加入常见问题集中进行解释也许是更好的办法？

没毛病

**Comment by chsbuffer** [comment]
> 现在默认关闭 `TLS AllowInsecure` ，实际上为了安全也该默认关闭 `TLS AllowInsecure`。所以我认为 `解析服务器主机名` 也应该默认关闭，并把这类问题加入常见问题集中进行解释也许是更好的办法？

`TLS Allow Insecure` 与 `解析服务器主机名` 毫无关系，不明白为什么由此提出应该默认关闭后者。
使用技巧 文档内说明了何时该启用 `解析服务器主机名` ，该说明是在默认禁用时编写的。

有空补充下

**Comment by wc7086** [comment]
> > 现在默认关闭 `TLS AllowInsecure` ，实际上为了安全也该默认关闭 `TLS AllowInsecure`。所以我认为 `解析服务器主机名` 也应该默认关闭，并把这类问题加入常见问题集中进行解释也许是更好的办法？
> 
> `TLS Allow Insecure` 与 `解析服务器主机名` 毫无关系，不明白为什么由此提出应该默认关闭后者。
> 使用技巧 文档内说明了何时该启用 `解析服务器主机名` ，该说明是在默认禁用时编写的。
> 
> 有空补充下

因为大部分人都是签署域名证书，目前 `acme.sh` 并不支持签署IP证书，当本应该是域名的 `address` 被解析为IP之后就会因为证书对不上导致无法使用TLS协议成功连接服务器。开启 `TLS Allow Insecure ` 又有一定的安全风险，所以我认为默认关闭 `解析服务器主机名` 是更好的办法，或者把下面这两部分代码中的 `AutoResolveHostname()` 改为 `Hostname`，因为 `Xray-core` 在这两种协议下会正常解析域名。

https://github.com/netchx/netch/blob/8a48e321b5cd2ea103db6365f27235c07bcbef3b/Netch/Servers/V2ray/Utils/V2rayConfigUtils.cs#L144-L151

https://github.com/netchx/netch/blob/8a48e321b5cd2ea103db6365f27235c07bcbef3b/Netch/Servers/V2ray/Utils/V2rayConfigUtils.cs#L185-L192

**Comment by chsbuffer** [comment]
https://www.v2fly.org/config/transport.html#tlsobject
> serverName
> 指定服务器端证书的域名，在连接由 IP 建立时有用。当目标连接由域名指定时，比如在 Socks 入站时接收到了域名，或者由 Sniffing 功能探测出了域名，这个域名会自动用于 serverName，无须手动配置。

在一切之前，我不使用 v2ray。
文档中提到可用 `serverName` 配置服务端证书域名，如果这是你需要的，请修改合并请求分支。

**Comment by wc7086** [comment]
> https://www.v2fly.org/config/transport.html#tlsobject
> 
> > serverName
> > 指定服务器端证书的域名，在连接由 IP 建立时有用。当目标连接由域名指定时，比如在 Socks 入站时接收到了域名，或者由 Sniffing 功能探测出了域名，这个域名会自动用于 serverName，无须手动配置。
> 
> 在一切之前，我不使用 v2ray。
> 文档中提到可用 `serverName` 配置服务端证书域名，如果这是你需要的，请修改合并请求分支。

看了一下，写这部分的人已经把 `serverName` 加上了。因为之前只看过 https://xtls.github.io 的文档，而文档中对 `serverName` 的表述有比较模糊，所以我一直没有加上 `serverName` 的习惯，对于此issue我已经没有其他问题了。

https://github.com/netchx/netch/blob/8a48e321b5cd2ea103db6365f27235c07bcbef3b/Netch/Servers/V2ray/Utils/V2rayConfigUtils.cs#L242-L246
