### ISSUE TITLE
关于强制关闭软件后引发的bug

### ISSUE THREAD

**Issue by Maolaohei** [netchx/netch#655]
### 错误描述

打开程序后闪一下命令行之后弹出log记录的文件，但是主程序没有打开

### 复现步骤

1.打开netchx.exe软件
2.加速游戏
3.软件卡住了，点击UI没有反应
4.通过任务管理器强制关闭软件
5.强制关闭软件后打不开软件了
6.重启设备，还是这样，打开就弹出日志
7.尝试用最新版的文件覆盖，问题依旧

### 日志

[Xray.log](https://github.com/netchx/netch/files/6601928/Xray.log)
[application.log](https://github.com/netchx/netch/files/6601926/application.log)
[NTT.log](https://github.com/netchx/netch/files/6601927/NTT.log)

### 操作环境

```txt
版本	Windows 10 专业工作站版
版本号	Dev
安装日期	‎2021/‎5/‎27
操作系统版本	21390.1
序列号	PF246PGN
体验	Windows 10 Feature Experience Pack 321.13302.10.3
```

### 额外信息

![image](https://user-images.githubusercontent.com/24179463/120878181-47f39980-c5ed-11eb-9e28-aa911d1bef6e.png)

**Comment by chsbuffer** [comment]
请通过 资源监视器-CPU-关联的句柄搜索 D:\Netch\data\settings.json 确认占用配置文件的进程。如果是 Netch，请依据 pid 结束进程

**Comment by Maolaohei** [comment]
settings.json 文件通过关联的句柄搜索没有发现其他程序占用，
我特意试验了一下，发现data/settings.json 变成了0kb大小。
我就把有问题的settings.json文件删除，此时没有提示被其他文件占用可以正常删除
让程序自己生成一个，问题解决.
