### ISSUE TITLE
Netch 1.8.3+ 无法启动，提示需要安装 .NET

### ISSUE THREAD

**Issue by 2773281213** [netchx/netch#656]

**Comment by chsbuffer** [comment]
Netch 自 1.8.3 起需要 **.NET 5 Desktop x64 Runtime (.NET 5 运行桌面应用 64位 运行时)**，需自行安装

https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.8-windows-x64-installer

**Comment by ghost** [comment]
https://t.me/netch_channel/11
