### ISSUE TITLE
1.8.5无法启动

### ISSUE THREAD

**Issue by lookaheadp** [netchx/netch#659]
### 错误描述

在双击程序文件，在用户账户控制中允许启动后，程序并没有启动。右键使用管理员启动也无效。改为兼容模式任然无效。

### 复现步骤

1. 双击程序/右键以管理员权限启动
2. 用户账户控制弹出
3. 允许更改
4. 无反应，程序未启动

### 日志

无

### 操作环境

```txt
版本	Windows 10 专业工作站版
版本号	21H1
安装日期	‎2021/‎2/‎20
操作系统内部版本	19043.1023
体验	Windows Feature Experience Pack 120.2212.2020.0
```

**Comment by liuhongzhe111** [comment]
https://dotnet.microsoft.com/download/dotnet/5.0/runtime/?utm_source=getdotnetcore&utm_medium=referral 下载安装后见证奇迹。

**Comment by subtank** [comment]
@liuhongzhe111 装了也没用呢？

**Comment by liuhongzhe111** [comment]
> @liuhongzhe111 装了也没用呢？

不能啊，安装时候就应该可以启动了。再不行就只能问作者了。
