### ISSUE TITLE
windows升级到最新的21H1，打开软件会闪退

### ISSUE THREAD

**Issue by bignof** [netchx/netch#663]
### 错误描述

  打开后闪退

### 复现步骤

 打开后闪退

### 日志

无

### 操作环境

```txt
操作系统：windows 21H1
软件： 1.8.5
```

**Comment by Lightmani** [comment]
21H1复现了此问题，打开即闪退

**Comment by SakuraFallingMad** [comment]
@Lightmani 21H1用户，不闪退，请先将各种运行库 依赖装了再试

**Comment by ghost** [comment]
https://t.me/netch_channel/11

**Comment by Lightmani** [comment]
> @Lightmani 21H1用户，不闪退，请先将各种运行库 依赖装了再试

谢谢，已解决
