### ISSUE TITLE
Netch 2.0

### ISSUE THREAD

**Issue by netch-org** [netchx/netch#665]
## Protocols
- [x] `Socks5`
- [x] `Shadowsocks`
- [x] `ShadowsocksR`
- [ ] `WireGuard`
- [ ] `Trojan`
- [ ] `VMess`
- [ ] `VLess`

## Modes
- [x] `ProcessMode`
- [ ] `ShareMode`
- [x] `TunMode`
- [ ] `WebMode`

## Others
- [ ] Window state position save
- [ ] Support for multiple modes while starting ? [Rejected]
- [x] Full open source [There are still some parts that are still in progress]

## UI/UX
- [ ] WinUI 3

**Comment by Whibelf2** [comment]
Improvments and Features:


* Window State Position Save of Client "Netch.exe"

* Put back Fake DNS Feature

* Put back TUN/TAP Feature (Wintun issue: It dont allow bind Packets direct to interface)

* Forward WebRTC Connections "Fake WebRTC"

* IP leak protection removing default gateway

* DNS leak protection put 0.0.0.0 in physical network card

**Comment by netch-org** [comment]
> Improvments and Features:
> 
> * Window State Position Save of Client "Netch.exe"
> * Put back Fake DNS Feature
> * Put back TUN/TAP Feature (Wintun issue: It dont allow bind Packets direct to interface)
> * Forward WebRTC Connections "Fake WebRTC"
> * IP leak protection removing default gateway
> * DNS leak protection put 0.0.0.0 in physical network card

* planned
* this feature cannot be added for the first time, it can be considered in the future
* we will support both TAP-Windows and WinTUN driver
* idk what is this
* maybe ?
* maybe ?

the first version may not be so perfect

**Comment by Whibelf2** [comment]
> * idk what is this


Little more about feature "Fake WebRTC"

I know a tool with this feature its called "AntiRTC" if your need more info about this Tool ping me plz.

Some Socks5 does not support forwarding over UDP, it might be possible to create a mode that reports a "WebRTC Fake" to match with Reported IP see picture:

![Fake WebRTC Feature Explained](https://user-images.githubusercontent.com/36669087/122106896-df789980-cdf0-11eb-88ed-d75f092fbf8f.jpg)

**Comment by Whibelf2** [comment]
* Support Socks5 Authentication in TUN/TAP Mode
The most proxies current require Authentication user:pass

* Support Anothers Protocols:
SOCKS4, SOCKS4a, HTTP Proxy, HTTPS Proxy, SSL Proxy, SSH2.

**Comment by mxyd233** [comment]
maybe enable the SelfContained argument for publishing? it may can reduce someone asking the .net runtime required prompts times.

**Comment by netch-org** [comment]
> * Support Socks5 Authentication in TUN/TAP Mode
>   The most proxies current require Authentication user:pass
> * Support Anothers Protocols:
>   SOCKS4, SOCKS4a, HTTP Proxy, HTTPS Proxy, SSL Proxy, SSH2.

- Socks5 with Authentication supported
- These may not be considered

**Comment by laaArmy** [comment]
进程模式增加 链接请求记录的日志
我不会编程不知道难不难，我只是觉得这个功能容易排错/解决路由器翻墙列表不完整导致的问题（比如Play商店解析到cn导致无法访问的问题）

还有软件启动了才能激活Socks5端口，我觉得为什么不让它软件启动就激活


如果上述功能实现难度大的话，当我没说

**Comment by netch-org** [comment]
> 进程模式增加 链接请求记录的日志
> 我不会编程不知道难不难，我只是觉得这个功能容易排错/解决路由器翻墙列表不完整导致的问题（比如Play商店解析到cn导致无法访问的问题）
> 
> 还有软件启动了才能激活Socks5端口，我觉得为什么不让它软件启动就激活
> 
> 如果上述功能实现难度大的话，当我没说

现有的版本应该就可以查看日志的

给 Netch 加上 `-console` 参数

**Comment by Ahmedeisa25** [comment]
Can you add share config future that allows sharing encrypted configaration file to other user cotains trojan and v2ray sittings with encrypted sni

**Comment by A-little-bit-of-data** [comment]
希望恢复web端功能，能增加白名单黑名单功能么### web

**Comment by initialjie** [comment]
希望恢复http代理支持

**Comment by vickunwu** [comment]
- Add user modifible domain blacklist/whitelist in Bypass LAN and China MODE

**Comment by minGGeMG** [comment]
增加 split-tunneling 作为流量分流的方法

**Comment by xvx233** [comment]
Support Wireguard 
❛˓◞˂̵✧

**Comment by SafaSafari** [comment]
process mode bypass
bypass proxy from a process

**Comment by congzhangzh** [comment]
可不可以跨平台一下？

**Comment by tianzy12138** [comment]
加油

**Comment by gongyoyo** [comment]
My advice Features:

1. User can change the Main/Tray icon
2. New Microsoft Fluent Design UI

**Comment by Zedd233** [comment]
程序启动后，任务栏图标消失，无法再次唤醒。但是在后台任务进程中又正常运行。

**Comment by kawaiidora** [comment]
1. start with os
2. run previous config when netch started

**Comment by chsbuffer** [comment]
@kawaiidora Netch Settings-Others
1. Run at startup
2. Start when opened

**Comment by kawaiidora** [comment]
> @kawaiidora Netch Settings-Others
> 
> 1. Run at startup
> 2. Start when opened

@chsbuffer  Sorry, I am using 1.8.5, don't see settings-others

![image](https://user-images.githubusercontent.com/41125342/125400126-1936c300-e3e4-11eb-99b4-c07268164537.png)

**Comment by kawaiidora** [comment]
> 1. start with os
> 2. run previous config when netch started

Oh shoot, these features are already implemented that i didn't notice. I'm sorry

**Comment by kawaiidora** [comment]
Modern and beautiful windows UI like powertoys or windows terminal

**Comment by SafaSafari** [comment]
cross platform :)))

**Comment by wssy001** [comment]
支持IPV6
理由1：有些商家提供的IPV4地址，绕路严重，但是IPV6地址却很舒服，再者国内IPV6普及程度很不错，直接给公网IP
理由2：不少机场现在只给IPV6地址

**Comment by qq583372062** [comment]
请解决两个问题1.Tun 2.0socks start failed
2.剪贴板导入vmess 链接偶发性的导入失败或者成功。

**Comment by chsbuffer** [comment]
@qq583372062 
1. 请提供控制台日志，可能的解决方法：
- 更新至 Windows 10
- 设备管理器-网络适配器 卸载所有 Wireguard Tunnel 
2. 请检查你的剪切板。否则请提供 application.log 文件日志

**Comment by netch-org** [comment]
The current 2.0 progress is blocked. We are waiting for the release of the official version of Windows 11 and WinUI 3

**Comment by djoeni** [comment]
Support trojan-go or add websocket transport for trojan protocol

**Comment by tianzy12138** [comment]
可以加一个随机模式 随机从服务器列表里面选择一个 进行连接发送请求 。
使用场景：网络爬虫使用随机ip防止被标记

**Comment by Bryan2333** [comment]
Support NaïveProxy

**Comment by tianzy12138** [comment]
增加ICMP转发支持 用于欺骗GTA5游戏客户端

**Comment by p-w-p** [comment]
增加对wireguard的支持 :D

**Comment by ElPsyKongroooo** [comment]
可否恢复对VMess、Trojan、VLess的支持？
不知为何从v1.84开始就不再支持这三种协议了。

**Comment by HP-hhe** [comment]
请问，是否支持 windows sandbox 代理吗？ 不管我怎么设置，netch都不接管 windows sandbox的流量。谢谢

**Comment by nidbCN** [comment]
Use MAUI to make netch a cross-platform tool.

**Comment by RTM945** [comment]
希望能支持限速

**Comment by elmagnificogi** [comment]
add block ip in process or route mode, some game need manual block some server ip(Game give you random server IP, some you dont want to join)

also the route mode could support ip range(like 111.1111.111.111 - 222.222.222.222), not only mask

the route mode editor has bug that the ip font some biger some smaller,it's strange

**Comment by mianyan-echo** [comment]
可不可以支持一些初步的http代理功能

**Comment by DinuruSeniya** [comment]
Is Netch 2.0 going to use .NET 6.0 ?

**Comment by ERN645** [comment]
> > * idk what is this
> 
> Little more about feature "Fake WebRTC"
> 
> I know a tool with this feature its called "AntiRTC" if your need more info about this Tool ping me plz.
> 
> Some Socks5 does not support forwarding over UDP, it might be possible to create a mode that reports a "WebRTC Fake" to match with Reported IP see picture:
> 
> ![Fake WebRTC Feature Explained](https://user-images.githubusercontent.com/36669087/122106896-df789980-cdf0-11eb-88ed-d75f092fbf8f.jpg)

Maybe know were can got this tool ?
