### ISSUE TITLE
在 VMess / VLess 下 DNS 工作异常

### ISSUE THREAD

**Issue by brianler** [netchx/netch#668]
连接vmess和vless协议代理，在tun模式90%概率以上会出现以下问题，导致无法使用。是否为bug？
2021/06/16 09:04:07 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:04:07 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:04:39 [tun2socks][adns] Failed to unpack data: dns: bad rdata
2021/06/16 09:04:44 [tun2socks][adns] Failed to unpack data: dns: bad rdata
2021/06/16 09:04:49 [tun2socks][adns] Failed to unpack data: dns: bad rdata
或
2021/06/16 09:43:29 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:43:29 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:44:00 [tun2socks][adns] Failed to unpack data: dns: bad rdata
2021/06/16 09:44:04 [tun2socks][adns] Failed to unpack data: dns: buffer size too small
2021/06/16 09:44:07 [tun2socks][adns] Failed to unpack data: dns: buffer size too small
2021/06/16 09:44:10 [tun2socks][adns] Failed to unpack data: dns: bad rdata

在ss协议(代理主机的ss开启了udp转发)下无此问题，tun模式可以正常使用。

**Comment by brianler** [comment]
现在发现SS协议也阵亡了......，还是DNS解释的问题。

**Comment by brianler** [comment]
![Image text](https://www.hualigs.cn/image/60ca1aaf07ae3.jpg)
今天也研究了一下Clash的tun模式，也是各种问题，但最终解决了。需要指定出站网卡的名称(即电脑的物理网卡)，虽然文档说可以通过自动指定，但实测在Windows系统下必须手动指定才能生效(linux和mac系统可能可以自动生效)。上图网卡的名称“100Gbps”是我改的，原来网卡名称是“本地连接”，想到用网卡用中文名称的话可能会有问题(可能有字符编码转换问题)，所以重命名了。指定了出站网卡名后，clash就能完美运行tun模式了。
我想Netch的DNS解释问题会不会与此有关，解决办法就是指定出站网卡的名称，因为其无法自动正确地绑定出站物理网卡，导致DNS请求不断在内部回环打转，造成问题。

**Comment by brianler** [comment]
![Image text]( https://www.hualigs.cn/image/60ca1f4d3dbb0.jpg)
今天也研究了一下Clash的tun模式，也是各种问题，但最终解决了。需要指定出站网卡的名称(即电脑的物理网卡)，虽然文档说可以通过自动指定，但实测在Windows系统下必须手动指定才能生效(linux和mac系统可能可以自动生效)。上图网卡的名称“100Gbps”是我改的，原来网卡名称是“本地连接”，想到用网卡用中文名称的话可能会有问题(可能有字符编码转换问题)，所以重命名了。指定了出站网卡名后，clash就能完美运行tun模式了。
我想Netch的DNS解释问题会不会与此有关，解决办法就是指定出站网卡的名称，因为其无法自动正确地绑定出站物理网卡，导致DNS请求不断在内部回环打转，造成问题。

**Comment by FelixFeli** [comment]
实测TUN模式下的系统DNS设置为6.6.6.6，解析过程中会由虚拟网关交给AioDNS对国内国外分别处理，如果勾选了“使用自定义DNS”，则会按照指定的DNS进行解析。只要是TUN模式，最终都会通过连接的服务器将DNS请求发送到远程解析，否则无法绕过国内DNS污染。问题似乎就是出在这个过程，控制台里不断报错，如“Failed to unpack data: dns: buffer size too small”还有各种timeout。尝试将AioDNS地址或自定义DNS地址直接加入到“全局ip直连”中，也就等效在系统路由表中专门添加DNS地址到物理网卡条目。此时控制台不再报告上述错误，没有被DNS污染的域名可以正常打开，污染过的类似www.google.com，无法打开，说明DNS解析过程是直连的。这些实验让我猜测bug出现的可能在于netch将DNS请求打包交给远程服务器的过程当中。然而此问题却有一定概率自然修复，目前没有发现确定的复现方法，只是大概率触发。
![QQ截图20210701195641](https://user-images.githubusercontent.com/57336904/124120728-ad309280-daa6-11eb-8f6f-b8b6572ae3d0.png)

**Comment by log-z** [comment]
> 实测TUN模式下的系统DNS设置为6.6.6.6，解析过程中会由虚拟网关交给AioDNS对国内国外分别处理，如果勾选了“使用自定义DNS”，则会按照指定的DNS进行解析。只要是TUN模式，最终都会通过连接的服务器将DNS请求发送到远程解析，否则无法绕过国内DNS污染。问题似乎就是出在这个过程，控制台里不断报错，如“Failed to unpack data: dns: buffer size too small”还有各种timeout。尝试将AioDNS地址或自定义DNS地址直接加入到“全局ip直连”中，也就等效在系统路由表中专门添加DNS地址到物理网卡条目。此时控制台不再报告上述错误，没有被DNS污染的域名可以正常打开，污染过的类似www.google.com，无法打开，说明DNS解析过程是直连的。这些实验让我猜测bug出现的可能在于netch将DNS请求打包交给远程服务器的过程当中。然而此问题却有一定概率自然修复，目前没有发现确定的复现方法，只是大概率触发。
> ![QQ截图20210701195641](https://user-images.githubusercontent.com/57336904/124120728-ad309280-daa6-11eb-8f6f-b8b6572ae3d0.png)

太感谢了，终于不报 timeout 了，原来只要把 Orther DNS 加入到全局直连 IP 就行。
我这里 1.0.0.1 和 1.1.1.1 都用不了，只能用 8.8.8.8 。

![TVD{L1 PJS%`06E}W~J$WGL](https://user-images.githubusercontent.com/25786567/124133976-f091fd80-dab4-11eb-8e8e-9c2062aa9b6e.png)

![Z%$N$_8M(~924N0 9GY7X`M](https://user-images.githubusercontent.com/25786567/124133987-f38cee00-dab4-11eb-84e0-25357c472f9e.png)

![SKGE 0PWP2~}1 X R18%OK2](https://user-images.githubusercontent.com/25786567/124134002-f556b180-dab4-11eb-895e-524881c9b3ae.png)

**Comment by brianler** [comment]
> > 实测TUN模式下的系统DNS设置为6.6.6.6，解析过程中会由虚拟网关交给AioDNS对国内国外分别处理，如果勾选了“使用自定义DNS”，则会按照指定的DNS进行解析。只要是TUN模式，最终都会通过连接的服务器将DNS请求发送到远程解析，否则无法绕过国内DNS污染。问题似乎就是出在这个过程，控制台里不断报错，如“Failed to unpack data: dns: buffer size too small”还有各种timeout。尝试将AioDNS地址或自定义DNS地址直接加入到“全局ip直连”中，也就等效在系统路由表中专门添加DNS地址到物理网卡条目。此时控制台不再报告上述错误，没有被DNS污染的域名可以正常打开，污染过的类似www.google.com，无法打开，说明DNS解析过程是直连的。这些实验让我猜测bug出现的可能在于netch将DNS请求打包交给远程服务器的过程当中。然而此问题却有一定概率自然修复，目前没有发现确定的复现方法，只是大概率触发。
> > ![QQ截图20210701195641](https://user-images.githubusercontent.com/57336904/124120728-ad309280-daa6-11eb-8f6f-b8b6572ae3d0.png)
> 
> 太感谢了，终于不报 timeout 了，原来只要把 Orther DNS 加入到全局直连 IP 就行。
> 我这里 1.0.0.1 和 1.1.1.1 都用不了，只能用 8.8.8.8 。
> 
> ![TVD{L1 PJS%`06E}W~J$WGL](https://user-images.githubusercontent.com/25786567/124133976-f091fd80-dab4-11eb-8e8e-9c2062aa9b6e.png)
> 
> ![Z%$N$_8M(~924N0 9GY7X`M](https://user-images.githubusercontent.com/25786567/124133987-f38cee00-dab4-11eb-84e0-25357c472f9e.png)
> 
> ![SKGE 0PWP2~}1 X R18%OK2](https://user-images.githubusercontent.com/25786567/124134002-f556b180-dab4-11eb-895e-524881c9b3ae.png)

我之前设置过全局直连ip，所以没有timeout问题，但以下问题依然会出现，导致无法使用：
2021/06/16 09:04:07 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:04:07 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:04:39 [tun2socks][adns] Failed to unpack data: dns: bad rdata
2021/06/16 09:04:44 [tun2socks][adns] Failed to unpack data: dns: bad rdata
2021/06/16 09:04:49 [tun2socks][adns] Failed to unpack data: dns: bad rdata
或
2021/06/16 09:43:29 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:43:29 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
2021/06/16 09:44:00 [tun2socks][adns] Failed to unpack data: dns: bad rdata
2021/06/16 09:44:04 [tun2socks][adns] Failed to unpack data: dns: buffer size too small
2021/06/16 09:44:07 [tun2socks][adns] Failed to unpack data: dns: buffer size too small
2021/06/16 09:44:10 [tun2socks][adns] Failed to unpack data: dns: bad rdata

**Comment by log-z** [comment]
> > > 实测TUN模式下的系统DNS设置为6.6.6.6，解析过程中会由虚拟网关交给AioDNS对国内国外分别处理，如果勾选了“使用自定义DNS”，则会按照指定的DNS进行解析。只要是TUN模式，最终都会通过连接的服务器将DNS请求发送到远程解析，否则无法绕过国内DNS污染。问题似乎就是出在这个过程，控制台里不断报错，如“Failed to unpack data: dns: buffer size too small”还有各种timeout。尝试将AioDNS地址或自定义DNS地址直接加入到“全局ip直连”中，也就等效在系统路由表中专门添加DNS地址到物理网卡条目。此时控制台不再报告上述错误，没有被DNS污染的域名可以正常打开，污染过的类似www.google.com，无法打开，说明DNS解析过程是直连的。这些实验让我猜测bug出现的可能在于netch将DNS请求打包交给远程服务器的过程当中。然而此问题却有一定概率自然修复，目前没有发现确定的复现方法，只是大概率触发。
> > > ![QQ截图20210701195641](https://user-images.githubusercontent.com/57336904/124120728-ad309280-daa6-11eb-8f6f-b8b6572ae3d0.png)
> > 
> > 
> > 太感谢了，终于不报 timeout 了，原来只要把 Orther DNS 加入到全局直连 IP 就行。
> > 我这里 1.0.0.1 和 1.1.1.1 都用不了，只能用 8.8.8.8 。
> > ![TVD{L1 PJS%`06E}W~J$WGL](https://user-images.githubusercontent.com/25786567/124133976-f091fd80-dab4-11eb-8e8e-9c2062aa9b6e.png)
> > ![Z%$N$_8M(~924N0 9GY7X`M](https://user-images.githubusercontent.com/25786567/124133987-f38cee00-dab4-11eb-84e0-25357c472f9e.png)
> > ![SKGE 0PWP2~}1 X R18%OK2](https://user-images.githubusercontent.com/25786567/124134002-f556b180-dab4-11eb-895e-524881c9b3ae.png)
> 
> 我之前设置过全局直连ip，所以没有timeout问题，但以下问题依然会出现，导致无法使用：
> 2021/06/16 09:04:07 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
> 2021/06/16 09:04:07 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
> 2021/06/16 09:04:39 [tun2socks][adns] Failed to unpack data: dns: bad rdata
> 2021/06/16 09:04:44 [tun2socks][adns] Failed to unpack data: dns: bad rdata
> 2021/06/16 09:04:49 [tun2socks][adns] Failed to unpack data: dns: bad rdata
> 或
> 2021/06/16 09:43:29 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
> 2021/06/16 09:43:29 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16
> 2021/06/16 09:44:00 [tun2socks][adns] Failed to unpack data: dns: bad rdata
> 2021/06/16 09:44:04 [tun2socks][adns] Failed to unpack data: dns: buffer size too small
> 2021/06/16 09:44:07 [tun2socks][adns] Failed to unpack data: dns: buffer size too small
> 2021/06/16 09:44:10 [tun2socks][adns] Failed to unpack data: dns: bad rdata

我现在只会出现下面这个错误，倒是不影响使用。之前有点过这三个，不知道有没有影响。或许你可以换个DNS，再或者另外下一个最新版本试试看看。
[tun2socks][adns] DNS resolution failed: EOF

![image](https://user-images.githubusercontent.com/25786567/124145622-8894e480-dabf-11eb-9f73-f75aa84891d9.png)

**Comment by brianler** [comment]
有时确实可以用的，但过段时间后，不知道怎么会又不行的。我觉得DNS一直没有正常解释。像我开头说的“在ss协议(代理主机的ss开启了udp转发)下无此问题，tun模式可以正常使用。”，但是过段时间，又不能用了，控制台也是输出dns错误的信息。

**Comment by FelixFeli** [comment]
测试之前最好点一下“清理DNS缓存”，否则系统NDS缓存可能会影响测试结果，比如本来解析有问题，但因为系统有记录反而能正常访问的情况。如果没勾选“使用自定义DNS”，添加进IP直连的要包含AioDNS下的otherDNS（chinaDNS会自动添加进直连），如果勾选了，就可以只添加自定义的那一个。目前我总结的触发这个bug的场景就是：TUN模式下让远程服务器来进行DNS解析，即将dns请求打包交给远程服务器的过程当中。只要是本地直连的dns请求均不会触发。
