### ISSUE TITLE
最新版怎么还被杀后台啊

### ISSUE THREAD

**Issue by AromanRon** [netchx/netch#670]
放在后台十几分钟就被杀进程

**Comment by netch-org** [comment]
我们认为这是您的问题

- 内存满了
- 杀毒软件
- 你猜

**Comment by avboy1337** [comment]
二进制bin文件用了加壳软件，然后直接内存加载，这里可以考虑自行编译或者下载官网的软件，我也在尝试替换部分bin文件

**Comment by netch-org** [comment]
> 二进制bin文件用了加壳软件，然后直接内存加载，这里可以考虑自行编译或者下载官网的软件，我也在尝试替换部分bin文件

您可以使用 UPX 解压，我们的 .bin 文件均为 UPX 加壳压缩
