### ISSUE TITLE
使用netch

### ISSUE THREAD

**Issue by phrnet** [netchx/netch#671]
使用netch的全局代理.使用的是xray的配置会出现以下问题：
1、如果是代理192.168.1.1或者172.0.0.01之类的局域网地址，使用全局或者ACL模式都不行
查看具体的log发现是Netch的bin下的geoip.dat有个路由表，忽略了此类地址，请大佬看下
我尝试修改了geoip.dat后，覆盖源文件即可正常访问

**Comment by phrnet** [comment]
不懂如何插入附件  我是使用v2raycustomgeo_windows_amd64 修改的

**Comment by netch-org** [comment]
我们目前没有提供 *真全局* 功能，建议使用 ProcessMode 去代理，可能是真全局

**Comment by phrnet** [comment]
> 我们目前没有提供 _真全局_ 功能，建议使用 ProcessMode 去代理，可能是真全局

如果是使用xray or v2ray只需要修改geoip.dat 即可全局了 包括局域网
