### ISSUE TITLE
关于代理discord

### ISSUE THREAD

**Issue by mzk602400288** [netchx/netch#673]
之前一段时间用的进程代理添加了discord.exe可以正常访问 这几天发现一直卡转圈圈 切换到自带的网页代理就可以正常访问 再说下代理节点吧 我换了个其他的节点进程模式又可以使用了 但是我其他三四个节点都不行就，这一个节点可以正常进程代理其他节点都需要网页代理

**Comment by netch-org** [comment]
```
# Discord, 0
\\Discord\\
```

**Comment by jisa8438** [comment]
> ```
> # Discord, 0
> \\Discord\\
> ```

还是一直转圈圈
