### ISSUE TITLE
建议添加更多加密协议（shadowsocksr）

### ISSUE THREAD

**Issue by him41111** [netchx/netch#68]
比如rc4-md5-6，我的用的机场都是这个协议的，所以无法使用您的软件。

**Comment by BingLingGroup** [comment]
这是ssr的协议吧，先码着。

**Comment by ghost** [comment]
不会为 ShadowsocksR 增加更多的 加密、协议、混淆

**Comment by BingLingGroup** [comment]
建议参考[readme](https://github.com/NetchX/NetchMode/blob/master/docs/README.zh-CN.md#socks-5-代理中转)这部分所说的方法通过socks5中转的方法使用[HMBSbige/ShadowsocksR-Windows](https://github.com/HMBSbige/ShadowsocksR-Windows/releases)
