### ISSUE TITLE
进程模式-被墙的网页还是打不开，打开墙内的网页查询ip会显示代理地址的ip

### ISSUE THREAD

**Issue by 7Azure** [netchx/netch#681]

**Comment by izANTM** [comment]
![Uploading S_2021-06-29_9.jpg…]()

**Comment by 7Azure** [comment]
![S_2021-06-29_9](https://user-images.githubusercontent.com/35513144/123782605-16c66a80-d908-11eb-8980-db671bc405bc.jpg)
