### ISSUE TITLE
莫名其妙今天突然报错

### ISSUE THREAD

**Issue by AromanRon** [netchx/netch#682]
tun2socks start failed，net5装过了，杀毒关了，电脑也重启了，重新安装还是没用

**Comment by chsbuffer** [comment]
Win+R 输入 `%appdata%\Microsoft\Crypto` 后重命名 RSA 文件夹为 RSA_ 或直接删除。

**Comment by AromanRon** [comment]
全删了也没用




Zelda
***@***.***



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "netchx/netch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [netchx/netch] 莫名其妙今天突然报错 (#682)





 
Win+R 输入 %appdata%\Microsoft\Crypto 后重命名 RSA 文件夹为 RSA_ 或直接删除。
