### ISSUE TITLE
在使用UI内置的版本更新功能后，配置文件被全部删除

### ISSUE THREAD

**Issue by IceLitty** [netchx/netch#687]
个人不喜欢按各个游戏分类配置文件，所以统一出了一份应用名的GamesAIO.txt的配置，在更新为1.8.5后，发现配置文件被全部删除重新填充安装目录，但非原生的配置文件将不复存在，使用DG恢复文件功能，发现了被其重命名为.old结尾的备份，但压缩格式不明确，无法复原成原本正常使用的配置文件。
![Snipaste_2021-07-03_20-34-32](https://user-images.githubusercontent.com/6522057/124354332-172f7000-dc3e-11eb-8ec0-9ecf345cdf68.png)
[GamesAIO.txt](https://github.com/netchx/netch/files/6758408/GamesAIO.txt)
请帮我恢复，谢谢。

**Comment by chsbuffer** [comment]
请将要在升级时保留的自定义模式放入 mode/Custom/
.old 只是重命名标注下次打开时删除，未作其他处理
请自行重建模式

**Comment by IceLitty** [comment]
> 请将要在升级时保留的自定义模式放入 mode/Custom/
> .old 只是重命名标注下次打开时删除，未作其他处理
> 请自行重建模式

旧版本根本没有mode里用文件夹分类的形式，这种破坏性操作执行前没有任何提示，这是不合理的。
这个文件节点dg解析失败所以没法像别的文件一样恢复，所以没办法找到原本咯？
用户只希望能正常使用，这种东西随时修改也不会有备份，所以我来也只是提出个建议，一般来说除非没的选择，否则遇到这种事是不会去自行重建模式，而是避免继续使用……

**Comment by chsbuffer** [comment]
写在 1.7.5 更新日志里了
