### ISSUE TITLE
tun/tcp模式只有勾选上"解析服务器主机名"才有效果

### ISSUE THREAD

**Issue by FanNengHu** [netchx/netch#688]
使用的版本：1.7.6
问题描述：当选用tun/tcp模式，启动之后，用chrome浏览器无法上google。进入设置里面，把解析服务器主机名勾选上，重新启动，马上就可以访问google了。请问这个选项是什么原理呢？一定要勾选这个选项才可以吗？

**Comment by chsbuffer** [comment]
`解析服务器主机名` 作用是向代理客户端传递解析后的服务端地址。此选项是为了防止虚拟网卡模式启动后代理客户端无法解析服务端地址而无法与服务端建立连接。
