### ISSUE TITLE
启动游戏的官网难打开，启动游戏后操作也比较卡

### ISSUE THREAD

**Issue by Cirooo** [netchx/netch#69]
**错误描述**
游戏是日服的，talesweaver.nexon.co.jp ，ssr节点试了很多个（这些节点都能用sstap打开官网登录并进入游戏），有的打不开官网，有的不能在网页登陆帐号，也有是游戏启动了不能选区以及进入人物，进了人物的也有顺一下卡一下的。
这并不算netch的建议，也不算错误报告，错误报告是要提供日志的，这款软件基本不提供什么连接情况的信息。
netch的优势是针对进程名来挂代理，sstap做不到，还是期待netch能优化好吧。
**复现步骤**
1. 打开 Netch 软件
2. ×打开游戏官网
3. ×打开登录网页
4. ×登录成功后点网页中的启动游戏
5. ×跟大部分游戏一样，选区，选人物，开始玩
×号是sstap可以，而netch有可能不成功，看脸
**信息**
 - 操作系统：[例如 Windows 10 专业版 64 位]
 - 软件版本：[例如 1.2.1-STABLE 64 位]

**额外信息**
我是原本的加速服务不太靠谱，找了别家的ssr服务，才折腾那么多- - 
有朋友说，netch的ssr支持不太好，所以我尝试了自带的netch-ssr，或者通过正常的ssr客户端打开一个本地端口，让netch以socks5方式连接，这些结果都区别不大，连接不顺，或是根本不成功。

**Comment by ghost** [comment]
#67

**Comment by BingLingGroup** [comment]
可能是DNS问题，建议先试试更换DNS。

**Comment by BingLingGroup** [comment]
需要更多的信息，否则按照 #152 处理
