### ISSUE TITLE
Resolve Server Hostname may break the xray connection

### ISSUE THREAD

**Issue by chsbuffer** [netchx/netch#694]
Need further communication for solution

**Comment by chsbuffer** [comment]
现有信息表明 `解析服务器主机名` 选项确实有帮助在使用 Bypass LAN 虚拟网卡模式时 Xray 客户端与服务端连接（而不是导致解析服务器域名请求在本机链路中循环），但是也有信息表明当服务端 Nginx 配置为拒绝与非指定 SNI 握手时无法与代理服务器连接（或 Netch 生成的客户端配置文件有误）

因为没有开发成员使用/测试 Xray 代理、主要开发人员(@chsbuffer ) 无法理解相关文档、缺少更多用户报告等原因，此问题长期阻塞

请测试使用不同传输协议时（WebSocket 和 mKCP 为代表的），启用、禁用 `解析服务器主机名` 是否会影响与服务端连接，评论附上 logging 下的所有日志文件（请自行抹去敏感信息，拖拽到评论框上传文件），启动后生成的客户端配置文件（data\last.json）

**Comment by chsbuffer** [comment]
https://github.com/netchx/netch/blob/master/Netch/Servers/V2ray/Utils/V2rayConfigUtils.cs

**Comment by testermania** [comment]
ipv6 only server + wireguard cloudflare ipv4

server side xray 1.4.2
config.json

> { "log": { "loglevel": "warning" }, "inbounds": [ { "port": 2002, "listen": "127.0.0.1", "protocol": "vless", "settings": { "clients": [ { "id": "44f234ef-82e4-4162-9842-69aa375525f5" // 填写你的 UUID } ], "decryption": "none" }, "streamSettings": { "network": "grpc", "grpcSettings": { "serviceName": "mydomain.com" // 填写你的 ServiceName } } } ], "outbounds": [ { "tag": "direct", "protocol": "freedom", "settings": {} }, { "tag": "blocked", "protocol": "blackhole", "settings": {} } ], "routing": { "domainStrategy": "AsIs", "rules": [ { "type": "field", "ip": [ "geoip:private" ], "outboundTag": "blocked" } ] } }

nginx default.conf
```
server {
        listen [::]:80;
        listen [::]:443 ssl http2 reuseport;
        server_name mydomain;              # 主机头，请更改为你绑定的域名
        index index.html;                         # 默认页面
        root /usr/share/nginx/html;               # 网页根目录路径

        ssl_certificate /root/cert.crt;           # 证书路径
        ssl_certificate_key /root/private.key;    # 密钥路径
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POL$

        # 在 location 后填写 /{你的 ServiceName}
        location /mydomain {
                if ($content_type !~ "application/grpc") {
                        return 404;
                }
                client_max_body_size 0;
                client_body_timeout 1071906480m;
                grpc_read_timeout 1071906480m;
                grpc_pass grpc://127.0.0.1:2002;
        }
}
```
netch settings and last.json here
[settings.zip](https://github.com/netchx/netch/files/6791362/settings.zip)

only works with cdn ip. not working with domain name. host doesn't matter, it's empty or running with a different domain name.

**Comment by chsbuffer** [comment]
@testermania if you disabled `Resolve Server Hostname` and see many `[tun2socks][adns] DNS resolution failed:  read xxx: i/o timeout`, that is expected behavior.
it's because xray client try to resolve the domain name to ip, and the request be intercept to xray client again causing a local loop. please enable `Resolve server hostname` and try again, the setting is used for pre-resolve domain name to ip and put in the client configuration file.
the topic is about this setting broken the connections, not about "why i disabled it and something not work."

**Comment by chsbuffer** [comment]
@testermania nginx configuration issue.

**Comment by netch-org** [comment]
From the next release, we should force this feature

**Comment by netch-org** [comment]
Always enable `Resolve Server Hostname`
