### ISSUE TITLE
failed to start shadowsocks with plugin when Netch run at os startup

### ISSUE THREAD

**Issue by chsbuffer** [netchx/netch#696]
current have no idea about how to fix it (keep using task scheduler to bypass UAC)

**Comment by nidbCN** [comment]
For developer: How about use a shadowsocks(R) library or use codes in shadowsocks(R)-windows inside of execute binary file?

**Comment by ghost** [comment]
Check the network status after Netch starts, and sleep 114514s

**Comment by nidbCN** [comment]
> Check the network status after Netch starts, and sleep 114514s

哼哼哼，啊啊啊啊啊——
