### ISSUE TITLE
windows11 NETCH无法启动 显示tun2socks start failed 重启无用 需要手动添加驱动才能启动

### ISSUE THREAD

**Issue by miaopasimiao** [netchx/netch#698]
控制台信息 
2021/07/14 23:22:20 [Wintun] CreateAdapter: Creating adapter
2021/07/14 23:22:20 [Wintun] SelectDriver: Using existing driver 0.10
2021/07/14 23:22:20 [Wintun] CreateAdapter: Failed to setup adapter (status: 0x0): 操作成功完成。 (Code 0x00000000)
2021/07/14 23:22:20 [Wintun] OpenDeviceObject: Failed to connect to adapter ROOT\NET\0000 associated instance : 系统找不到指定的路径。 (Code 0x00000003)
2021/07/14 23:22:20 [Wintun] WintunStartSession: Failed to open adapter device object
2021/07/14 23:22:20 [tun2socks][newTUN][tun.CreateTUN] Error starting session: The system cannot find the path specified.
windows11 22000.65 出现的问题
手动安装驱动后可以启动 停止后再启动会出现问题

**Comment by miaopasimiao** [comment]
版本1.8.5

**Comment by chsbuffer** [comment]
请尝试 1.8.6

**Comment by miaopasimiao** [comment]
的确是可以了 但是启动Bypass LAN无法连接 
2021/07/15 13:34:36 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65221->1.1.1.1:53: i/o timeout
2021/07/15 13:34:36 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65222->1.1.1.1:53: i/o timeout
2021/07/15 13:34:36 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65223->1.1.1.1:53: i/o timeout
2021/07/15 13:34:36 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65226->1.1.1.1:53: i/o timeout
2021/07/15 13:34:37 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65236->1.1.1.1:53: i/o timeout
2021/07/15 13:34:37 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65299->1.1.1.1:53: i/o timeout
2021/07/15 13:34:37 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65305->1.1.1.1:53: i/o timeout
2021/07/15 13:34:37 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65304->1.1.1.1:53: i/o timeout
2021/07/15 13:34:37 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65311->1.1.1.1:53: i/o timeout
2021/07/15 13:34:37 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65313->1.1.1.1:53: i/o timeout
2021/07/15 13:34:37 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65312->1.1.1.1:53: i/o timeout
2021/07/15 13:34:38 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65317->1.1.1.1:53: i/o timeout
2021/07/15 13:34:38 [tun2socks][adns] DNS resolution failed: read tcp 10.0.236.10:65380->1.1.1.1:53: i/o timeout

**Comment by miaopasimiao** [comment]
1.8.5和以前的版本都正常

**Comment by miaopasimiao** [comment]
服务端版本XRAY1.4.2 协议VMESS WS TLS

**Comment by chsbuffer** [comment]
请自行查看启动时在 Netch\data\last.json 生成的 xray 客户端配置是否有误并反馈

**Comment by miaopasimiao** [comment]
没有last.json  只有一个settings.json ，json是正常的

**Comment by 8090s** [comment]
我也遇到 这个问题了 1.8.7版本

**Comment by snomgq** [comment]
1.97，启动失败

**Comment by juzizaiw** [comment]
解决了嘛·，我也出现这个问题
![Netch 2023_4_14 22_15_07](https://user-images.githubusercontent.com/114214943/232069845-dbb6d8b8-d0cd-4c05-a0d2-4bf5fef23b59.png)

**Comment by RyanLoil** [comment]
同样的情况
<img width="155" alt="image" src="https://user-images.githubusercontent.com/50242494/233444908-20e0e274-5df3-4b39-8300-b758a77d2093.png">

**Comment by ylhy2299** [comment]
![123](https://github.com/netchx/netch/assets/149266192/2ba71b73-7e98-47c7-be77-6c90fe011c92)
这个怎么解决
