### ISSUE TITLE
请问 .NET 6 支持运行 Netch 吗？

### ISSUE THREAD

**Issue by cherinyy** [netchx/netch#700]
Netch 1.8.6 提示未发现 .NET 5，需要下载。

个人不太了解 .NET 5 和 .NET 6 的区别，但感觉应该没有 .NET 3 和 .NET 4 的差别大？
主要是之前在使用 [SteamTools-Team/SteamTools](https://github.com/SteamTools-Team/SteamTools) 的时候，它要求需要 .NET 6 Preview 4，就直接装 .NET 6 预览版了。

如果 .NET 6 支持运行 Netch 的话，能否识别一下 .NET 6 运行库呢？
谢谢！

祝好，

**Comment by chsbuffer** [comment]
大版本互不兼容。.NET 6 正式版时 Netch 也会升到 .NET 6
