### ISSUE TITLE
RemoveDupeAssemblies workaround is no longer needed with .NET SDK 6 Preview 5+

### ISSUE THREAD

**Issue by chsbuffer** [netchx/netch#702]
## What Happend

0. .NET SDK 5
1. Install "Microsoft.Diagnostics.Tracing.TraceEvent"
2. Publish with -p:PublishSingleFile=true
```
MSB4018 "Multiple entries with the same BundleRelativePath"
```
3. To prevent the error, use the workaround https://github.com/microsoft/perfview/issues/1002 , works fine
4. Update to .NET 6 SDK Preview 5+ that fixed MSB4018 (https://github.com/dotnet/runtime/pull/50476) but still with the workaround at step 3 and publish like step 2

```
Description: A .NET application failed.
Application: test.exe
Path: xxx
Message: Error:
  An assembly specified in the application dependencies manifest (test.deps.json) was not found:
    package: 'Microsoft.Diagnostics.Tracing.TraceEvent', version: '2.0.70'
    path: 'lib/netstandard2.0/Dia2Lib.dll'
```

## How to fix
currently i have created global.json to ensure use stable .NET 5 SDK, but when .NET 6 release with the stable SDK, Netch will update TFM to net6.0 too, then have to remove the old [workaround](https://github.com/netchx/netch/blob/060c42efbc1fee881dd4e02cbd3298b1d57307ac/Netch/Netch.csproj#L98-L100)

## Other
currently no plan about backport the sdk fix to .NET 5 SDK https://github.com/dotnet/runtime/issues/52671#issuecomment-880174756

**Comment by xuanwoa** [comment]
1.8.7 has same problem
