### ISSUE TITLE
用netch直接导致电脑wifi功能自动不见

### ISSUE THREAD

**Issue by Round-Leaf** [netchx/netch#703]
电脑只用过一次netch，从那以后电脑wifi功能会时不时自动不见，必须重启。
我之后在命令行输入netsh winsock reset之后这个问题才得以解决

**Comment by Round-Leaf** [comment]
为什么把我的问题删了？？？？

ChsBuffer ***@***.***> 于2021年7月20日周二 下午5:47写道：

**Comment by KiritoCheng** [comment]
netsh winsock reset 已解决
