### ISSUE TITLE
Windows 11 自带杀毒显示该软件有威胁？

### ISSUE THREAD

**Issue by Neillll** [netchx/netch#706]
![微信图片_20210724002628](https://user-images.githubusercontent.com/10258176/126812759-5005d0bc-d1d7-44ff-aabe-b65ed8f99472.png)

**Comment by avboy1337** [comment]
这个情况我也不知，不过不管如何，我尽量实现将netch用到的所有代码全部重新编译一遍。
和cheatengine不一样，cheatengine全部代码开源，netch毕竟自己提供一部分编译后的代码，一些加了壳子后提供，虽然也是一些开源的，毕竟有些是改造后再编译。
其实还是希望netch能开源所有的代码。我已经将netch回退到1.5版本，并将所有用到的代码全部自己溯源编译了一遍。
