### ISSUE TITLE
不兼容最新的.NET Framework 5.0.8

### ISSUE THREAD

**Issue by zdz2019** [netchx/netch#707]
未安装前提示：
![01](https://user-images.githubusercontent.com/50648881/126884581-badc1f45-b8cc-43e1-80c6-7f083f62049c.png)

安装 .NET Framework 5.0.8 后提示：
![02](https://user-images.githubusercontent.com/50648881/126884585-72ff14e9-568c-4e1c-b0c5-adebba48fe49.png)
![03](https://user-images.githubusercontent.com/50648881/126884588-8787a7fb-d298-4340-a423-a9650add7215.png)

**Comment by wukecheng** [comment]
要安装桌面版 Ayu Mini ***@***.*** 签名由 网易邮箱大师 定制 在2021年07月25日 09:11，zdz2019 写道： 未安装前提示： 安装 .NET Framework 5.0.8 后提示： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zdz2019** [comment]
已测试，默认跳转的链接下载的 .NET Framework 不适用，建议作者更换跳转链接，否则容易误导使用者。

已验证正确的下载链接：
https://dotnet.microsoft.com/download/dotnet/5.0

![04](https://user-images.githubusercontent.com/50648881/126885080-3267c02d-29d2-473e-a82c-fb518d0ee57d.png)
