### ISSUE TITLE
能否提供netchdata里用到Shadowsocks源代码？

### ISSUE THREAD

**Issue by cute** [netchx/netch#708]
我留意到netchdata用到的二进制 Shadowsocks.exe 似乎与官方的shadowsocks-libev不一样。
能否提供一下修改后的代码呢？

**Comment by chsbuffer** [comment]
仅使用 upx 压缩

**Comment by cute** [comment]
> 仅使用 upx 压缩

有用户反映通过netch可以使用 64 字符长度密码访问 chacha20-ietf-poly1305 加密的 Shadowsocks 节点，而使用别的软件却不可以。

**Comment by avboy1337** [comment]
弱弱问一下，shadowsocksr的源代码能提不

**Comment by chsbuffer** [comment]
https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.3.4
