### ISSUE TITLE
Redirector优化

### ISSUE THREAD

**Issue by jinbasex** [netchx/netch#71]
**功能描述**
在sstap下进入pubg 没有任何问题 延迟掉包都没有 使用的是 不代理中国ip的模式

但是在netch 必须要用pubg 模式才能加速  bypass lan and china 不能加速
我个人习惯是直接bypass 然后无脑丢一边就好 游戏网页 两齐全

**额外信息**

还有一点就是netch 的 pubg模式 对比 sstap的不代理中国ip ping平均多10-20ping  且丢包严重 在sstap上没有出现丢包， 线路同一边 游戏时间也是一把一个软件测试的
还希望作者能看一下

**Comment by ghost** [comment]
1. Bypass LAN and China 是给浏览器用的（但是也能加速游戏，选带 TUN/TAP 标识的）
2. 请使用 SSTap thx

**Comment by jinbasex** [comment]
> 1. Bypass LAN and China 是给浏览器用的（但是也能加速游戏，选带 TUN/TAP 标识的）
> 2. 请使用 SSTap tks

您可能误解的我的意思  谢谢您 netch 很好用特别实在类似wf的游戏上面
在这只是给你提多一个建议 是tun 标识的是吗 谢谢您 我等会继续测试一下
初次使用这个软件 只是一个小白 还望海涵

**Comment by BingLingGroup** [comment]
关于模式的说明[详见](https://github.com/NetchX/Netch/blob/master/docs/USAGE.zh-CN.md#%E6%A8%A1%E5%BC%8F%E4%BB%8B%E7%BB%8D)

**Comment by jinbasex** [comment]
> 关于模式的说明[详见](https://github.com/NetchX/Netch/blob/master/docs/USAGE.zh-CN.md#%E6%A8%A1%E5%BC%8F%E4%BB%8B%E7%BB%8D)

感谢

**Comment by ghost** [comment]
请问您 PUBG 是上行丢包还是下行丢包呢？

**Comment by jinbasex** [comment]
> 请问您 PUBG 是上行丢包还是下行丢包呢？

我个人的网络环境下是两者都丢包 看着丢包率忽然跳到60+
后来我都是netch 作为上网用 sstap 不代理中国ip来加速pubg

**Comment by ghost** [comment]
好的，感谢您的反馈

有待测试

我之前玩的时候能出现超出 100% 的丢包，然而并没有造成啥不良的影响 ...

有待深度测试

**Comment by jinbasex** [comment]
如果需要上传log文件之类 能够帮到您的话 我乐意之至 明晚下班我再试试加速pubg 具体再测试一下

我这边是 一旦60+丢包 直接开门延迟 子弹捡不起来

**Comment by ghost** [comment]
十分感谢您提供日志参考，但是现在就是给了日志也没用，需要我本地复现，才好调试

然而 PUBG 游戏太大，测试起来很不方便 ...

**Comment by jinbasex** [comment]
> 十分感谢您提供日志参考，但是现在就是给了日志也没用，需要我本地复现，才好调试
> 
> 然而 PUBG 游戏太大，测试起来很不方便 ...

再次为这样一个便捷高效的软件向您表示感谢

更新最新版本之后 游戏加速方面仍然对比sstap 有波动 但是基本可以忽略不计
然后想请问一下可以让bypass lan and china 实现游戏加速吗？
这样国内的软件和网页不受影响
当然我也深知其中的不易 还是谢谢您后续的回复

**Comment by ghost** [comment]
不太想做进程级别的 Bypass LAN and China（个人没需求啊，希望有人贡献代码吧）

不过现在是有 TUN/TAP 的 Bypass LAN（跟 SSTap 差不多的原理，效果有待测试，不太稳定，可能启动失败，或者没生效啥的，需要优化）

**Comment by jinbasex** [comment]
> 不太想做进程级别的 Bypass LAN and China（个人没需求啊，希望有人贡献代码吧）
> 
> 不过现在是有 TUN/TAP 的 Bypass LAN（跟 SSTap 差不多的原理，效果有待测试，不太稳定，可能启动失败，或者没生效啥的，需要优化）

这一个我感觉是全局的 会影响到太多自己工作的软件  还是谢谢您

**Comment by imoldchen** [comment]
TUN/TAP 我这里确实开启成功但不生效（Win10），按道理说这种模式是最高效的，对延迟的影响最小。至于全局问题可以自己去设置里添加China IP 段，GitHub也有 windows 路由脚本，效果因为大网站都有全球CDN分布所以一般般，但好歹能可以节省一部分流量。但软件最好内置局域网IP段，这样就不用自己去添加这一部分了。

**Comment by BingLingGroup** [comment]
@imoldchen TUN/TAP 无效的话建议重装 Tap-windows 驱动，我这里试过模式三是没有问题的。或者请检查是否开启了自定义 DNS，在设置里面有，建议设置成 1.1.1.1。

**Comment by BingLingGroup** [comment]
先关了，参见 #152
