### ISSUE TITLE
无法启动tun2socks

### ISSUE THREAD

**Issue by Hikari0964** [netchx/netch#711]
![image](https://user-images.githubusercontent.com/77787562/126930382-c519cef0-95b2-49e8-9710-b7a3ccd023c5.png)
![image.png](https://i.loli.net/2021/07/27/s1hxNUmoYa6wM8Z.png)

**Comment by chsbuffer** [comment]
请附上控制台日志

**Comment by chsbuffer** [comment]
请尝试网络重置 ```系统设置 - 网络 & Internet - 高级网络设置 - 网络重置```

**Comment by Hikari0964** [comment]
> 请尝试网络重置 `系统设置 - 网络 & Internet - 高级网络设置 - 网络重置`

![image](https://user-images.githubusercontent.com/77787562/127251376-94ba9700-69ef-4404-8e3c-10b1dfd73dc6.png)
还是失败

**Comment by ghost** [comment]
> > 请尝试网络重置`系统设置 - 网络 & Internet - 高级网络设置 - 网络重置`
> 
> ![image](https://user-images.githubusercontent.com/77787562/127251376-94ba9700-69ef-4404-8e3c-10b1dfd73dc6.png)
> 还是失败

系统设置 - 网络 & Internet - 更改适配器选项 - 把主网络以外的链接都禁用
然后重启PC后管理员运行Netch  选项 - 卸载NF服务 试试
我1.8.5的时候出过几次这个问题  每次都是这样搞好的
搞好后恢复那几个链接也没事的

好像也不用重启PC（不过还是建议你重启下）
同时建议每次更新版本后卸载一次NF服务
WIN10 21H1

**Comment by netch-org** [comment]
- 关闭杀毒软件
- 尝试修复系统
- 尝试重装系统

```
Dism /Online /Cleanup-Image /ScanHealth
Dism /Online /Cleanup-Image /CheckHealth
Dism /Online /Cleanup-Image /RestoreHealth
sfc /scannow
```

关于 TunMode 我们已经在 Windows 10 21H1 19043.1151 上测试通过

**Comment by telnetpig** [comment]
> * 关闭杀毒软件
> * 尝试修复系统
> * 尝试重装系统
> 
> ```
> Dism /Online /Cleanup-Image /ScanHealth
> Dism /Online /Cleanup-Image /CheckHealth
> Dism /Online /Cleanup-Image /RestoreHealth
> sfc /scannow
> ```
> 
> 关于 TunMode 我们已经在 Windows 10 21H1 19043.1151 上测试通过

按照这个方法解决了同样的问题
