### ISSUE TITLE
默认启用的“解析服务器主机名”会导致部分游戏卡死在更新/登录阶段

### ISSUE THREAD

**Issue by TheCGDF** [netchx/netch#715]
英雄联盟、原神等游戏默认启用解析服务器主机名时会卡死在更新/登录阶段或加载极其缓慢，关闭`解析服务器主机名`则一切正常

猜测应该是由于游戏更新包是CDN就近分发，本地解析到的IP，节点端连接该IP时并不一定通畅

**Comment by chsbuffer** [comment]
如果解析（代理）服务器主机名影响了连接速率，请检查（代理）服务器配置是否填写正确

**Comment by TheCGDF** [comment]
> 如果解析（代理）服务器主机名影响了连接速率，请检查（代理）服务器配置是否填写正确

配置应该没有问题，因为无论开不开解析服务器主机名都不影响游戏局内的体验，只会影响更新和登录这一阶段
