### ISSUE TITLE
建议分离ss的udp和tcp

### ISSUE THREAD

**Issue by thisdk** [netchx/netch#72]
**功能描述**
就是可以指定ss的tcp服务器,可以指定udp的服务器.因为我有一个专门的udp加速服务器.这台服务器是没有任何tcp连接的.这样做的好处是可以嵌套各种工具.如tcp通道直连到某个服务器.

而我的udp通道可以嵌套udp的多倍发包.或者再嵌套一个udp伪装tcp.

**Comment by thisdk** [comment]
重新打开问题

**Comment by thisdk** [comment]
重新打开问题

**Comment by ghost** [comment]
想法不错，可以考虑

**Comment by BingLingGroup** [comment]
估计得用 [tinyportmapper](https://github.com/wangyu-/tinyPortMapper) 了吧，CR 有什么意见 @ConnectionRefused

**Comment by ghost** [comment]
我可以在 Redirector 上做更改啊 :)

**Comment by thisdk** [comment]
大佬们好,其实可以这样,SS原生就支持分离.不需要做太多的代码修改比如你代码里是这样的
Shadowsocks.exe -s {0} -p {1} -b 0.0.0.0 -l {2} -m {3} -k \"{4}\" -u
-u参数代表同时使用tcp和udp.因为同一个端口分为tcp通道和udp通道.SS还支持这样

Shadowsocks.exe -s 服务器IP -p 服务器端口 -b 0.0.0.0 -l 2801 -m 加密 -k 密码
Shadowsocks.exe -s 127.0.0.1 -p UDP多倍发包端口 -b 0.0.0.0 -l 2801 -m 加密 -k 密码 -U

-U参数是只使用UDP通道.

这样TCP就会直走到服务器.而我们指定的UDP通道,就会到指定的IP和端口.

其实udp多倍发包还是有那么一点点意义.但是可能用的人不多.对于服务器有不超过10%丢包的.可以把丢包降为0.

**Comment by BingLingGroup** [comment]
好吧，原来本地端口可以复用

**Comment by Rioders** [comment]
我认为这个想法很好。大多数时候用普通的线路玩游戏难以达到不丢包的。因此通常会考虑用流量比较昂贵的 IPLC 线路，或是用 Kcptun、udpspeeder 等多倍发包工具来玩游戏。但游戏有时会下载更新，这时候就比较浪费 IPLC 线路的流量或需忍受 udpspeeder 带来的带宽下降。

可能有部分人觉得多倍发包工具会使国际线路更加拥堵，但对于普通人为了玩个游戏这是最便捷的方法了。况且游戏所需要的 udp 带宽并不高，如 50KB/s 按 5 倍发包是 250KB/s。如果能把 UDP 和 TCP 分离，整体的线路利用率还会更高。

**Comment by lyafancn** [comment]
偷窥ing

**Comment by AmazingDM** [comment]
https://github.com/AmazingDM/Netch-ForOwnUse
