### ISSUE TITLE
core.bin

### ISSUE THREAD

**Issue by avboy1337** [netchx/netch#721]
Dear Master , wish there is any possible to make Core.bin opensource.
Really appreciated!!

**Comment by netch-org** [comment]
In the old Redirector, it was indeed bound to Core

The new Redirector will be improved. core is no longer required. Please wait until the main branch is developed

**Comment by netch-org** [comment]
Finally, all components of Netch will be open source

**Comment by avboy1337** [comment]
> Finally, all components of Netch will be open source

Really 3ks for your well done work!!
