### ISSUE TITLE
必须要net 5.0.0的版本才能使用

### ISSUE THREAD

**Issue by 67here** [netchx/netch#725]
显示缺失，自动点击下载 跳到的链接是5.0.2 还是3的官方下载，64位和32位都不行
非要5.0.0的64位才行，，，略麻烦

**Comment by chsbuffer** [comment]
**.NET 5 Desktop Runtime x64**

**Comment by 67here** [comment]
我服，这你也关，你那个链接自动跳的是5.0.2的版本，下载根本不能用，我提示一下就关了？行，算我多嘴

**Comment by 67here** [comment]
> **.NET 5 Desktop Runtime x64**

我服，这你也关，你那个链接自动跳的是5.0.2的版本，64位 32位都不行，我自己搜的5.0.0才行，我提示一下就关了？行，算我多嘴

**Comment by avboy1337** [comment]
最新的可以编译OK？

**Comment by xuanwoa** [comment]
+1，都有这个问题，为啥要关闭？

**Comment by netch-org** [comment]
https://t.me/netch_channel/11

**Comment by xuanwoa** [comment]
试过了，安装了5.0.8或者5.0.0 .net runtime x64都还是报错让安装

**Comment by chsbuffer** [comment]
.NET 运行时安装程序文件名里带 Desktop 的才是正确的，否则装上后会提示你请安装 WindowsDesktop Framework，眼神不好使、看不懂英语请不要用。

**Comment by chsbuffer** [comment]
欢迎实现 .NET apphost 支持自动安装运行时并向 dotnet/runtime 发送拉取请求
