### ISSUE TITLE
建议新版本恢复1.82版本有的网页代理和全局代理这几个模式

### ISSUE THREAD

**Issue by weiShaoY** [netchx/netch#726]
您好
  本人用这个软件快两年了，最近更新了到了1.87发现模式全改了，想代理游览器都不行，只好回退到了1.82，不知道您们团队可否在新版本上恢复网页代理和全局代理这几个模式啊，另外就是所有模式能否弄成中英文对照的啊，我们英语不好的得一个个去翻译，有点麻烦，恳求了。

**Comment by chsbuffer** [comment]
网页代理模式会在 Netch v2 回归
v1 没有计划做模式多语言

**Comment by weiShaoY** [comment]
> 网页代理模式会在 Netch v2 回归
> v1 没有计划做模式多语言

好的，感谢
