### ISSUE TITLE
Windows Defender误报毒

### ISSUE THREAD

**Issue by AkihaDesu** [netchx/netch#727]
![屏幕截图 2021-08-07 124920](https://user-images.githubusercontent.com/54067488/128588319-21cf9e1d-9d06-4709-b21c-539323e79363.png)

**Comment by netch-org** [comment]
我们目前无法解决杀毒软件误报问题

**Comment by avboy1337** [comment]
可以尝试去掉压缩壳

**Comment by avboy1337** [comment]
跪求大神开源依赖组件。
