### ISSUE TITLE
进程模式打不开部分站点？

### ISSUE THREAD

**Issue by Cirooo** [netchx/netch#729]
由于我玩那个游戏是通过网页启动，原本我给firefox是挂了v2rayN的端口，netch使用IP规则分析游戏的IP列表之后生效。
现在由于我架设的vps线路质量不好，打算购买另外的线路服务给游戏用。如果说netch启动时设置的socks5或者http端口可以全局接管流量，我还不需要用进程模式，现在的情况是，我一步步按照进程模式添加规则，就发现需要用到的Google打不开。
Firefox提示这个
----------------------------------------------------------------------------------------------------------------------------------------
Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to www.google.com because this website requires a secure connection.

What can you do about it?

www.google.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.
----------------------------------------------------------------------------------------------------------------------------------------
同时，我在通过v2rayN的另一个浏览器是可以访问的，原先firefox使用它的端口来访问也OK。
文字比较罗嗦，主要是想准确描述这个情况。那么，有什么办法是可以让netch满足接管firefox跟游戏的网络请求？
进程模式：目前只操作到firefox，游戏帐号就没法登录了（因为网站使用了Google的验证），后续还有没有别的验证手段还不清楚。
IP模式：原本我是配合v2rayN两边同时来，但后续我v2rayN走我的vps，netch走游戏的，google的IP不可控，我也没法添加规则。

**Comment by chsbuffer** [comment]
根据你的使用场景建议放弃使用 Netch
