### ISSUE TITLE
反馈2个bug，一个是添加服务器须关闭软件重新进入才能显示，另一个是by pass lan china全局

### ISSUE THREAD

**Issue by AmberisMyShiba** [netchx/netch#73]
**错误描述**
1、初次使用，添加Vmess服务器后，添加的服务器不会出现，重启后才会出现
2、使用模式 by pass LAN and China 打开浏览器后发现是全局代理，国内的ip也是通过代理的

**复现步骤**
1. 打开 Netch 软件
2. 添加vmess服务器并保存
3.服务器下拉框中没有新添加的服务器
4.关闭软件退出后重新进入，新添加的服务器才出现

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
 - 操作系统：[例如 Windows 10 专业版 64 位]
 - 软件版本：[例如 1.2.2-STABLE 64 位]

**额外信息**

**Comment by ghost** [comment]
VMess 的问题交给 @tindy2013 处理

你 Bypass LAN and China 应该是用在 VMess 代理上的吧？是的话，那也交给 @tindy2013 处理

**Comment by tindy2013** [comment]
![image](https://user-images.githubusercontent.com/49061470/63763132-b1158b80-c8f6-11e9-83d0-6aa7970522bf.png)
测试正常

**Comment by AmberisMyShiba** [comment]
@tindy2013 用浏览器打开ip111.cn，贴测试结果

**Comment by tindy2013** [comment]
实测未能绕过。
由于 V2Ray-Core 不使用 ACL 文件进行分流，将引入 GeoSite。请等待更新。

**Comment by tindy2013** [comment]
[Debug.zip](https://github.com/NetchX/Netch/files/3547070/Debug.zip)
这个测试 Build 已修复上述问题

**Comment by ghost** [comment]
请尝试最新的 1.2.4 版本
