### ISSUE TITLE
tun2socks start failed - Failed to open registry key...

### ISSUE THREAD

**Issue by Raywl** [netchx/netch#733]
系统版本：
Netch v1.8.7
Win7 Ultimate SP1 补丁齐
.Net和Run time已安装

模式2（指定IP路由）启动出错：
[Wintun] WintunSetAdapterName: Failed to open registry key System\CurrentControlSet\Enum\ROOT\NET\0000: 拒绝访问。 <Code 0x00000005>
[Wintun] CreateAdapter: Failed to set adapter name to aioCloud
[tun2socks][newTUN][tun.CreateTUN] Error creating interface: Access is denied

已尝试，然并卵：1. 用管理员启动Netch.exe
2. 用管理员启动CMD，然后用命令行启动Netch.exe
已搜索Solved issues，无果，求助，谢谢！

**Comment by chsbuffer** [comment]
并非 Windows 10 1809 及以上且无法复现的问题不会受到支持和进一步调查。你可以尝试在安全软件中排除 Netch 目录 或 [升级到更安全，个性化的 Windows 10](https://www.microsoft.com/en-us/software-download/windows10)
