### ISSUE TITLE
功能：使“服务器“、”模式“栏可以键入字符进行搜索。

### ISSUE THREAD

**Issue by wc7086** [netchx/netch#734]
服务器或规则太多不容易找，希望能添加类似下图中的搜索功能。
![gn](https://user-images.githubusercontent.com/74053663/130048787-10f48232-3242-41b1-9686-e81256cc2f67.gif)

**Comment by backed80405** [comment]
以前的一个版本记得确实是已经有了这个功能的，后来没了。

**Comment by wc7086** [comment]
@chsbuffer 麻烦重新开一下这个issue
