### ISSUE TITLE
关于加速Minecraft (Java)的问题

### ISSUE THREAD

**Issue by shuntou** [netchx/netch#742]
### Describe the bug

先启动Netch再打开游戏无网络连接,必须先打开Minecraft (Java)游戏再启动Netch.

### To Reproduce

1.启动Netch
2.打开游戏Minecraft (Java)

### CAPTCHA

- [X] Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.

### Log

[2021-08-29 23:27:38][Information] 内置驱动版本: 1.6.0.7
[2021-08-29 23:27:38][Information] 系统驱动版本: 1.6.0.7
[2021-08-29 23:29:49][Information] Stop Main Controller
[2021-08-29 23:32:00][Information] Start MainController: VMess [0]Minecraft (Java)
[2021-08-29 23:32:00][Debug] Server Information: VMess auto + ws + none + tls
[2021-08-29 23:32:00][Debug] Running Processes: 
\SystemRoot\System32\smss.exe
C:\Program Files\Common Files\Apple\Mobile Device Support\AppleMobileDeviceService.exe
C:\Program Files\Bonjour\mDNSResponder.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\Google\Update\1.3.36.102\GoogleCrashHandler.exe
C:\Program Files (x86)\Google\Update\1.3.36.102\GoogleCrashHandler64.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsTray.exe
C:\Users\tooka\AppData\Roaming\Netch\Netch.exe
C:\Program Files\iTunes\iTunesHelper.exe
D:\Users\tooka\AppData\Roaming\baidu\BaiduNetdisk\YunDetectService.exe
C:\Program Files (x86)\Common Files\Java\Java Update\jusched.exe
C:\Program Files\iPod\bin\iPodService.exe
C:\Users\tooka\AppData\Roaming\.pcl\Plain Craft Launcher 2.exe
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsDaemon.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\usysdiag.exe
C:\Program Files\Java\jre1.8.0_301\bin\javaw.exe
C:\Users\tooka\AppData\Roaming\.minecraft\versions\Fa♂Q\LabyMod\spotify\SpotifyAPI.exe

### Environment

```txt
Windows 7 Service Pack 1 (SP1)
```

**Comment by netch-org** [comment]
https://github.com/netchx/netch/issues/360#issuecomment-687856255
