### ISSUE TITLE
tun2socks.bin can not compile ok

### ISSUE THREAD

**Issue by avboy1337** [netchx/netch#743]
### Describe the bug

file of main.go from tun2socks is empyt

```
package main

func main() {

}
```
dear master , really hoping could opensource  tun2socks

### To Reproduce

None

### CAPTCHA

- [X] Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.

### Log

None

### Environment

```txt
windows10
```

**Comment by netch-org** [comment]
Since we are using some private code, we are not uploading its source code at the moment. We are still working on it and will upload it as soon as the culling is done
