### ISSUE TITLE
能否支持进程模式，不同进程用不同ip代理？

### ISSUE THREAD

**Issue by baofengqqwwff** [netchx/netch#753]
如题，或者别的方式做到不同程序用不同ip代理也可以

**Comment by taoletsgo** [comment]
目前我用到的一个办法是，clash tun模式下，观察软件进程的ip/32或者DOMAIN-SUFFIX域名，自己添加对应代理规则就行；如果同时开启netch，可对netch上的节点ip/32设置direct，这样互不干扰、
个人觉得，netch还是专一点比较好，多进程多ip真的容易出bug

**Comment by ghost** [comment]
不会受到支持
