### ISSUE TITLE
Socks5不能保存用户密码

### ISSUE THREAD

**Issue by GPhantomCN** [netchx/netch#756]
系统1 : Win10 LTSC
系统2 : Win10 20H1
系统3 : Win10 20H2
Netch版本：1.8.7

问题：手动添加Socks5服务器信息（Socks5有用户、密码认证），点击保存后第一次可以用。切换线路或者退出程序后，再次连接服务器就会报错。并且编辑该服务信息会发现保存的用户密码全没了，在软件后台直接修改config.json文件，添加`user`和`pass`字段也没有用。望修复。

-----

`2021/09/10 21:45:23 tcp:***.**.**.***:57095 rejected  v2ray.com/core/proxy/socks: invalid username or password`

-----

**Comment by chsbuffer** [comment]
baf3b39dd3a327f9c92598f587845b5b05b7b426
