### ISSUE TITLE
希望能够支持vless的两个Flow流控选项：xtls-rprx-direct和xtls-rprx-origin

### ISSUE THREAD

**Issue by wangyu1314** [netchx/netch#757]
大佬的程序很好，现在是我的主用，希望能够支持vless的两个Flow流控选项：xtls-rprx-direct和xtls-rprx-origin，并且能够在设置里进行选择，非常感谢。

**Comment by wangyu1314** [comment]
大佬的程序很好，现在是我的主用，希望能够支持vless的两个Flow流控选项：xtls-rprx-direct和xtls-rprx-origin，并且能够在设置里进行选择，非常感谢。

**Comment by chsbuffer** [comment]
Flow 是输入框，自己填
核心在平台上不支持的协议就是不支持，Netch 只是调用核心
