### ISSUE TITLE
题外话：出于安全考虑，有没有隔离传统加速器，使之不运行在主环境却达到加速目的办法？

### ISSUE THREAD

**Issue by lb-chc** [netchx/netch#759]
因为线路并不好找，试错成本很高，针对不同游戏可能还要不同线路？（或者对于大陆只需要一个好线路的HK主机就行了？）

如果能让传统游戏加速器运行在虚拟机或另一台主机中的某种软路由中，且控制传入它的流量（只传入netch筛出的游戏流量），好像就可以确保安全性，让加速器没机会过滤我的其他流量，同时保证主环境里没有国产软件

但实践上，关键在于不能指望厂商推出专用固件，而是让运行在win主机中的exe加速器接收来自另一台win主机中游戏的数据并代理，这样才能避免厂商的针对性优化，和写作傻瓜化读作黑盒化的不可控危险性？

**Comment by netch-org** [comment]
没有
