### ISSUE TITLE
当代理服务器为ipv6地址时会启动失败

### ISSUE THREAD

**Issue by rainingNya** [netchx/netch#76]
**错误描述**
当代理服务器为ipv6地址时会启动失败
**复现步骤**
 1.打开 Netch 软件
 2.添加一个IPv6地址的socks5代理服务器
 3.启动

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
 - 操作系统：[Windows 10 专业工作站版 64 位]
 - 软件版本：[1.2.3-STABLE 64 位]

**额外信息**
 redirector.log
  [WSAStringToAddress] Failed, err=10022Usage: Redirector.exe -r IP:port [-p "<Process Name>"] 
  [-username <Username>] [-password <Password>]

**Comment by ghost** [comment]
当前没有做 IPv6 支持
