### ISSUE TITLE
开了aiodns浏览器还是会走本地连接的DNS

### ISSUE THREAD

**Issue by xugui0821** [netchx/netch#760]
### 错误描述

路由器上装了个adguardhome，本地连接设置的dns也是adguardhome，开了netch刚开始正常，过一会后谷歌之类被墙的就打不开了；用nslookup测试了几十次返回的都是aioCloud，nslookup时adguardhome日志也没有记录，但是只要用浏览器打开任意网页adguardhome上就有解析记录，浏览器用的也是adguardhome的结果，导致谷歌什么的都打不开，测试了chrome edge ie都一样。
![1](https://user-images.githubusercontent.com/21220256/133937168-67fc3f65-195f-4d8b-9c5a-18c97bf6e368.jpg)
![2](https://user-images.githubusercontent.com/21220256/133937171-a952f70f-5ab1-4c87-91ac-8e04773f2dd4.jpg)
![3](https://user-images.githubusercontent.com/21220256/133937239-370d4c56-5f9f-40d4-8e4e-776a10057f20.jpg)
![4](https://user-images.githubusercontent.com/21220256/133937240-b625a2d0-5119-48cb-b6f0-327f149df1a0.jpg)

### 复现步骤

1.打开netch
2.用chrome打开任意网页

### 日志

[2021-09-19 17:43:06][Information] Netch Version: NetchX/Netch@1.8.8
[2021-09-19 17:43:06][Information] OS: Microsoft Windows NT 10.0.19043.0
[2021-09-19 17:43:06][Information] SHA256: 149eb2ecce5f04367ebc02c8aa6b4c8c371964e430894e026307400a29893e14
[2021-09-19 17:43:06][Information] System Language: zh-CN
[2021-09-19 17:43:06][Debug] Third-party Drivers:
ACE-BASE [ACE-BASE]()
	\??\C:\WINDOWS\system32\drivers\ACE-BASE.sys
ACE-GAME [ACE-GAME]()
	\??\C:\WINDOWS\system32\drivers\ACE-GAME.sys
AliPaladin [AliPaladin]()
	\??\C:\WINDOWS\system32\drivers\AliPaladin64.sys
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\WINDOWS\system32\drivers\amdgpio2.sys
AMD GPIO Client Driver [AMD GPIO Client Driver]((C)2012-2016 Advanced Micro Devices, INC.)
	C:\WINDOWS\system32\drivers\amdgpio3.sys
AMD PSP Service [AMD PSP Service](Copyright (c) 2013 - 2017 Advanced Micro Devices, Inc.)
	C:\WINDOWS\system32\drivers\amdpsp.sys
AMDRyzenMasterDriver [AMDRyzenMasterDriver]()
	\??\C:\Program Files\AMD\RyzenMaster\bin\AMDRyzenMasterDriver.sys
AppEx Networks Accelerator LWF [AppEx Networks Accelerator LWF](© AppEx Networks Corporation.)
	C:\WINDOWS\system32\DRIVERS\appexDrv.sys
CimFS [CimFS]()
	C:\WINDOWS\system32\drivers\CimFS.sys
Ext2 File System [Ext2 File System]()
	\??\C:\WINDOWS\system32\Drivers\Ext2Fsd.sys
Game Controller Mapper [Game Controller Mapper](Copyright (C) 2016-2021)
	C:\WINDOWS\system32\drivers\hidgamemap.sys
Huorong Internet Security Devmon Kext [Huorong Internet Security Devmon Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\hrdevmon_win10.sys
Huorong Network Security Firewall Core Kext (WFP) [Huorong Network Security Firewall Core Kext (WFP)](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\hrwfpdrv_win10.sys
ShunWang Virtual Audio Devi [ShunWang Virtual Audio Devi]()
	C:\WINDOWS\system32\drivers\swvad.sys
kpzs Support Driver [kpzs Support Driver]()
	\??\C:\kpzsttmnq\vbox\kpzsDrv.sys
Logitech USB Surround Filter Driver (LGS) [Logitech USB Surround Filter Driver (LGS)](© 2004-2016 Logitech.  All rights reserved.)
	C:\WINDOWS\system32\drivers\ladfGSS.sys
LdBoxDrv [LdBoxDrv]()
	\??\C:\Program Files\dnplayerext2\LdBoxDrv.sys
Logitech Gaming Virtual Bus Enumerator Driver [Logitech Gaming Virtual Bus Enumerator Driver](© 2004-2012 Logitech.  All rights reserved.)
	C:\WINDOWS\system32\drivers\LGBusEnum.sys
Logitech CPU Core Tempurature [Logitech CPU Core Tempurature]()
	\??\C:\Program Files\Logitech Gaming Software\Drivers\LgCoreTemp\lgcoretemp.sys
Logitech Translation Layer Driver (LGS) [Logitech Translation Layer Driver (LGS)](© 1999-2016 Logitech.  All rights reserved.)
	C:\WINDOWS\system32\drivers\LGJoyXlCore.sys
Logitech Gamepanel Virtual HID Device Driver [Logitech Gamepanel Virtual HID Device Driver](© 2004-2012 Logitech.  All rights reserved.)
	C:\WINDOWS\system32\drivers\LGVirHid.sys
MiServiceDaemon [MiServiceDaemon]()
	\??\C:\Program Files (x86)\Timi Personal Computing\MiService\3.0.0.318\Drivers\MiServiceDaemon.sys
VPN Client Device Driver - VPN [VPN Client Device Driver - VPN](Copyright (C) 2012-2015 SoftEther VPN Project. All Rights Reserved.)
	C:\WINDOWS\system32\drivers\Neo_VPN.sys
Netease UU TAP-Win32 Adapter V9.21 [Netease UU TAP-Win32 Adapter V9.21](OpenVPN Technologies, Inc.)
	C:\WINDOWS\system32\drivers\Netease_UU_TAP_0921.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\WINDOWS\system32\drivers\netfilter2.sys
NetGroup Packet Filter Driver [NetGroup Packet Filter Driver](Copyright © 2010-2013 Riverbed Technology, Inc. Copyright © 2005-2010 CACE Technologies. Copyright © 1999-2005 NetGroup, Politecnico di Torino.)
	C:\WINDOWS\system32\drivers\npf.sys
PassGuard [PassGuard]()
	\??\C:\WINDOWS\system32\drivers\PassGuard_x64.sys
PECKbdProtector [PECKbdProtector]()
	\??\C:\WINDOWS\system32\drivers\PECKP_x64.SYS
QqGameMasterControl [QqGameMasterControl]()
	\??\C:\WINDOWS\system32\drivers\QMTgpNetflow764.sys
SAMSUNG RAPID Mode Disk Filter Driver [SAMSUNG RAPID Mode Disk Filter Driver](© Samsung Electronics Co., Ltd.. All rights reserved.)
	C:\WINDOWS\system32\DRIVERS\SamsungRapidDiskFltr.sys
SamsungRapidFSFltr [SamsungRapidFSFltr](© Samsung Electronics Co., Ltd.. All rights reserved.)
	C:\WINDOWS\system32\DRIVERS\SamsungRapidFSFltr.sys
savitar [savitar](Copyright © NetFilterSDK.com)
	C:\WINDOWS\system32\drivers\savitar.sys
Scp Virtual Bus Driver [Scp Virtual Bus Driver](Copyright Â© 2012, 2013 Scarlet.Crush Productions. All rights reserved.)
	C:\WINDOWS\system32\drivers\ScpVBus.sys
SWVir Enumerator Service [SWVir Enumerator Service]()
	C:\WINDOWS\system32\drivers\SWVir.sys
Huorong Network Security Core Kext [Huorong Network Security Core Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\sysdiag_win10.sys
UIM Bus Controller [UIM Bus Controller]()
	C:\WINDOWS\system32\drivers\uimbus.sys
UIM Direct Device Image Plugin [UIM Direct Device Image Plugin]()
	C:\WINDOWS\system32\drivers\uimdevim.sys
Kiwitap USB Monitor Service [Kiwitap USB Monitor Service](Copyright (C) 2009-2019 Oracle Corporation)
	C:\WINDOWS\system32\DRIVERS\VBoxUSBMon.sys
Nefarius Virtual Gamepad Emulation Service [Nefarius Virtual Gamepad Emulation Service]((C) 2016-2020 Nefarius Software Solutions e.U.)
	C:\WINDOWS\system32\drivers\ViGEmBus.sys
Wintun [Wintun](Copyright © 2018-2021 WireGuard LLC. All Rights Reserved.)
	C:\WINDOWS\system32\DRIVERS\wintun.sys
xfilter [xfilter](Copyright © NetFilterSDK.com)
	C:\WINDOWS\system32\drivers\xfilter.sys
XLGuard Driver [XLGuard Driver]()
	C:\WINDOWS\system32\drivers\XLGuard.sys
Xunlei WFP Driver [Xunlei WFP Driver]()
	C:\WINDOWS\system32\drivers\xlwfp.sys
XunYouFilter [XunYouFilter](Copyright @ XunYou.com)
	C:\WINDOWS\system32\drivers\XunYouFilter.sys
ZeroTier Virtual Port [ZeroTier Virtual Port](ZeroTier, Inc., OpenVPN Technologies, Inc.)
	C:\WINDOWS\system32\drivers\zttap300.sys
WinRing0_1_2_0 [WinRing0_1_2_0]()
	\??\C:\TrafficMonitor\LibreHardwareMonitorLib.sys
[2021-09-19 17:43:09][Information] Github 最新发布版本: 1.8.7
[2021-09-19 17:43:09][Information] 目前是最新版本
[2021-09-19 17:43:21][Information] Start MainController: SS [2]Bypass LAN and China
[2021-09-19 17:43:22][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2021-09-19 17:43:22][Information] 自带 wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2021-09-19 17:43:22][Information] 系统 wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2021-09-19 17:43:23][Debug] Running Processes: 
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsDaemon.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\usysdiag.exe
C:\Users\Administrator\AppData\Roaming\Desktoplite\360DesktopService64.exe
C:\Program Files (x86)\Bonjour\mDNSResponder.exe
C:\Program Files\Huawei\HMS Core\HMSCoreService.exe
C:\Program Files (x86)\Common Files\Adobe\AdobeGCClient\AGMService.exe
C:\Program Files\Fastlink\cpcsvr.exe
C:\Program Files (x86)\Common Files\Macrovision Shared\FlexNet Publisher\FNPLicensingService.exe
C:\Program Files\Parsec\pservice.exe
C:\Program Files (x86)\pinduoduo\2.4.7.21\PddCoreService.exe
C:\Program Files (x86)\Timi Personal Computing\MiService\3.0.0.318\MiService.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files\Everything\Everything.exe
C:\Program Files (x86)\AlibabaProtect\1.0.70.446\AlibabaProtect.exe
C:\Program Files\Logitech Gaming Software\Drivers\APOService\LogiRegistryService.exe
C:\Program Files (x86)\alipay\aliedit\5.1.0.3754\secbizsrv.exe
C:\Program Files (x86)\alipay\aliedit\5.1.0.3754\pcas.exe
C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe
C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe
C:\Program Files (x86)\Alibaba\wwbizsrv\wwbizsrv.exe
C:\Program Files (x86)\MSI\Live Update\MSI_LiveUpdate_Service.exe
C:\Program Files (x86)\Origin\OriginWebHelperService.exe
C:\Program Files (x86)\ToDesk\ToDesk_Service.exe
C:\Program Files\Parsec\parsecd.exe
C:\Program Files\Huawei\HMS Core\HMSCoreContainer.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\PopBlock.exe
C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe
C:\TrafficMonitor\TrafficMonitor.exe
C:\Program Files (x86)\ToDesk\ToDesk.exe
C:\Program Files (x86)\alipay\aliedit\5.1.0.3754\aliwssv.exe
C:\Program Files\WindowsApps\Microsoft.YourPhone_1.21072.161.0_x64__8wekyb3d8bbwe\YourPhone.exe
C:\Program Files\Common Files\microsoft shared\ink\TabTip.exe
C:\Program Files (x86)\pinduoduo\2.4.7.21\PddService.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsTray.exe
C:\Program Files\Logitech Gaming Software\LCore.exe
C:\Program Files (x86)\Samsung\Samsung Magician\SamsungMagician.exe
C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe
C:\Program Files\Logitech Gaming Software\ArxApplets\Discord\logitechg_discord.exe
C:\Program Files (x86)\Samsung\RAPID\CacheFilter\SamsungRapidApp.exe
C:\Users\Administrator\AppData\Local\Microsoft\OneDrive\OneDrive.exe
C:\Program Files (x86)\Tencent\TIM\Bin\TIM.exe
C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper64.exe
C:\Program Files\Fastlink\fastlink.exe
C:\Users\Administrator\AppData\Roaming\Desktoplite\360DesktopLite64.exe
C:\Program Files (x86)\Tencent\TIM\Bin\TXPlatform.exe
C:\Program Files (x86)\Tencent\TIM\Bin\QQExternal.exe
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
C:\PROGRA~1\SERVER~1\AppexAcceleratorUI.exe
C:\Program Files\WindowsApps\Microsoft.WindowsStore_12107.1001.15.0_x64__8wekyb3d8bbwe\WinStore.App.exe
C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.2103.8.0_x64__8wekyb3d8bbwe\Calculator.exe
C:\Program Files (x86)\Origin\OriginThinSetupInternal.exe
C:\Program Files (x86)\AlibabaProtect\1.0.70.446\AlibabaprotectUI.exe
C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.721.9022.0_x64__8wekyb3d8bbwe\GameBar.exe
C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.721.9022.0_x64__8wekyb3d8bbwe\GameBarFTServer.exe
C:\Program Files (x86)\Tencent\WeChat\WeChat.exe
C:\Users\Administrator\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\XWeb\348\extracted\WeChatBrowser.exe
C:\Users\Administrator\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\ThumbPlayer\3132\extracted\WeChatPlayer.exe
C:\Users\Administrator\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\XWeb\348\extracted\WeChatApp.exe
C:\Program Files\Notepad++\notepad++.exe
C:\Program Files\WeGame\wegame.exe
C:\Program Files\WeGame\TCLS\tcls_core.exe
C:\Program Files\WeGame\apps\rail\rail.exe
C:\Program Files\WeGame\apps\pallas\pallas.exe
C:\Program Files\WeGame\QBBlinkTrial\browser.exe
d:\wegame\wegameapps\英雄联盟\riot client\riotclientservices.exe
d:\wegame\wegameapps\英雄联盟\cross\core\stable\crossproxy.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\LeagueCrashHandler.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\FeedBack\FeedBack.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\LeagueClientUx.exe
C:\Program Files\AntiCheatExpert\SGuard\x64\SGuardSvc64.exe
D:\Wegame\WeGameApps\英雄联盟\LeagueClient\LeagueClientUxRender.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\NetworkAssist\xunyou\yxqxunyou.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\NetworkAssist\QM\QMLolAssist.exe
C:\Program Files (x86)\yxq_nethelper\XY_YXQ_Nethelper.exe
C:\Program Files\WindowsApps\45479liulios.17062D84F7C46_2.6.6.0_x64__p7pnf6hceqser\Snipaste.exe
D:\ssr\Netch\Netch.exe
[2021-09-19 17:43:25][Information] 流量统计进程: (20740)Shadowsocks
[2021-09-19 20:43:55][Information] Stop Main Controller
[2021-09-19 20:43:57][Information] Start MainController: SS [2]Bypass LAN and China
[2021-09-19 20:43:57][Debug] Server Information: SS chacha20-ietf-poly1305 + 
[2021-09-19 20:43:57][Information] 自带 wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2021-09-19 20:43:57][Information] 系统 wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2021-09-19 20:43:59][Debug] Running Processes: 
C:\Users\Administrator\AppData\Roaming\Desktoplite\360DesktopService64.exe
C:\Program Files (x86)\Bonjour\mDNSResponder.exe
C:\Program Files\Huawei\HMS Core\HMSCoreService.exe
C:\Program Files (x86)\Common Files\Adobe\AdobeGCClient\AGMService.exe
C:\Program Files\Fastlink\cpcsvr.exe
C:\Program Files (x86)\Common Files\Macrovision Shared\FlexNet Publisher\FNPLicensingService.exe
C:\Program Files\Parsec\pservice.exe
C:\Program Files (x86)\pinduoduo\2.4.7.21\PddCoreService.exe
C:\Program Files (x86)\Timi Personal Computing\MiService\3.0.0.318\MiService.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files\Everything\Everything.exe
C:\Program Files (x86)\AlibabaProtect\1.0.70.446\AlibabaProtect.exe
C:\Program Files\Logitech Gaming Software\Drivers\APOService\LogiRegistryService.exe
C:\Program Files (x86)\alipay\aliedit\5.1.0.3754\secbizsrv.exe
C:\Program Files (x86)\alipay\aliedit\5.1.0.3754\pcas.exe
C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe
C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe
C:\Program Files (x86)\Alibaba\wwbizsrv\wwbizsrv.exe
C:\Program Files (x86)\MSI\Live Update\MSI_LiveUpdate_Service.exe
C:\Program Files (x86)\Origin\OriginWebHelperService.exe
C:\Program Files (x86)\ToDesk\ToDesk_Service.exe
C:\Program Files\Parsec\parsecd.exe
C:\Program Files\Huawei\HMS Core\HMSCoreContainer.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\PopBlock.exe
C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe
C:\TrafficMonitor\TrafficMonitor.exe
C:\Program Files (x86)\ToDesk\ToDesk.exe
C:\Program Files (x86)\alipay\aliedit\5.1.0.3754\aliwssv.exe
C:\Program Files\WindowsApps\Microsoft.YourPhone_1.21072.161.0_x64__8wekyb3d8bbwe\YourPhone.exe
C:\Program Files\Common Files\microsoft shared\ink\TabTip.exe
C:\Program Files (x86)\pinduoduo\2.4.7.21\PddService.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsTray.exe
C:\Program Files\Logitech Gaming Software\LCore.exe
C:\Program Files (x86)\Samsung\Samsung Magician\SamsungMagician.exe
C:\Program Files\Realtek\Audio\HDA\RtkNGUI64.exe
C:\Program Files\Logitech Gaming Software\ArxApplets\Discord\logitechg_discord.exe
C:\Program Files (x86)\Samsung\RAPID\CacheFilter\SamsungRapidApp.exe
C:\Users\Administrator\AppData\Local\Microsoft\OneDrive\OneDrive.exe
C:\Program Files (x86)\Tencent\TIM\Bin\TIM.exe
C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper64.exe
C:\Program Files\Fastlink\fastlink.exe
C:\Users\Administrator\AppData\Roaming\Desktoplite\360DesktopLite64.exe
C:\Program Files (x86)\Tencent\TIM\Bin\TXPlatform.exe
C:\Program Files (x86)\Tencent\TIM\Bin\QQExternal.exe
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
C:\PROGRA~1\SERVER~1\AppexAcceleratorUI.exe
C:\Program Files\WindowsApps\Microsoft.WindowsStore_12107.1001.15.0_x64__8wekyb3d8bbwe\WinStore.App.exe
C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.2103.8.0_x64__8wekyb3d8bbwe\Calculator.exe
C:\Program Files (x86)\Origin\OriginThinSetupInternal.exe
C:\Program Files (x86)\AlibabaProtect\1.0.70.446\AlibabaprotectUI.exe
C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.721.9022.0_x64__8wekyb3d8bbwe\GameBar.exe
C:\Program Files\WindowsApps\Microsoft.XboxGamingOverlay_5.721.9022.0_x64__8wekyb3d8bbwe\GameBarFTServer.exe
C:\Program Files (x86)\Tencent\WeChat\WeChat.exe
C:\Users\Administrator\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\XWeb\348\extracted\WeChatBrowser.exe
C:\Users\Administrator\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\ThumbPlayer\3132\extracted\WeChatPlayer.exe
C:\Program Files\Notepad++\notepad++.exe
C:\Program Files\WeGame\wegame.exe
C:\Program Files\WeGame\TCLS\tcls_core.exe
C:\Program Files\WeGame\apps\rail\rail.exe
C:\Program Files\WeGame\apps\pallas\pallas.exe
C:\Program Files\WeGame\QBBlinkTrial\browser.exe
d:\wegame\wegameapps\英雄联盟\riot client\riotclientservices.exe
d:\wegame\wegameapps\英雄联盟\cross\core\stable\crossproxy.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\LeagueCrashHandler.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\FeedBack\FeedBack.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\LeagueClientUx.exe
C:\Program Files\AntiCheatExpert\SGuard\x64\SGuardSvc64.exe
D:\Wegame\WeGameApps\英雄联盟\LeagueClient\LeagueClientUxRender.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\NetworkAssist\xunyou\yxqxunyou.exe
d:\wegame\wegameapps\英雄联盟\LeagueClient\NetworkAssist\QM\QMLolAssist.exe
C:\Program Files (x86)\yxq_nethelper\XY_YXQ_Nethelper.exe
C:\Program Files\WindowsApps\45479liulios.17062D84F7C46_2.6.6.0_x64__p7pnf6hceqser\Snipaste.exe
D:\ssr\Netch\Netch.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsDaemon.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\usysdiag.exe
C:\Users\Administrator\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\XWeb\348\extracted\WeChatApp.exe
D:\ssr\Netch\bin\Shadowsocks.exe
[2021-09-19 20:43:59][Information] 流量统计进程: (3320)Shadowsocks 

### 操作环境

```txt
Windows10
Netch1.8.8
```

**Comment by yond36** [comment]
这是控制台的日志

2021/09/19 20:43:55 [tun2socks] Closed
2021/09/19 20:43:55 [tun2socks][UDP][socks][Connect] Handshake failed: read tcp 127.0.0.1:1042->127.0.0.1:2801: wsarecv: An existing connection was forcibly closed by the remote host.
[aiodns][aiodns_dial] TYPE_REST
[aiodns][aiodns_dial] TYPE_ADDR => 127.0.0.1:253
[aiodns][aiodns_dial] TYPE_LIST => D:\ssr\Netch\bin\aiodns.conf
[aiodns][aiodns_dial] TYPE_CDNS => tcp://223.5.5.5:53
[aiodns][aiodns_dial] TYPE_ODNS => tcp://1.1.1.1:53
2021/09/19 20:43:57 [Wintun] WintunCreateAdapter: Creating adapter
2021/09/19 20:43:57 [Wintun] SelectDriver: Using existing driver 0.13
2021/09/19 20:48:08 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 21:03:01 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 21:19:18 [tun2socks][adns] DNS resolution failed: read tcp 127.0.0.1:31189->127.0.0.1:253: i/o timeout
2021/09/19 21:44:58 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 22:10:13 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 22:25:14 [tun2socks][adns] DNS resolution failed: read tcp 127.0.0.1:17593->127.0.0.1:253: i/o timeout
2021/09/19 22:26:43 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 22:50:56 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 23:02:20 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 23:14:54 [tun2socks][adns] DNS resolution failed: read tcp 127.0.0.1:32534->127.0.0.1:253: i/o timeout
2021/09/19 23:14:54 [tun2socks][adns] DNS resolution failed: read tcp 127.0.0.1:32538->127.0.0.1:253: i/o timeout
2021/09/19 23:25:19 [tun2socks][adns] Failed to unpack data: dns: buffer size too small
2021/09/19 23:35:10 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/19 23:59:04 [tun2socks][adns] DNS resolution failed: read tcp 127.0.0.1:1034->127.0.0.1:253: i/o timeout
2021/09/19 23:59:04 [tun2socks][adns] DNS resolution failed: read tcp 127.0.0.1:1036->127.0.0.1:253: i/o timeout
2021/09/20 00:10:27 [tun2socks][adns] DNS resolution failed: read tcp 127.0.0.1:7770->127.0.0.1:253: i/o timeout
2021/09/20 00:15:32 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/20 01:42:43 [tun2socks][UDP][socks][ReceiveTo] Non-existent connection
2021/09/20 01:50:09 [tun2socks][adns] Failed to unpack data: dns: overflow unpacking uint16

**Comment by chsbuffer** [comment]
Netch 目前不支持代理 IPv6
