### ISSUE TITLE
语言设为日语时，UI部分有遮挡

### ISSUE THREAD

**Issue by tasty0tomato** [netchx/netch#761]
### Describe the bug

![Netch_9RR6T4h0Oy](https://user-images.githubusercontent.com/48764449/134328277-12191e23-581c-4f9f-b9ff-7ad988ad601b.png)

### To Reproduce

1. 设置netch语言为日语。

### Log

不太清楚日志在哪里，似乎也并不需要。

### Environment

```txt
Windows 10 Pro 20H2 19042.1237
1.9.0
```

### Additional information

优先级：高

中文界面：
![Netch_kx4fjuLIYg](https://user-images.githubusercontent.com/48764449/134328389-9d44b255-6ff7-454d-976f-fcce351d6353.png)

**Comment by ghost** [comment]
等 2.0 的 WPF 再说吧，1.0 目前不想维护了
