### ISSUE TITLE
The software stucked and “UnsupportedServer”

### ISSUE THREAD

**Issue by Eberron91** [netchx/netch#764]
### Describe the bug

When you turn on both functions at the same time and it get stucked,
当你同时打开这两个功能的时候就卡住了

Stuck in tun2socks
卡在 tun2socks

and “UnsupportedServer”
![1](https://user-images.githubusercontent.com/42966631/135476746-55974013-5a05-4c40-9a40-6b2b353ac149.png)
![2](https://user-images.githubusercontent.com/42966631/135476752-b4e36d81-675e-41ed-94b8-4f8d0c122816.png)
![3](https://user-images.githubusercontent.com/42966631/135476883-0975e6ea-3d8d-461b-b8b1-e964a373d65a.png)
![4](https://user-images.githubusercontent.com/42966631/135476757-7edf7996-2829-4917-afc8-4389dd35acc5.png)

### To Reproduce

1.Open Netch
2.When you have enabled "Mux", then enable "FullCone" and you will get stuck
3.When only "MUX" is enabled, the NAT test will show "UnsupportedServer"

### Log

Can't find it

### Environment

```txt
Windows 10 Enterprise 
Versions:19042.985
```

**Comment by chsbuffer** [comment]
start failed will cause UI hangs is a known issue. the fix will be included in 1.9.1

NAT Test result `Unsupported Server` is proxy protocol issue
