### ISSUE TITLE
远程控制无法连接内网设备

### ISSUE THREAD

**Issue by yyxida** [netchx/netch#767]
### 错误描述

从1.8.x（具体版本不记得了）更新到1.9.1之后，代理到家中ss，无法访问内网win server设备（192.168.2.x），用v2rayn连ss再用netch去连v2rayn发现没有连接到192.168.2.x:3389 的请求。使用1.8.9版本没这个问题，能正常远程，也能看到连接到192.168.2.x:3389 的请求。

### 复现步骤

1.使用netch连接到回家ss并代理远程控制mstsc.exe
2，使用win10自带远程控制，连接到192.168.2.x
3，连接超时

### 日志

[application.log](https://github.com/netchx/netch/files/7284509/application.log)

### 操作环境

```txt
Windows 11 专业工作站版 21H2

netch 1.9.1
```

### 额外信息

![image](https://user-images.githubusercontent.com/22792135/135997375-a5823481-b8a9-466d-a3d3-fb7db8e407e8.png)
能正常链接事的截图

**Comment by ghost** [comment]
最新的 1.9.1 使用了新的 Redirector 模块，但是开发人员 @chsbuffer 对接匆忙，没有做一些选项

参见代码
https://github.com/netchx/netch/blob/master/Netch/Controllers/NFController.cs#L37

将 false 改为 true 即可
