### ISSUE TITLE
屏幕缩放时“速率”标签位置不正确

### ISSUE THREAD

**Issue by JiuLing-zhang** [netchx/netch#769]
### 错误描述

屏幕缩放时“速率”标签位置不正确

![缩放](https://user-images.githubusercontent.com/78294929/136688448-ab4c30c9-52d2-4f10-ad60-f90ab15fac69.png)
![标签位置异常](https://user-images.githubusercontent.com/78294929/136688445-dd64d621-383e-436d-b3c4-da926c03c3a1.png)

### 复现步骤

1、设置屏幕缩放比例（非100%）
2、启动Netch

### 日志

无

### 操作环境

```txt
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎9/‎4
操作系统内部版本	19043.1237
体验	Windows Feature Experience Pack 120.2212.3530.0
```

**Comment by chsbuffer** [comment]
无法复现此问题。
请检查 .NET 运行时是否已更新至最新版本 5.0.10 并停用会改变 GDI 行为的软件如 MacType **等**
