### ISSUE TITLE
无法保存Socks5的用户名及密码

### ISSUE THREAD

**Issue by cupkappu** [netchx/netch#770]
### 错误描述

添加Socks5代理时可以正常使用带用户名与密码的Socks5代理，但无法保存相关用户名以及密码。再次打开的时候用户名和密码会被清空。

### 复现步骤

1. 打开netch
2. 点击Server 添加Socks5代理
3. 填写完毕后（包括用户名与密码）之后点击保存
4. 选择相应服务器后开始服务
5. 关闭Netch，然后再次打开
6. 之前添加的Socks5代理的用户名与密码信息已经丢失

### 日志

无特殊日志

### 操作环境

```txt
Windows 10
```

**Comment by chsbuffer** [comment]
请使用最新版本
