### ISSUE TITLE
1.9.2显示HTTP：time out NAT：noUDP

### ISSUE THREAD

**Issue by ax003** [netchx/netch#774]
### Describe the bug

服务器是vless+tcp+xtls，服务器端xray更新到1.4.5。
用1.9.1一切正常，更新到1.9.2出现上述错误。
目前已回退到1.9.1

### To Reproduce

每次

### Log

log无报错

### Environment

```txt
win11
netch 1.9.2
```

**Comment by DSbajRv5Ol4X** [comment]
设置-V2Ray-TLS AllowInsecure ，把这个勾给勾上。

**Comment by reizhi** [comment]
socks5 连接本机的 clash 也会出现同样的问题，并且导致 clash 所有节点都超时。
退回 1.9.1 恢复正常。

**Comment by ghost** [comment]
提供日志

**Comment by sOO006** [comment]
154.38.118.56

**Comment by jeanhello** [comment]
> 设置-V2Ray-TLS AllowInsecure ，把这个勾给勾上。

thanks very much
