### ISSUE TITLE
tun2socks start failed 解决方法

### ISSUE THREAD

**Issue by AZmake** [netchx/netch#779]
### 错误描述

打开 `netchx` 出现 `tun2socks start failed`

### 复现步骤

1、使用win10镜像安装Win10新系统
2、安装360杀毒或者360管家
3、安装 `netchx` 并且打开使用，此时360会弹窗询问是否允许 `C:\Windows\System32\drivers\netfilter32.sys` 运行，点击允许，`netchx` 能正常使用
4、使用360杀毒或者360管家进行查杀，会标记 以下2个文件为驱动病毒
`C:\Windows\System32\drivers\netfilter32.sys`
`C:\WINDOWS\system32\DRIVERS\wintun.sys`

点击修复后，360会备份以上2个文件并且更改这2个文件
5、查杀后再打开`netchx `就会出现 `tun2socks start failed`
6、到360隔离器回复以上2个文件之后 `netchx` 能正常使用

### 日志

无

### 操作环境

```txt
Windows 10 X64
```

**Comment by netch-org** [comment]
I don't know why 360 marks two files with digital signatures as virus files and other unsigned files are not marked ?

Since you're using Windows 10, I suggest you just use Windows Defender. Don't use 360 software

Or, use [Huorong](https://www.huorong.cn)

**Comment by netch-org** [comment]
I would suggest @ChsBuffer to just close the program if it detects 360 exists
