### ISSUE TITLE
SSR随机性无法上网，需要重新启动才可以

### ISSUE THREAD

**Issue by HonorWater** [netchx/netch#78]
**错误描述**
使用SSR节点，采用模式4 （By Lan & China），一开始可以正常上网。但是随机的，大概一小时左右就无法上网，只有重新启动才可。

**信息**
 - 操作系统：Windows 10 专业版 64 位
 - 软件版本：1.2.4-STABLE 64 位

**额外信息**
log如下

 2019-08-29 16:09:20 INFO: listening at 127.0.0.1:2801
Assertion failed: ("libev: fd >= FD_SETSIZE passed to fd_set-based select backend", fd < FD_SETSIZE), file ev_select.c, line 85

**Comment by tindy2013** [comment]
可尝试将 bin/ShadowsocksR.exe 替换为该重新编译的 ShadowsocksR 客户端：[ShadowsocksR.zip](https://github.com/NetchX/Netch/files/3554817/ShadowsocksR.zip)

**Comment by ghost** [comment]
现在 SSR 停止维护了，用的端有点问题（不知道你们怎么弄出闪退问题的，我自己一直用没有出事）

**Comment by HonorWater** [comment]
尝试tindy2013提供的SSR替换了，暂时没有出现之前的报错。
windows下的开发可能遇到不同机器不同情况太多了，就连windows自己都有bug...
