### ISSUE TITLE
更新到1.9.2后，进程模式下导致本地DNS解析全部经过代理。

### ISSUE THREAD

**Issue by chenshaoju** [netchx/netch#780]
### 错误描述

在更新到1.9.2后，进程模式下启动后，导致未位于进程模式下的应用的DNS请求经过DNS代理。

该问题引起国内网站访问速度下降等问题。

### 复现步骤

1.停止Netch的情况下，执行 nslookup 命令： nslookup www.sina.com.cn ，此时可以看到IP为大陆的IP。
2.启动Netch，连接到任意海外服务。
3.再次执行 nslookup www.sina.com.cn ，此时可以看到IP已经变成非大陆的IP。

### 日志

[application_edited.log](https://github.com/netchx/netch/files/7371063/application_edited.log)
[Shadowsocks.log](https://github.com/netchx/netch/files/7371064/Shadowsocks.log)

备注：处于某些因素考虑，application.log 隐藏了应用列表。

### 操作环境

```txt
操作系统版本：Windows 10 Pro 21H1 19043.1288
Netch版本：1.9.2
```

### 额外信息

1.9.2版演示：
![1 9 2_demo](https://user-images.githubusercontent.com/515763/137861968-81deea07-64a4-4d0c-9e90-2d918fbece70.gif)

该问题不存在于1.9.1版本，此问题导致了当遇到 https://github.com/netchx/netch/issues/776 问题时，本地DNS失效的问题。

1.9.1版演示：
![1 9 1_demo](https://user-images.githubusercontent.com/515763/137862727-8758302b-2b0b-42bf-86e5-3825f001f793.gif)

**Comment by ghost** [comment]
是的，你没有搞错。但是这不是 BUG，这是实验性的特性。等 @chsbuffer 推送新的 1.9.3 版本，新的版本将提供选项关闭

**Comment by chenshaoju** [comment]
感谢回复。
