### ISSUE TITLE
开启加速后，点击程序菜单栏的退出按钮直接就退出程序了

### ISSUE THREAD

**Issue by ghost** [netchx/netch#781]
### Describe the bug

开启加速后，右下角任务栏点击退出会提示 `请先点击停止按钮`。但是点开程序点击程序菜单栏里的退出按钮直接就退出了

### To Reproduce

none

### Log

none

### Environment

```txt
版本 1.9.2
```

**Comment by chsbuffer** [comment]
设计如此，预期行为
