### ISSUE TITLE
近期pokemmo 直接进程加速无法登陆，提取了一下雷神的ip规则做出分享。

### ISSUE THREAD

**Issue by jinbasex** [netchx/netch#782]
### 功能描述

# Pokemmo - leigood, 1
116.63.64.204/32
116.63.64.52/32
223.5.5.5/32

https://github.com/micnp/PokemmoIP
恳请作者添加到后续规则更新中

**Comment by ghost** [comment]
请 PR 至 [此仓库](https://github.com/netchx/netchmode)
