### ISSUE TITLE
添加自动检测并提示有没有新的稳定版本在Github发布

### ISSUE THREAD

**Issue by ghost** [netchx/netch#79]
**功能描述**
看到群里有个老哥提的建议不错：客户端在启动时检测有无新稳定版本，并弹出提示。

**额外信息**
提示框建议在有新本的情况下直接弹出来，而且必须点击"我知道了"，才能继续使用，不升级下次继续弹。必须要根治有些人不爱升级的毛病，还总反馈老版本的BUG。

**Comment by ghost** [comment]
建议接受，将在近期开展工作，咕咕咕

**Comment by lyafancn** [comment]
> 建议接受，将在近期开展工作，咕咕咕

咕咕咕出来了吗？
之前加了代理更新订阅和{TUN/TAP )bypass LAN&China编译，真的好用！！AWESOME！

**Comment by BingLingGroup** [comment]
你这是运用自如啊，还 awesome

**Comment by ghost** [comment]
> 建议接受，将在近期开展工作，咕咕咕

这位爸爸。。还咕俺的这个issue吗？我有done的强迫症，想尽快close这个issue。

**Comment by ghost** [comment]
其实，已经做好了吧。但是，没有发布新版本。那么，先 close 了吧
