### ISSUE TITLE
Redirector的原仓库没了

### ISSUE THREAD

**Issue by elmagnificogi** [netchx/netch#793]
### Describe the feature you want

Redirector的原仓库没了
https://github.com/aiocloud/redirector

我想在redirector里面给进程加一个ip屏蔽的特性，某些ip我就想让他屏蔽掉，从而让游戏选择正确的ip。
但是我从main里面编译出来的redirector.bin 虽然能用，特性也ok，但是会出现一上来就全局代理了，无法做到进程过滤，我没找到问题。

所以我想请求一份redirector 对应netch的1.9.2版本的代码，如果可以的话，telgram群里我也问过了，麻烦了

**Comment by netch-org** [comment]
目前 1.9.* 用的就是 main 里的。你的问题，我们不会进行解释

**Comment by elmagnificogi** [comment]
> 目前 1.9.* 用的就是 main 里的。你的问题，我们不会进行解释

能说1.9.2是具体哪个commit嘛？
