### ISSUE TITLE
进行反向代理时无法全局代理

### ISSUE THREAD

**Issue by k-fire** [netchx/netch#799]
### 功能描述

1.搭了一台frp服务器，用来反向连接某台私网主机
2.使用netch连接socks5代理到私网
3.代理动作<绕过规则IP为空>，即全局代理，代理包括私网IP在内
4.连接成功后无法连接任何网络，无论私网还是公网。
与sstap对比发现，sstap可以同时代理私网和公网，可以访问私网中其他主机，也可通过该反向代理连接到互联网。

PS：netch已关闭dns劫持

**Comment by chsbuffer** [comment]
请使用 1.9.3, 该版本修复了使用 Socks5 代理时未绕过服务器地址的问题
