### ISSUE TITLE
我也不知道为什么会出现这样的问题

### ISSUE THREAD

**Issue by CHINASGL** [netchx/netch#80]
**错误描述**
对错误的清晰简洁描述

**复现步骤**
1. 打开 Netch 软件
2. ...

**错误截图**
![1](https://user-images.githubusercontent.com/54720114/64040001-91989000-cb8e-11e9-9b57-a1142f9954bf.PNG)

如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
 - 操作系统：[例如 Windows 7 专业版 64 位]
 - 软件版本：[例如 1.2.6-STABLE 64 位]

**额外信息**

**Comment by CHINASGL** [comment]
还有就是驱动注册失败

**Comment by Hitiko** [comment]
@CHINASGL 这边建议您立刻升级Windows10呢

**Comment by BingLingGroup** [comment]
win7驱动问题参见[中文readme FAQ](https://github.com/NetchX/Netch/blob/master/docs/README.zh-CN.md#%E6%97%A0%E6%B3%95%E8%BF%90%E8%A1%8C)部分有写。

下次提问之前先说明已看过readme。
