### ISSUE TITLE
1.9.3中完全无法使用了

### ISSUE THREAD

**Issue by leanoon** [netchx/netch#801]
### 错误描述

报错，此记录同样出现于Shadowsocks.log
error: 'xchacha20-ietf-poly1305' isn't a valid value for '--encrypt-method <ENCRYPT_METHOD>'

### 复现步骤

打开软件，点击启动，然后报错，按钮还是为“启动”（即并未生效）

### 日志

application.log

[2021-11-14 10:15:28][Information] Netch Version: NetchX/Netch@1.9.3
[2021-11-14 10:15:28][Information] OS: Microsoft Windows NT 10.0.19043.0
[2021-11-14 10:15:28][Information] SHA256: 05f06aa8f199aeb734afffe38fe2b37a2ffd2598bad66595af71cb42b7c48e70
[2021-11-14 10:15:28][Information] System Language: zh-CN
[2021-11-14 10:15:28][Debug] Running Processes: 
C:\Program Files (x86)\360\360zip\360zip.exe
C:\Program Files (x86)\Alibaba\wwbizsrv\wwbizsrv.exe
C:\Program Files (x86)\AlibabaProtect\1.0.23.863\AlibabaProtect.exe
C:\Program Files (x86)\alipay\aliedit\4.0.0.101\pcas.exe
C:\Program Files (x86)\bililive\livehime\3.45.1.2550\plugins\bililive_browser.exe
C:\Program Files (x86)\bililive\livehime\livehime.exe
C:\Program Files (x86)\Common Files\Java\Java Update\jusched.exe
C:\Program Files (x86)\Common Files\Steam\SteamService.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\Foxit Software\Foxit Reader\FoxitProtect.exe
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
C:\Program Files (x86)\Google\Update\1.3.36.112\GoogleCrashHandler.exe
C:\Program Files (x86)\Google\Update\1.3.36.112\GoogleCrashHandler64.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsDaemon.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsTray.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\PopBlock.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\usysdiag.exe
C:\Program Files (x86)\Internet Download Manager\IDMan.exe
C:\Program Files (x86)\MSI\SUPER CHARGER\ChargeService.exe
C:\Program Files (x86)\MSI\SUPER CHARGER\SUPER CHARGER.exe
C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe
C:\Program Files (x86)\SogouInput\9.8.0.3746\SGTool.exe
C:\Program Files (x86)\SogouInput\9.8.0.3746\SogouCloud.exe
C:\Program Files (x86)\Splashtop\Splashtop Software Updater\SSUService.exe
C:\Program Files (x86)\Steam\bin\cef\cef.win7x64\steamwebhelper.exe
C:\Program Files (x86)\Steam\steam.exe
C:\Program Files (x86)\Synology\Assistant\UsbClientService.exe
C:\Program Files (x86)\Tencent\WeChat\WeChat.exe
C:\Program Files (x86)\Thrustmaster\TARGET\TmService.exe
C:\Program Files\Bonjour\mDNSResponder.exe
C:\Program Files\cFosSpeed\cfosspeed.exe
C:\Program Files\cFosSpeed\spd.exe
C:\Program Files\Clash for Windows\Clash for Windows.exe
C:\Program Files\Clash for Windows\resources\static\files\win\x64\clash-win64.exe
C:\Program Files\Common Files\Apple\Mobile Device Support\AppleMobileDeviceService.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Google\Drive File Stream\52.0.6.0\crashpad_handler.exe
C:\Program Files\Google\Drive File Stream\52.0.6.0\GoogleDriveFS.exe
C:\Program Files\Logitech Gaming Software\Drivers\APOService\LogiRegistryService.exe
C:\Program Files\Logitech Gaming Software\LAClient\LAClient.exe
C:\Program Files\Logitech Gaming Software\LCore.exe
C:\Program Files\Logitech\LogiCapture\bin\Service\LogiFacecamService.exe
C:\Program Files\NVIDIA Corporation\NvBroadcast.NvContainer\NvBroadcast.Container.exe
C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe
C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA Share.exe
C:\Program Files\NVIDIA Corporation\ShadowPlay\nvsphelper64.exe
C:\Program Files\obs-studio\bin\64bit\obs64.exe
C:\Program Files\TeamViewer\TeamViewer_Service.exe
C:\Program Files\Thrustmaster\TM Flight Series\drivers\amd64\tmHInstall.exe
C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe
C:\Users\leano\AppData\Local\Microsoft\OneDrive\OneDrive.exe
C:\Users\leano\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\ThumbPlayer\3146\extracted\WeChatPlayer.exe
C:\Users\leano\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\XWeb\470\extracted\WeChatApp.exe
C:\Users\leano\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\XWeb\470\extracted\WeChatBrowser.exe
C:\Users\leano\Desktop\微软模拟飞行2020工具包\Netch\Netch.exe
[2021-11-14 10:15:28][Debug] Third-party Drivers:
AliPaladin [AliPaladin]()
	\??\C:\Windows\system32\drivers\AliPaladin64.sys
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdgpio2.sys
cFosSpeed for faster Internet connections (NDIS 6) [cFosSpeed for faster Internet connections (NDIS 6)](Copyright © Lueders/Winkler 2003-2020)
	C:\Windows\system32\DRIVERS\cfosspeed6.sys
chdrvr01 [chdrvr01](Copyright (c) Robert L. Church 2001-2011)
	C:\Windows\system32\drivers\chdrvr01.sys
chdrvr02 [chdrvr02](Copyright (c) Robert L. Church 2001-2011)
	C:\Windows\system32\drivers\chdrvr02.sys
chdrvr03 [chdrvr03](Copyright (c) Robert L. Church 2001)
	C:\Windows\system32\drivers\chdrvr03.sys
CimFS [CimFS]()
	C:\Windows\system32\drivers\CimFS.sys
Duet Static Bus Enumerator [Duet Static Bus Enumerator](Duet, Inc.)
	C:\Windows\system32\drivers\duetbus.sys
googledrivefs3525 [googledrivefs3525](Copyright (C) 2016 Google, Inc., Copyright (C) 2016 Dokan Project)
	C:\Windows\system32\DRIVERS\googledrivefs3525.sys
Huorong Internet Security Devmon Kext [Huorong Internet Security Devmon Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\hrdevmon_win10.sys
Huorong Network Security Firewall Core Kext (WFP) [Huorong Network Security Firewall Core Kext (WFP)](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\hrwfpdrv_win10.sys
IDMWFP [IDMWFP](Copyright © 1999 - 2018 Tonec Inc.)
	C:\Windows\system32\DRIVERS\idmwfp.sys
LuminonCore WDDM PROXY [LuminonCore WDDM PROXY](Copyright (C) 2015 LuminonCore)
	C:\Windows\system32\drivers\lci_proxywddm.sys
Logitech Gaming Virtual Bus Enumerator Driver [Logitech Gaming Virtual Bus Enumerator Driver](© 2004-2012 Logitech.  All rights reserved.)
	C:\Windows\system32\drivers\LGBusEnum.sys
Logitech CPU Core Tempurature [Logitech CPU Core Tempurature]()
	\??\C:\Program Files\Logitech Gaming Software\Drivers\LgCoreTemp\lgcoretemp.sys
Logitech Translation Layer Driver (LGS) [Logitech Translation Layer Driver (LGS)](© 1999-2016 Logitech.  All rights reserved.)
	C:\Windows\system32\drivers\LGJoyXlCore.sys
Logitech Gamepanel Virtual HID Device Driver [Logitech Gamepanel Virtual HID Device Driver](© 2004-2012 Logitech.  All rights reserved.)
	C:\Windows\system32\drivers\LGVirHid.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
Steam Xbox Controller Enhanced Features Driver [Steam Xbox Controller Enhanced Features Driver]((C) 2020 Valve Corporation)
	C:\Windows\system32\drivers\steamxbox.sys
Huorong Network Security Core Kext [Huorong Network Security Core Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\Windows\system32\DRIVERS\sysdiag_win10.sys
TAP-Windows Adapter V9 [TAP-Windows Adapter V9](OpenVPN Technologies, Inc.)
	C:\Windows\system32\drivers\tap0901.sys
Thrustmaster Bus Enumerator [Thrustmaster Bus Enumerator](©2010 Guillemot Corporation. All rights reserved.)
	C:\Windows\system32\drivers\TmBusEn.sys
Virtual Gamepad Emulation Service [Virtual Gamepad Emulation Service](Copyright (C) Benjamin Höglinger-Stelzer 2016)
	C:\Windows\system32\drivers\ViGEmBus.sys
XLGuard Driver [XLGuard Driver]()
	C:\Windows\system32\drivers\XLGuard.sys
Xunlei WFP Driver [Xunlei WFP Driver]()
	C:\Windows\system32\drivers\xlwfp.sys
ZeroTier One Virtual Port [ZeroTier One Virtual Port](ZeroTier, Inc., OpenVPN Technologies, Inc.)
	C:\Windows\system32\drivers\zttap300.sys
NTIOLib_1_0_3 [NTIOLib_1_0_3]()
	\??\C:\Program Files (x86)\MSI\SUPER CHARGER\NTIOLib_X64.sys
[2021-11-14 10:15:29][Information] Github latest release: 1.9.2
[2021-11-14 10:15:29][Information] Already the latest version
[2021-11-14 10:15:33][Information] Start MainController: SS [0]System.Collections.Generic.Dictionary`2[System.String,System.String]
[2021-11-14 10:15:33][Debug] Server Information: SS xchacha20-ietf-poly1305 + simple-obfs
[2021-11-14 10:15:33][Information] Stop Main Controller

### 操作环境

```txt
设备名称	
处理器	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
机带 RAM	32.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

netch1.9.3版
```

**Comment by chsbuffer** [comment]
已知问题，已修复，请等待新版本
