### ISSUE TITLE
1.9.5

### ISSUE THREAD

**Issue by backed80405** [netchx/netch#809]
### 功能描述

相比以前的，1.9.5怎么体积巨大？解压后还要大
1.9.5 --- 60.4 MB
1.9.4 --- 21 MB
         ...
1.8.9 ---  20.3 MB

**Comment by ksode** [comment]
Netch.exe 就有162MB了，不知道增加了什么。

**Comment by stacknoflow** [comment]
应该是集成了 .NET，经测试无需单独安装 .NET，之前安装的 .NET 卸载后也能运行

**Comment by AmazingDM** [comment]
https://github.com/netchx/netch/blob/2f685a2c6fd8b5f33d3fb232afa5b5c8fc97fcc0/build.ps1#L62
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview#publish-a-single-file-app---sample-project-file
