### ISSUE TITLE
1.9.6 doesn't executed on Windows 10

### ISSUE THREAD

**Issue by shayandavoodii** [netchx/netch#832]
### Describe the bug

New update can't be executed in windows 10. However, every thing is okay with 1.9.2

### To Reproduce

1. Double click on Netch v1.9.6
2. It doesn't run.

### Log

There isn't any logging folder:
![image](https://user-images.githubusercontent.com/52105833/172907594-97a07e49-2ab9-408b-a3f1-833b3d215317.png)

### Environment

```txt
Windows 10 x64 Professional 21H1
Netch: V1.9.6
```

**Comment by Azuriye** [comment]
Same here!

**Comment by netch-org** [comment]
https://aka.ms/dotnet/6.0/windowsdesktop-runtime-win-x64.exe
