### ISSUE TITLE
1.9.6版本无法启动

### ISSUE THREAD

**Issue by CODE-7z** [netchx/netch#835]
### 错误描述

打开程序时，程序会卡在0.1MB的内存，然后闪退，甚至log文件也没有启动程序的记录

### 复现步骤

1.打开netch
2.打开任务管理器
3.netch在后台0.1MB然后就进程被关闭

### 日志

日志没有任何记载，甚至连log文件都没创建

### 操作环境

```txt
OS：Windows10 家庭中文版 21H2 19044.1706
软件 ver：1.9.6
```

**Comment by Dhanurjan** [comment]
Work well for me. I recently did a clean install of Windows 11.
Edition	Windows 11 Home Single Language
Version	21H2
Installed on	‎07/‎06/‎2022
OS build	22000.708
Experience	Windows Feature Experience Pack 1000.22000.708.0
