### ISSUE TITLE
[功能]进程代理模式对于内部IP地址不进行转发

### ISSUE THREAD

**Issue by peterjc123** [netchx/netch#84]
**功能描述**
简明扼要地描述需要的功能

在使用进程模式时，对于一些常见的内部IP地址，可以在Redirector.exe内部不将其转发至Socks服务器。一些常见的内部IP地址段：
```
192.168.0.0/16
172.16.0.0/20
10.0.0.0/24
```

在GUI方面，可以通过提供开关的方式来选取，也可以直接使用设置中的全局直连IP列表（目前仅TAP方式可用）。

**额外信息**

更多可参见：
https://en.wikipedia.org/wiki/Reserved_IP_addresses

**Comment by chsbuffer** [comment]
请使用[魔改版](https://github.com/AmazingDM/Netch-ForOwnUse)
