### ISSUE TITLE
netch 提示 invalide tcp type，vmess URL

### ISSUE THREAD

**Issue by zstdadi** [netchx/netch#842]
### 错误描述

netch 提示 invalide tcp type，不能用，怎么回事啊

### 复现步骤

vmess://eyJ2IjogIjIiLCAicHMiOiAiMTAzLjExOC4yNy4yMjozMDE4MCIsICJhZGQiOiAiMTAzLjExOC4yNy4yMiIsICJwb3J0IjogMzAxODAsICJhaWQiOiAwLCAidHlwZSI6ICIiLCAibmV0IjogInRjcCIsICJwYXRoIjogIiIsICJob3N0IjogIiIsICJpZCI6ICI0ZjljNTIyZS1jMzM3LTExZWMtYTdkNS0wMDE2M2U1NTExMDkiLCAidGxzIjogIm5vbmUifQ==

vmess://eyJ2IjogIjIiLCAicHMiOiAiMTAzLjE0NC4zMi4zNDoyNjEzIiwgImFkZCI6ICIxMDMuMTQ0LjMyLjM0IiwgInBvcnQiOiAyNjEzLCAiYWlkIjogMCwgInR5cGUiOiAiIiwgIm5ldCI6ICJ0Y3AiLCAicGF0aCI6ICIiLCAiaG9zdCI6ICIiLCAiaWQiOiAiMWQwNDlmNTYtYzMzNy0xMWVjLWE0ZjEtYTc3YjJkODZhMTcxIiwgInRscyI6ICJub25lIn0=

netch 提示 invalide tcp type，不能用，怎么回事啊

### 日志

netch 提示 invalide tcp type，不能用，怎么回事啊

### 操作环境

```txt
windows 10 X64
```

### 额外信息

rt

**Comment by H1JK** [comment]
![image](https://user-images.githubusercontent.com/106379370/173232789-4f69fec7-6eb6-4a41-b2f6-81c805ea18ed.png)
type item is empty, but `none` or `http` type name is required for VMess TCP method.  
This is about v2rayN share link standard, see https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)
