### ISSUE TITLE
socks5国内代理无法访问http https协议

### ISSUE THREAD

**Issue by goldming** [netchx/netch#844]
### 错误描述

[Redirector][EventHandler][tcpConnectRequest][13056][5868] 0.0.0.0:53123 -> 106.42.232.109:443
[Redirector][SocksHelper::Handshake] Receive server response failed: 10054

### 复现步骤

代理的wechat.exe

### 日志

[Redirector][EventHandler][tcpConnectRequest][13056][5868] 0.0.0.0:53123 -> 106.42.232.109:443
[Redirector][SocksHelper::Handshake] Receive server response failed: 10054

### 操作环境

```txt
win10 x64
```

**Comment by EtherealAO** [comment]
10054是指[WinError 10054] 远程主机强迫关闭了一个现有的连接。这不太可能是netch的问题
