### ISSUE TITLE
1.9.6 unstable connection then crashed

### ISSUE THREAD

**Issue by adminferries** [netchx/netch#846]
### Describe the bug

1.9.6 gave me some unstable connection then crashed while trying to establish a connection without any popup or logs. I've checked the log files but there's been no warning or exception.

### To Reproduce

Follows the exact same routine how I used Netch 1.9.3 - open and start

### Log

I've checked both application and V2Ray log

### Environment

```txt
Win 10 21H2
Netch 1.9.6
```

### Additional information

- Not sure what's going on with this buggy release... Please do dev tests extensively as it is a really unpleasant experience to be told to update yet the update breaks everything.

**Comment by H1JK** [comment]
> Log
> I've checked both application and V2Ray log

I think it is better to post it there to help us find problems. You can remove any private infomation from logs.

**Comment by avboy1337** [comment]
目前看，恢复tun2socks为独立进程确实比做成dll要稳定。
