### ISSUE TITLE
1.9.6版本 V2Ray (SagerNet) 控制器启动失败

### ISSUE THREAD

**Issue by EdLovecraft** [netchx/netch#848]
### 错误描述

更换为SagerNet/v2ray-core后无法连接使用simple-obfs插件的节点

### 复现步骤

1. 选择任何使用simple-obfs插件的节点
2. 点击启动

### 日志

V2Ray 5.0.14 (V2Fly, a community-driven edition of V2Ray.) SagerNet (go1.18.3 windows/amd64)
A unified platform for anti-censorship.
Failed to start: main/commands: failed to create server > proxy/shadowsocks: failed to start plugin > proxy/shadowsocks/plugin/external: plugin simple-obfs not found > exec: "simple-obfs": executable file not found in %PATH%

### 操作环境

```txt
操作系统：Windows 10 21H2 19044.1706
软件版本：1.9.6
```

**Comment by H1JK** [comment]
Manually change `simple-obfs` to `obfs-local`, or re-import your share link/update subscription.
