### ISSUE TITLE
可否将程序与.net库打包到一起呢？

### ISSUE THREAD

**Issue by luckyjinx** [netchx/netch#853]
### 功能描述

或者另做一个打包的版本 因为有时需要批量安装 基本现在的电脑也基本都没带

**Comment by AmazingDM** [comment]
当前默认是打包在一起的，如有需要可自行调整。
https://github.com/netchx/netch/blob/2b7483b696cc3a8cfb8a3305e30504683c836a2c/build.ps1#L14
https://docs.microsoft.com/en-us/dotnet/core/deploying/
