### ISSUE TITLE
无法设置UDP不转发

### ISSUE THREAD

**Issue by ytwxj88** [netchx/netch#855]
### Describe the feature you want

设置里找不到设置UDP不转发功能，希望在设置里能添加自由开启或关闭UDP转发功能

**Comment by binbin999789** [comment]
> ### 描述你想要的功能
> 设置里找不到设置UDP不转发功能，希望能在自由添加开启关闭或设置里UDP转发功能

设置里，不 是有处理TCP和处理UDP还有处理ICMP的麻，前面不打勾，应该就是不处理相应的协议吧。

**Comment by ytwxj88** [comment]
> 



> > ### 描述你想要的功能
> > 设置里找不到设置UDP不转发功能，希望能在自由添加开启关闭或设置里UDP转发功能
> 
> 设置里，不 是有处理TCP和处理UDP还有处理ICMP的麻，前面不打勾，应该就是不处理相应的协议吧。
那个不是，我试过了！！
