### ISSUE TITLE
By pass LAN 系列规则缺失

### ISSUE THREAD

**Issue by Smallthing** [netchx/netch#862]
### 错误描述

netch附带的规则：
# Bypass LAN, 2
10.0.0.0/8
172.16.0.0/16
192.168.0.0/16

172.16.0.0这个段应该为
172.16.0.0/12

### 复现步骤

如题

### 日志

如题

### 操作环境

```txt
如题
```

### 额外信息

个人使用的是
127.0.0.0/8
192.168.0.0/16
10.0.0.0/8
172.16.0.0/12
100.64.0.0/10
17.0.0.0/8   

17.0.0.0/8是苹果服务和隐私代理 目前苹果服务是通的 所以认为可以暂时by pass

**Comment by H1JK** [comment]
> 17.0.0.0/8是苹果服务和隐私代理 目前苹果服务是通的 所以认为可以暂时by pass

I think it is better to put it into Bypass LAN and China.  
  
BTW, would you like to make a PR?
