### ISSUE TITLE
为什么youtube 可以打开但不能播放，google网页打不开

### ISSUE THREAD

**Issue by neozhu** [netchx/netch#866]
### 错误描述

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1549611/176047223-e1b65647-4456-451d-b981-72d30c9d6dc4.png">

### 复现步骤

<img width="439" alt="image" src="https://user-images.githubusercontent.com/1549611/176047486-76828346-0f40-4ddb-b014-bae27df833df.png">

### 日志

V2Ray 5.0.14 (V2Fly, a community-driven edition of V2Ray.) SagerNet (go1.18.3 windows/amd64)
A unified platform for anti-censorship.
2022/06/28 06:31:37 [Warning] V2Ray 5.0.14 started
2022/06/28 06:31:45 [Warning] [878137651] app/dispatcher: default route for tcp:cp.cloudflare.com:80
2022/06/28 06:31:45 [Warning] [1480281418] app/dispatcher: default route for udp:198.211.120.59:3478
2022/06/28 06:31:48 [Warning] [4155960579] app/dispatcher: default route for udp:224.0.0.251:5353
2022/06/28 06:31:48 [Warning] [3746402614] app/dispatcher: default route for udp:10.0.236.255:137
2022/06/28 06:31:49 [Warning] [43792291] app/dispatcher: default route for udp:239.255.255.250:1900
2022/06/28 06:31:49 [Warning] [3054511007] app/dispatcher: default route for udp:239.255.255.250:1900
2022/06/28 06:31:50 [Warning] [3480732281] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:31:50 [Warning] [3624804128] app/dispatcher: default route for tcp:34.203.184.117:443
2022/06/28 06:31:52 [Warning] [3450342811] app/dispatcher: default route for tcp:23.219.38.64:443
2022/06/28 06:31:53 [Warning] [846321108] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:31:58 [Warning] [860993966] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:05 [Warning] [1377886920] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:05 [Warning] [2683279217] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:10 [Warning] [1145386541] app/dispatcher: default route for udp:142.251.42.234:443
2022/06/28 06:32:10 [Warning] [3374757058] app/dispatcher: default route for tcp:13.225.142.120:443
2022/06/28 06:32:10 [Warning] [353340700] app/dispatcher: default route for udp:203.208.39.230:443
2022/06/28 06:32:10 [Warning] [2473869345] app/dispatcher: default route for udp:104.19.53.22:443
2022/06/28 06:32:10 [Warning] [831287506] app/dispatcher: default route for tcp:180.163.150.34:443
2022/06/28 06:32:11 [Warning] [4280164854] app/dispatcher: default route for tcp:203.208.43.70:443
2022/06/28 06:32:11 [Warning] [4126751812] app/dispatcher: default route for tcp:180.163.150.33:443
2022/06/28 06:32:11 [Warning] [4120789417] app/dispatcher: default route for tcp:203.208.40.98:443
2022/06/28 06:32:11 [Warning] [4274281057] app/dispatcher: default route for tcp:142.251.42.238:443
2022/06/28 06:32:11 [Warning] [2834006397] app/dispatcher: default route for tcp:203.208.43.70:443
2022/06/28 06:32:11 [Warning] [664879923] app/dispatcher: default route for tcp:35.190.80.1:443
2022/06/28 06:32:11 [Warning] [3221673694] app/dispatcher: default route for tcp:172.217.160.86:443
2022/06/28 06:32:11 [Warning] [3361719581] app/dispatcher: default route for tcp:203.208.39.225:443
2022/06/28 06:32:11 [Warning] [2957119144] app/dispatcher: default route for tcp:203.208.40.98:443
2022/06/28 06:32:12 [Warning] [3825114572] app/dispatcher: default route for udp:199.59.149.205:443
2022/06/28 06:32:12 [Warning] [3168339635] app/dispatcher: default route for udp:35.190.80.1:443
2022/06/28 06:32:13 [Warning] [3103869896] app/dispatcher: default route for tcp:140.82.114.26:443
2022/06/28 06:32:16 [Warning] [3541901077] app/dispatcher: default route for tcp:44.236.175.31:443
2022/06/28 06:32:17 [Warning] [3038196694] app/dispatcher: default route for tcp:157.240.17.35:443
2022/06/28 06:32:17 [Warning] [3020704781] app/dispatcher: default route for udp:157.240.17.35:443
2022/06/28 06:32:17 [Warning] [3744471092] app/dispatcher: default route for tcp:203.208.40.34:443
2022/06/28 06:32:17 [Warning] [3231311223] app/dispatcher: default route for tcp:203.208.43.70:443
2022/06/28 06:32:17 [Warning] [3498984047] app/dispatcher: default route for udp:203.208.43.70:443
2022/06/28 06:32:17 [Warning] [3940518298] app/dispatcher: default route for tcp:157.240.17.35:443
2022/06/28 06:32:17 [Warning] [188632680] app/dispatcher: default route for tcp:203.208.40.34:80
2022/06/28 06:32:18 [Warning] [684248450] app/dispatcher: default route for tcp:157.240.17.35:443
2022/06/28 06:32:20 [Warning] [656283715] app/dispatcher: default route for tcp:199.59.149.205:443
2022/06/28 06:32:20 [Warning] [1396031237] app/dispatcher: default route for udp:199.59.149.205:443
2022/06/28 06:32:20 [Warning] [4239502731] app/dispatcher: default route for tcp:180.163.151.162:443
2022/06/28 06:32:22 [Warning] [402775660] app/dispatcher: default route for tcp:142.251.42.238:443
2022/06/28 06:32:22 [Warning] [2214076173] app/dispatcher: default route for udp:142.251.42.238:443
2022/06/28 06:32:22 [Warning] [3381512028] app/dispatcher: default route for tcp:142.251.43.1:443
2022/06/28 06:32:22 [Warning] [31544676] app/dispatcher: default route for udp:172.217.163.42:443
2022/06/28 06:32:22 [Warning] [617583257] app/dispatcher: default route for tcp:203.208.43.101:443
2022/06/28 06:32:22 [Warning] [978504630] app/dispatcher: default route for tcp:203.208.39.225:443
2022/06/28 06:32:22 [Warning] [3568470780] app/dispatcher: default route for tcp:142.251.43.1:443
2022/06/28 06:32:22 [Warning] [1709591951] app/dispatcher: default route for tcp:142.251.43.1:443
2022/06/28 06:32:22 [Warning] [3931736317] app/dispatcher: default route for tcp:142.251.43.1:443
2022/06/28 06:32:22 [Warning] [600047965] app/dispatcher: default route for udp:224.0.0.251:5353
2022/06/28 06:32:23 [Warning] [773033702] app/dispatcher: default route for tcp:199.59.149.205:443
2022/06/28 06:32:25 [Warning] [142949504] app/dispatcher: default route for tcp:23.204.146.160:80
2022/06/28 06:32:31 [Warning] [370001243] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:32 [Warning] [3485347757] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:32 [Warning] [1113546757] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:32 [Warning] [4144869189] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:33 [Warning] [1689604232] app/dispatcher: default route for tcp:23.204.146.163:80
2022/06/28 06:32:33 [Warning] [4045952926] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:33 [Warning] [1382662226] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:37 [Warning] [4141310290] app/dispatcher: default route for tcp:23.63.47.52:80
2022/06/28 06:32:37 [Warning] [1370570226] app/dispatcher: default route for tcp:168.63.250.82:80
2022/06/28 06:32:38 [Warning] [1303149061] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:40 [Warning] [1562675989] app/dispatcher: default route for tcp:183.232.141.89:561
2022/06/28 06:32:42 [Warning] [746768695] app/dispatcher: default route for tcp:20.190.163.18:443
2022/06/28 06:32:43 [Warning] [3952150549] app/dispatcher: default route for tcp:52.113.194.132:443
2022/06/28 06:32:43 [Warning] [3877305700] app/dispatcher: default route for tcp:52.113.194.132:443
2022/06/28 06:32:44 [Warning] [111761010] app/dispatcher: default route for tcp:52.152.90.172:443
2022/06/28 06:32:44 [Warning] [498966441] app/dispatcher: default route for tcp:40.90.184.82:443
2022/06/28 06:32:44 [Warning] [2587659934] app/dispatcher: default route for tcp:202.89.233.96:443
2022/06/28 06:32:44 [Warning] [85835616] app/dispatcher: default route for tcp:52.113.194.132:443
2022/06/28 06:32:44 [Warning] [2413004511] app/dispatcher: default route for tcp:52.113.194.132:443
2022/06/28 06:32:44 [Warning] [1283267943] app/dispatcher: default route for tcp:52.113.194.132:443
2022/06/28 06:32:44 [Warning] [1317043290] app/dispatcher: default route for tcp:202.89.233.96:443
2022/06/28 06:32:44 [Warning] [2440531851] app/dispatcher: default route for tcp:20.205.34.189:443
2022/06/28 06:32:45 [Warning] [1770044087] app/dispatcher: default route for tcp:61.147.226.43:443
2022/06/28 06:32:47 [Warning] [3066348804] app/dispatcher: default route for tcp:104.124.1.42:443
2022/06/28 06:32:47 [Warning] [3971230979] app/dispatcher: default route for tcp:222.186.189.70:443
2022/06/28 06:32:47 [Warning] [2312765258] app/dispatcher: default route for tcp:222.186.189.70:443
2022/06/28 06:32:47 [Warning] [1183931863] app/dispatcher: default route for tcp:222.186.189.70:443
2022/06/28 06:32:47 [Warning] [3244972804] app/dispatcher: default route for tcp:222.186.189.70:443
2022/06/28 06:32:47 [Warning] [1834403470] app/dispatcher: default route for tcp:222.186.189.60:443
2022/06/28 06:32:47 [Warning] [2077356992] app/dispatcher: default route for tcp:222.186.189.60:443

### 操作环境

```txt
win11
```

**Comment by neozhu** [comment]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/1549611/176048817-d1aa8fe8-5941-4951-8d88-e333068a620b.png">
玩游戏也不行

**Comment by neozhu** [comment]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/1549611/176049328-54454bd4-eac9-42d4-8114-f6bb089720e9.png">
<img width="646" alt="image" src="https://user-images.githubusercontent.com/1549611/176049352-b0acf0a3-daee-4703-bb10-b95bc9bc68a2.png">

**Comment by Glen-Ni** [comment]
一样的问题，神奇

**Comment by OnlyCharacter** [comment]
一样，使用nslookup发现用的还是系统dns，ping的时候，使用wireshark抓包，也是使用系统DNS。
估计是AIODNS的问题。
不过对于Bypass Lan的需求，你在设置里面的wintun，使用自定义dns并代理dns，换个1.1.1.1应该是能用的。

**Comment by 3463014081** [comment]
我也是这个问题

**Comment by neozhu** [comment]
另外，据了解通过机场根本不能实现外服游戏加速，估计想玩外服还得花钱买账号

**Comment by raion26** [comment]
> 另外，据了解通过机场根本不能实现外服游戏加速，估计想玩外服还得花钱买账号

如果你准备试玩ow2的话那确实，国服跟外服是隔离的，要买外服资格才能试玩，这个问题我也遇到了，直接用回1.5了

**Comment by neozhu** [comment]
> 如果你准备试玩ow2的话那确实，国服跟外服是隔离的，要买外服资格才能试玩，这个问题我也遇到了，直接用回1.5了

晚上试了一下竟然可以，我用r2s openwrt wallpass 用香港节点可以玩 亚洲区的cod warzone，这样可以省了加速器的钱

**Comment by 2131411** [comment]
我也是，出现问题的都是ss或者ssr的节点

**Comment by neozhu** [comment]
> 我也是，出现问题的都是ss或者ssr的节点

不靠谱，玩游戏不如买个软路由或是加速器账号，200一年或是买1个月 省事省心

**Comment by expfukck** [comment]
看视频 和逛网页  使用clash吧  Netch  游戏加速 我用了 很久了

**Comment by qgfhe** [comment]
1.9.2会自动设置aioCloud的dns为6.6.6.6，而1.9.7没有设置
<img width="496" alt="Snipaste_2022-07-08_15-23-48" src="https://user-images.githubusercontent.com/49047132/177940612-182ba56f-badd-4696-96fa-628b02676ac5.png">

<img width="544" alt="Snipaste_2022-07-08_15-25-26" src="https://user-images.githubusercontent.com/49047132/177940643-66b283c5-e2be-49c5-a36d-83d123b491aa.png">

手动设置之后nslookup好像正常了
<img width="284" alt="Snipaste_2022-07-08_15-26-09" src="https://user-images.githubusercontent.com/49047132/177940658-213a5a0e-1d3f-4431-9baa-429d9505ec79.png">

<img width="548" alt="Snipaste_2022-07-08_15-27-28" src="https://user-images.githubusercontent.com/49047132/177940690-4df73207-36b3-4af4-b668-778ed06b5ab1.png">

**Comment by OnlyCharacter** [comment]
> 1.9.2会自动设置aioCloud的dns为6.6.6.6，而1.9.7没有设置 <img alt="Snipaste_2022-07-08_15-23-48" width="496" src="https://user-images.githubusercontent.com/49047132/177940612-182ba56f-badd-4696-96fa-628b02676ac5.png">
> 
> <img alt="Snipaste_2022-07-08_15-25-26" width="544" src="https://user-images.githubusercontent.com/49047132/177940643-66b283c5-e2be-49c5-a36d-83d123b491aa.png">
> 
> 手动设置之后nslookup好像正常了 <img alt="Snipaste_2022-07-08_15-26-09" width="284" src="https://user-images.githubusercontent.com/49047132/177940658-213a5a0e-1d3f-4431-9baa-429d9505ec79.png">
> 
> <img alt="Snipaste_2022-07-08_15-27-28" width="548" src="https://user-images.githubusercontent.com/49047132/177940690-4df73207-36b3-4af4-b668-778ed06b5ab1.png">

可是我修改完了，如果发起查询netch就闪退了

**Comment by OnlyCharacter** [comment]
> 1.9.2会自动设置aioCloud的dns为6.6.6.6，而1.9.7没有设置 <img alt="Snipaste_2022-07-08_15-23-48" width="496" src="https://user-images.githubusercontent.com/49047132/177940612-182ba56f-badd-4696-96fa-628b02676ac5.png">
> 
> <img alt="Snipaste_2022-07-08_15-25-26" width="544" src="https://user-images.githubusercontent.com/49047132/177940643-66b283c5-e2be-49c5-a36d-83d123b491aa.png">
> 
> 手动设置之后nslookup好像正常了 <img alt="Snipaste_2022-07-08_15-26-09" width="284" src="https://user-images.githubusercontent.com/49047132/177940658-213a5a0e-1d3f-4431-9baa-429d9505ec79.png">
> 
> <img alt="Snipaste_2022-07-08_15-27-28" width="548" src="https://user-images.githubusercontent.com/49047132/177940690-4df73207-36b3-4af4-b668-778ed06b5ab1.png">

日志如下：
`
[2022-07-08 22:13:12][Information] Netch Version: NetchX/Netch@1.9.7
[2022-07-08 22:13:12][Information] OS: Microsoft Windows NT 10.0.19044.0
[2022-07-08 22:13:13][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2022-07-08 22:13:13][Information] System Language: zh-CN
[2022-07-08 22:13:13][Debug] Running Processes: 
C:\Program Files (x86)\Common Files\Macrovision Shared\FlexNet Publisher\FNPLicensingService.exe
C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
C:\Program Files (x86)\Google\Update\1.3.36.132\GoogleCrashHandler.exe
C:\Program Files (x86)\Google\Update\1.3.36.132\GoogleCrashHandler64.exe
C:\Program Files (x86)\Internet Download Manager\IDMan.exe
C:\Program Files (x86)\VMware\VMware Workstation\vmware-authd.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files\Microsoft Update Health Tools\uhssvc.exe
C:\Users\???\Desktop\SOFTWARE\Netch\Netch.exe
[2022-07-08 22:13:13][Debug] Third-party Drivers:
CimFS [CimFS]()
	C:\Windows\system32\drivers\CimFS.sys
VMware hcmon [VMware hcmon](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\hcmon.sys
IDMWFP [IDMWFP](Copyright © 1999 - 2018 Tonec Inc.)
	C:\Windows\system32\DRIVERS\idmwfp.sys
Npcap Packet Driver (NPCAP) [Npcap Packet Driver (NPCAP)](Copyright (c) 2022, Insecure.Com LLC.  All rights reserved.)
	C:\Windows\system32\DRIVERS\npcap.sys
Steam Streaming Microphone [Steam Streaming Microphone]()
	C:\Windows\system32\drivers\SteamStreamingMicrophone.sys
Steam Streaming Speakers [Steam Streaming Speakers]()
	C:\Windows\system32\drivers\SteamStreamingSpeakers.sys
VMware VMCI Bus Driver [VMware VMCI Bus Driver](Copyright © 1998-2019 VMware, Inc.)
	C:\Windows\system32\drivers\vmci.sys
VMware Bridge Protocol [VMware Bridge Protocol](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetbridge.sys
VMware Virtual Ethernet Userif for VMnet [VMware Virtual Ethernet Userif for VMnet](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmnetuserif.sys
VMware vmx86 [VMware vmx86](Copyright © 1998-2021 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vmx86.sys
vSockets Virtual Machine Communication Interface Sockets driver [vSockets Virtual Machine Communication Interface Sockets driver](Copyright © 1998-2020 VMware, Inc.)
	C:\Windows\system32\DRIVERS\vsock.sys
Wintun [Wintun](Copyright © 2018-2021 WireGuard LLC. All Rights Reserved.)
	C:\Windows\system32\DRIVERS\wintun.sys
[2022-07-08 22:13:13][Information] Github latest release: 1.9.7
[2022-07-08 22:13:13][Information] Already the latest version
[2022-07-08 22:13:15][Information] Start MainController: VLESS [2]Bypass LAN and China
[2022-07-08 22:13:15][Debug] Server Information: VLESS none + tcp + xudp + none + xtls
[2022-07-08 22:13:15][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-07-08 22:13:15][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-07-08 22:13:23][Information] Net traffic processes: (4896)v2ray-sn

`


`
V2Ray 5.0.14 (V2Fly, a community-driven edition of V2Ray.) SagerNet (go1.18.3 windows/amd64)
A unified platform for anti-censorship.
2022/07/08 22:13:15 [Warning] V2Ray 5.0.14 started
2022/07/08 22:13:23 [Warning] [614734858] app/dispatcher: default route for udp:198.211.120.59:3478
2022/07/08 22:13:23 [Warning] [2638657374] app/dispatcher: default route for tcp:cp.cloudflare.com:80
2022/07/08 22:13:24 [Warning] [196650493] app/dispatcher: default route for tcp:cp.cloudflare.com:80
2022/07/08 22:13:26 [Warning] [1868487267] app/dispatcher: default route for udp:224.0.0.251:5353
2022/07/08 22:13:26 [Warning] [2006521695] app/dispatcher: default route for udp:10.10.10.255:137
2022/07/08 22:13:27 [Warning] [1553534696] app/dispatcher: default route for tcp:40.90.189.152:443
2022/07/08 22:13:28 [Warning] [2391801423] app/dispatcher: default route for tcp:211.136.192.6:53
2022/07/08 22:13:28 [Warning] [2917583794] app/dispatcher: default route for tcp:74.125.204.188:443
2022/07/08 22:13:28 [Warning] [3163632751] app/dispatcher: default route for udp:239.255.255.250:1900
2022/07/08 22:13:28 [Warning] [1694352794] app/dispatcher: default route for tcp:211.136.192.6:53
2022/07/08 22:13:28 [Warning] [2867502699] app/dispatcher: default route for tcp:211.136.192.6:53
2022/07/08 22:13:28 [Warning] [3033631804] app/dispatcher: default route for tcp:211.136.192.6:53
2022/07/08 22:13:29 [Warning] [3523411126] app/dispatcher: default route for tcp:211.136.192.6:53
2022/07/08 22:13:29 [Warning] [387917375] app/dispatcher: default route for udp:239.255.255.250:1900
2022/07/08 22:13:32 [Warning] [2508457596] app/dispatcher: default route for udp:10.10.10.255:138
2022/07/08 22:13:38 [Warning] [1903189243] app/dispatcher: default route for tcp:120.196.165.24:53
2022/07/08 22:13:38 [Warning] [2255904290] app/dispatcher: default route for tcp:120.196.165.24:53
2022/07/08 22:13:38 [Warning] [4122962229] app/dispatcher: default route for tcp:120.196.165.24:53
2022/07/08 22:13:38 [Warning] [400282171] app/dispatcher: default route for tcp:120.196.165.24:53
2022/07/08 22:13:38 [Warning] [2338408316] app/dispatcher: default route for tcp:184.27.185.68:443
2022/07/08 22:13:39 [Warning] [1976285827] app/dispatcher: default route for tcp:120.196.165.24:53
2022/07/08 22:13:49 [Warning] [2164590751] app/dispatcher: default route for tcp:52.184.216.226:443
2022/07/08 22:14:03 [Warning] [3146884784] app/dispatcher: default route for udp:224.0.0.251:5353
2022/07/08 22:14:03 [Warning] [1862282416] app/dispatcher: default route for udp:224.0.0.252:5355
`
