### ISSUE TITLE
进程模式命运2无法连接到服务器

### ISSUE THREAD

**Issue by RubiksCubei** [netchx/netch#880]
### 错误描述

![image](https://user-images.githubusercontent.com/48173817/178748593-c936a84f-fdce-4c19-b5e4-cd9c432e3a22.png)

### 复现步骤

1.打开netch软件
2.创建进程模式，并选择命运2游戏根目录
3.选择节点并启动
4.打开游戏

### 日志

V2Ray 5.0.14 (V2Fly, a community-driven edition of V2Ray.) SagerNet (go1.18.3 windows/amd64)
A unified platform for anti-censorship.
2022/07/13 21:47:03 [Warning] V2Ray 5.0.14 started
2022/07/13 21:47:03 [Warning] [2824475152] app/dispatcher: default route for udp:139.59.84.212:3478
2022/07/13 21:47:03 [Warning] [148882860] app/dispatcher: default route for tcp:cp.cloudflare.com:80
2022/07/13 21:47:12 [Warning] [2023093945] app/dispatcher: default route for udp:239.255.255.250:1900
2022/07/13 21:47:14 [Warning] [1799890293] app/dispatcher: default route for udp:172.97.59.54:3074
2022/07/13 21:47:15 [Warning] [760250981] app/dispatcher: default route for tcp:54.71.150.100:443
2022/07/13 21:47:24 [Warning] [3779963289] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:47:29 [Warning] [1984158084] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:47:33 [Warning] [3476534252] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:47:36 [Warning] [561863772] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:47:40 [Warning] [3225182252] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:47:49 [Warning] [152324582] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:47:59 [Warning] [1126620422] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:06 [Warning] [3597007850] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:11 [Warning] [3389247886] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:24 [Warning] [1353670143] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:28 [Warning] [63763873] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:31 [Warning] [2343198526] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:35 [Warning] [4122466852] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:38 [Warning] [2836459356] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:42 [Warning] [1497323740] app/dispatcher: default route for udp:1.1.1.1:53
2022/07/13 21:48:49 [Warning] [1944644715] app/dispatcher: default route for udp:1.1.1.1:53

### 操作环境

```txt
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2020/‎6/‎3
操作系统内部版本	19043.1806
体验	Windows Feature Experience Pack 120.2212.4180.0
软件版本   1.9.7
```

**Comment by visibleLi** [comment]
为什么我的速🐸☁️游戏专线 都在1000ms。。。
