### ISSUE TITLE
连接上netch后就没网了

### ISSUE THREAD

**Issue by dfdfwff** [netchx/netch#881]
### 错误描述

连接netch后，客户端右下角显示NAT：no UDP   然后电脑右下角的wifi显示已连接但是下面又有一层 网络3无发访问internet

### 复现步骤

1.打开netch，选择一个节点连接bypass lan and china
2.连接成功后，客户端右下角显示NAT：no UDP  然后同时，电脑右下角的wifi界面显示cmcc-xx已连接  但是下面还有一层显示
 网络3无法访问internet
3.这样以后 ，我本来登着的qq还能照样发信息 收信息，但是无法用浏览器上网，国内外的都不行

### 日志

抱歉 日志复制不下来

### 操作环境

```txt
win11 家庭中文版  21H
操作系统版本22000.795
```

### 额外信息

![image](https://user-images.githubusercontent.com/102846037/179251188-78d40ad5-df49-4f3f-b1d1-e38cc1112e4a.png)
![image](https://user-images.githubusercontent.com/102846037/179251220-276d26be-d1df-4bbc-b20d-4d66d060de7c.png)
![image](https://user-images.githubusercontent.com/102846037/179251261-2ae9a635-c977-42df-ae2f-37b1a1569ddb.png)

**Comment by geeksKK8** [comment]
我也碰到了一样的问题，请问你解决了吗

**Comment by iToolstm** [comment]
请问版主解决了吗？我也碰到了和你一模一样的问题，困扰我好久了
