### ISSUE TITLE
ShadowsocksR停止运行

### ISSUE THREAD

**Issue by BWZS** [netchx/netch#89]
**错误描述**
（提出错误报告之前，先确保自己已看过readme，并搜索过相关问题）
电脑弹窗提示ShadowsocksR停止运行，然后服务就挂掉了，netch还在后台，但是不能代理了。

**复现步骤**
1. 打开 Netch 软件
2. 然后使用久了就酱紫

**错误截图**
忘了……就是一个停止运行的图……

**信息**
 - 操作系统：Windows 10 1607 专业版 64 位
 - 软件版本：1.2.7-STABLE 64 位

**额外信息**
来自shadowsocksr.log:

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!
Program: C:\Users\\AppData\Local\Netch\bin\ShadowsocksR.exe
File: ev_select.c, Line 85
Expression: ("libev: fd >= FD_SETSIZE passed to fd_set-based select backend", fd < FD_SETSIZE)
```

**Comment by ghost** [comment]
@tindy2013 你看看把 SS 那边的 libev 库拉到 SSR 这边来，能不能编译成功

**Comment by tindy2013** [comment]
现在可尝试从 binaries/x64 中下载最新 SSR 客户端替换后再行测试

**Comment by 57a4c324e742** [comment]
Same here, crash every 5 minutes.

**Comment by ghost** [comment]
@CrystalInternet The new version should have fixed this problem by @tindy2013

**Comment by ghost** [comment]
请尝试 1.2.9 新版本

**Comment by ghost** [comment]
如果有问题再新开一个 issue 出来
