### ISSUE TITLE
The above rules do not conform to c++ regular expressions

### ISSUE THREAD

**Issue by BZ666a** [netchx/netch#895]
### Describe the bug

As I said, when I want to start the agent he pops up a window says The above rules do not conform to c++ regular expressions.

### To Reproduce

![Uploading image.png…]()

### Log

[application.log](https://github.com/netchx/netch/files/9204906/application.log)

### Environment

```txt
win10x64 21h2
```

**Comment by BZ666a** [comment]
By the way, I'm using a global proxy

**Comment by huychoipro5** [comment]
Just go Edit the global mode
And delete \netch\ in the bypass rule

![Screenshot 2022-09-11 113715](https://user-images.githubusercontent.com/79309028/189512659-561f4975-090e-4e86-acd6-1093a4260f93.png)

**Comment by egor-lisp** [comment]
any solution for this? Faced the same issue
