### ISSUE TITLE
bypass lan and china没法使用DISCORD

### ISSUE THREAD

**Issue by chaonengyuan** [netchx/netch#896]
### 错误描述

bypass lan and china没法使用DISCORD

### 复现步骤

bypass lan and china没法使用DISCORD
理论来说所有加速方式都没法使用discord

### 日志

无

### 操作环境

```txt
win11
```

### 额外信息

DNS已经完全刷新过了

**Comment by UoKAa** [comment]
同问，不管是bypass lan and china还是DISCORD模式又或者是自己创建新的进程模式都会卡在checking for update。1.9.4可以连接的上

**Comment by chaonengyuan** [comment]
> 

我解决了，把AIODNS换成1.1.1.1并且代理这个DNS就行了，缺点就是你的上传延迟会上天

**Comment by UoKAa** [comment]
我设置了AIODNS但是仍然不管用，我修改了其他DNS配置到8.8.8.8但是也只有在bypass lan and china这边可以加速，单单选择Discord仍然无法加速

**Comment by chaonengyuan** [comment]
> 我设置了AIODNS但是仍然不管用，我修改了其他DNS配置到8.8.8.8但是也只有在bypass lan and china这边可以加速，单单选择Discord仍然无法加速

单选择DISCORD需要添加个svhost

**Comment by UoKAa** [comment]
> 

具体如何操作呢？请教我一下，谢谢

**Comment by UoKAa** [comment]
> > 我设置了AIODNS但是仍然不管用，我修改了其他DNS配置到8.8.8.8但是也只有在bypass lan and china这边可以加速，单单选择Discord仍然无法加速
> 
> 单选择DISCORD需要添加个svhost

具体如何操作呢？请教我一下，谢谢

**Comment by chaonengyuan** [comment]
> > > 我设置了AIODNS但是仍然不管用，我修改了其他DNS配置到8.8.8.8但是也只有在bypass lan and china这边可以加速，单单选择Discord仍然无法加速
> > 
> > 
> > 单选择DISCORD需要添加个svhost
> 
> 具体如何操作呢？请教我一下，谢谢

创建进程模式》处理进程》discord   svhost

**Comment by UoKAa** [comment]
> > > > 我设置了AIODNS但是仍然不管用，我修改了其他DNS配置到8.8.8.8但是也只有在bypass lan and china这边可以加速，单单选择Discord仍然无法加速
> > > 
> > > 
> > > 单选择DISCORD需要添加个svhost
> > 
> > 
> > 具体如何操作呢？请教我一下，谢谢
> 
> 创建进程模式》处理进程》discord svhost

我发现这样会导致其他一些东西也走代理，国服的一些游戏反而加载不出来了0.0

**Comment by chaonengyuan** [comment]
> > > > > 我设置了AIODNS但是仍然不管用，我修改了其他DNS配置到8.8.8.8但是也只有在bypass lan and china这边可以加速，单单选择Discord仍然无法加速
> > > > 
> > > > 
> > > > 单选择DISCORD需要添加个svhost
> > > 
> > > 
> > > 具体如何操作呢？请教我一下，谢谢
> > 
> > 
> > 创建进程模式》处理进程》discord svhost
> 
> 我发现这样会导致其他一些东西也走代理，国服的一些游戏反而加载不出来了0.0

全局进程代理   " ."
