### ISSUE TITLE
v1.9.7访问谷歌（HSTS）异常

### ISSUE THREAD

**Issue by Xr267** [netchx/netch#904]
### Describe the bug

SS节点，模式Bypass LAN and China，访问谷歌出现（1.9.2正常）：
www.google.com 通常会使用加密技术来保护您的信息。Chrome 此次尝试连接到 www.google.com 时，该网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 www.google.com，或者 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 www.google.com，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

### To Reproduce

升级到1.9.7版本出现该问题，之前版本无此问题，同样节点回退1.9.2正常
也可能我的节点配合新版的问题吧

### Log

[application.log](https://github.com/netchx/netch/files/9305832/application.log)
[V2Ray (SagerNet).log](https://github.com/netchx/netch/files/9305833/V2Ray.SagerNet.log)

### Environment

```txt
Windows 11 专业版 21H2 22000.795
Netch 1.9.7
```

**Comment by Morpheus1123** [comment]
访问google出现了类似的错误。

而且我这里使用vmess服务器，Bypass LAN and China基本上不可用。创建虚拟网卡后，访问被墙的网站，有极小的概率能访问，大部分情况都是一直加载。youtube偶尔能加载网页，但视频一直加载，不能播放。

我看到了这个issue，尝试换回1.9.2，一切正常。感谢Xr267。

**Comment by abc-123-sudo** [comment]
> 

我也是一样的，1.9.7版本的Bypass LAN and China用不了，连接不到谷歌和youtube，然后我换到了1.9.2的就行了

**Comment by shinpei710** [comment]
我看到更新日志里面有修复Sock5认证
是不是反向修复了haha /狗头

**Comment by shinpei710** [comment]
我还以为是我的节点问题，多买了两个平台的订阅55555
我肉疼啊555555

**Comment by abc-123-sudo** [comment]
> 我还以为是我的节点问题，多买了两个平台的订阅55555 我肉疼啊555555

没事，用1.9.2的就行

**Comment by abc-123-sudo** [comment]
> 我看到更新日志里面有修复Sock5认证 是不是反向修复了haha /狗头

反向修复最为致命，哈哈
