### ISSUE TITLE
游戏代理不上

### ISSUE THREAD

**Issue by YouHaveGone** [netchx/netch#91]
**错误描述**
游戏是台服剑灵,别的游戏没试.扫描目录是整个根文件夹再加上游戏的反外挂文件(des后缀),试了很多次依然登录不上.

**复现步骤**
1. 打开 Netch 软件 启动
2. 运行游戏

**信息**
 - 操作系统：例如 Windows 10 专业版 64 位
 - 软件版本：例如 1.2.7 STABLE 64 位

**额外信息**
附上当时的节点fast测速,节点是没问题的
![image](https://user-images.githubusercontent.com/36957938/64078459-9df72700-cd0d-11e9-88e0-29c6178f477d.png)
[redirector.log](https://github.com/NetchX/Netch/files/3563629/redirector.log)

**Comment by ghost** [comment]
很抱歉，现有的日志很难供我分析（忘记把 UDP 也写日志了）

**Comment by ghost** [comment]
将在近期改进 UDP 相关日志

**Comment by ghost** [comment]
请您在最新版本的基础上，手动替换一下 Redirector 文件，下载地址：[这里](https://github.com/NetchX/Netch/raw/master/binaries/x64/Redirector.exe)

这个新的 Redirector 加上了 UDP 日志

**Comment by ghost** [comment]
您好，1.2.8-BETA 中已经包含带 UDP 日志的端，请您更新后测试，不行的话请提供一下日志

**Comment by BingLingGroup** [comment]
你可以参考一下 #109 的解决方法

**Comment by YouHaveGone** [comment]
剛測試了一下還是代理不上,使用的是 1.2.8-BETA ,也用了 #109 的方法替換了FAQ里的Redirector.exe,下面是兩次的日誌
[redirector1.28.log](https://github.com/NetchX/Netch/files/3574702/redirector1.28.log)
[redirectorFAQ.log](https://github.com/NetchX/Netch/files/3574703/redirectorFAQ.log)

**Comment by BingLingGroup** [comment]
@YouHaveGone 1.2.8-BETA 原生的 Redirector.exe 肯定是不行的，至于替换后还不行就比较麻烦了。这个问题估计需要一段时间才能修好。临时性的替代方案是使用 TUN/TAP 模式来代理游戏。
对了替换完了别忘了重启一下电脑，有时候可能有玄学，重启一下能解决

**Comment by BingLingGroup** [comment]
@YouHaveGone 1.3.0 的 `redirector.exe` 修复了中文路径无法代理的 bug，你可以再试试

**Comment by BingLingGroup** [comment]
先关了，参见 #152
