### ISSUE TITLE
TUN-TAP

### ISSUE THREAD

**Issue by lssmoon2019** [netchx/netch#911]
### 功能描述

新版本为何没有了[TUN-TAP]绕过局域网和大陆地址  这个模式。这导致我Vmware虚拟机无法使用代理。

**Comment by ohkl** [comment]
https://github.com/AmazingDM/Netch-ForOwnUse
netch升级版

**Comment by Xuyiyang23333** [comment]
试试“Bypass LAN and China”模式？
