### ISSUE TITLE
Wireguard有流量出入，但不起作用

### ISSUE THREAD

**Issue by PeakGymnast** [netchx/netch#912]
### Describe the bug

自己vps搭建的wireguard，官方客户端没问题，但netch连上了却访问不了google，已经设置模式为bypass LAN and China
![image](https://user-images.githubusercontent.com/85560713/186170202-bf2cf15f-5e9a-4d7c-9b92-b3a194007049.png)
![image](https://user-images.githubusercontent.com/85560713/186170502-78bdceb6-e7a7-42fe-ac85-cc36cbf44e39.png)

### To Reproduce

无

### Log

无

### Environment

```txt
Netch Version: 1.9.7
```

**Comment by abc-123-sudo** [comment]
最新1.9.7的bypass LAN and China有点问题，你用1.9.2版本的bypass LAN and China就没这个问题了
