### ISSUE TITLE
By pass lan and china无法访问微软产品

### ISSUE THREAD

**Issue by twoone-3** [netchx/netch#915]
### 错误描述

如题
我开启代理时就无法登录office或者minecraft
关闭就可以

### 复现步骤

添加服务器
选择Bypass lan and china
启动

### 日志

无

### 操作环境

```txt
Windows10企业版 21H2 19044.1889
软件版本：1.9.7
```

**Comment by starless1919** [comment]
请问这个问题解决了吗
