### ISSUE TITLE
1.9.7版本完全不可用

### ISSUE THREAD

**Issue by Morpheus1123** [netchx/netch#918]
### 错误描述

1.9.7版本，添加我自己搭建的VMESS服务器（V2fly和Xray最新版均已测试），以Bypass LAN and China启动后，可以看到虚拟网卡，但访问谷歌极大概率打不开，youtube可以打开，但所有视频都一直读取，无法播放，其它被墙网站几乎都无法打开。但是使用socks5工作正常。这说明问题出在虚拟网卡上。
如果以Bypass LAN启动，国内的网站几乎都不能打开。

更换版本为1.9.2，相同的配置，可以正常使用。

设置全部是默认。

### 复现步骤

1.打开netch 1.9.7
2.添加VMESS服务器（自建）
3.以Bypass LAN and China启动
4.几乎所有被墙网站都打不开。其它软件使用socks5端口可以正常翻墙。

### 日志

[2022-08-30 00:13:40][Information] Netch Version: NetchX/Netch@1.9.7
[2022-08-30 00:13:40][Information] OS: Microsoft Windows NT 10.0.19044.0
[2022-08-30 00:13:40][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2022-08-30 00:13:40][Information] System Language: zh-CN
[2022-08-30 00:13:40][Debug] Running Processes: 
C:\Program Files (x86)\ASUS\AsusCertService\AsusCertService.exe
C:\Program Files (x86)\ASUS\AXSP\4.00.45\atkexComSvc.exe
C:\Program Files (x86)\ASUS\ROG Armoury\Live Update\ArmouryLiveUpdate.exe
C:\Program Files (x86)\ASUS\ROG Armoury\Live Update\LiveUpdateSyncCheck.exe
C:\Program Files (x86)\ASUS\ROG Armoury\MacroAgent.exe
C:\Program Files (x86)\ASUS\ROG Armoury\Mouse\ROG STRIX CARRY\P508PowerAgent.exe
C:\Program Files (x86)\ASUS\ROG Armoury\Protocol\AudioLEDControl\ledcontrolservice3.exe
C:\Program Files (x86)\ASUS\ROG Armoury\Tools\Mutually Exclusive AURA Agent.exe
C:\Program Files (x86)\Common Files\Macrovision Shared\FlexNet Publisher\FNPLicensingService.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\LightingService\LightingService.exe
C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe
C:\Program Files (x86)\Samsung\Samsung Magician\SamsungMagicianSVC.exe
C:\Program Files\ASUS\AacExtCard\extensionCardHal_x86.exe
C:\Program Files\ASUS\AacMB\Aac3572MbHal_x86.exe
C:\Program Files\ASUS\KINGSTON_Aac_DRAM\AacKingstonDramHal_x86.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\NahimicAPI\NahimicAPISvc64.exe
C:\Program Files\NahimicAPI\x86\NahimicAPISvc32.exe
C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe
C:\Program Files\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA Share.exe
C:\Program Files\NVIDIA Corporation\ShadowPlay\nvsphelper64.exe
C:\Users\Morpheus\AppData\Local\NhNotifSys\sonicstudio\asusns.exe
J:\Netch197\Netch.exe
J:\Program Files\reWASD\reWASDService.exe
J:\v2ray\wv2ray.exe
[2022-08-30 00:13:40][Debug] Third-party Drivers:
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\Windows\system32\drivers\amdgpio2.sys
AMD PSP Service [AMD PSP Service](Copyright (c) 2013 - 2022 Advanced Micro Devices, Inc.)
	C:\Windows\system32\drivers\amdpsp.sys
Asusgio2 [Asusgio2]()
	\??\C:\Windows\system32\drivers\AsIO2.sys
Asusgio3 [Asusgio3]()
	\??\C:\Windows\system32\drivers\AsIO3.sys
Sonic Studio Virtual Mixer - Driver [Sonic Studio Virtual Mixer - Driver](Copyright 2019 (C) A-Volute2018)
	C:\Windows\system32\drivers\AVoluteSS3Vad.sys
CimFS [CimFS]()
	C:\Windows\system32\drivers\CimFS.sys
EneTechIo [EneTechIo]()
	\??\C:\Windows\system32\drivers\ene.sys
Game Controller Mapper [Game Controller Mapper](Copyright (C) 2016-2022)
	C:\Windows\system32\drivers\hidgamemap.sys
IDMWFP [IDMWFP](Copyright © 1999 - 2018 Tonec Inc.)
	C:\Windows\system32\DRIVERS\idmwfp.sys
MSIO [MSIO]()
	\??\C:\Windows\system32\drivers\MsIo64.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\Windows\system32\drivers\netfilter2.sys
ROG Keyboard [ROG Keyboard]()
	C:\Windows\system32\DriverStore\FileRepository\rogkb.inf_amd64_9c19fffb5d62d536\ROGKB.sys
ROG Mouse [ROG Mouse]()
	C:\Windows\system32\DriverStore\FileRepository\rogms.inf_amd64_94d9766656ff6011\ROGMS.sys
secnvme [secnvme](Copyright ©Samsung Electronics Co., Ltd 2020)
	C:\Windows\system32\drivers\secnvme.sys
[2022-08-30 00:13:42][Information] Start MainController: VMess [2]Bypass LAN and China
[2022-08-30 00:13:42][Debug] Server Information: VMess auto + tcp + packet + none + none
[2022-08-30 00:13:42][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-08-30 00:13:42][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-08-30 00:13:47][Information] Github latest release: 1.9.7
[2022-08-30 00:13:47][Information] Already the latest version
[2022-08-30 00:13:49][Information] Net traffic processes: (8252)v2ray-sn
[2022-08-30 00:14:44][Information] Stop Main Controller
[2022-08-30 00:14:55][Information] Start MainController: VMess [2]Bypass LAN and China
[2022-08-30 00:14:55][Debug] Server Information: VMess auto + tcp + xudp + none + none
[2022-08-30 00:14:55][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-08-30 00:14:55][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-08-30 00:15:02][Information] Net traffic processes: (13124)v2ray-sn
[2022-08-30 00:16:03][Information] Stop Main Controller
[2022-08-30 00:16:31][Information] Start MainController: VMess [2]Bypass LAN and China
[2022-08-30 00:16:31][Debug] Server Information: VMess auto + tcp + xudp + none + none
[2022-08-30 00:16:32][Information] Built-in  wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-08-30 00:16:32][Information] Installed wintun.dll Hash: 8a0581991caf829cd92b27aabcb2bab618cc8fbc887d8f86a533c95d2e3f17d4
[2022-08-30 00:16:39][Information] Net traffic processes: (14292)v2ray-sn
[2022-08-30 00:17:47][Information] Stop Main Controller

V2Ray 5.0.14 (V2Fly, a community-driven edition of V2Ray.) SagerNet (go1.18.3 windows/amd64)
A unified platform for anti-censorship.
2022/08/30 00:16:32 [Warning] V2Ray 5.0.14 started
2022/08/30 00:16:39 [Warning] [3139712125] app/dispatcher: default route for tcp:cp.cloudflare.com:80
2022/08/30 00:16:39 [Warning] [1871260131] app/dispatcher: default route for udp:198.211.120.59:3478
2022/08/30 00:16:41 [Warning] [2729398455] app/dispatcher: default route for udp:224.0.0.251:5353
2022/08/30 00:16:41 [Warning] [1387152152] app/dispatcher: default route for udp:10.0.236.255:137
2022/08/30 00:16:42 [Warning] [1551979425] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:16:42 [Warning] [3883877038] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:16:43 [Warning] [1037113091] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:16:43 [Warning] [90248876] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:16:43 [Warning] [3115854230] app/dispatcher: default route for udp:239.255.255.250:1900
2022/08/30 00:16:43 [Warning] [545418255] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:16:43 [Warning] [1545447334] app/dispatcher: default route for tcp:172.217.160.106:443
2022/08/30 00:16:43 [Warning] [682222823] app/dispatcher: default route for tcp:142.251.42.237:443
2022/08/30 00:16:44 [Warning] [1754484649] app/dispatcher: default route for tcp:20.198.162.76:443
2022/08/30 00:16:44 [Warning] [2733482284] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:16:44 [Warning] [2321057967] app/dispatcher: default route for tcp:172.217.163.42:443
2022/08/30 00:16:44 [Warning] [693455938] app/dispatcher: default route for tcp:142.251.42.238:443
2022/08/30 00:16:46 [Warning] [4157999311] app/dispatcher: default route for tcp:74.125.204.188:5228
2022/08/30 00:16:47 [Warning] [2335163224] app/dispatcher: default route for udp:10.0.236.255:138
2022/08/30 00:16:54 [Warning] [3326157487] app/dispatcher: default route for tcp:172.217.160.78:443
2022/08/30 00:16:54 [Warning] [779355861] app/dispatcher: default route for tcp:172.217.160.78:443
2022/08/30 00:16:55 [Warning] [1742537056] app/dispatcher: default route for tcp:172.217.160.86:443
2022/08/30 00:16:56 [Warning] [1387836487] app/dispatcher: default route for udp:172.217.160.78:443
2022/08/30 00:16:57 [Warning] [3876179932] app/dispatcher: default route for udp:172.217.160.86:443
2022/08/30 00:16:57 [Warning] [4005395600] app/dispatcher: default route for tcp:142.251.43.1:443
2022/08/30 00:16:57 [Warning] [4087307264] app/dispatcher: default route for tcp:142.251.43.1:443
2022/08/30 00:16:57 [Warning] [3200524844] app/dispatcher: default route for tcp:142.251.43.10:443
2022/08/30 00:16:58 [Warning] [896555606] app/dispatcher: default route for udp:142.251.43.10:443
2022/08/30 00:16:59 [Warning] [591052849] app/dispatcher: default route for tcp:185.45.7.97:443
2022/08/30 00:17:00 [Warning] [4163505420] app/dispatcher: default route for tcp:185.45.7.97:443
2022/08/30 00:17:00 [Warning] [2249443843] app/dispatcher: default route for tcp:185.45.7.97:443
2022/08/30 00:17:01 [Warning] [26923645] app/dispatcher: default route for udp:142.251.43.1:443
2022/08/30 00:17:03 [Warning] [1550276796] app/dispatcher: default route for tcp:199.59.150.44:443
2022/08/30 00:17:06 [Warning] [564549244] app/dispatcher: default route for tcp:104.244.43.228:443
2022/08/30 00:17:07 [Warning] [2979373730] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:08 [Warning] [2651293137] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:08 [Warning] [3585427613] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:08 [Warning] [391828401] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:10 [Warning] [4013861909] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:11 [Warning] [390218356] app/dispatcher: default route for tcp:108.160.163.102:443
2022/08/30 00:17:11 [Warning] [2599494469] app/dispatcher: default route for tcp:104.244.42.2:443
2022/08/30 00:17:11 [Warning] [1645246214] app/dispatcher: default route for tcp:152.199.43.83:443
2022/08/30 00:17:11 [Warning] [1640915724] app/dispatcher: default route for tcp:104.244.46.5:443
2022/08/30 00:17:11 [Warning] [3236135997] app/dispatcher: default route for tcp:104.244.42.69:443
2022/08/30 00:17:11 [Warning] [2179912065] app/dispatcher: default route for tcp:35.188.42.15:443
2022/08/30 00:17:11 [Warning] [1101354697] app/dispatcher: default route for tcp:104.244.42.2:443
2022/08/30 00:17:11 [Warning] [1584646011] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:11 [Warning] [3298103286] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:11 [Warning] [1764994208] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:11 [Warning] [3627342206] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:11 [Warning] [708588800] app/dispatcher: default route for tcp:104.244.42.2:443
2022/08/30 00:17:11 [Warning] [4132872638] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:11 [Warning] [1974751177] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [1240523352] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [4084666604] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [3384490029] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [2929670206] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [929439190] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [3783860502] app/dispatcher: default route for tcp:35.188.42.15:443
2022/08/30 00:17:12 [Warning] [911027131] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [229922771] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [245624872] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:12 [Warning] [1719927143] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:13 [Warning] [1566113839] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:13 [Warning] [3279453865] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:13 [Warning] [1561797404] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:14 [Warning] [4292640061] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:15 [Warning] [1861132962] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:16 [Warning] [178494802] app/dispatcher: default route for tcp:104.244.43.228:443
2022/08/30 00:17:16 [Warning] [4271366752] app/dispatcher: default route for tcp:104.244.43.228:443
2022/08/30 00:17:16 [Warning] [1956924336] app/dispatcher: default route for udp:224.0.0.251:5353
2022/08/30 00:17:17 [Warning] [3065312269] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:18 [Warning] [3824965757] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:19 [Warning] [3064247785] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:19 [Warning] [2977543133] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:20 [Warning] [3446309998] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:21 [Warning] [1294041606] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:22 [Warning] [715345235] app/dispatcher: default route for tcp:157.240.2.50:443
2022/08/30 00:17:25 [Warning] [4186732232] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:17:25 [Warning] [1069268747] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:25 [Warning] [1313781362] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:17:26 [Warning] [2659340836] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:17:26 [Warning] [1771875252] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:26 [Warning] [2457062147] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:17:26 [Warning] [2139847770] app/dispatcher: default route for tcp:192.168.50.1:53
2022/08/30 00:17:29 [Warning] [986713353] app/dispatcher: default route for udp:172.217.160.78:443
2022/08/30 00:17:30 [Warning] [1146075483] app/dispatcher: default route for tcp:172.217.160.78:443
2022/08/30 00:17:30 [Warning] [2939636021] app/dispatcher: default route for tcp:104.244.43.228:443
2022/08/30 00:17:36 [Warning] [675254728] app/dispatcher: default route for tcp:185.45.7.97:443
2022/08/30 00:17:40 [Warning] [691099793] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:40 [Warning] [3360084206] app/dispatcher: default route for tcp:162.125.18.133:443
2022/08/30 00:17:44 [Warning] [1213963794] app/dispatcher: default route for tcp:65.21.112.201:443
2022/08/30 00:17:46 [Warning] [3495524556] app/dispatcher: default route for udp:172.217.160.86:443
2022/08/30 00:17:46 [Warning] [1553637630] app/dispatcher: default route for tcp:185.45.7.97:443
2022/08/30 00:17:46 [Warning] [841602713] app/dispatcher: default route for tcp:185.45.7.97:443

### 操作环境

```txt
操作系统：Windows 10 专业版 21H2 19044.1949
软件版本：1.9.7
```

**Comment by Morpheus1123** [comment]
自己解决了。在1.9.7版本点一次 选项--卸载NF服务，然后再启动就好了。

**Comment by Morpheus1123** [comment]
第二天使用再次出问题，和之前一样，完全无法使用。卸载NF服务也没有解决。
事件管理器里发现很多错误。
1.来源server，ID 2505，内容为：服务器无法与 \Device\NetBT_Tcpip_{44E38CEA-0FB1-4DEE-9088-A6A3E1A89C7B} 传输绑定，因为网络上的另一部计算机具有相同的名称。服务器无法启动。
2.来源NetBT，ID 4311，内容为：由于无法创建驱动程序设备，初始化失败。 使用字符串“000000000100320000000000D71000C011010000250200C001000000000000000000000000000000”识别初始化失败的 接口。如果 NetBT 无法从全局唯一接口标识符(GUID) 映射到 MAC 地址，则该接口表示已失败接口 或 GUID 的 MAC 地址。如果 MAC 地址或 GUID 都 不可用，字符串表示群集设备名称。 

.NET 5.0和6.0的最新版（X64和X86）都安装了。我无能为力了。

**Comment by nspron** [comment]
把你订阅发我试试

**Comment by Morpheus1123** [comment]
> 把你订阅发我试试

感谢你的好意。但我没有订阅。我是自己搭建的VPS服务器，只有我自己在用，我不想把IP地址分享出去，见谅。但我可以提供我的config。
其实非常简单。服务端用的是Xray官方最新版，用官方的安装命令安装的，没有使用第三方一键脚本。服务端是bandwagon的CN2 GIA服务器，系统是debian 11 x64。
服务端config：
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log"
  },
  "inbounds": [
    {
      "port": 我的服务端端口，是10000以上的端口,
      "protocol": "vmess",    
      "settings": {
        "clients": [
          {
            "id": "我的ID"
          }
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

就是最简单的VMESS协议，连TLS都没用。客户端使用Xray官方的版本，然后chrome用SwitchyOmega设置socks5代理，或者用IE设置系统全局代理，都是可以正常使用的。netch使用1.9.2版本创建虚拟网卡，也是可以正常使用的。
netch1.9.7不能正常使用。创建虚拟网卡后，绝大部分时候是任何墙外网站都不能访问，有时候是能访问油管，不能访问谷歌和推特，油管只能看网页，视频会一直加载，有时候谷歌推特油管都能访问，但视频一直加载。

以上是我能提供的信息。感谢。

**Comment by lunzima** [comment]
把华硕奥创卸载一下看看

**Comment by Morpheus1123** [comment]
> 把华硕奥创卸载一下看看

我没装奥创。

**Comment by Morpheus1123** [comment]
> 把华硕奥创卸载一下看看

主板是X570-E，鼠标是ROG gladius ii。分别用AURA和ROG armoury控制的。这俩东西卸载之后我不保证能装回来....之前因为折腾这俩东西重装过系统。

**Comment by abc-123-sudo** [comment]
这个netch的1.9.7版本Bypass LAN and China有点问题，我用了1.9.2版本的选择Bypass LAN and China就没啥问题了，访问youtu和谷歌都行，你可以换成1.9.2版本再试试

**Comment by abc-123-sudo** [comment]
其实可以用满足自身需求就行，没必要用最新的，最新的有些时候有点小问题

**Comment by Morpheus1123** [comment]
> 这个netch的1.9.7版本Bypass LAN and China有点问题，我用了1.9.2版本的选择Bypass LAN and China就没啥问题了，访问youtu和谷歌都行，你可以换成1.9.2版本再试试

1.9.2确实可以用。我有点好奇为什么1.9.7有些人能用，有些人不能用...

**Comment by abc-123-sudo** [comment]
> > 这个netch的1.9.7版本Bypass LAN and China有点问题，我用了1.9.2版本的选择Bypass LAN and China就没啥问题了，访问youtu和谷歌都行，你可以换成1.9.2版本再试试
> 
> 1.9.2确实可以用。我有点好奇为什么1.9.7有些人能用，有些人不能用...

**Comment by abc-123-sudo** [comment]
> > > 这个netch的1.9.7版本Bypass LAN and China有点问题，我用了1.9.2版本的选择Bypass LAN and China就没啥问题了，访问youtu和谷歌都行，你可以换成1.9.2版本再试试
> > 
> > 
> > 1.9.2确实可以用。我有点好奇为什么1.9.7有些人能用，有些人不能用...

确实，我感觉是这个软件问题，我就等新版本更新了，目前我就用1.9.2先用着了，目前可以满足我的需求

**Comment by helbing** [comment]
> 

确实有问题，用1.9.7翻不了墙，用1.9.4了

**Comment by AAxjcy** [comment]
1.9.6也有同样的问题，但1.9.5没问题可以正常用

**Comment by jmxu007** [comment]
我也遇到用1.9.7无法打开youtbe网址，解决方案：设置---WinTUN---勾选使用自定义DNS（默认DNS：1.1.1.1） 
以上重新设置后正常打开youtbe

**Comment by ly5519** [comment]
> 我也遇到用1.9.7无法打开youtbe网址，解决方案：设置---WinTUN---勾选使用自定义DNS（默认DNS：1.1.1.1） 以上重新设置后正常打开youtbe

兄弟牛的，这个可以用

**Comment by 110560** [comment]
> 我也遇到1.9.7无法打开youtbe网址，解决方案：设置---WinTUN---勾选使用自定义DNS（默认DNS：1.1.1.1） 以上重新设置后正常打开youtbe

这个可以用好了 ！

**Comment by kokutoukiritsugu** [comment]
Windows如果防火墙被完全禁用了, 比如start=4
会无法打开tun模式的System和Mixed
同时系统日志里显示

> 来源NetBT，ID 4311，内容为：由于无法创建驱动程序设备，初始化失败。 使用字符串“000000000100320000000000D71000C011010000250200C001000000000000000000000000000000”识别初始化失败的 接口。如果 NetBT 无法从全局唯一接口标识符(GUID) 映射到 MAC 地址，则该接口表示已失败接口 或 GUID 的 MAC 地址。如果 MAC 地址或 GUID 都 不可用，字符串表示群集设备名称。
