### ISSUE TITLE
不支持win7吗？

### ISSUE THREAD

**Issue by gameboyring** [netchx/netch#921]
### 错误描述

已经安装.NET 6.0，打开还是提示不支持

### 复现步骤

打开软件

### 日志

无

### 操作环境

```txt
WIN7 64位
```

### 额外信息

![image](https://user-images.githubusercontent.com/42858485/188217118-7b4416ac-aab6-47f2-9b87-a5b24707c87a.png)

**Comment by canmengxian** [comment]
> ### 错误描述
> 已经安装.NET 6.0，打开还是提示不支持
> 
> ### 复现步骤
> 打开软件
> 
> ### 日志
> 无
> 
> ### 操作环境
> ```
> WIN7 64位
> ```
> 
> ### 额外信息
> ![image](https://user-images.githubusercontent.com/42858485/188217118-7b4416ac-aab6-47f2-9b87-a5b24707c87a.png)

用旧版本吧，要不就放弃win7
