### ISSUE TITLE
win10 pypass LAN and China 报错 run2socks start failed

### ISSUE THREAD

**Issue by ulphonse** [netchx/netch#926]
### 错误描述

所有的[3]pypass XXX 启动时都会报错run2socks启动失败，但是代理单独的程序没问题

### 复现步骤

1.打开netch
2.模式选择 [3]pypass LAN and China
3.弹出报错 run2socks start failed

### 日志

.

### 操作环境

```txt
Netch Version: NetchX/Netch@1.9.2
win10
```

**Comment by M03ED** [comment]
i have same problem on win 11 

i was using netch like 1 week and last night randomly this happen 

![image](https://user-images.githubusercontent.com/50927468/197150463-216e5623-ff3f-443f-8b89-9807fb5f84fa.png)
