### ISSUE TITLE
能否在服务器栏加一个http代理呢?

### ISSUE THREAD

**Issue by one-pyy** [netchx/netch#929]
### 功能描述

![image](https://user-images.githubusercontent.com/72590023/190935362-dc2a0dce-f11f-43a4-8651-5f81a5fd10e6.png)
如图, 没有http代理。希望可以添加http代理。

用途举例: 将WeChatAppEx.exe的流量打到burp上, 达到小程序抓包的效果。

**Comment by user1121114685** [comment]
+1 确实需要

**Comment by marlkiller** [comment]
+10086

**Comment by bitjerry** [comment]
需求 +1
