### ISSUE TITLE
netch在启动代理的时候,我的shadowsockr客户端就会闪退

### ISSUE THREAD

**Issue by TaessicaDae** [netchx/netch#93]
**错误描述**
（提出错误报告之前，先确保自己已看过readme，并搜索过相关问题）
netch 1.2.7在启动代理的时候,就会把小飞机客户端给干掉

**复现步骤**
1. netch一点启动
2. 右下角的小飞机就没了,直接闪退,什么提示都没有

**错误截图**
莫得

**信息**
 - 操作系统：win7 x64 旗舰sp1
 - 软件版本：1.2.7 satble x64

**额外信息**
我用的小飞机客户端也是需要.net 4.8的,不知道是不是这个原因冲突了?
附上github地址:https://github.com/HMBSbige/ShadowsocksR-Windows

**Comment by ghost** [comment]
#86 您就不能找找，有没有重复吗

**Comment by chsbuffer** [comment]
@TaessicaDae #迷惑行为大赏

**Comment by BingLingGroup** [comment]
知道了，下次会在issue_template里提示搜索closed issues
