### ISSUE TITLE
netchx 1.9.7 无法翻墙

### ISSUE THREAD

**Issue by anteyecam** [netchx/netch#933]
### Describe the bug

NetchAfter tossing for a long time, using Netch 1.9.7 version, I can't go over the wall!

### To Reproduce

NetchAfter tossing for a long time, using Netch 1.9.7 version, I can't go over the wall!

### Log

[2022-09-25 13:03:06][Information] Netch Version: NetchX/Netch@1.9.7
[2022-09-25 13:03:06][Information] OS: Microsoft Windows NT 10.0.22621.0
[2022-09-25 13:03:06][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2022-09-25 13:03:06][Information] System Language: zh-CN
[2022-09-25 13:03:06][Debug] Third-party Drivers:
360Safe Anti Hijack Service [360Safe Anti Hijack Service]((C) 360.cn All Rights Reserved)
	C:\WINDOWS\system32\Drivers\360AntiHijack64.sys
360Safe Anti Steal File Service [360Safe Anti Steal File Service]((C) 360.cn All Rights Reserved)
	C:\WINDOWS\system32\Drivers\360AntiSteal64.sys
360Box mini-filter driver [360Box mini-filter driver]((C) 360.cn Inc. All Rights Reserved.)
	C:\WINDOWS\system32\DRIVERS\360Box64.sys
360Safe Camera Filter Service [360Safe Camera Filter Service]((C) 360.cn All Rights Reserved)
	C:\WINDOWS\system32\Drivers\360Camera64.sys
360FsFlt mini-filter driver [360FsFlt mini-filter driver]((C) 360.cn Inc. All Rights Reserved.)
	C:\WINDOWS\system32\DRIVERS\360FsFlt.sys
360netmon [360netmon]((C) 360.cn Inc. All Rights Reserved.)
	C:\WINDOWS\system32\DRIVERS\360netmon.sys
360reskit driver [360reskit driver]()
	\??\C:\WINDOWS\system32\drivers\360reskit64.sys
360Sensor [360Sensor]()
	\??\C:\WINDOWS\system32\drivers\360Sensor64.sys
360Sensor_DM [360Sensor_DM]()
	\??\C:\WINDOWS\system32\drivers\360Sensor_DM64.sys
AliPaladin [AliPaladin]()
	\??\C:\WINDOWS\system32\drivers\AliPaladin64.sys
Asusgio2 [Asusgio2]()
	\??\C:\WINDOWS\system32\drivers\AsIO2.sys
Asusgio3 [Asusgio3]()
	\??\C:\WINDOWS\system32\drivers\AsIO3.sys
cbfs6 [cbfs6]()
	\??\C:\WINDOWS\system32\drivers\cbfs6.sys
CTIIO [CTIIO]()
	\??\C:\WINDOWS\system32\drivers\CtiIo64.sys
MSIO [MSIO]()
	\??\C:\WINDOWS\system32\drivers\MsIo64.sys
NetGroup Packet Filter Driver [NetGroup Packet Filter Driver](Copyright © 2010-2013 Riverbed Technology, Inc. Copyright © 2005-2010 CACE Technologies. Copyright © 1999-2005 NetGroup, Politecnico di Torino.)
	C:\WINDOWS\system32\drivers\npf.sys
VB-Audio Virtual Cable (WDM) [VB-Audio Virtual Cable (WDM)](Copyright (C)Vincent Burel.2010-2012)
	C:\WINDOWS\system32\drivers\vbaudio_cable64_win7.sys
EldoS PnP Virtual Bus driver [EldoS PnP Virtual Bus driver](Copyright (C) 2016, /n software, Inc.)
	C:\WINDOWS\system32\drivers\vpnpbus.sys
XLGuard Driver [XLGuard Driver]()
	C:\WINDOWS\system32\drivers\XLGuard.sys
Xunlei WFP Driver [Xunlei WFP Driver]()
	C:\WINDOWS\system32\drivers\xlwfp.sys
ComputerZ_x64 [ComputerZ_x64]()
	\??\C:\Program Files (x86)\360\360DrvMgr\ComputerZ_x64.sys
[2022-09-25 13:03:07][Information] Github latest release: 1.9.7
[2022-09-25 13:03:07][Information] Already the latest version
[2022-09-25 13:03:07][Debug] Running Processes: 
C:\Netch\Netch.exe
C:\Program Files (x86)\360\360DrvMgr\360DrvMgr.exe
C:\Program Files (x86)\360\360DrvMgr\ComputerZService.exe
C:\Program Files (x86)\360\360DrvMgr\ScriptExecute.exe
C:\Program Files (x86)\360\360Safe\safemon\360tray.exe
C:\Program Files (x86)\Alibaba\wwbizsrv\wwbizsrv.exe
C:\Program Files (x86)\AlibabaProtect\1.0.70.716\AlibabaProtect.exe
C:\Program Files (x86)\alipay\aliedit\4.0.0.101\pcas.exe
C:\Program Files (x86)\ASUS\AsusCertService\AsusCertService.exe
C:\Program Files (x86)\ASUS\AXSP\4.02.15\atkexComSvc.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\Google\Update\1.3.36.152\GoogleCrashHandler.exe
C:\Program Files (x86)\Google\Update\1.3.36.152\GoogleCrashHandler64.exe
C:\Program Files (x86)\HiSuite\HandSetService\HuaweiHiSuiteService64.exe
C:\Program Files (x86)\Kakao\KakaoTalk\KakaoTalk.exe
c:\program files (x86)\KuGou2012\10.0.53.24820\service.exe
C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
C:\Program Files (x86)\Microsoft\Skype for Desktop\Skype.exe
C:\program files (x86)\sogoupinyin\11.8.0.5496\SGTool.exe
C:\program files (x86)\sogoupinyin\11.8.0.5496\SogouCloud.exe
C:\Program Files (x86)\ToDesk\ToDesk_Service.exe
C:\Program Files (x86)\ToDesk\ToDesk.exe
C:\Program Files\Common Files\Apple\Mobile Device Support\AppleMobileDeviceService.exe
C:\Program Files\Common Files\microsoft shared\ink\TabTip.exe
C:\Program Files\Google\Chrome\Application\chrome.exe
C:\Program Files\Mozilla Firefox\firefox.exe
C:\Program Files\OpenBoxLab\RaiDrive\CefSharp.BrowserSubprocess.exe
C:\Program Files\OpenBoxLab\RaiDrive\RaiDrive.exe
C:\Program Files\OpenBoxLab\RaiDrive\RaiDrive.Service.x64.exe
C:\Program Files\Oray\SunLogin\SunloginClient\SunloginClient.exe
C:\Program Files\TeamViewer\TeamViewer_Service.exe
C:\Users\wuzho\AppData\Roaming\360huabao\360huabao.exe
C:\Users\wuzho\AppData\Roaming\360Safe\SoftMgr\cuttle\cuttle.exe
C:\Users\wuzho\AppData\Roaming\360Safe\SoftMgr\MultiTip.exe
C:\Users\wuzho\AppData\Roaming\baidu\BaiduNetdisk\yundetectservice.exe
C:\Users\wuzho\AppData\Roaming\secoresdk\360se6\Application\components\seapp\SeAppService.exe
C:\Users\wuzho\AppData\Roaming\secoresdk\360se6\Application\components\sesvc\sesvc.exe
C:\Users\wuzho\AppData\Roaming\secoresdk\360se6\Application\components\sesvr\13.0.0.1323\sesvr.exe
E:\clash\Clash for Windows.exe
E:\clash\resources\static\files\win\x64\clash-win64.exe

### Environment

```txt
Windows 11
```

**Comment by abc-123-sudo** [comment]
这个1.9.7的Bypass LAN and China模式有点问题，你用1.9.2版本的netch就行
