### ISSUE TITLE
模式 4，5，6 整合成一个

### ISSUE THREAD

**Issue by BingLingGroup** [netchx/netch#94]
**功能描述**

模式 4，5，6 比较冗余，感觉可以整合到设置里面。具体而言是 HTTP 代理搞一个 CheckBox，Bypass China 搞一个 CheckBox，系统代理搞一个 CheckBox。界面设计上，这三个单独搞一个 GroupBox，不点开 HTTP 代理的 CheckBox，其他两个 CheckBox 都是 disable 的状态。

整合成的新模式可以叫做仅本地代理，这样在使用该模式时可以做到不打开进程代理或者 TUN/TAP 全局代理就能使用之前模式 4，5，6 的功能。与此同时，也能做到在使用进程代理或者 TUN/TAP 全局代理时同时使用模式 4，5，6 的功能。

**额外信息**

**Comment by BingLingGroup** [comment]
@ConnectionRefused CR 有什么意见（

**Comment by ghost** [comment]
不整，不做，不需要
