### ISSUE TITLE
多网卡情况下指定网卡出口

### ISSUE THREAD

**Issue by Flashcard8009** [netchx/netch#945]
### 功能描述

# Specify the network card outlet in case of multiple network cards
# 多网卡情况下指定网卡出口

能不能指定流量出口到指定的物理网卡或者hyper-v虚拟交换机模拟出来的虚拟网卡

![image](https://user-images.githubusercontent.com/110398988/197331660-d2576a37-c642-421f-bb3a-326e76fb87e3.png)

**Comment by youwei5683** [comment]
这种情况的话，你可以手动指定网卡的跃点来临时解决
