### ISSUE TITLE
不能保存配置

### ISSUE THREAD

**Issue by TonyShitDark** [netchx/netch#95]
**功能描述**
如题
不能保存配置和订阅 关闭软件后重新打开就没有了
（提出功能请求之前，先确保自己已看过readme，并搜索过相关问题）
简明扼要地描述需要的功能

**额外信息**

**Comment by BingLingGroup** [comment]
请具体说明是什么配置，以及订阅不能保存的问题我没有遇到，另外对已有功能的错误报告，请选择`错误报告`模版。
