### ISSUE TITLE
只想让它配合nps作为内网vpn的工具

### ISSUE THREAD

**Issue by mokibox** [netchx/netch#954]
### 功能描述

只想用它作为socks5转化成虚拟网卡的工具，达到访问内网的效果，那么ping检测和nat检测也就没有必要了，建议加一个ping检测开关和nat检测开关
![image-20221105102529122](https://pic-go2897.oss-cn-chengdu.aliyuncs.com/ftebox/image-20221105102529122.png)

**Comment by pytomtoto** [comment]
nat检测失败 能手动选吗 现在检测失败直接用不了？
