### ISSUE TITLE
订阅不能正常保存

### ISSUE THREAD

**Issue by TonyShitDark** [netchx/netch#96]
**错误描述**
关闭软件后订阅消失节点也消失要重新添加

**复现步骤**
1. 打开 Netch 软件
2. 添加订阅 更新订阅
3. 正常使用
4. 关闭软件
5. 重新打开
6. 订阅和节点全没了

**错误截图**
如果适用，请添加屏幕截图以帮助解释您的问题

**信息**
 - 操作系统：[例如 Windows 10 专业版 64 [位]]
![QQ截图20190902182658](https://user-images.githubusercontent.com/32632071/64108451-66d95200-cdaf-11e9-9aa2-1464af814315.png)

 - 软件版本：[例如 1.0.0-STABLE 64 位]
1.2.7-STABLE 64 位

**额外信息**

**Comment by BingLingGroup** [comment]
请先确保你存放 Netch 所在的文件夹具有写权限。

或者也可以用文本编辑器（建议 notepad++）查看一下`Netch/data/`目录下`server.dat`，`link.dat`里的内容，以及`Netch/logging/application.log`。

特别是以下两个时间点下，`server.dat`和`link.dat`的内容：
1. 导入订阅或服务器配置，再关闭软件后
2. 以及再打开软件后

请注意服务器配置和订阅配置是存储在`server.dat`和`link.dat`里的。

**Comment by TonyShitDark** [comment]
![QQ截图20190903003407](https://user-images.githubusercontent.com/32632071/64127025-a9685200-cde2-11e9-82e2-63b10d271afa.png)
data里面的两个文件也是空记事本打开只有[]两符号
权限检查过应该没问题放在非系统盘的目录下

**Comment by chsbuffer** [comment]
@wsdd977 更新订阅成功之后启动任意模式,
然后右键通知栏图标点击退出,
这时配置文件会保存但程序不会退出
在此时检查 Netch/data/server.dat

**Comment by TonyShitDark** [comment]
照你说的重复了几次 有时候有有时候没有  不知道什么情况

**Comment by BingLingGroup** [comment]
会不会是杀软的锅（万事不决先卸360）

**Comment by TonyShitDark** [comment]
。。。我最讨厌的就是国产流氓软件好吧 我电脑上绝对不可能运行任何360腾讯管家这些的东西
杀毒。。。用的是系统自带的没有改过设置防火墙也默认用

**Comment by chsbuffer** [comment]
@wsdd977 如果不更新订阅,, 在现有一些节点的情况下, 打开软件再退出节点是否会消失?

**Comment by TonyShitDark** [comment]
配置有时候能保存下来有时候没有
订阅和节点同时消失
用的是v2ray的订阅

**Comment by chsbuffer** [comment]
@wsdd977 检查 data 文件夹下的所有文件的内容
```
tuntap.ini
bypass.dat
server.dat
link.dat
settings.dat
```
分开描述 能保存 不能保存 时以上文件的内容

**Comment by TonyShitDark** [comment]
sever
link这两个有时有问题打开只有两个符号在里面[ ]
其他我又试了几次都没问题正常保存正确内容

**Comment by ghost** [comment]
早说是 v2ray 的订阅，这个需要 @tindy2013

**Comment by TonyShitDark** [comment]
v2有什么特殊吗  我平时用v2rayn没问题啊
