### ISSUE TITLE
请问为什么编译会有这么多报错啊

### ISSUE THREAD

**Issue by fendoubuxi** [netchx/netch#985]
### 错误描述

编译的时候，为什么会这么多报错啊，刚下载的最新代码，VS2019编译的，报错见下面的截图。
请问是反编译的代码吗？请问还需要额外的什么环境不？

### 复现步骤

编译报错

### 日志

编译报错

### 操作环境

```txt
win10
```

### 额外信息

![netch](https://user-images.githubusercontent.com/121556955/210211328-1dbbc7e3-5dd1-4f80-aba8-bf6c37dce196.jpg)

**Comment by daogework** [comment]
我觉得你应该试试vs2022
