### ISSUE TITLE
非127.0.0.1地址的sock5服务器udp支持不正常

### ISSUE THREAD

**Issue by Accelerator-Li** [netchx/netch#988]
### Describe the bug

sock5服务器配置
![image](https://user-images.githubusercontent.com/51698795/210256238-1eddfd49-8dee-481b-9c09-46cc37a0a0fb.png)

进程模式
![image](https://user-images.githubusercontent.com/51698795/210256501-6cbb2271-c71e-42d0-a05d-5d37b7d613e9.png)

启动之后右下角一直卡在正在测试NAT类型，日志无报错，被代理进程发了udp包也无反应，使用Wireshark抓包发现udp包并没有发送
![image](https://user-images.githubusercontent.com/51698795/210256331-afcd046d-d46d-41c5-a2a0-02ba0d6c8c9d.png)

![image](https://user-images.githubusercontent.com/51698795/210256772-402af94d-4824-4004-a5a2-a8845e869b95.png)

使用127.0.0.1 sock5服务器则正常
![image](https://user-images.githubusercontent.com/51698795/210257067-f0b13f92-eca7-4112-be3c-55283e5ec364.png)

### To Reproduce

1. 使用非127.0.0.1地址的sock5服务器
2. 启动

### Log

[2023-01-03 00:09:02][Information] Netch Version: NetchX/Netch@1.9.7
[2023-01-03 00:09:02][Information] OS: Microsoft Windows NT 10.0.19045.0
[2023-01-03 00:09:03][Information] SHA256: 1c81b4aab67defd3718d1acc057e23020dab2a2d5ceac612254464aa0728e224
[2023-01-03 00:09:03][Information] System Language: zh-CN
[2023-01-03 00:09:03][Debug] Running Processes: 
C:\Program Files (x86)\ASUS\ArmouryDevice\dll\AIOFanSDK\ArmouryAIOFanServer.exe
C:\Program Files (x86)\ASUS\ArmouryDevice\dll\ArmourySocketServer\ArmourySocketServer.exe
C:\Program Files (x86)\ASUS\AsusCertService\AsusCertService.exe
C:\Program Files (x86)\ASUS\AXSP\4.02.05\atkexComSvc.exe
C:\Program Files (x86)\Common Files\Steam\SteamService.exe
C:\Program Files (x86)\Common Files\Tencent\QQProtect\Bin\QQProtect.exe
C:\Program Files (x86)\Common Files\VMware\USB\vmware-usbarbitrator64.exe
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
C:\Program Files (x86)\Google\Update\1.3.36.152\GoogleCrashHandler.exe
C:\Program Files (x86)\Google\Update\1.3.36.152\GoogleCrashHandler64.exe
C:\Program Files (x86)\Google\Update\GoogleUpdate.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsDaemon.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\HipsTray.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\PopBlock.exe
C:\Program Files (x86)\Huorong\Sysdiag\bin\usysdiag.exe
C:\Program Files (x86)\Microsoft GameInput\x64\gameinputsvc.exe
C:\Program Files (x86)\NVIDIA Corporation\NvTelemetry\NvTelemetryContainer.exe
C:\Program Files (x86)\Razer\Razer Services\GMS\GameManagerService.exe
C:\Program Files (x86)\Razer\Razer Services\Razer Central\CefSharp.BrowserSubprocess.exe
C:\Program Files (x86)\Razer\Razer Services\Razer Central\Razer Central.exe
C:\Program Files (x86)\Razer\Razer Services\Razer Central\RazerCentralService.exe
C:\Program Files\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe
C:\Program Files\Common Files\microsoft shared\ink\TabTip.exe
C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqld.exe
C:\Program Files\PowerToys\modules\AlwaysOnTop\PowerToys.AlwaysOnTop.exe
C:\Program Files\PowerToys\modules\FancyZones\PowerToys.FancyZones.exe
C:\Program Files\PowerToys\PowerToys.exe
C:\Program Files\Windows Sidebar\sidebar.exe
D:\Program Files\Autodesk\3ds Max 2014\NVIDIA\Satellite\raysat_3dsmax2014_64server.exe
D:\Program Files\Java\jdk17\bin\java.exe
D:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\bin\fsnotifier64.exe
D:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\bin\idea64.exe
D:\Program Files\Microsoft VS Code\Code.exe
D:\Program Files\Microvirt\MEmu\MemuService.exe
D:\Program Files\Razer\Synapse3\Service\..\UserProcess\Razer Synapse Service Process.exe
D:\Program Files\Razer\Synapse3\Service\Razer Synapse Service.exe
D:\Program Files\Razer\Synapse3\WPFUI\Framework\Razer Synapse 3 Host\Razer Synapse 3.exe
D:\Program Files\SogouInput\13.0.0.6729\SGTool.exe
D:\Program Files\SogouInput\13.0.0.6729\SogouCloud.exe
D:\Program Files\v2rayN\v2rayN.exe
D:\Program Files\v2rayN\xray.exe
D:\Program Files\VMware\VMware Workstation\vmware-authd.exe
D:\Program Files\VMware\VMware Workstation\vmware-tray.exe
D:\Program Files\Wireshark\dumpcap.exe
D:\Program Files\Wireshark\Wireshark.exe
D:\Steam\bin\cef\cef.win7x64\steamwebhelper.exe
D:\Steam\steam.exe
F:\Accelerator\Netch\Netch.exe
[2023-01-03 00:09:03][Debug] Third-party Drivers:
AMD GPIO Client Driver [AMD GPIO Client Driver](Copyright © 2014-2020 Advanced Micro Devices, Inc)
	C:\WINDOWS\system32\drivers\amdgpio2.sys
AMD PSP Service [AMD PSP Service](Copyright (c) 2013 - 2020 Advanced Micro Devices, Inc.)
	C:\WINDOWS\system32\drivers\amdpsp.sys
AMDRyzenMasterDriverV16 [AMDRyzenMasterDriverV16]()
	\??\C:\Program Files\AMD\RyzenMaster\bin\AMDRyzenMasterDriver.sys
Asusgio2 [Asusgio2]()
	\??\C:\Windows\system32\drivers\AsIO2.sys
Asusgio3 [Asusgio3]()
	\??\C:\Windows\system32\drivers\AsIO3.sys
CimFS [CimFS]()
	C:\WINDOWS\system32\drivers\CimFS.sys
USB Audio Class 1.0 and 2.0 Device Driver [USB Audio Class 1.0 and 2.0 Device Driver](© C-Media Inc. All rights reserved.)
	C:\WINDOWS\system32\drivers\CMUAC.sys
EneTechIo [EneTechIo]()
	\??\C:\Windows\system32\drivers\ene.sys
Android Emulator Hypervisor Driver for AMD Processors Service [Android Emulator Hypervisor Driver for AMD Processors Service](Copyright (c) 2019 Google LLC)
	C:\WINDOWS\system32\DRIVERS\gvm.sys
VMware hcmon [VMware hcmon](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\hcmon.sys
Huorong Internet Security Devmon Kext [Huorong Internet Security Devmon Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\hrdevmon_win10.sys
Huorong Network Security Firewall Core Kext (WFP) [Huorong Network Security Firewall Core Kext (WFP)](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\hrwfpdrv_win10.sys
inpoutx64 [inpoutx64](Copyright (c) 2008 Highresolution Enterprises. Portions Copyright (c) Logix4u)
	C:\WINDOWS\system32\Drivers\inpoutx64.sys
FaceRig Virtual Audio Driver (WDM) [FaceRig Virtual Audio Driver (WDM)](Copyright (c) Adoriasoft LLC 2015)
	C:\WINDOWS\system32\drivers\Larmkanal.sys
MemuHyperv Service [MemuHyperv Service](Copyright (C) 2009-2019 Maiwei Corporation)
	C:\WINDOWS\system32\DRIVERS\MEmuDrv.sys
MemuHyperv NDIS6 Bridged Networking Service [MemuHyperv NDIS6 Bridged Networking Service](Copyright (C) 2009-2019 Maiwei Corporation)
	C:\WINDOWS\system32\DRIVERS\MEmuNetLwf.sys
MSIO [MSIO]()
	\??\C:\Windows\system32\drivers\MsIo64.sys
Netease UU TAP-Win32 Adapter V9.21 [Netease UU TAP-Win32 Adapter V9.21](OpenVPN Technologies, Inc.)
	C:\WINDOWS\system32\drivers\Netease_UU_TAP_0921.sys
Npcap Packet Driver (NPCAP) [Npcap Packet Driver (NPCAP)](Copyright (c) 2022, Insecure.Com LLC.  All rights reserved.)
	C:\WINDOWS\system32\DRIVERS\npcap.sys
FaceRig Virtual Camera [FaceRig Virtual Camera](Copyright (c) Adoriasoft LLC 2015)
	C:\WINDOWS\system32\DRIVERS\Phosgene.sys
Razer Control Service [Razer Control Service](Copyright © 2021 Razer Inc. All rights reserved)
	C:\WINDOWS\system32\drivers\RzCommon.sys
Razer 006e Service [Razer 006e Service](Copyright © 2021 Razer Inc. All rights reserved)
	C:\WINDOWS\system32\drivers\RzDev_006e.sys
Showshock Softnology Generic Driver [Showshock Softnology Generic Driver]()
	\??\C:\Windows\SysWOW64\DRIVERS\ssgdio64.sys
Huorong Network Security Core Kext [Huorong Network Security Core Kext](Beijing Huorong Network Technology Co., Ltd.)
	C:\WINDOWS\system32\DRIVERS\sysdiag_win10.sys
TAP-Windows Adapter V9 [TAP-Windows Adapter V9](OpenVPN Technologies, Inc.)
	C:\WINDOWS\system32\drivers\tap0901.sys
TweakCube Ram Disk Driver [TweakCube Ram Disk Driver]()
	\??\C:\Windows\system32\drivers\TweakCubeRM.sys
USBPcap Capture Service [USBPcap Capture Service]((c) 2013-2019 Tomasz Mon)
	C:\WINDOWS\system32\DRIVERS\USBPcap.sys
vJoy Device [vJoy Device](© Shaul Eizikovich. All rights reserved.)
	C:\WINDOWS\system32\drivers\vjoy.sys
VMware VMCI Bus Driver [VMware VMCI Bus Driver](Copyright © 1998-2019 VMware, Inc.)
	C:\WINDOWS\system32\drivers\vmci.sys
VMware Input Filter and Injection Driver (vmkbd) [VMware Input Filter and Injection Driver (vmkbd)](Copyright © 1998-2020 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmkbd.sys
VMware Virtual Ethernet Adapter Driver [VMware Virtual Ethernet Adapter Driver](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmnetadapter.sys
VMware Bridge Protocol [VMware Bridge Protocol](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmnetbridge.sys
VMware Virtual Ethernet Userif for VMnet [VMware Virtual Ethernet Userif for VMnet](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmnetuserif.sys
VMware vmx86 [VMware vmx86](Copyright © 1998-2021 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vmx86.sys
vSockets Virtual Machine Communication Interface Sockets driver [vSockets Virtual Machine Communication Interface Sockets driver](Copyright © 1998-2020 VMware, Inc.)
	C:\WINDOWS\system32\DRIVERS\vsock.sys
Vstor2 MntApi 2.0 Driver (shared) [Vstor2 MntApi 2.0 Driver (shared)](Copyright © 1998-2009 VMware, Inc.)
	C:\WINDOWS\system32\drivers\vstor2-mntapi10-shared.sys
xfilter [xfilter](Copyright © NetFilterSDK.com)
	C:\WINDOWS\system32\drivers\xfilter.sys
netfilter2 [netfilter2](Copyright © NetFilterSDK.com)
	C:\WINDOWS\system32\drivers\netfilter2.sys
[2023-01-03 00:09:03][Information] Github latest release: 1.9.7
[2023-01-03 00:09:03][Information] Already the latest version
[2023-01-03 00:09:08][Information] Start MainController: SOCKS [0]All
[2023-01-03 00:09:08][Information] Built-in  netfilter2 driver version: 1.6.3.0
[2023-01-03 00:09:08][Information] Installed netfilter2 driver version: 1.6.3.0
[2023-01-03 00:09:08][Information] Net traffic processes: (7412)Netch

### Environment

```txt
OS: Windows 10 专业版 22H2 19045.2364
Netch Version: 1.9.7
```

**Comment by iselt** [comment]
可能关联的issue：[https://github.com/netchx/netch/issues/813](url)

**Comment by iselt** [comment]
可能关联的issue：https://github.com/netchx/netch/issues/813
