### ISSUE TITLE
多core支持

### ISSUE THREAD

**Issue by Fhokud** [netchx/netch#996]
### 功能描述

开发者可以使用具有良好活跃度维护社区维护的xray-core/v2fly-core作为主要核心嘛？
或者像V2rayN那样对部分代理平台提供主要支持，同时部分较小众的代理平台具有自定义配置文件支持

平时使用netch时，不得不和其他软件进行使用socks的对接转换，要开好几个代理平台，还要注意网络上的冲突

在编译Netch的过程编译v2ray-sn时碰到了这个......
`Error: C:\Users\runneradmin\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.27.2\internal\qtls\go119.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.19 yet. For more details`
难到还要去再去维护上游？

**Comment by Smallthing** [comment]
我直接把xray改名成v2ray-sn。。。
