### ISSUE TITLE
Why isn't tun2socks open source?

### ISSUE THREAD

**Issue by themiralay** [netchx/netch#997]
### Describe the feature you want

I can't see the tun_dial, tun_init, tun_free, tun_luid, tun_getUP, tun_getDL methods used for tun2socks in the current tun2socks version. Can you add the open source version to the repo?

**Comment by themiralay** [comment]
i wait a message for development team

**Comment by tozik** [comment]
Hi, is really important question, can you add the open source version to the repo?

**Comment by themiralay** [comment]
Definitely,
The actual kernel DLL that does the job is tun2socks but I see it's not open source.
